### ISSUE TITLE
Can we please get a Fluent theme?

### ISSUE THREAD

**Issue by AvMavs** [jeffvli/feishin#1]
Can we get a theme that might look like https://github.com/nimsandu/spicetify-bloom?

It'd look really cool and be fun to use, so it's not necessary, but it would be a really great enhancement that would further bridge the gap and let self-hosted FOSS look as good as or even better than proprietary software like Spotify.

**Comment by jeffvli** [comment]
Thanks for the suggestion!

I'll try to incorporate some of those design styles in the core app since I do like them. 
I'm also trying to write the app in a way to allow custom stylesheets for theming so it can be more customizable than Sonixd is.

**Comment by AvMavs** [comment]
Amazing. As a dedicated Sonixd user, I can't wait for Feishin!

**Comment by Gin-no-kami** [comment]
Sorry to necro this closed issue, but since my question is directly related I'll post it here.

> I'm also trying to write the app in a way to allow custom stylesheets for theming so it can be more customizable than Sonixd is.

Is there any documentation on how to apply custom stylesheets? Or is this feature not implemented yet?
