### ISSUE TITLE
Ultrawidescreen support for the Card & Poster views

### ISSUE THREAD

**Issue by falstaff1288** [jeffvli/feishin#10]
Hi.

The Card & Poster views width is limited with ultrawidescreens. It's not the case for the table view which works fine.

Thanks!

**Comment by falstaff1288** [comment]
![cardwidth](https://user-images.githubusercontent.com/16071741/213501327-e42f81e0-f022-4505-a24d-04936ebbcbf6.png)

**Comment by jeffvli** [comment]
This is due to performance concerns, but I'll probably experiment with trying to allow for ultrawide support by dynamically sizing the grid items when the app width is changed.

**Comment by jeffvli** [comment]
I've removed the max-width limits for all the pages for the time being in the latest release. There's a couple places where it doesn't scale well on ultrawide but I'll likely address them in the future.
