### ISSUE TITLE
[Bug] Playlist Items duplication

### ISSUE THREAD

**Issue by YourSandwich** [jeffvli/feishin#100]
## Expected Behavior

When Playlist is for example 100 entries long, i should be able to scroll down till entry 100

## Current Behavior

After scrolling down below Entry 50, the Playlist entries duplicate

## Steps to Reproduce

1. Create a Playlist with over 50 Entries
2. Try to scroll down to reach Entry 51

Not Scrolling below 50 entry 
![image](https://github.com/jeffvli/feishin/assets/20018243/0ee61e36-c233-4c48-ae0e-e3d30403c2a3)

Scrolling Below 50 entry 
![image](https://github.com/jeffvli/feishin/assets/20018243/14c97590-0b9b-4afa-9e63-cc299a85ee72)

## Your Environment

- Application version :0.0.1_alpha6
- Operating System and version : ArchLinux 11.05.2023

**Comment by YourSandwich** [comment]
Sry, this is a duplicate of #53

**Comment by kgarner7** [comment]
I'll close this in favor of 53. If this issue is still seen, please follow up there
