### ISSUE TITLE
ARM dmg gives 'file is damaged and cannot be opened' error

### ISSUE THREAD

**Issue by motlaghreyhan** [jeffvli/feishin#104]
## Expected Behavior

feishin should open, currently have to use intel version 

## Current Behavior

<img width="264" alt="image" src="https://github.com/jeffvli/feishin/assets/88353058/380285ff-eec9-4182-8c8d-b14402251d54">

## Steps to Reproduce

1. Install on m1 macbook pro

2. Either drag to applications folder, or try to open directly, errors both times

3.

4.

## Context

Intel apps will have higher resource usage on ARM macs

## Your Environment

- Application version : 0.0.1-alpha6
- Operating System and version : M1 Macbook pro 16" macOS 13.3.1 (a) (22E772610a) Ventura
- Node version (if developing locally) :

**Comment by jeffvli** [comment]
You'll have to remove the file from quarantine. The binary isn't signed due to Apple cost restrictions so you need to remove the file from quarantine.

```bash
# Change the path if necessary
xattr -r -d com.apple.quarantine /Applications/Feishin.app

# If you have a conflicting xattr binary 
# From https://github.com/jeffvli/feishin/issues/637
/usr/bin/xattr -r -d com.apple.quarantine /Applications/Feishin.app
```

**Comment by motlaghreyhan** [comment]
I didn't know about this, typical Apple crap, thank you! I've always been able to fix it in system settings. Sorry if I missed an existing ticket or documentation somewhere.

Unrelated, but this is by FAR the best desktop jellyfin music client I've come across and I really appreciate the hard work, thanks! 

Edit: again unrelated, but your sponsor button in github doesn't seem to do anything. I'd happily donate a small amount monthly!
