### ISSUE TITLE
Keyboard media keys don't seem to work

### ISSUE THREAD

**Issue by motlaghreyhan** [jeffvli/feishin#105]
## Expected Behavior

Control media with keyboard media keys

## Current Behavior

Play/pause, and previous/next track on the keyboard don't do anything in feishin 

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Application version : 0.0.1-alpha6
- Operating System and version : Win 11 22H2, (it DOES work on MacOS ventura)
- Node version (if developing locally) :

**Comment by jeffvli** [comment]
Do you have the `Global media hotkeys` toggle enabled?

![image](https://github.com/jeffvli/feishin/assets/42182408/3c83aa0c-54e2-453b-b545-83ec21b3d779)

If it doesn't work, try re-toggling it and restarting the app as well.

**Comment by motlaghreyhan** [comment]
Yep, that fixed it thank you. Is there a reason that's off by default? I went through all the settings and somehow completely breezed past that. 

MacOS also doesn't seem to care what the toggle is set to, it works either way

**Comment by S-n-d** [comment]
Hello,

It seems this issue has to be re-opened. I'm on Ventura 13.5.1 and the media keys won't work. Tried re-togging global media hotkeys but to no avail.

**Comment by Dauntless-One** [comment]
I am experiencing this issue. Hotkeys work while the application is focused but not when it is in the background. Toggling the global media hotkeys has not resolved it.

**Comment by northamerican** [comment]
On a mac: play, pause, next, previous, mute and volume keys do not work and cannot be configured from the hotkeys menu.
