### ISSUE TITLE
Playing a song from an album only plays that one song

### ISSUE THREAD

**Issue by motlaghreyhan** [jeffvli/feishin#106]
## What do you want to be added?

Sorry I don't mean to spam issues 😬

Currently when double clicking/pressing play on a song in an album/playlist/artist page, it only plays that single song. Can there be an option to play the remainder of the music as well? For example, if I want to play only disc 2 of the new RAM Daft Punk Album, I have to click play the whole album and then skip down to disc 2.

It also looks like I can double click the "disc 2" text, but it doesn't seem to do anything other than change the title of whatever song is currently playing to "disc 2" with no album art. This may be a bug?

## Additional context

<img width="1452" alt="image" src="https://github.com/jeffvli/feishin/assets/88353058/a830e215-d90c-487b-bf52-d5839127698f">

**Comment by jeffvli** [comment]
Yep that's a bug. It'll be fixed in the next release.

**Comment by jeffvli** [comment]
Going to close this for now since it's similar to #67.
