### ISSUE TITLE
Filtering albums by favorite switches it to tracks until app restart

### ISSUE THREAD

**Issue by motlaghreyhan** [jeffvli/feishin#108]
## Expected Behavior

When enabling the "Is Favorited" toggle under the album tab, only whole albums that have been favorited should show up. 

## Current Behavior

Toggling the "Is Favorited" switch changes the "Album" tab on the left to behave as a "Tracks" tab, but with the album tab viewing settings. Untoggling just stops filtering by favorite, but is still tracks and not albums. An app restart fixes this

<img width="1474" alt="image" src="https://github.com/jeffvli/feishin/assets/88353058/ecad19ce-54e1-46d0-af51-8b3aadd97d46">

## Steps to Reproduce

1. Open album tab

2. Click filter and toggle "is favorite"

## Your Environment

- Application version : v0.0.1-alpha6
- Operating System and version : macOS ventura 13.3.1 (a) (22E772610a)
- Node version (if developing locally) :

**Comment by jeffvli** [comment]
Unfortunately the Jellyfin implementation is a bit broken on v0.0.1-alpha6.

This is resolved on the latest dev builds, and a new release will be coming later this weekend.
