### ISSUE TITLE
Broken Seek Bar

### ISSUE THREAD

**Issue by Sakooooo** [jeffvli/feishin#112]
## Expected Behavior
Bar should be a quarter of the full bar

## Current Behavior
It is stuck at the beginning
![image](https://github.com/jeffvli/feishin/assets/78461130/86cf109f-7198-4933-9639-5d9a52aef0a3)
![image](https://github.com/jeffvli/feishin/assets/78461130/114d0b0f-0c1b-4cfa-943e-a9d95ae87887)

## Steps to Reproduce

1. No stack traces

2.

3.

4.

## Your Environment

- Application version :alpha-001
- Operating System and version : Windows 10
- Node version (if developing locally) :

**Comment by jeffvli** [comment]
I'm unable to reproduce this. Try downloading a different version of mpv and re-set it in the settings page.

**Comment by Sakooooo** [comment]
Fixed! run updater.bat in mpv install dir on windows thanks!
