### ISSUE TITLE
Open fullscreen player tooltip does not appear on expanded album artwork

### ISSUE THREAD

**Issue by Gecked-Deck** [jeffvli/feishin#114]
## Expected Behavior

"Open fullscreen player" tooltip should appear when hovering over album artwork (as shown below)
![image](https://github.com/jeffvli/feishin/assets/104325921/8de23f26-6132-436e-af78-6e1faffe4029)

## Current Behavior

When album artwork is expanded, hovering over the image does not show the tooltip.
![image](https://github.com/jeffvli/feishin/assets/104325921/e31361cb-eb41-428b-9d2a-29387ad55cf2)

## Steps to Reproduce

Expand image artwork, and hover the cursor over it.

## Context

Was just checking out the 0.10 update, as this issue is related to a discussion that happened in the discord. It's not super impactful, but I think having the tooltip appear would be good for making the app's behaviour uniform.

## Your Environment

- Application version (e.g. v0.1.0) : v0.1.0
- Operating System and version (e.g. Windows 10) : Fedora Linux 38.20230521.0 (Kinoite) x86_64 
- Server and version (e.g. Navidrome v0.48.0) : Jellyfin v10.8.10
- Node version (if developing locally) :

**Comment by jeffvli** [comment]
Fixed
