### ISSUE TITLE
Album Artist images not displaying

### ISSUE THREAD

**Issue by rwdnnz** [jeffvli/feishin#116]
## Expected Behavior

When I browse or look at an album artist the image for that artist to display. 

## Current Behavior

When I browse to an artist, the image for that artist doesn't currently display. This does display in Navidrome and Symfonium.

In addition, if I browse to Album Artists under library, no images are displayed there either.

I've checked the console, and there are no errors there.  I can see that the getArtistInfo.view call is returning with image urls in it for the artist, so maybe missing a call to get the image? It is interesting that the images for related artists are loading.

## Steps to Reproduce

1. Browse to an artist, no image for the artist is displayed

2. Browse to Album Artists, no images are displayed

## Your Environment

- Application version (e.g. v0.1.0) : 0.1.1
- Operating System and version (e.g. Windows 10) : Windows 10
- Server and version (e.g. Navidrome v0.48.0) :Navidrome 0.49.3-SNAPSHOT (85d43d23)

**Comment by jeffvli** [comment]
Are your artist images being populated by local images or is it fetching from the Spotify plugin?

I haven't tested local images, but from what I can tell external images are working fine albeit the image isn't fetched until after navigating to the artist page for the first time.

**Comment by rwdnnz** [comment]
Hey - the artist images are populated by local images.

**Comment by jeffvli** [comment]
This is now fixed on the actual artist page, but it's missing from the artist list api response so you won't be able to see the images on the artist grid.

An issue can be created on the Navidrome repo regarding this, but knowing that a [new API](https://github.com/navidrome/navidrome/pull/2365) is currently being wrriten it may be better just to wait.
