### ISSUE TITLE
Support for Track Numbers

### ISSUE THREAD

**Issue by AvMavs** [jeffvli/feishin#12]
Navidrome supports track numbers from the metadata, but both Sonixd and Feishin don't.

I know the project is still in development, but I'd be grateful if you could add support for track numbers if they are supported by the Subsonic API!

(Thank you for this wonderful client!)

**Comment by jeffvli** [comment]
Track numbers are already supported for both Feishin and Sonixd.
Check out the table column selector on the queue page / song list.

Unless there's something else I'm missing?

**Comment by AvMavs** [comment]
I'm sorry, I just messed my metadata up, thank you.

(I apologise, this was completely on me.)
