### ISSUE TITLE
Cover art proportion problem at certain screen resolution in fullscreen player

### ISSUE THREAD

**Issue by AuroraViola** [jeffvli/feishin#124]
## Expected Behavior

In fullscreen player song cover art should be a perfect square

## Current Behavior

It is not a perfect square
![image](https://github.com/jeffvli/feishin/assets/110638310/0980d380-cdce-44f5-96ad-3b4980d383d0)

## Steps to Reproduce

1. Activate fullscreen player
2. Scale the window to 1366x768 (my monitor resolution)
3. look at the cover art proportion

## Context

I don't like a cover art that should be a square being a rectangle

## My Environment

- Application version: v0.1.1
- Operating System and version: Fedora 38
- Server and version: Navidrome v0.49.3

**Comment by jeffvli** [comment]
Related to #130 and #137
