### ISSUE TITLE
Native window bar style

### ISSUE THREAD

**Issue by keawade** [jeffvli/feishin#126]
## What do you want to be added?

A "Native" window bar style option similar to what is available in Sonixd would be greatly appreciated.

**Comment by Gecked-Deck** [comment]
Already been done, just not in the latest release.
https://github.com/jeffvli/feishin/pull/122

**Comment by keawade** [comment]
Well, that's what I get for searching for "window bar" instead of "titlebar" lol.

That's great! I'll close this then.
