### ISSUE TITLE
Multiple mpv instances open

### ISSUE THREAD

**Issue by TotalChaos05** [jeffvli/feishin#127]
## Expected Behavior

Only one media session should be open

## Current Behavior

Multiple media sessions are open
![image](https://github.com/jeffvli/feishin/assets/70387628/48558d8f-d054-46c3-a341-8e18e1481778)

Ghost session is left behind after closing feishin
![image](https://github.com/jeffvli/feishin/assets/70387628/b9a95c2a-be8e-4fe6-bad2-193c4b1a8c97)

can be killed by running `killall mpv`

## Steps to Reproduce

1. Open feishin

2. Set player to mpv

## Your Environment

- Application version (0.1.1
- openSUSE Tumbleweed kernel 6.3.2-1-default
- Jellyfin 10.8.10
- Node version (if developing locally) :

**Comment by jeffvli** [comment]
The 2 players open is expected since both Feishin and MPV implement their own mpris instance.

Regarding mpv not opening, can you try re-installing the latest version of mpv and point Feishin towards it? There's been some reports of inconsistent behavior between different versions of mpv.

**Comment by TotalChaos05** [comment]
the mpris was fixed by compiling my own mpv. the other problem wasn't mpv not opening, it was it not closing after feishin was closed.
