### ISSUE TITLE
Fullscreen player interface does not scale well at small window sizes

### ISSUE THREAD

**Issue by Gecked-Deck** [jeffvli/feishin#130]
## Expected Behavior

The fullscreen player's UI should scale properly to smaller window sizes

## Current Behavior

The fullscreen player UI does not scale well. At the smallest window size the album art is unrecognisable and the volume slider is cut off (This is also an issue in the normal player).

![image](https://github.com/jeffvli/feishin/assets/104325921/08e18b98-9ad8-4c46-a480-cc455bee8dab)

The stop, shuffle, repeat and shuffle all buttons also get hidden at small window sizes. (Large vs Small window comparison)

![image](https://github.com/jeffvli/feishin/assets/104325921/a029fae2-94fe-4664-a965-9c356a960854)
![image](https://github.com/jeffvli/feishin/assets/104325921/573e4545-5817-4c8b-908f-b5365314e6e9)

## Steps to Reproduce

1. Open Feishin

2. Enter the fullscreen player

3. Resize the window

## Context

It would be nice for the fullscreen player to scale nicely, as I like to have my music player pinned on top of other apps however in it's current state it looks slightly broken.

## Your Environment

- Application version : 0.1.1
- Operating System and version  : Fedora Linux 38.20230531.0 (Kinoite) x86_64
- Server and version  : Jellyfin v10.8.10

**Comment by jeffvli** [comment]
This is mostly fixed in the latest dev versions.

Unfortunately not all the controls can fit when sized to the minimum width on 100% scaling. At least 2 items will be hidden (if skip buttons are enabled).
