### ISSUE TITLE
add Right-Click context menu to left-hand playlist sidebar area

### ISSUE THREAD

**Issue by psych0d0g** [jeffvli/feishin#133]
## What do you want to be added?

right-clicking a playlist in the left sidebar should be possible coming up with the same menu one gets presented with when right- clicking a playlist in the main window to the right

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/9f4861a78a4cd7b8c162c488a945cd2848bc233f
