### ISSUE TITLE
Full Screen Player Spacing between Album Cover and Title

### ISSUE THREAD

**Issue by OriginCode** [jeffvli/feishin#137]
## Expected Behavior

The spacing between the cover and the title should be larger.

## Current Behavior

![圖片](https://github.com/jeffvli/feishin/assets/17294071/e59a080c-67c2-4707-9cc2-e04b73762671)

Currently if the album cover is not a square, there's barely spacing between the title and the image.

## Steps to Reproduce

1. Play a music with an album cover longer than a square

2. Go to Full Screen Player mode.

## Possible Solution (Not obligatory)

Add spacing relative to the album image.

## Context

The shadow of the image also covers a little bit of the title text. It doesn't look very good to me.

## Your Environment

- Application version (e.g. v0.1.0) : v0.1.1
- Operating System and version (e.g. Windows 10) : AOSC OS 10.2.0 (GNU/Linux, x86_64)
- Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3

**Comment by jeffvli** [comment]
This is fixed on the latest development builds, which you can [download here via the build artifacts](https://github.com/jeffvli/feishin/actions/runs/5226935765). Otherwise a new release will be coming soon with the fixes.

**Comment by OriginCode** [comment]
> This is fixed on the latest development builds, which you can [download here via the build artifacts](https://github.com/jeffvli/feishin/actions/runs/5226935765). Otherwise a new release will be coming soon with the fixes.

It seems that it just clips the image to force it become a square, it works but I still hope that I can have the whole image :(

**Comment by jeffvli** [comment]
Oh yeah sorry I missed that part of your issue.

This can be added.
