### ISSUE TITLE
Shorcut to always open search in fullscreen

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#141]
## What do you want to be added?
Add a shortcut (Shift + Enter) that would trigger the full search command. This would make it a lot easier to do a full search just using the keyboard.

## Additional context
![image](https://github.com/jeffvli/feishin/assets/74906541/82d5ef94-5c3a-411c-bbce-bb6f5539279a)

**Comment by kgarner7** [comment]
If by full search command you mean `Global search`, then that is already a feature, which defaults to `mod + k`. You can tweak this in `Settings > Hotkeys > Global search`
![image](https://github.com/jeffvli/feishin/assets/17521368/f315ca2c-282a-43f8-aa55-4583553daba2)

**Comment by isle9** [comment]
This wasn't really about opening the global search. This was about shortcuts while being in the global search already. If I remember correctly, pressing enter used to open the first entry in the search popup instead of opening the command the search command at the bottom (seems to be changed now though).

**Comment by isle9** [comment]
Seems like there's been a misunderstanding. I didn't say that it wasn't fixed. I just clarified that it wasn't about the global search hotkey.

**Comment by kgarner7** [comment]
Ah, my bad. It does look like pressing enter on a highlighted section does open the item, so that should hopefully satisfy your request
