### ISSUE TITLE
Feishin doesn't reopen if closed to tray after re-launch

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#145]
## Expected Behavior

I expected the app to reopen the previously opened instance that was closed to tray. This is how it worked in the previous version.

## Current Behavior

Looking at my system tray it seems to open a new instance, then close that one and ends there instead of reopening the old instance.

## Steps to Reproduce

1. Open Feishin.
2. Close it to tray.
3. Try to open it again.
4. Nothing happens.

## Your Environment

- Application version (e.g. v0.1.0) : 0.2.0
- Operating System and version (e.g. Windows 10) : Ubuntu 23.04
- Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3

**Comment by gelaechter** [comment]
Do you mean trying to reopen Feishin by relaunching the application instead of using the context menu in the tray?
If so, that should be a simple fix.

**Comment by isle9** [comment]
Seems to be broken again?

**Comment by isle9** [comment]
Can you please reopen? @jeffvli

**Comment by iiPythonx** [comment]
~~Not sure if this is happening in 0.5.3, but in development I don't see this issue on Arch/Cinnamon. If I minimize to the tray and click on Feishin in my dock, it unminimizes like it should with no extra instance getting created.~~

~~Granted, I *do* see this issue on windows which lines up pretty much 1:1 with what you're describing (even on the dev branch).~~

**Comment by isle9** [comment]
> If I minimize to the tray and click on Feishin in my dock, it unminimizes like it should with no extra instance getting created.

Do you click X to close to tray (I'm guessing this is what you are referring to)?

**Comment by iiPythonx** [comment]
> Do you click X to close to tray (I'm guessing this is what you are referring to)?

Woops. I was clicking minimize to tray as I thought that's what you meant. Using the close to tray option, I do get this issue.

**Comment by isle9** [comment]
No need to re-open. It does seem to have been fixed in 0.6.0.

edit: Upon further testing, it actually seems like it still doesn't seem to work...

Only minimize to tray works, but close to tray doesn't as mentioned by @iiPythonx .

**Comment by isle9** [comment]
@jeffvli Please re-open... It's still reproducible.

**Comment by liperium** [comment]
Same here. Can't reopen when in tray.

**Comment by kgarner7** [comment]
This is resolved by https://github.com/jeffvli/feishin/commit/a9e0689619e004b9df62c75471bd2fbae965d5a1. Alternatively, you can also right click and select `Open Main Window` for the next release (or build it yourself)

**Comment by isle9** [comment]
I just wanted to mention that this has nothing to do with clicking on system tray. What doesn't work is trying to re-open Feishin by opening it again through the system menu.

![imagen](https://github.com/jeffvli/feishin/assets/74906541/fe6e1b36-d72c-4104-ac40-2a9100b91542)

Something like this won't re-open it if you close it to tray, but if you minimize it to tray, it will.

> This is resolved by [a9e0689](https://github.com/jeffvli/feishin/commit/a9e0689619e004b9df62c75471bd2fbae965d5a1). Alternatively, you can also right click and select `Open Main Window` for the next release (or build it yourself)

Isn't Open Main Window already implemented?
![imagen](https://github.com/jeffvli/feishin/assets/74906541/a1d9f9b9-9245-456e-bb11-ef35f6385e7c)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/961d1838c0aa20559fe6757761b678aaef729580
