### ISSUE TITLE
[Feature Request] Add option to change buffer size

### ISSUE THREAD

**Issue by Mis1ify** [jeffvli/feishin#147]
## What do you want to be added?
As Reddit user says [https://web.archive.org/web/20220428002302/https://www.reddit.com/r/jellyfin/comments/uar4aa/very_slow_content_loading_with_jellyfin_vs_plex/](url)
`In PlexAmp, there's a setting for changing the number of tracks to cache to your client's RAM.`
It would be awesome to set that in Feishin!

**Comment by kgarner7** [comment]
If you are using MPV, you can pass in certain options to do this. See [cache settings](https://mpv.io/manual/master/#cache) and `--demuxer-max-back-bytes` and `--demuxer-max-bytes` ([demuxer settings](https://mpv.io/manual/master/#demuxer))

**Comment by kgarner7** [comment]
I'll note a couple of things:
1. In terms of tracks that Feishin caches, there are only at most 2 songs the queue (both MPV/web audio)
2. For MPV, there are ways to limit the cache (noted above). For Web/HTML `<media>`, that's mostly up to the browser for how much it fetches.

Given 1 and 2, I would consider this resolved. If you are still seeing a problem with skip delay, please feel free to reopen!
