### ISSUE TITLE
Add indicator to played song in album/playlist view.

### ISSUE THREAD

**Issue by Filip-Sutkowy** [jeffvli/feishin#152]
## What do you want to be added?
indicator to played song in album/playlist view

## Additional context
In sonixd played song was highlighted in album/playlist view.
![image](https://github.com/jeffvli/feishin/assets/24491499/8823c507-3c15-476d-8e92-88997a1f847f)

In feishin it is only visible in queue panel.
![image](https://github.com/jeffvli/feishin/assets/24491499/4ed825ca-29fc-4bf3-ba55-a809dc6847bb)

**Comment by jeffvli** [comment]
Same as #178.
