### ISSUE TITLE
Track Within Album Repeats After Being Played

### ISSUE THREAD

**Issue by Lanklow** [jeffvli/feishin#166]
## Expected Behavior

Songs within an album play once, sequentially.

## Current Behavior

Twice, I had songs within albums repeat; where the lyrics would be for the next track, but the audio would just be the same as the track previous. Both instances happened to be the second track repeating. The second track also still only appears once in the queue. I can work around the issue by skipping to the previous track, then skipping forward again.

## Steps to Reproduce

1. Press play on album

2. Listen through first and second track

3. Second track repeats when the third should start playing.

## Context

I want to listen to an album without songs repeating.

## Your Environment

- Application version: v0.2.0
- Operating System and version: Arch Linux
- Server and version: 0.49.3

**Comment by Gecked-Deck** [comment]
I wasn't able to recreate this, do you have context on how it actually happened?

**Comment by Lanklow** [comment]
> I wasn't able to recreate this, do you have context on how it actually happened?

I have no idea. I just hit play on an album, and the problem occurred.

**Comment by shangyuj** [comment]
I encountered a similar problem. When I play albums with only one song (singles), the song repeated after finishing playing. When the song repeated, the stop button also stopped working. I was using Web as the audio player.

**Comment by drakethecake** [comment]
I have this issue in both v0.2.0 and v0.3.0. I think the problem is caused by having "loop=yes" in my mpv.conf file. Changing it to loop=no (or just removing the setting) seems to fix the issue after restarting feishin.

**Comment by kgarner7** [comment]
I believe this should be resolved with https://github.com/jeffvli/feishin/commit/fdff79496a7067f994e666a36683563e99703acf, are you still seeing this issue?

**Comment by Lanklow** [comment]
> I believe this should be resolved with [fdff794](https://github.com/jeffvli/feishin/commit/fdff79496a7067f994e666a36683563e99703acf), are you still seeing this issue?

You're right. No problems with this for a while now. Just forgot to close the issue. :)
