### ISSUE TITLE
Spectrum

### ISSUE THREAD

**Issue by Mis1ify** [jeffvli/feishin#169]
## What do you want to be added?
![image](https://github.com/jeffvli/feishin/assets/111151942/ad5e9708-6fa2-4aa4-b400-8962c985d91b)
It would be cool if you could open some kind of visualizer like this one.

**Comment by signalno11** [comment]
I definitely would like this. Guess I'm learning react

**Comment by kgarner7** [comment]
Closed with #314. Note that this is web audio only, no plans for supporting MPV
