### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by misaka10384** [jeffvli/feishin#171]
Do you plan to develop an Android version	¿

**Comment by jeffvli** [comment]
No plans for Android (or any mobile apps).

I don't have the skills necessary for mobile development, and there are plenty of mobile apps available for Jellyfin and Navidrome.

Examples:

- [Symfonium](https://symfonium.app/)
- [Tempo](https://github.com/CappielloAntonio/tempo)
- [Finamp](https://github.com/jmshrv/finamp)
- more...
