### ISSUE TITLE
Default to the web-backend instead of mpv, or provide an easy way to disable mpv on first start.

### ISSUE THREAD

**Issue by jixunmoe** [jeffvli/feishin#177]
## What do you want to be added?

Change the default behaviour of asking the user to select mpv executable to defaulting the Web backend without asking.

Current behaviour, the very first launch will ask for the path to `mpv.exe`:

![image](https://github.com/jeffvli/feishin/assets/5713045/0db52097-28fc-4d2a-b8c8-b168d98c6126)

It could be simply a button, `[ Use web-backend for music playback ]`, with some explanation why MPV is recommended.

## Additional context

To me, the web backend works perfectly fine as I had all my library pre-encoded in `m4a/aac-lc`. Though I am not sure about the reasoning behind the idea to default to mpv.

It would also be a good idea to search the `PATH` environment variable and populate it when found. I had it installed via [`scoop`](https://scoop.sh/#/apps?q=mpv&id=b05b47128464d8969416289383fbfc69a47353e3) and the binary directory was available in my PATH environment - `%USERPROFILE%\scoop\apps\mpv\current\mpv.exe`. It would be nice if I can just click "next" to continue.

**Comment by thomaschampagne** [comment]
> It could be simply a button, `[ Use web-backend for music playback ]`, with some explanation why MPV is recommended.

Totally agree. I had to install **mpv** to switch to **web** next (mpv didn't play tracks on my win10)

> It would also be a good idea to search the `PATH` environment variable and populate it when found. I had it installed via [`scoop`](https://scoop.sh/#/apps?q=mpv&id=b05b47128464d8969416289383fbfc69a47353e3) and the binary directory was available in my PATH environment - `%USERPROFILE%\scoop\apps\mpv\current\mpv.exe`. It would be nice if I can just click "next" to continue.

I also installed mpv using scoop (since I dropped chocolatey cause not open-source...). Scoop is an official way to install it: https://mpv.io/installation/

I encoutered same issue.

Thanks for the GREAT WORK 👍  !!
