### ISSUE TITLE
Genres not displaying correctly on Navidrome 0.4.9.3 server

### ISSUE THREAD

**Issue by SStelioss** [jeffvli/feishin#183]
## Expected Behavior

When I click on the genres, i should get a list of genres I can browse.

## Current Behavior

Clicking on the genres button gives me this screen.

![image](https://github.com/jeffvli/feishin/assets/90136900/9c43f5a4-e876-4cf8-bf4c-bde3ed9f8dc5)

In addition, clicking on genres in an album just boots me back to the full album list.

## Steps to Reproduce

1. Make a navidrome server

2. Click on genres with genre tagged music

3. Bug

## Possible Solution (Not obligatory)

I assume this is a mismatch between the subsonic API and the navidrome one? I'm not sure. Either way, modifying feishin to use the Navidrome URL might work? For example:

filter={"genre_id":"0553c943-129b-4426-913e-538723b49ad7"}

At the very least this might work as a stopgap solution? I'm not familiar with how this works, to be honest.
## Context

I was trying to display genres on my machine and play music based on genre.

## Your Environment

I'm playing on a navidrome server from a raspberry pi that's accessing an NFS server, forwarded on nginx. The navidrome server accessed from the WebUI displays genres correctly

-   Application version (e.g. v0.1.0) : 0.2.0
-   Operating System and version (e.g. Windows 10) : Arch Linux on KDE. I've also been able to reproduce this on my windows 10 machine
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3

**Comment by jeffvli** [comment]
The genres page isn't implemented yet which is why you see that page. It'll be implemented in the next version. #3
