### ISSUE TITLE
[BUG REPORT] Last.fm scrobbles not submitting to Jellyfin

### ISSUE THREAD

**Issue by adriqnb** [jeffvli/feishin#186]
## Expected Behavior

Songs played through Feishin get scrobbled through Jellyfin.

## Current Behavior

When playing back music and finishing half the song/240 seconds of the song, scrobbles do not seem to get submitted. Not a problem with the Last.fm plugin as playing back through the Jellyfin web player submits scrobbles successfully.

## Steps to Reproduce

1. Setup settings in Feishin to allow scrobbling

2. Play back a song to the end

## Context

Trying to track my scrobbles while using Feishin.

## Your Environment

-   Application version (e.g. v0.1.0) : v0.2.0
-   Operating System and version (e.g. Windows 10) : Windows 10
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin v10.8.10

**Comment by jeffvli** [comment]
I'm not seeing any scrobbling issues on my side. Can you try the following?

1. Toggle the "scrobble" setting in Feishin off and then back on
2. Update the last.fm plugin to the latest version via Jellyfin web (v8.0.0.3)
3. Begin song playback on Feishin and check that the status is displayed on Jellyfin's web dashboard. This is the important part, as Jellyfin's lastfm plugin directly uses Jellyfin progress events to determine its scrobbling

**Comment by adriqnb** [comment]
This is interesting...
Did everything that you suggested, the status was showing up and it seemed it should have been working. However, once I checked "Sync favourites for this user?" box in the Last.fm plugins settings, scrobbles began to go through. Seems to be an issue with the plugin itself then, will post a bug report there.

Thank you for the help!
