### ISSUE TITLE
Request: Personal mix

### ISSUE THREAD

**Issue by dillfrescott** [jeffvli/feishin#188]
Symfonium has a feature that plays similar songs in an on demand created playlist. It would be nice if feishin had this.

**Comment by yashaskm11** [comment]
This would be a good feature and also endpoints are already available on both Navidrome [(Subsonic)](https://www.subsonic.org/pages/api.jsp#getSimilarSongs2) and [Jellyfin](https://typescript-sdk.jellyfin.org/classes/generated_client.InstantMixApi.html#getInstantMixFromItem).
Hoping this would be considered.

**Comment by kgarner7** [comment]
This is available as of https://github.com/jeffvli/feishin/pull/650
