### ISSUE TITLE
Macbook M1: Fails to playback any audio from Navidrome server

### ISSUE THREAD

**Issue by foxdavidj** [jeffvli/feishin#189]
## Expected Behavior

Once clicking play on a given track, audio should begin to play and the playback seeker should begin to progress forwards each second

## Current Behavior

The entire app loads wonderfully. It connects to my Navidrome server, loads all the images, playlists, favorites, song metadata (like tags and length). However once i click on a song to play nothing happens. I can tell that the frontend responded to my request as the album art and title appear in the bottom left, but no sound plays and the playback seeker stays at 00:00.

I have tested on my windows computer and the app works flawlessly. So it appears to be either a mac or apple silicon problem.

## Steps to Reproduce

1. Log into Navidrome server on Feishin on a Mac M1

2. Play any song. No sound will play

## Your Environment

-   Application version (e.g. v0.1.0) : 0.2.0
-   Operating System and version (e.g. Windows 10) : Ventura 13.5; Apple M1 Pro 32GB
-   Server and version (e.g. Navidrome v0.48.0) : 0.49.3

**Comment by jeffvli** [comment]
Can you try out [this solution](https://github.com/jeffvli/feishin/discussions/139) that was posted?

**Comment by foxdavidj** [comment]
Followed the instructions, and now when i press play it flickers between pause and play every millisecond. Quite a wild sight to see. So progress, but not quite a fix yet.

Swapping to using the Web player worked perfectly, though.

**Comment by jeffvli** [comment]
You can also try running [this command](https://github.com/jeffvli/feishin/issues/104#issuecomment-1553914730) to remove the mpv files from quarantine like posted in the other thread.

**Comment by witchcraftsman** [comment]
Works just fine with M1 Pro, app version 0.20, navidrome v0.49.3, mvp v0.36.0.
Check your MVP path in the app, it should be something similar to `/opt/homebrew/Cellar/mpv/0.36.0/bin/mpv` if you installed it with homebrew

**Comment by foxdavidj** [comment]
Ah, running `xattr -r -d com.apple.quarantine /Applications/mpv/Contents/MacOS/mpv` seems to have done the trick. It's working well now
