### ISSUE TITLE
Change playlist order

### ISSUE THREAD

**Issue by IceWreck** [jeffvli/feishin#190]
## What do you want to be added?

Ability to edit playlists and change their sort order, just like the one in sonixd.

## Additional context

I'm using Navidrome.

**Comment by tcurdt** [comment]
Is this meant for the playlists? or the songs inside a playlist?

**Comment by IceWreck** [comment]
The songs inside the playlist, sorry if that wasnt clear.

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/10fca2dc12795248c17b5416cf5a093e3e731ee1
