### ISSUE TITLE
Songs don't play and are stuck at 0:00

### ISSUE THREAD

**Issue by xkevinx** [jeffvli/feishin#197]
Hi! Sorry the issue is most probably on my side but I cannot get any song to play.

## Expected Behavior

Expected behavior would be to play the song once I press play

## Current Behavior

I can see that the Play button has changed state, but nothing else happens

<img width="472" alt="image" src="https://github.com/jeffvli/feishin/assets/22234781/888732a5-ba9a-45a7-a88f-01ca0dd7d74a">

## Steps to Reproduce

1. Open the app

2. Press play on an album

## Context

This is my very first time using Feishin, it seems that all my albums are loaded so it doesn't seem to be a network issue

## Your Environment

-   Application version (e.g. v0.1.0) : 0.2.0
-   Operating System and version (e.g. Windows 10) : MacOS Ventura 13.5
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3
-   Node version (if developing locally) :

**Comment by jeffvli** [comment]
Can you try all the troubleshooting steps listed in [this thread](https://github.com/jeffvli/feishin/issues/189)?

**Comment by xkevinx** [comment]
ah sorry I didn't find that thread when searching, it has worked, thanks!

For anyone else coming on the topic, what worked for me was updating mpv.app to mpv and then run `xattr -r -d com.apple.quarantine /Applications/mpv/Contents/MacOS/mpv`.
