### ISSUE TITLE
Tracks empty on 0.3.0

### ISSUE THREAD

**Issue by Toxithot** [jeffvli/feishin#198]
## Expected Behavior

Tracks should show tracks

## Current Behavior

Tracks does not show tracks

![image](https://github.com/jeffvli/feishin/assets/81329262/18893b32-163e-4a97-bd81-c0092257e3e9)

## Steps to Reproduce

1. open feishin

2. select tracks from sidebar

3. see nothing

## Possible Solution (Not obligatory)

not a 100% sure what i'm looking at here, but there doesn't seem to be a div for the tracklist itself, i am able to enqueue the entirety without issue, and they play just fine, however there's simply nothing showing in the tracks list, which was not the case with the prior release

## Context

unable to search for individual tracks, as there's no display in the center

## Your Environment

-   Application version (e.g. v0.1.0) : 0.3.0
-   Operating System and version (e.g. Windows 10) : windows 10 pro
-   Server and version (e.g. Navidrome v0.48.0) : navidrome 0.49.3
-   Node version (if developing locally) : 20.5.0

**Comment by isle9** [comment]
Same with genre lists.

![image](https://github.com/jeffvli/feishin/assets/74906541/c9fc511c-d625-4b96-9315-b7d20701fa8c)

**Comment by jeffvli** [comment]
This is probably the result of me removing the `Table (Paginated)` view. Can you go into the config at the top right and select the `Table` view?

**Comment by rkowalsk** [comment]
I had the same problem, the tracks appeared after selecting the `Table` View.

**Comment by Toxithot** [comment]
> This is probably the result of me removing the `Table (Paginated)` view. Can you go into the config at the top right and select the `Table` view?

this solved the issue, thanks!
