### ISSUE TITLE
Drag and Drop Titles

### ISSUE THREAD

**Issue by MaZe3D** [jeffvli/feishin#200]
## What do you want to be added?
I would like to drag and drop titles from the library to the playing queue and playlists, similar to files in the filebrowser can be dragged to folders. The best would be if this would be possible form everywhere. 
Like those scenarios:

- songs from Playlists to other Playlist on the left side or the queue
- Albums from the Homepage to the playlist or queue
## Additional context

Like selecting songs on the playlist, album or artist view and dragging them to the queue and other playlists.

![image](https://github.com/jeffvli/feishin/assets/45102464/f15d0445-6e43-4a34-baeb-a32dd2b73158)

I hope you understand what I mean. Have a lovely day.

**Comment by jeffvli** [comment]
It's on my to-do list, though I'm going to close this in favor of #79.

**Comment by MaZe3D** [comment]
Oh sorry I didn't found the other one. Happy to hear this is already a topic. Great Player by the way.
