### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by shishkin** [jeffvli/feishin#203]
## What do you want to be added?

A "Back" button at the top left of the window, like in a web browser or Spotify.

## Additional context

I used to like the back button in Spotify. It is very convenient to jump to some album or artist from a search, add a few songs to the queue and go back to the search results. I'm just very used to stack-based UIs like web browsers.

**Comment by jeffvli** [comment]
The back buttons already exist if you use the non-collapsed sidebar. If you used the collapsed sidebar, then you only have access to it via the "Menu" dropdown, or you would have to utilize other native hotkeys like forward/backward buttons on your mouse.

**Comment by shishkin** [comment]
Thanks, I collapsed the sidebar and didn't notice back button was there. Maybe it would be better to make navigation buttons more prominent in the main content area? Here is how they look like in Spotify:

<img width="640" alt="Screenshot 2023-08-09 at 17 55 27" src="https://github.com/jeffvli/feishin/assets/124065/fae966b8-f6e1-4af2-a9b2-05b8edc6962c">

**Comment by jeffvli** [comment]
I don't want to break the current layout of the app so I decided to add navigation buttons directly in the collapsed sidebar as well. It will be the first item, above the menu button.

![image](https://github.com/jeffvli/feishin/assets/42182408/9dc9b140-731d-47ed-a83b-031c56eb355b)
