### ISSUE TITLE
Incorrect album times/lengths since recent update

### ISSUE THREAD

**Issue by Optekah** [jeffvli/feishin#205]
## Expected Behavior

Time should display correct length

## Current Behavior
Every album in the library shows wildly incorrect time lengths

![1](https://github.com/jeffvli/feishin/assets/141325652/61b63fbe-097b-40ce-a010-ba5a2a63a8dd)

## Steps to Reproduce

1. Open app on Windows 11

2. Click on any album

## Your Environment

-   Feishin version 0.3.0
-   Microsoft Windows 11: Pro Education (22H2)
-   Navidrome version 0.49.3 (8b93962f)

**Comment by jeffvli** [comment]
Seems like #191 broke this.

**Comment by northamerican** [comment]
i can reproduce using navidrome as server. https://github.com/jeffvli/feishin/pull/191 might not be the only culprit.

**Comment by tsnavi** [comment]
![image](https://github.com/jeffvli/feishin/assets/145156860/46631427-a836-44ab-bb5f-e9c8a5d9524b)
Happening for me also (wish this was 15 days long! 😁)

**Comment by jeffvli** [comment]
This is fixed on the development branch, just pending release!
