### ISSUE TITLE
No longer able to drag app window around the desktop when using Web (Hidden) bar style

### ISSUE THREAD

**Issue by Optekah** [jeffvli/feishin#206]
## Expected Behavior

Application should be fully moveable on the desktop as it was on 0.2.0

## Current Behavior
When using the window bar style known as "Web (hidden)" and attempting to view certain tabs and pages within the app, the window locks up when the top bar is clicked and held with a mouse, making it impossible to move the app around the desktop. It appears to work fine when viewing the `Albums`, `Artists`, and `Genres` tab from the left hand menu, but not from the `Home` tab, or when you are anywhere else in the app such as viewing a specific artist page or an album page. This also appears to only apply to this particular window bar style.

![navi 3 0 - no longer to drag window around desktop from 'home' tab, or from album pages, only other tabs, like artists tab or when viewing a discography from an artist](https://github.com/jeffvli/feishin/assets/141325652/e6c7c08f-c39b-44d0-86cf-7abcb74065b9)

## Steps to Reproduce

1. Open app on Windows 11

2. Settings > Window > Window bar style > Web (hidden)

3. Navigate to either the home screen, a specific album page, or a specific artist page and try to drag the app by the top bar area of the app around the desktop.

## Your Environment

-   Feishin version 0.3.0
-   Microsoft Windows 11: Pro Education (22H2)
-   Navidrome version 0.49.3 (8b93962f)

**Comment by BlackDragon-B** [comment]
I did some testing and it seems that the divs are preventing users from being able to drag the window.

**Comment by Optekah** [comment]
Edit: I'm dumb

**Comment by jeffvli** [comment]
> This has broke again with the new 0.4.1 version, just a heads up

Still works on my side. Anyone else having trouble with it?

**Comment by iiPythonx** [comment]
Also works for me on 0.4.1, I can't find any pages that don't let you drag from the topbar.
