### ISSUE TITLE
Last track in queue is not scrobbled

### ISSUE THREAD

**Issue by JortRoelofs** [jeffvli/feishin#207]
## Expected Behavior

When playing a queue, consisting of an album for example, all tracks are expected to be scrobbled properly.

## Current Behavior

When playing a single track or a queue, the single track or last track in the queue are not scrobbled properly most of the time. I can see in the access log of my Navidrome webserver that a scrobble request is passed to the server API with submission=false, probably to indicate the track that is currently playing. Then, whenever the next track comes on, an API call is made for the played song with submission=true to write the scrobble and a second call is made with submission=false to register the next song that is playing. However, when the last song in the queue has ended, there's (almost) never a scrobble API call made.

## Steps to Reproduce

1. Turn on scrobbling, both on Navidrom as in Feishin.
2. Play an album or any queue of songs.
3. Let scrobbles be registered by the application.
4. The final song is then never scrobbled.

## Possible Solution (Not obligatory)

N/A

## Context

Because of this bug my scrobbles on LastFM don't get registered properly.

## Your Environment

-   Application version (e.g. v0.1.0) : the bug persists both on v0.2.0 and v0.3.0
-   Operating System and version (e.g. Windows 10) : Windows 10
-   Server and version (e.g. Navidrome v0.48.0) : Navidrom v0.49.3
-   Node version (if developing locally) : N/A

**Comment by JortRoelofs** [comment]
To add: I just discovered scrobbles are also not properly being registered when a song is on repeat. Just like with the other example, a call to the scrobble view of the Navidrome API is never made.

**Comment by nrlght** [comment]
I can confirm this happens on a Jellyfin server too.

**Comment by jeffvli** [comment]
Fixed in #269
