### ISSUE TITLE
First selected track upon a hard launch fails to play via MPV

### ISSUE THREAD

**Issue by Optekah** [jeffvli/feishin#210]
## Expected Behavior
The first initial track selected upon launching Feishin should play back properly

## Current Behavior

When using MPV as the audio player, upon a standard hard launch of the app, the first track selected never seems to play. 
It will show the track stuck at 0:00, but the play/pause button will indicate it is actually playing when in fact it isn't.

![0](https://github.com/jeffvli/feishin/assets/141325652/3b2aca4c-2173-43d9-b291-5861331bfcd3)

This only applies to when the app is completely closed, and freshly launched (not simply closed to the Windows tray).

The only way to get the desired track to play it to press the dedicated stop button, then play it again, or to simply select a different track entirely (which always works) then go back to the original track you wanted to hear.

It does not matter what track is selected, what type of audio format it is, or even where the track is selected from. This happens from the home screen, a specific album page, playlists, and so on.

On my end, the fail rate is 100% when using MPV as the audio player. 

I switched to Web as the audio player in the desktop app, and this does indeed "solve" the issue, but the trade off there is that the Web audio player comes with an even worse bug for me, which is that when an album ends, it will simply go back to the first song on the album and repeat itself endlessly, even though the repeat toggle has never been turned on. I would assume that would be another bug worth submitting.

## Steps to Reproduce

1. Settings > Playback > Audio player > MPV
2. Exit Feishin entirely and hard launch the program 
3. Select any track from any location

## Context

The end goal is to have the first track play back properly when initially launching the program

## Your Environment

-   Feishin version 0.3.0
-   Microsoft Windows 11 Pro Education (22H2)
-   Navidrome version 0.49.3 (8b93962f)

Thanks :)

**Comment by jdewoody71** [comment]
Wanted to throw my hat in on this. I've been having this issue too, even in the previous version.

**Comment by Optekah** [comment]
> even in the previous version.

Yeah, I forgot to mention that this happens in 0.2.0 as well. Good to know this isn't just me then!

**Comment by jeffvli** [comment]
I'm aware of this issue and it has unfortunately been here since adding the mpv implementation. I've tried various fixes but unfortunately I think it stems from the library I'm using for mpv playback.

I may try switching to a different library to fix this.

**Comment by Optekah** [comment]
> I may try switching to a different library to fix this.

Sweet, thanks!

**Comment by northamerican** [comment]
on a mac, i couldn't get mpv to work at all and only after did i realize there is a web option. why not get rid of the mpv dialog on initial run and make the web player the default, keeping the settings for mpv for advanced users?

**Comment by CataIana** [comment]
Hello, unfortunately I am still experiencing this issue.

Using Windows 10, all latest versions of navidrome, feishin and mpv (weekly).
Attached log in case it can help
[feishin_log.txt](https://github.com/jeffvli/feishin/files/12720652/feishin_log.txt)

**Comment by jeffvli** [comment]
@CataIana Are you using the `Save play queue` setting? If so, that is still broken regarding first start playback.

**Comment by CataIana** [comment]
@jeffvli Yes I am, although I did also try with save play queue off, and had the same issue.

Log does show something different with that option turned off though.
[save_queue_off.log](https://github.com/jeffvli/feishin/files/12720781/save_queue_off.log)

Edit: It actually just seems that the button state does not match the player state, pausing and unpausing makes it play, so nevermind.

**Comment by Optekah** [comment]
Just did a fresh Windows install and this is now an issue on my end again, oddly enough. 

I have confirmed that I am not using the `Save play queue` setting.

Feishin 0.5.3
Navidrome 0.50.2 (823bef54)
Unraid server
Microsoft Windows 11 Pro Education (23H2)


Thanks!!

**Comment by CoordSpace** [comment]
I've been experiencing the same issue on both of my windows systems for months now. 

Navidrome doesn't seem to know that anything weird is happening when looking at the logs and the issue doesn't happen with other Navidrome/subsonic clients like SonixD or supersonic. Is there any way to get more debug information out of Feishin to help track down the problem?

Feishin 0.5.3 - Save play queue is not enabled.
Navidrome 0.50.1-SNAPSHOT (6f7b4820)
Windows 10 LTSC Version 10.0.19044 Build 19044 & Windows 10 Professional Version 22H2

**Comment by M-Ryba** [comment]
Hi,
I'm also experiencing this issue, both with "Save play queue" turned on and off.
Windows 11 22H2
Feishin 0.5.2
Navidrome 0.50.2
