### ISSUE TITLE
New icon has poor visibility on light backgrounds

### ISSUE THREAD

**Issue by rbrunt** [jeffvli/feishin#211]
## Expected Behavior

Logo should be clearly visible on all backgrounds, since we don't know what background it will be rendered on in user's computers.

## Current Behavior

The new Feishin logo is nice, but when it's on a light background (like it is on my Win 11 taskbar), it's hard to see because it's white on a light background. (See screenshot below as an example)

![image](https://github.com/jeffvli/feishin/assets/1533730/2bf55f41-73e9-4a17-bedc-06c7a8400fa5)

## Steps to Reproduce

1. Set taskbar to a light background
2. Feishin logo is hard to see

## Possible Solution

Add a black outline to the logo so that it's clear on both light and dark backgrounds. I'm happy to do this, but can't find the 'source' files for the logo in the repository, just the rendered png/ico versions.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.3.0
-   Operating System and version (e.g. Windows 10) : Windows 11
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3
-   Node version (if developing locally) : n/a

**Comment by jeffvli** [comment]
A background is planned for the new logo!

**Comment by northamerican** [comment]
consider using https://github.com/jeffvli/feishin/issues/232 as the app icon in the meantime

**Comment by jeffvli** [comment]
Resolved in #232
