### ISSUE TITLE
Column adjustments don't save after restarting the app

### ISSUE THREAD

**Issue by Optekah** [jeffvli/feishin#212]
## Expected Behavior

Columns that have been adjusted to the users liking should be saved when the app is relaunched, not reverted to the default experience.

## Current Behavior

After adjusting and removing certain unneeded column headers, they only stay that way until the app is restarted.

![0](https://github.com/jeffvli/feishin/assets/141325652/7e3b1b08-7fd6-4c89-88ed-18e57071e4b5)

## Steps to Reproduce

1. Select an album

3. Use the gear icon on the right to remove and customize column headers

4. Hard quit the app

5. Restart the app

6. Visit another (or the same) album

## Context

Honestly loving the idea and ability to clean up my album pages by using this feature, but it's unfortunately a bit pointless in its current state.

## Your Environment

-   Feishin version 0.3.0
-   Microsoft Windows 11 Pro Education (22H2)
-   Navidrome version 0.49.3 (8b93962f)

**Comment by jeffvli** [comment]
I noticed this after I already pushed 3.0... it'll be fixed soon.

**Comment by Optekah** [comment]
> I noticed this after I already pushed 3.0... it'll be fixed soon.

Sweet, thanks mate! Appreciate the hard work

**Comment by kgarner7** [comment]
Marking this as resolved!
