### ISSUE TITLE
Artist images no longer populate in 0.3.0

### ISSUE THREAD

**Issue by Optekah** [jeffvli/feishin#213]
## Expected Behavior

Artist images should display the "artist.jpg" image found in the relevant file folder on the corresponding artist page in Feishin

## Current Behavior

Artist images no longer show on their pages, nor via search results, nor through related artists links.

I restarted Feishin, rescanned the Navidrome library, restarted Navidrome entirely, and also restarted my server, but the issue still persists.

### _Below is a screenshot of 0.3.0:_
![0 3 0 Navi](https://github.com/jeffvli/feishin/assets/141325652/a45da9f0-8d45-4f10-b349-da2fa7182b46)

### _And here is a screenshot of 0.2.0:_
![0 2 0 Navi](https://github.com/jeffvli/feishin/assets/141325652/b36b7981-bb73-4f4b-ae9b-c1ba09964161)

## Steps to Reproduce

1. Update to 0.3.0

2. Navigate to an artist page

## Context

End goal is to help users identify artists easier via visual cues instead of relying purely on text.

## Your Environment

-   Feishin version 0.3.0
-   Microsoft Windows 11 Pro Education (22H2)
-   Navidrome version 0.49.3 (8b93962f)

**Comment by Turtlepoker** [comment]
I had a similar issue. If I click on artist the artist doesn't load initially. If a go back after a minute the artist photo does load correctly. However, no photos in similar artist ever load correctly.

- using feishin portable win 64
- Windows 10 Student Edition (22H2)
- Navidrome 49.3

**Comment by Optekah** [comment]
> However, no photos in similar artist ever load correctly

Interesting. That definitely doesn't work for me. Did you try manually clearing the cache in %appdata% ?

I tried that and it didn't work either but maybe you'll have better luck.

**Comment by jeffvli** [comment]
> I had a similar issue. If I click on artist the artist doesn't load initially. If a go back after a minute the artist photo does load correctly.

The artist image showing later behavior is due to Navidrome only fetching artist images from spotify after the API endpoint is accessed. After it has been fetched once, it'll be cached directly to your Navidrome server.

> However, no photos in similar artist ever load correctly.

I accidentally broke this in 3.0, I've already pushed a fix on the development branch which I'll likely push in a couple days.
