### ISSUE TITLE
ReplayGain mode not persisting

### ISSUE THREAD

**Issue by b1n4ry5010** [jeffvli/feishin#216]
## Expected Behavior

ReplayGain mode should persist between application sessions.

## Current Behavior

When setting ReplayGain mode, it will only apply until the application is closed. Once reopened, the application seemingly ignores the selected ReplayGain mode until it is changed again.

## Steps to Reproduce

1. Set ReplayGain to Album or Track

2. Close app

3. Open app

4. Play music – ReplayGain will be ignored despite mode being Album/Track, until the mode is selected again

## Your Environment

-   Feishin v0.3.0
-   MacOS Ventura 13.3.1
-   Navidrome [0.49.3]

**Comment by churipputori** [comment]
Noticed this problem too. A workaround for the time being would be to put `--replaygain=album` (or track if you so desire) in MPV parameters and then restart Feishin.

**Comment by b1n4ry5010** [comment]
That works perfectly, thanks!

**Comment by kgarner7** [comment]
This should be resolved by https://github.com/jeffvli/feishin/pull/222
