### ISSUE TITLE
UI/UX related feedback

### ISSUE THREAD

**Issue by manuel-rw** [jeffvli/feishin#22]
Hello. I have been using Sonixd for quite some while and would like to provide some feedback to the changes in Feishin.

## Favorite button should be added to the payer control menu
The old Sonixd version has this icon, that can be used to favorite the track.
![image](https://user-images.githubusercontent.com/30572287/216777238-036caa0a-d628-42e5-85cc-361cfe188e1d.png)

Feishin does not have this anymore:
![image](https://user-images.githubusercontent.com/30572287/216777274-79538ed9-d26f-4f51-99f1-9bb0b85a75f5.png)

You can still add it to favorites using the context menu though:
![image](https://user-images.githubusercontent.com/30572287/216777288-33135e35-026d-41d9-aafd-4f19f740a035.png)

I think that the button should be added back.

## Adding icons for context modal
The new context modal already looks much better than the old one in Sonixd.
I believe that it could be improved even further using icons, that indicate that the action of that button is.
Windows 11 is doing that already quite well:

![image](https://user-images.githubusercontent.com/30572287/216777358-960d4caa-c6c1-4484-a323-b1cd9a52b7f2.png)

## Inconsistent window tool bar

In Sonixd, the toolbar looks quite cohesive with all other windows and applications:
![image](https://user-images.githubusercontent.com/30572287/216777425-051bd3e9-02ef-488c-8beb-eb8b2f05a06a.png)

The new one is not a mess, but too cluttered in my opinion:
![image](https://user-images.githubusercontent.com/30572287/216777447-33e480ad-dc69-4422-af47-a705b97bc718.png)

I'd suggest that the dark gray background color of the window actions would be expanded to the left:
![image](https://user-images.githubusercontent.com/30572287/216777492-6b0d5503-6ce5-4b05-a42a-b25b8ed28bfd.png)

Perhaps this action menu here should also be moved. It feels out of place in this header and also looks significantly different from the other context menus.
![image](https://user-images.githubusercontent.com/30572287/216777502-53371c77-9d45-4675-be98-2f2730825a04.png)

## High contrast in the navigation bar
The contrast of the black color in the navigation bar is quite extreme.
Perhaps it would make sense to use the same color, which is being used here in the red circle?
![image](https://user-images.githubusercontent.com/30572287/216777577-286eedf2-b658-4425-b5b9-3c389126a690.png)

## Context modal for having more control over your current playing track
In Feishin, this small display already looks much better.
But I'd suggest that it would be possible, to have the same context menu as in the track list, when right clicking this here:
![image](https://user-images.githubusercontent.com/30572287/216777680-16d51338-498c-4338-92d7-1334fa756954.png)

For example, Spotify is already doing that:
![image](https://user-images.githubusercontent.com/30572287/216777723-abbe458e-b39e-4338-a074-24a0f6698236.png)

## A filter, that will return no results, may confuse a user
I was pretty confused, that I didn't get any results when opening the album tab.
Then, I found out, that I was still using a filter, that I had created previously.

![image](https://user-images.githubusercontent.com/30572287/216777787-e904cf4d-4bab-47c8-b236-1a5efce2f9fe.png)

There should be two different things informing the user:
- An indication that a filter is active
- An text or icon that informs the user, that there were no results found

## Rethinking the structure of the window decorator
Personally, I don't like how the filters and sorting is at the very top of the window.
I'd suggest that they would be moved a bit down:

![image](https://user-images.githubusercontent.com/30572287/216778327-7e2333db-9051-465e-adb8-de8e25e9a79c.png)

## Unrounded corners in the queue popover
The design in the popover has no rounded corners.
The buttons at the bottom also look a bit off, especially with that extreme contrast:

![image](https://user-images.githubusercontent.com/30572287/216778419-0dd8e3fa-275d-44a0-986a-ccc59a650505.png)

## Missing stop button and add button in the video controller
Those two buttons are not in Feishin yet:
![image](https://user-images.githubusercontent.com/30572287/216778456-7c1cf89d-05de-4b4c-9153-61132f79fe33.png)

-----------

Otherwise, Feishin is looking pretty great so far.
I donated to Sonixd before and can't wait to see how Feishin will look in the future!

**Comment by jeffvli** [comment]
Hi @manuel-rw, appreciate the feedback!

There's quite a lot to go through, but I'll try to address most of them.

---

- ### Favorite button should be added to the player control menu

This is currently available in the development build which will be coming soon.

---

- ### Adding icons for context modal

Agreed, it looks kind of bare without icons. I've made some changes in my most recent branch (#21) with these additions.
![image](https://user-images.githubusercontent.com/42182408/216820308-8ac7a87a-d2b7-4fe9-a7f2-2fca4972115b.png)

--- 

- ### Inconsistent window tool bar / Rethinking the structure of the window decorator

I decided to try out the design more similar to Spotify with the rewrite, where it omits the typical OS window titlebar. I may end up adding an option to add the titlebar back. 

I'll experiment with adding a dedicated header to the list pages and pushing the filters down. My reasoning for the current design was to try to have as much vertical space as possible for the grid / list, but like your screenshot shows it gets quite a bit squished if used on low resolution screens or if the window size is small.

I'm not sure about adding the currently playing song to the header though, since it wouldn't be consistent on all the pages. If I add the dedicated titlebar back it would go there.

> Perhaps this action menu here should also be moved. It feels out of place in this header and also looks significantly different from the other context menus.

I thought about it, but I actually don't know where else to put it. Maybe somewhere in the sidebar?

---

- ### Context modal for having more control over your current playing track

Also added in the latest release (#21).
![image](https://user-images.githubusercontent.com/42182408/216820945-e76775dd-ee91-45a3-b322-0e740e15b6b1.png)

---

- ### Unrounded corners in the queue popover

I'll round the corners a bit and remove the dar kbackground on the control bar.

---

- ### Missing stop button and add button in the video controller

These will be added, just haven't gotten to it yet.
It will likely be configurable as well as to whether or not they're displayed.

**Comment by manuel-rw** [comment]
> This is currently available in the development build which will be coming soon.

🚀💪

> Agreed, it looks kind of bare without icons. I've made some changes in my most recent branch (https://github.com/jeffvli/feishin/pull/21) with these additions.

Yes, that looks already much better! Thanks

> These will be added, just haven't gotten to it yet.

Very nice, thank you!

> I decided to try out the design more similar to Spotify with the rewrite, where it omits the typical OS window titlebar. I may end up adding an option to add the titlebar back.
> I'll experiment with adding a dedicated header to the list pages and pushing the filters down. My reasoning for the current design > was to try to have as much vertical space as possible for the grid / list, but like your screenshot shows it gets quite a bit squished > if used on low resolution screens or if the window size is small.
> I'm not sure about adding the currently playing song to the header though, since it wouldn't be consistent on all the pages. If I add the dedicated titlebar back it would go there.
> Perhaps this action menu here should also be moved. It feels out of place in this header and also looks significantly different from the other context menus.
> I thought about it, but I actually don't know where else to put it. Maybe somewhere in the sidebar?

Honestly, I didn't really think about the title in the decorator / title bar.
Perhaps it would eliminate titles on the dedicated views as a trade off?
Not sure though if it makes any sense after hearing your point.

I understand your point in having as much vertical space as possible, but I quite dislike how crammed it seems.
The elements at the left have completely other sizing as the ones on the right in the header.
They should be unified or have the same height if possible.

> I thought about it, but I actually don't know where else to put it. Maybe somewhere in the sidebar?

How about displaying the name of the application at the top left with a small settings cog icon besides it?
![image](https://user-images.githubusercontent.com/30572287/216831468-8823f73a-28fc-45e4-95f7-ec965033b604.png)

Let me know if you have any questions! I really like your work :)

**Comment by jeffvli** [comment]
@manuel-rw I've made a sizable amount of design changes in my most recent PR based on what we discussed if you'd like to take a look and provide feedback.

https://github.com/jeffvli/feishin/pull/24

**Comment by manuel-rw** [comment]
Awesome, I will look through it!

**Comment by manuel-rw** [comment]
Okay, so here is my feedback about that nightly version:
- The decorator bar / header already looks much better in my opinion. Is way less crammed and has a very nice seam with the colors from albums or tracks. Only thing I complain a bit about, is that the header seems massive in height. I assume you did that because you wanted to place a big text and the blue play button up there? In my opinion, they should be reduced in size, so the header is smaller
- I think you added the search box at the top right in the header? I like that a lot and it seems like a good place to do it. Only thing I am thinking is, why is there still the disabled "Search" box on the left navigation bar, when it has been moved to the top right? Maybe remove one of them?
- Contrast for the navigation bar still seems quite high. The queue already looks much better though.
- Context menu is looking fancy! Although I would wish the corners would be rounded. Maybe this is just me, but I love it when they are slightly rounded 😅
- Things like this could be avoided:
  ![image](https://user-images.githubusercontent.com/30572287/217623859-b5ce70b0-a010-478b-ad10-5b057621f46a.png)
- I still think that some of this is not necessary here. What about replacing the search box with the logo, move the burger menu to the complete right of the navbar and break the previous and next arrows to a next line?
- Not a major issue, but the colors here look a bit out of place:
  ![image](https://user-images.githubusercontent.com/30572287/217624291-fff5463c-765a-46b9-a204-67c65298ef68.png)
  Perhaps the same colors as in the queue should be used here?
- Still no warning if filters were applied and no results were found. Not a huge priority, but I think it should be implemented at some time.

Otherwise, this is looking more and more promising. One question I'd like to ask: Has the behavior of the playback for albums & artists been changed compared to Sonixd? Sometimes Feishin just stops playing my queue, but it might be my stupidity not noticing why / when.

**Comment by jeffvli** [comment]
> The decorator bar / header already looks much better in my opinion. Is way less crammed and has a very nice seam with the colors from albums or tracks. Only thing I complain a bit about, is that the header seems massive in height. I assume you did that because you wanted to place a big text and the blue play button up there? In my opinion, they should be reduced in size, so the header is smaller

I'll be honest, I'm not sure I can budge on the header size. It's currently set at a fixed 65px for all pages which seems reasonable for modern desktop resolutions. It's also a stand-in for the dedicated titlebar, and matches the navigation section height on the sidebar as well. For reference, Sonixd's dedicated titlebar's height is 32px.

> I think you added the search box at the top right in the header? I like that a lot and it seems like a good place to do it. Only thing I am thinking is, why is there still the disabled "Search" box on the left navigation bar, when it has been moved to the top right? Maybe remove one of them?

The search on the page header for the list pages acts as a local search for the current page's list which is focusable via click or `CTRL + F`. The search on the left hand side isn't implemented yet, but later will act as a global search and command pallete using [cmdk](https://cmdk.paco.me/) or another similar library.

> I still think that some of this is not necessary here. What about replacing the search box with the logo, move the burger menu to the complete right of the navbar and break the previous and next arrows to a next line?

I did test out the logo with burger menu and navigation on a second line, but I personally wasn't a fan of how it looked. The sidebar potentially can be resized to 400px by the user which makes the scaling a bit weird when you only have 2 navigation buttons on a line.

> Not a major issue, but the colors here look a bit out of place:
> Perhaps the same colors as in the queue should be used here?

Which colors in the queue are you referencing? 

> Still no warning if filters were applied and no results were found. Not a huge priority, but I think it should be implemented at some time.

I made some fixes on the loading indication when no items are found so it should display a 0 in the item count on the header. I added the primary color onto the filters button if filters are applied, but maybe it's not visible enough?

![image](https://user-images.githubusercontent.com/42182408/217639444-abfe0557-9304-4770-83bb-164bc96e1d0f.png)
![image](https://user-images.githubusercontent.com/42182408/217639473-09448ab6-5e5e-4461-89de-83d95e09a5d6.png)

> One question I'd like to ask: Has the behavior of the playback for albums & artists been changed compared to Sonixd? Sometimes Feishin just stops playing my queue, but it might be my stupidity not noticing why / when.

I completely rewrote the player behavior, so there's probably still some bugs. I have also noticed some issues with the queue stopping, so I'll try to do some debugging there.

**Comment by isle9** [comment]
Hi, I'd like to add a few of my UI suggestions as well:
1. An option to move favorite and rating buttons either to the middle or to the left
2. Possibly and option to open the right click menu while clicking on the media player bottom bar and/or the album cover art
3. An option to display song genres somewhere in the media player, possibly next to the title, album and artist

**Comment by manuel-rw** [comment]
> which seems reasonable for modern desktop resolutions

It seems huge for me on my screen. It's at least double the height compared to other windows.
Sonixd had the perfect size IMO.

> I added the primary color onto the filters button if filters are applied, but maybe it's not visible enough?

It's already better, but it still might not be clear, since you have to look on this icon, to see it.

**Comment by jeffvli** [comment]
@manuel-rw What resolution is your main display? I may be a bit biased since I'm running on a 1440p display.

**Comment by manuel-rw** [comment]
Main: 3840px x 1080px (32:9)
Secondary: 1920px x 1080px (16:9) 26"
Laptop: 1920px x 1080px (16:9) 15.6"

**Comment by flamwenco** [comment]
I don't _love_ the WIndows style toolbar buttons as a mac user, but I understand cross platform apps need to make design tradeoffs. Is it possible to do something to better indicate the size of the window buttons is correct before you begin scrolling tho? As it stands, I genuinely thought this was a bug until I scrolled down and saw the titlebar slowly fade in
<img width="1549" alt="Screenshot 2023-03-08 at 12 56 20" src="https://user-images.githubusercontent.com/2542062/223793080-a1a5ac42-1d32-4890-9c48-07db0b62b47e.png">

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/2542062/223793239-8edd59fb-28b5-4ea0-8f76-cf41b03c2b68.png">

**Comment by flamwenco** [comment]
Additionally, visually the titlebar does not visually line up with the sidebar header, which from my understanding appears to be the intent; I took a look at the web app and there seems to be a margin offsetting the sidebar header which makes it not line up with the titlebar, which looks weird next to the big play button because the buttons are obviously unaligned.

(If I'm being entirely honest I think the visual size of the sidebar as-is looks much better than the size of the titlebar, and think the title bar would look better _slightly_ smaller with button sizes more in line with the sidebar's)

<img width="822" alt="image" src="https://user-images.githubusercontent.com/2542062/223795597-d1df7af9-92c1-4073-99d5-399fa50145d1.png">
<img width="211" alt="image" src="https://user-images.githubusercontent.com/2542062/223795640-25864d0b-065a-479e-b0fb-f0e1776383a7.png">

**Comment by jeffvli** [comment]
If someone can fork and provide a working example of how they envision the titlebar to look I may be willing to make some adjustments there. I've been trying to do some adjustments on my side to decrease the height but it always ends up looking awkward.


What I have done though is lined up the sidebar and titlebar per your suggestions @flamwenco and also added dedicated OS titlebars which sits on top of the app (similar to Sonixd).

## Windows
![image](https://user-images.githubusercontent.com/42182408/228458775-1fef8690-ad52-4626-adc6-55cbe030a1b7.png)

## macOS
![image](https://user-images.githubusercontent.com/42182408/228458861-7065a2d9-5e5b-4177-b1e9-1db389901cc4.png)

**Comment by manuel-rw** [comment]
> If someone can fork and provide a working example of how they envision the titlebar to look I may be willing to make some adjustments there. I've been trying to do some adjustments on my side to decrease the height but it always ends up looking awkward.
> 
> What I have done though is lined up the sidebar and titlebar per your suggestions @flamwenco and also added dedicated OS titlebars which sits on top of the app (similar to Sonixd).
> ## Windows
> 
> ![image](https://user-images.githubusercontent.com/42182408/228458775-1fef8690-ad52-4626-adc6-55cbe030a1b7.png)
> ## macOS
> 
> ![image](https://user-images.githubusercontent.com/42182408/228458861-7065a2d9-5e5b-4177-b1e9-1db389901cc4.png)

I think this is already much better than before. Not much I would change tbh.

**Comment by flamwenco** [comment]
Yeah I think this looks much, much better

**Comment by jeffvli** [comment]
Added in [0.0.1-alpha6](https://github.com/jeffvli/feishin/releases/tag/v0.0.1-alpha6).

Going to close this for now since the design has mostly been updated. Feel free to provide additional feedback once you test the new version!
