### ISSUE TITLE
emby support

### ISSUE THREAD

**Issue by blackwhitebear8** [jeffvli/feishin#220]
## What do you want to be added?

I would like to have full emby support for this application.

## Additional context

i tried it with my emby server and a lot seems to work already but playlists are not there and some other small buggs are there sadly with search

**Comment by jeffvli** [comment]
Unfortunately I don't plan on supporting Emby.

I'm willing to merge a PR that adds support if anyone else is willing to go through and find the differences between it and Jellyfin.
