### ISSUE TITLE
Can't toggle off the is favorited filter on tracks

### ISSUE THREAD

**Issue by Dylan-G** [jeffvli/feishin#223]
## Expected Behavior

Toggle favorite in tracks filter

## Current Behavior

Can toggle it on but the switch stay on and I can't turn off favorite filter

## Steps to Reproduce

https://github.com/jeffvli/feishin/assets/32327501/ecf1cff3-b19a-404d-bcbd-a280c07b24dc

1. Go to tracks

2. Click on the filter button

3. Click on the switch is favorited

## Context

Filter my tracks

## Your Environment

-   Application version : v0.3.0 
-   Operating System and version: Windows 11
-   Server and version : Jellufin 10.8.10

**Comment by jeffvli** [comment]
Thanks for the report, has been fixed.
