### ISSUE TITLE
Maximum bitrate setting

### ISSUE THREAD

**Issue by K0SS4** [jeffvli/feishin#224]
## What do you want to be added?

I want to have a setting that allows selecting maximum bitrate for audio.

## Additional context

I use navidrome and it has a transcoding option. Many of the android clients have a bitrate setting that (I guess)tells the server to convert the audio to selected bitrate and/or format(like mp3, opus etc.). My navidrome library is mostly 24-bit/48kHz so it's not the best option to play it like that when not on the local network(single file could be like 70MB).

I could also be totally wrong and confused about how feishin really works because I'm an audio newb and in that case I'm sorry :)

**Comment by jeffvli** [comment]
You can currently set it directly in the Navidrome web UI if you go to from the `User Menu` -> `Players`, and set the `Feishin` players transcoding to certain bitrates.

**Comment by K0SS4** [comment]
Oh I didn't see that. Closing the issue, thanks.
