### ISSUE TITLE
Dynamic background is transparent when the cover is Navidrome's default fallback cover image

### ISSUE THREAD

**Issue by OriginCode** [jeffvli/feishin#225]
## Expected Behavior

A blue or fallback color should be used.

## Current Behavior

![image](https://github.com/jeffvli/feishin/assets/17294071/3146ca8c-c581-4cb7-bf77-21b643d65aae)

## Steps to Reproduce

1. Play a song with no cover image, which Navidrome will provide a fallback image instead.

## Possible Solution (Not obligatory)

Add a fallback background color?

## Context

It doesn't look right, as you can see the content below the now-playing interface.

## Your Environment

-   Application version (e.g. v0.1.0) : v0.3.0
-   Operating System and version (e.g. Windows 10) : Windows 11 (as far as I know this also happens in Linux (AOSC OS 10))
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3
-   Node version (if developing locally) : N/A

**Comment by jeffvli** [comment]
Fixed in latest development versions
