### ISSUE TITLE
Play/pause button toggles on and off when changing song

### ISSUE THREAD

**Issue by morrowrasmus** [jeffvli/feishin#230]
## Expected Behavior

When starting playback of a song or changing the song, the next song should play without issues.

## Current Behavior

When changing songs during playback of a song, Feishin will start toggling the play/pause button on and off rapidly, resulting in very choppy playback. This issue sometimes occur at startup with the first song played, but other times I can play the first song without problems. However, in these cases I will need to press "Play" twice for the song to start. If the song ends, the next song will also play correctly. I have also been able to play the next song correctly by first stopping playback of the current song before starting a new one.

## Steps to Reproduce

1. Open Feishin

2. Play a song from the from the overview (Bug sometimes occurs here)

3. Start playback of another song mid-playback.

## Possible Solution (Not obligatory)

No suggestions.

## Context

This is preventing proper playback of songs, so the main purpose of using the application is hindered. 

## Your Environment

Application version: v.0.3.0
Operating System: Tuxedo OS 2
Server: Jellyfin 10.8.10

**Comment by Jaymoon85** [comment]
I too had the same bug (Pop OS running the latest AppImage, connecting to Navidrome server).

I went to **Menu > Settings > Player**.

Changing **Audio Player** to _Web_, then selecting _Default_ **Audio Device**, resolves the rapid Play/Pause behavior.

Switching back to _MPV_ (/usr/bin/mpv) causes the button to rapid fire again, causing the choppy playback.

**Comment by morrowrasmus** [comment]
Can confirm that this resolved the issue, thanks! The issue then seems to be related to MPV. I had that installed through the default apt repository, and judging from their own install instructions, this can be quite outdated. I failed installing an updated version with the mpv-build scripts, so I could not check whether an updated version also would resolve it.

Not sure whether we are sacrificing anything by using the _Web_ audio player, but I am so far not noticing any problems. If it is true that _Web_ is not inferior in any way, I would suggest not placing such a heavy emphasis on setting up MPV when first launching or at least highlighting the possibility of using an alternative method.

**Comment by jeffvli** [comment]
I've seen this issue a few times and it is indeed usually related to the mpv version (or potentially the library I'm using to control it).

There are some significant upsides to using mpv such as gapless playback, replaygain, and being able to use a host of other mpv features. I've been planning on trying to switch to a new mpv library soon so that may be able to fix it eventually.
