### ISSUE TITLE
Conform App Icon to MacOS design principles

### ISSUE THREAD

**Issue by flightmansam** [jeffvli/feishin#232]
## What do you want to be added?
For the MacOS build use a flavour of icons that fits a bit more in the ecosystem (my version supplied).
## Additional context
I have noticed the ongoing trend for apple to push app icons to have that rounded-square design. It has slowly got to me and now my OCD makes me want my dock to have all the same looking design language (DAMN IT Craig Federighi!). I had a go at making an icon set using [IconKitchen](https://icon.kitchen/).
I made two themes, a light version (my preference):
![light](https://github.com/jeffvli/feishin/assets/34013162/d7b89848-2d58-48b1-bbd8-6ed0a536189d)

And a dark version:
![dark](https://github.com/jeffvli/feishin/assets/34013162/e237a90f-69ae-4a21-8b4c-863eb16caac9)

I used the following session in IconKitchen (not sure how long until this link rots):
https://icon.kitchen/i/H4sIAAAAAAAAA2WPMQvCMBCF%2F8u5Oqjo0lXEyUk3cbgmlzQ0bSRpLVL6330JdPICB%2Ffx3rvcTB%2F2oySqZtIc20cjnVBl2CfZkrGP7xsjuY6t0JZqew4%2BRJDNrhSYsTdOLVVDHIvlX1GvMTaydtIPhV3XAatV9uyzyZSCoKBDRuqQHxD31iPmeFrynrti73oLhUKKxPKVizGiBpxDqWEdJoK0C3r0%2BcQnEnQMTkPqQkKfpEbvWGF6LT%2FNdDveDQEAAA%3D%3D

Output files attached below.
[IconKitchen-Output-light.zip](https://github.com/jeffvli/feishin/files/12485660/IconKitchen-Output-light.zip)
[IconKitchen-Output-dark.zip](https://github.com/jeffvli/feishin/files/12485661/IconKitchen-Output-dark.zip)

**Comment by benoitblancquaert** [comment]
Glad I'm not the only one bothered by this. The current icon just does not match the macOS look and feel.

I tried making an app icon in IconKitchen and used a gray gradient as background:

<img width="512" alt="AppIcon" src="https://github.com/jeffvli/feishin/assets/36985718/71126a5e-3789-4917-ba06-6a42e8cfe389">

The gray of the gradient background could then be made equal to the gray colored components (buttons, scrollbar, borders, ...) in the app itself.

**Comment by flightmansam** [comment]
Loving it!

**Comment by benoitblancquaert** [comment]
You're welcome, I'm glad I can help.

Here is the edit link from Icon Kitchen: https://icon.kitchen/i/H4sIAAAAAAAAAzWOQQqDMBRE7%2FK7zcZSKXiBXsBd6eJrftLQxJSkVkRydyeCDAzMYxhmoz%2F7WTJ1G2lOn%2F4tQagz7LMoMrZfv4jkAlshRcMJbGLtZPod7HEGjIzRx9SgcWlMFQoHulbU3quAeLIeM7e2FEUh6tnXC09wnaLTaLiY4YsM8MAj0qvsWzCod60AAAA%3D

If you want to generate it like that, you just need to upload the logo in SVG format and choose the option "macOS icon".

**Comment by flightmansam** [comment]
Maybe a bit of drop shadow around the logo?

https://icon.kitchen/i/H4sIAAAAAAAAAzWOwQrCMBBE%2F2W99lKxCL2LP9CbeNgmmxhMGkmTipT%2Bu5NCWViYx%2BzsrLSwLzJTv5Lm9B5eEoT6nIo0ZOzw%2B0CRC2yFGhoPYBNrJ1Pe2f0QyFDRx9TCcWpNHRh2dK6ou9YB4sl6xFy6rT65GSMqowKJl4WzEHCIuvja6wG3TtFp3Lk4Y39lxA6soJ7bHxf6GinCAAAA

![image](https://github.com/jeffvli/feishin/assets/34013162/40645bdd-015a-44de-90e7-e1b7f3c2fc44)

**Comment by ajwarnick** [comment]
I have been using my own icon for the last six months which is a diversion from the official icon but I thought I would share.
<img width="400" alt="Music Icon@2x" src="https://github.com/jeffvli/feishin/assets/1727737/c578f36c-65f6-4869-aa35-bdaec53d930d">

**Comment by jeffvli** [comment]
Thanks for the inspiration! I've settled on a modified version of the original logo using the light variant from IconKitchen. I played around a bit with various gradients but I think flat is better for now.
![axjfm-ulst5](https://github.com/jeffvli/feishin/assets/42182408/2fe9bc89-597d-4885-afa4-06804b4b2a6c)
