### ISSUE TITLE
When I play any song, it jumps between play and pause in quick succession

### ISSUE THREAD

**Issue by CreateWebNZ** [jeffvli/feishin#244]
## Expected Behavior

After starting to play, it should continuously play the selected song.

## Current Behavior

The play button flashes between play and pause about 4 times/second, the music plays/pauses along with it and the player buttons become unresponsive.
No error messages in the js console.

## Steps to Reproduce

Select a song or songs and press play or start a song in any other of the possible ways.

## Your Environment

Ubuntu 22.10
Feishin 0.3.0
MPV 0.34.1-ubuntu5
Navidrome 0.49.3

**Comment by OddBloke** [comment]
I encounter something like this for jellyfin also (which I can work around by using the "Web" player). In the terminal I launched the AppImage from, I see (repeated _a lot_):

```
MPV Event: status pause false []
MPV Event: paused
MPV Event: paused
MPV Event: status pause true []
MPV Event: resumed
MPV Event: resumed
MPV Event: status pause false []
MPV Event: paused
MPV Event: paused
MPV Event: status pause true []
```

(Ubuntu 20.04, Feishin 0.3.0, mpv 0.32.0-1ubuntu1)

**Comment by CreateWebNZ** [comment]
> MPV Event: status pause false []
> MPV Event: paused
> MPV Event: paused
> MPV Event: status pause true []
> MPV Event: resumed
> MPV Event: resumed
> MPV Event: status pause false []
> MPV Event: paused
> MPV Event: paused
> MPV Event: status pause true []
> ```


I just started it from a terminal and can confirm that.

**Comment by gabeclarke** [comment]
I'm encountering the same issue described by Oddbloke,

PopOS 22.04, Feishin 0.3.0, mpv 0.34.1 running off a Jellyfin server.

**Comment by Luxed** [comment]
Yup, same issue here. Same fix of using the "Web" player instead of `mpv`.

OS: `OpenSUSE Leap 15.4`
Feishin: `0.3.0`
mpv: `0.34.0+git.20211101T154439.9ca9066d05`
Jellyfin server: `10.8.10`

**Comment by jeffvli** [comment]
Has mpv worked previously for anyone or did it never work from the start?

I'm wondering if this is an issue due to a new mpv version or if it may be something else.

**Comment by iiPythonx** [comment]
Not sure if it helps, but running mpv 0.35.1 on Fedora leads to no issues with playback jumping.  
On Windows, I have encountered this issue when running mpv 0.34.1.

**Comment by CreateWebNZ** [comment]
> Not sure if it helps, but running mpv 0.35.1 on Fedora leads to no issues with playback jumping. On Windows, I have encountered this issue when running mpv 0.34.1.

Thx @iiPythonx, Installing mpv_0.36.0+fruit.1 from here https://apt.fruit.je/ubuntu/kinetic/mpv/ solved it for me.
I hope this helps anyone else and in particular @jeffvli. Btw. great work!

**Comment by jeffvli** [comment]
Just tried out v0.34.0 and it reproduces the rapid pause/play issue. Seems to be an external issue due to that version (and some previous ones) then. Thanks @iiPythonx for the information and @CreateWebNZ for the follow up. I'm going to pin this issue and add a notice in the README regarding the broken version.

If anyone else still encounters this issue using a known working version (v0.35.x or v0.36.x) we can re-open this.

**Comment by Sculas** [comment]
I just installed the v0.5.3 AppImage on Pop!_OS and I'm encountering this issue as well, using mpv [from](https://apt.fruit.je/ubuntu/jammy/mpv/):
```
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Dec 24 2023 11:54:26
libplacebo version: v6.338.1
FFmpeg version: 6.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```
Switched to the web player for now. I don't have this issue on Windows.

**Comment by SamLawAnthro** [comment]
Exact same problem, MPV 0.36, pop 22.06, jellyfin

**Comment by Luxed** [comment]
Additional information on my side:
It's now random. Sometimes it will work with my system's MPV (0.34), sometimes it will work with a version installed using Flatpak (0.37).
If I keep restarting the program again and again it ends up working after some time.......
