### ISSUE TITLE
Fuzzy Search

### ISSUE THREAD

**Issue by tsgoldladder** [jeffvli/feishin#246]
## What do you want to be added?
Fuzzy Search feature
## Additional context
EG: Near modifiers, one-word song names when they're actually two words. Currently search feature is looking for exact match only, which is not always present in mind when searching

**Comment by jeffvli** [comment]
Search is dependent on the server-side rather than from Feishin directly. You'll need to open this issue on whichever music server you use (jellyfin/navidrome/etc.)
