### ISSUE TITLE
Tidal integration :) 

### ISSUE THREAD

**Issue by silkyclouds** [jeffvli/feishin#252]
## What do you want to be added?
A way to add Tidal as an extra resource, directly in Feishin. 

## Additional context
As discussed on navidrome Discord server, it seems like it might be easier to get this integrated directly in the client.

**Comment by revy-git** [comment]
+1, basically main thing i miss from non-selfhost based streaming services is ability to seamlessly discover, get recommended, etc tracks from entire tidal or spotify or yt music or anything really library, quality isnt even important as its mostly for discovery

ideally you could just click to download tracks with tidal-dl or similar from tidal in the web ui to seamlessly include them into the local library, or have setting to automatically do so to any track you mark as favorite, or something else that serves that function, although that's probably a bit out of scope for any dev interest i assume so its not really required
