### ISSUE TITLE
"Shuffle All" button for tracks/playlists interfaces

### ISSUE THREAD

**Issue by OriginCode** [jeffvli/feishin#255]
## What do you want to be added?

A "Shuffle All" button for tracks/playlists interfaces, which functions the same as the "Play All" button at the top except it shuffles the songs.

## Additional context

N/A

**Comment by ryanwalder** [comment]
I'd add a second vote for a "Shuffle All" option on the Albums page as well:

1. Go to `Albums` Section
2. Hit a `Play All Shuffle` button
4. Album X plays all tracks in album
5. Album Y plays all tracks in album
6. And so on...

Preferably without adding everything to a playlist as that can take upwards of 10 mins for me.

So it might looks something like:


1. Go to `Albums` Section
2. Hit a `Play All Shuffle` button
3. Adds Album X to playlist
4. Plays all tracks in Album X 
5. Removes Album X from playlist
6. Adds Album Y to playlist
7. Plays all tracks in album Album Y
8. And so on...

**Comment by kgarner7** [comment]
https://github.com/jeffvli/feishin/commit/fbac33cebaf42b0a223cd6a8a80b5661755254d5 "play shuffled" context menu item, available everywhere (as well as default behavior). Like play, but it shuffles all items before adding to queue

**Comment by cameronj86** [comment]
Very appreciative of the playlist shuffle. Niche to some but essential for my music listening habits. Thanks @kgarner7
