### ISSUE TITLE
Album play hours seems very large

### ISSUE THREAD

**Issue by jboxman** [jeffvli/feishin#257]
## Expected Behavior

The hours of play time for the album matches the number of tracks.

## Current Behavior

The number is huge.

<img width="1159" alt="Screenshot 2023-09-23 at 11 44 37 PM" src="https://github.com/jeffvli/feishin/assets/354496/cddc86b2-f4fe-460f-810f-55b958d73cb6">

## Steps to Reproduce

1. Visited the specific album page

2.

3.

4.

-   Application version (e.g. v0.1.0) : 0.3.0
-   Operating System and version (e.g. Windows 10) : OS X 13.5.2
-   Server and version (e.g. Navidrome v0.48.0) : [0.49.3](https://github.com/navidrome/navidrome/releases/tag/v0.49.3)
-   Node version (if developing locally) : N/A

**Comment by iiPythonx** [comment]
I used to have the same problem, although this has been fixed and is presumably just awaiting release.

**Comment by jeffvli** [comment]
Yep, this is fixed in the current development branch!
