### ISSUE TITLE
Add Bitrate column to list view

### ISSUE THREAD

**Issue by DarkShadowxx** [jeffvli/feishin#26]
Hi,
I really like Feishin.
The only thing I am missing right now is the Bitrate column in the list view, like in Sonixd.

Could you maybe add it? Or some kind of option in the menu to enable it?

**Comment by jeffvli** [comment]
You can enable the bitrate column on the track list as well as playlist track list.

![image](https://user-images.githubusercontent.com/42182408/218334783-405cc93b-4c6a-4039-927f-0a2d312f296f.png)
