### ISSUE TITLE
Jellyfin : Playlist list displays media libraries

### ISSUE THREAD

**Issue by Kayn017** [jeffvli/feishin#261]
## Expected Behavior

Show my playlists

## Current Behavior

Show my media librairies and not my playlists

![image](https://github.com/jeffvli/feishin/assets/51646882/cc2128cf-b42c-488e-9b1d-6d49d7c09319)
![image](https://github.com/jeffvli/feishin/assets/51646882/ea07a349-e9be-4f22-bcf9-e9ed86e31956)

(My dev console is full of 500 errors)

![image](https://github.com/jeffvli/feishin/assets/51646882/1b64032f-fa4e-4d35-8f57-ff116bca9b83)

## Steps to Reproduce

Just open the latest release.

## Your Environment

-   Application version : 0.4.0
-   Operating System and version : Windows 11
-   Server and version : Jellyfin 10.8.10
-   Node version (if developing locally) : /

**Comment by jeffvli** [comment]
I believe this is due to the changed playlist implementation after Jellyfin v10.9.0. Can you try updating your server?

**Comment by Kayn017** [comment]
Indeed, I updated to the latest version of Jellyfin and it works perfectly now! Thank you very much and sorry for the inconvenience
