### ISSUE TITLE
Add support for Bauer stereophonic-to-binaural (bs2b)

### ISSUE THREAD

**Issue by Farnjang** [jeffvli/feishin#265]
## What do you want to be added?

Support for [Bauer stereophonic-to-binaural DSP](https://bs2b.sourceforge.net/)

## Additional context

> BS2B reduces the 'stereo fatigue' one can experience when listening to music with headphones for extended periods of time

**Comment by iiPythonx** [comment]
According to [the ffmpeg bs2b docs](https://ffmpeg.org/ffmpeg-filters.html#bs2b), you can add the following to your Feishin MPV parameters:
```
--af-add=lavfi=[bs2b=profile=default]
```
Substituting `default` with your profile of choice, or manually setting `fcut` and `feed` to your liking.

**Comment by kgarner7** [comment]
Given that there is an FFmpeg option for mpv, and no plans to do something similar for web audio (although it is _technically_ possible), I'm going to go ahead and close this issue.
