### ISSUE TITLE
Add option to show album cover for every single line

### ISSUE THREAD

**Issue by Farnjang** [jeffvli/feishin#266]
## What do you want to be added?

An option that enables showing the album art/cover for every single line of the playlist.

## Additional context

 Similar to MusicBee:

![musicbee](https://github.com/jeffvli/feishin/assets/43793653/71877f6e-7bae-42a6-84e5-1863eed1f4db)

**Comment by jeffvli** [comment]
This is already possible if you add the `Title (Combined)` column to the list, unless I'm misunderstanding what you're asking for.
