### ISSUE TITLE
[Feature Request] Support adding custom fonts

### ISSUE THREAD

**Issue by Visne** [jeffvli/feishin#270]
## What do you want to be added?
Apologies if this is already possible (wouldn't mind diving into files), but it would be cool if you could add a custom font for content, or if you could select from all fonts installed on your system.

**Comment by Nik-mmzd** [comment]
+1 for the issue, default ones do not contain a lot of symbols and it looks weird when missing symbols are replaced with another font.

P.S. I see no need in selecting *any* installed font, "System Default" font setting will be enough
