### ISSUE TITLE
0.4.0 Playlists no longer load correctly

### ISSUE THREAD

**Issue by kyagloski** [jeffvli/feishin#272]
Playlists now load movies shows and music rather than the actual music playlists in my library. Did a completely fresh install (deleted appdata) and still results with loading my libraries for other media rather than the playlists within my music library. This started happening after the 0.4.0 update, before this it worked perfectly fine.

Environment: Windows 11
Version: 0.4.0

**Comment by jeffvli** [comment]
Are you on Jellyfin? If so, check #261 for resolution

**Comment by againstpetra** [comment]
I'm on Jellyfin 10.8.10 and having the same issue.

Note this isn't latest because Jellyfin 10.8.11 has a [separate playlist bug](https://github.com/jellyfin/jellyfin/issues/10272).

**Comment by Ravencentric** [comment]
Jellyfin: 10.8.11
Feishin: [0.4.0](https://github.com/jeffvli/feishin/releases/tag/v0.4.0)

![Feishin_nyIe5airKn](https://github.com/jeffvli/feishin/assets/78981416/0937fdad-b528-4aaa-8dc8-4ce3299f0b83)
Stuck on this for me as well

**Comment by kyagloski** [comment]
I have also just updated to 10.8.11 and it does not seem to fix the issue, i also updated feishin to 0.4.1 to no avail. 
![Screenshot 2023-10-14 154242](https://github.com/jeffvli/feishin/assets/41209748/9d97daee-0b7c-498c-b569-1a2a26d04300)

**Comment by jeffvli** [comment]
Unfortunately I'm unable to reproduce this issue on my 10.8.11 instance (10.9.0 is the unstable release from the other post). Can you give me additional details such as how your Jellyfin server is deployed, such as if it's on Docker, Linux, Windows, etc.

**Comment by Ravencentric** [comment]
Jellyfin and Feishin are both installed on the same baremetal Windows 11 Pro 22H2 machine

**Comment by kyagloski** [comment]
For my setup I have a docker container using the latest linuxserver/jellyfin image on a remote debian server.

**Comment by jeffvli** [comment]
Do you have any playlists created? I tested on a fresh instance and it showed the Jellyfin libraries if there were 0 playlists.

**Comment by Ravencentric** [comment]
No playlists. My Jellyfin instance only has 1 library and it's called Music. I'm assuming that's the library that's showing up in Feishin playlists

**Comment by jeffvli** [comment]
I've reverted the playlist fetch implementation which should likely fix this issue for the next release (soon).
