### ISSUE TITLE
Visualizations

### ISSUE THREAD

**Issue by jboxman** [jeffvli/feishin#273]
## What do you want to be added?

I kind of miss the random visualizations that Clementine offered, when it would display random fractals for whatever you were playing.

**Comment by kowalcj0** [comment]
I love how PowerAmp app implemented support for MilkDrop vizualizations https://www.youtube.com/watch?v=ZZFMLtx9lfo

For desktop applications, I can suggest https://github.com/projectM-visualizer/projectm
Although it a bit resource hungry.

**Comment by pyxfluff** [comment]
For the record this did get added but the PR got closed for some reason. [The branch on the repo still works.](https://github.com/kgarner7/feishin/tree/visualizer) Works great if you add it manually into your client, I wish it would be default

![image](https://github.com/user-attachments/assets/32948181-842e-462e-840e-3a02e0adc065)
