### ISSUE TITLE
Make the search modal available in one click from the collapsed sidebar

### ISSUE THREAD

**Issue by avh4** [jeffvli/feishin#276]
## What do you want to be added?

I usually use the collapsed sidebar, and when I search, I almost always would prefer the search modal instead of the search page.  Currently (0.4.0) the button to open the search modal is only show in the expanded sidebar.  I'd love a way to quickly get to the search modal when using the collapsed sidebar.

I guess a keyboard shortcut to open the search modal would also solve this for me.

**Comment by 2048khz-gachi-rmx** [comment]
Have you tried the "Global search" hotkey?



https://github.com/jeffvli/feishin/assets/44749188/b078ca96-db6f-432f-9b5d-e583861fa8f4

**Comment by avh4** [comment]
> Have you tried the "Global search" hotkey?

Oh, I looked through the hotkey settings yesterday, but only saw "In-page search" there :facepalm:   Thanks, I'll give that a try!

**Comment by avh4** [comment]
Ah, yes, the "Global search" hotkey (defaults to Ctrl-K) works for what I want!

(Feel free to re-open this issue if you want to use it for adding something to the collapsed sidebar.)
