### ISSUE TITLE
Artist Play/Song List Adds Entire Library to Queue

### ISSUE THREAD

**Issue by HalianElf** [jeffvli/feishin#28]
## Expected Behavior

Hitting the Play button or going to All Songs under an Artist should only add that Artist to the queue

## Current Behavior

Both the Play button and going to All songs>add to queue adds the entire library (not just that artist) to the queue

## Steps to Reproduce

Go to Album Artists > Some Artist > Press Play button next to artist name or view all songs > add to queue

## Context

Top songs only adds the ones in the list to queue

## Your Environment
feishin-0.0.1-alpha5 AppImage

Note: bug template seemed to be the stock one from boilerplate which didn't seem to make sense for this so if you need something else let me know

**Comment by jeffvli** [comment]
Thanks for raising this issue. I did notice it as well but hadn't had the chance to address it yet!

Regarding the issue template: I'll update it soon. I've been more focused on the app so the readme and some other things still aren't up to date yet.

**Comment by HalianElf** [comment]
All good, just didn't want to make it seem like I was ignoring it.
