### ISSUE TITLE
A new update is ready to install

### ISSUE THREAD

**Issue by shishkin** [jeffvli/feishin#295]
The app currently (since 0.3.0 or so) notifies user that a new version has been downloaded and will be installed on exit. However, on exit and restart nothing gets updated and the notification pops up again.

## Expected Behavior

The update to be applied as advertised.

## Current Behavior

Update not being installed.

## Steps to Reproduce

Just run Feishin on not the latest version.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.4.0
-   Operating System and version (e.g. Windows 10) : MacOS
-   Server and version (e.g. Navidrome v0.48.0) : not relevant
-   Node version (if developing locally) : not applicable

**Comment by kgarner7** [comment]
Is this issue still happening? Try installing https://github.com/jeffvli/feishin/releases/tag/v0.5.0 and seeing if the update succeeds

**Comment by kgarner7** [comment]
Since there are not further updates, closing this issue. If it is still relevant, please reopen/add additional details

**Comment by mwean** [comment]
This has happened to me since I started using it around a year ago. Anything I can do to help debug?
