### ISSUE TITLE
Any chance we get a dedicated genres view?

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#3]
Filtering tracks, artists and albums by genres is great, but I would really love it if we had a dedicated tab.

**Comment by quamok** [comment]
If I'm not mistaken, this was implemented? Though when I click on it, I get a page not found /library/genres error.
![2023-06-28_22-22](https://github.com/jeffvli/feishin/assets/24906799/4808260d-f796-4d5d-b1f4-ceaa6af5d1ec)

**Comment by isle9** [comment]
> If I'm not mistaken, this was implemented? Though when I click on it, I get a page not found /library/genres error. ![2023-06-28_22-22](https://user-images.githubusercontent.com/24906799/249655594-4808260d-f796-4d5d-b1f4-ceaa6af5d1ec.png)

You get that exactly because it's not implemented yet.

**Comment by jeffvli** [comment]
Genres list has been added on dev, pending for next release.
