### ISSUE TITLE
Possible Album Art Display Changes

### ISSUE THREAD

**Issue by Lanklow** [jeffvli/feishin#30]
One of my favorite UI aspects of Sonixd were the large album art grids. 

I see that it has made a return in Feishin, as the 'Poster' display type in the 'Albums' menu. Though, I'd love to see it become an option in the other menus too ('Home' and 'Tracks').

Also, I think it would be nice to have dynamically re-sizable posters and cards; I often find that odd window sizes leave empty space on the right.

Love Sonixd, can't wait to see where Feishin goes!

**Comment by jeffvli** [comment]
The dynamically re-sizable grids are added in [0.0.1-alpha6](https://github.com/jeffvli/feishin/releases/tag/v0.0.1-alpha6). I'll make the cards be configurable in other menus in a future release.

**Comment by jeffvli** [comment]
Switched carousels over to Poster by default. Will be configurable in the future.
