### ISSUE TITLE
[Essential] Subsonic API Support

### ISSUE THREAD

**Issue by kobayashi90** [jeffvli/feishin#306]
**Why Feishin does need the Subsonic API Now?**
As previously mentioned [over here](https://github.com/jeffvli/feishin/issues/289) there is an essential need to enable the Subsonic API. Navidrome relies upon it heavly all the time, there are basically no clients that dont rely on navidrome's own api due to compability reasons i assume.

**Why there is no reason that we need to wait for Subsonic's API changes?**
After researching the Link that got mentioned on the Githubs Readme turnts out there is no eta or any development on new subsonic api changes so there is basically no need to wait for future subsonic api changes.
Even if someone rebuilds it, it takes up months if not years due to how old subsonic is in some regards.
So i hope this gets fixed as fast as possible.

**Comment by Sakooooo** [comment]
![image](https://github.com/jeffvli/feishin/assets/78461130/2f8879f3-97f6-47f8-bd04-984f25605d0d)
tried using gonic with feishin it errors out with 'please prodive a 'u' parameter when clicking tracks login doesnt seem to work either

**Comment by ProfMoo** [comment]
> After researching the Link that got mentioned on the Githubs Readme turnts out there is no eta or any development on new subsonic api changes so there is basically no need to wait for future subsonic api changes.

Just throwing in my 2 cents: It's worth exploring for Feishin to look into the [OpenSubsonic API](https://github.com/opensubsonic/open-subsonic-api). I believe the OpenSubsonic API is the end result of [the thread that was linked in the README](https://support.symfonium.app/t/subsonic-servers-participation/1233)

**Comment by kobayashi90** [comment]
> Just throwing in my 2 cents: It's worth exploring for Feishin to look into the [OpenSubsonic API](https://github.com/opensubsonic/open-subsonic-api). I believe the OpenSubsonic API is the end result of [the thread that was linked in the README](https://support.symfonium.app/t/subsonic-servers-participation/1233)

**Edit: I apologize if this sounds rude, ive had an tantrum about it,.. take your time.**
**Edit 2: Got notified that they work on it soon, so lets wait until its done.**

**Comment by Gt1ult** [comment]
Is there any chance to have gonic/opensubsonic as client too? It will be great. At the moment which one is the best client? Jellyfin or Navidrone?

**Comment by kenwoodken** [comment]
FYI, its on its way --> #419

**Comment by kobayashi90** [comment]
> FYI, its on its way --> #419

It failed tho, not sure how optimistic we should be.. @jeffvli might know..

**Comment by iiPythonx** [comment]
> It failed tho, not sure how optimistic we should be.. jeffvli might know..

Running off of #419, your server "squidify" (from #289) seems to load perfectly fine:

![image](https://github.com/jeffvli/feishin/assets/35084023/2ebd3cd3-6178-48d5-bb0a-39ac25a21804)

Additionally, if by "failed" you meant the "Some checks were not successful" notice, then it's worth noting that's just because of some basic missing configuration when building for MacOS:

![image](https://github.com/jeffvli/feishin/assets/35084023/722b0942-7b5b-4dd7-9058-470d95e6bdb1)

It should just be a matter of waiting for it to be finalized and merged.

**Comment by kobayashi90** [comment]
> It should just be a matter of waiting for it to be finalized and merged.

Indeed great news, i hope it happens soon because till now many people used SoniXD including myself..
I did also use Feishin over an Tailscale connection but its clearly not an option for other listeners.

**Comment by garfieldairlines** [comment]
Can we get a little estimate when it will be implemented ? I'm still stuck with Sonixd because of the lack of support of Subsonic…

Edit : or release https://github.com/jeffvli/feishin/pull/419 : yes you will say "it's old and you will lack features", but am I really lacking something when Sonixd isn't maintained at all ?

**Comment by iiPythonx** [comment]
> Can we get a little estimate when it will be implemented ?

jeffvli is planning/working on yet another rewrite which according to him will have support for subsonic.  
It's not public yet and I don't have any more information about it then that.

Also, if you just want a build of #419, I have a build [available here](https://github.com/iiPythonx/feishin/releases/tag/v419) (Linux/Windows only).

**Comment by garfieldairlines** [comment]
> Also, if you just want a build of #419, I have a build [available here](https://github.com/iiPythonx/feishin/releases/tag/v419).

Oooooooooooooh thank you so much

**Comment by kgarner7** [comment]
The likelihood of it hitting Feishin regular as-is is basically none. Unless someone (who is not me) spends the time to refine the linked PR and resolve all merge conflicts, it will likely not happen.

**Comment by kgarner7** [comment]
:face_exhaling: in light of Navidrome filtering making things worse, I'm taking a stab at this. 
Note that it will be a different branch (I'm not dealing with all those merge conflicts). My first goal will be to port over the changes that will support subsonic (without actually supporting subsonic) to make sure the quality of Navidrome/Jellyfin native isn't impacted. **If** that's the case, then adding Subsonic back is easy.
