### ISSUE TITLE
Persistent Window Size / Fullscreen toggle

### ISSUE THREAD

**Issue by Lanklow** [jeffvli/feishin#31]
Would it be possible to add a fullscreen toggle in settings?

I'd like to use this on my Steam Deck; but when using Feishin (and Sonixd, before) in gaming mode, I have to manually hit a bind for F11 on each launch to make the window match the screen resolution. Most of the other apps I use have persistent resolution and/or a fullscreen toggle, so it's probably the feature which I'd like to see implemented most.

FYI: I have have no grasp of the difficulty of implementing these features, due to lack of experience coding.

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/6824a5db7ad1f9adda630be7d52ede89685b402d
