### ISSUE TITLE
No playlists in "Add to Playlist" dialog

### ISSUE THREAD

**Issue by toasty-sunbeam** [jeffvli/feishin#311]
## Expected Behavior

I can right-click a track, click "Add to Playlist", and select a playlist to add the track to.

## Current Behavior

The "Playlists" box is dead. The cursor doesn't change on hover, and nothing happens when I click in it.

<img width="354" alt="image" src="https://github.com/jeffvli/feishin/assets/5524469/46d7b50c-5aaa-4f29-80fd-b8ef1001089e">

In the console, I see:

> renderer.js:2295     GET http://10.10.10.5:7777/api/playlist?_end=0&_order=ASC&_sort=name&_start=0&smart=false 500 (Internal Server Error)

The response payload for that request is:

> {"error":"no such column: smart"}null

## Steps to Reproduce

Right-click a track anywhere in the app and click "Add to Playlist"

## Your Environment

-   Application version (e.g. v0.1.0) : 0.4.0
-   Operating System and version (e.g. Windows 10) : MacOS 1.12.1
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.47.5

**Comment by toasty-sunbeam** [comment]
Fixed the issue by updating to Navidrome 0.49.3. It would be nice to have better error handling for this, though.

**Comment by jsspen** [comment]
I just had this happen on 0.5.3. Restarting the client fixed it.
