### ISSUE TITLE
"Now playing" status is sent to the scrobble service when nothing is playing

### ISSUE THREAD

**Issue by avh4** [jeffvli/feishin#316]
## Expected Behavior

When playback has not started, no "now playing" updates should be sent to the scrobbling service.

## Current Behavior

When feishin is launched, and also when a playlist stops playing because it reached the end of the playlist, a "now playing" status is sent to the backend for the first song in the play queue, even though playback is stopped.

## Steps to Reproduce

Method 1:
- Add at least one song to the play queue
- exit feishin
- start feishin again
- the scrobble service shows the first song in the play queue as "now playing" even though playback has not started

Method 2:
- Add at least two songs to the play queue
- start playing the last song in the play queue
- let the last song finish playing
- the scrobble service shows the first song in the play queue as "now playing" even though playback is stopped and hasn't been started again

## Context

This is not a big problem for me, since I personally only really care about the scrobble submissions (which work correctly) and I don't really care about the "now playing" status.  But I figured I'd just report this as unexpected behavior.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.4.1
-   Operating System and version (e.g. Windows 10) : Linux: NixOS
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3
  - Navidrome is configured to scrobble to ListenBrainz
-   Node version (if developing locally) : N/A

**Comment by kgarner7** [comment]
I am unable to reproduce this issue using latest. Can you try https://github.com/jeffvli/feishin/actions/runs/7939011303 (pretty recent build) and see if you are still able to reproduce this issue?

**Comment by kgarner7** [comment]
I am going to mark this resolved as the play behavior has changed for Method 1 and scrobble has been improved for method 2.
