### ISSUE TITLE
Playlists not working after update

### ISSUE THREAD

**Issue by Mis1ify** [jeffvli/feishin#319]
## Expected Behavior
Playlist button shows playlists.

## Current Behavior
Displays things that shouldn't be displayed, series, movies, etc.
Clicking on playlists does nothing.
![image](https://github.com/jeffvli/feishin/assets/111151942/a8978233-345f-431f-89a9-ee5f495c7a36)

## Steps to Reproduce

1. Upgrade Feishin from 0.3.0 to 0.4.0/0.4.1

2. Open updated app

3. The playlists are not shown.

## Possible Solution (Not obligatory)
Downgrade the version to 0.3.0

## Context

Before updating, I could see my playlists, now I see all of my media from Jellyfin, movies etc.
My playlists transformed into one 'Playlists' button, which does nothing.
## Your Environment

-   Application version (e.g. v0.1.0) : 0.4.1
-   Operating System and version (e.g. Windows 10) : Debian 12
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin 10.8.10
-   Node version (if developing locally) : -

**Comment by iiPythonx** [comment]
Possible duplicate of https://github.com/jeffvli/feishin/issues/272?

**Comment by Mis1ify** [comment]
Probably yes, cannot upgrade Jellyfin for now but I believe this is the solution.

**Comment by Mis1ify** [comment]
FYI, Feishin 0.5.1 fixes this bug, I'm still on Jellyfin 10.8.10.
