### ISSUE TITLE
Add cups into appimage

### ISSUE THREAD

**Issue by kuj0nell0** [jeffvli/feishin#320]
## What do you want to be added?
Cups and other libs to be shipped directly in the appimage (without need to install libcups and other libs as a system package)
## Additional context
Appimages by their sole purpose should be self-contained, so any software needed to run Feishin should be in the Appimage.

full list of libraries needed:
libgssapi_krb5.so.2
libavahi-common.so.3
libavahi-client.so.3
libkrb5.so.3
libkrb5.so.3
libkrb5support.so.0
libkeyutils.so.1
libcups.so.2

**Comment by jeffvli** [comment]
I've added the dependencies to [electron-builder's](https://www.electron.build/configuration/linux#debian-package-options) config. Let me know if it doesn't work still after the next release.
