### ISSUE TITLE
"Most Played" section isnt correct

### ISSUE THREAD

**Issue by sammy-ette** [jeffvli/feishin#324]
## Expected Behavior

The "Most Played" section on the home page should show the most played music on my Jellyfin server.

## Current Behavior
I'm not really sure what albums its grabbing but it isnt my most played

Feishin showing incorrect albums for Most Played  
![](https://safe.saya.moe/k1eIFcHED6Hf.png)

and it being correct in Sonixd  
![](https://safe.saya.moe/MKZeHvPP2psi.png)

## Your Environment
-   Application version (e.g. v0.1.0) : v0.4.1
-   Operating System and version (e.g. Windows 10) : Fedora Linux 38
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin v10.8.11
-   Node version (if developing locally) :

**Comment by sammy-ette** [comment]
still not fixed (v0.5.0)

![](https://safe.saya.moe/Lvmw372Cldo1.png)


meanwhile on jellyfin (and sonixd)
![](https://safe.saya.moe/hEaD9jlEvUlh.png)

**Comment by jeffvli** [comment]
Jellyfin web UI shows frequently played by songs. On Feishin it's being displayed by most played albums.

**Comment by sammy-ette** [comment]
even then, my most played albums should show up with the pop smoke albums. i've played those more than ballads 1 and it doesn't even show up.

and some of those i've only played once.

**Comment by jeffvli** [comment]
I just remembered Jellyfin doesn't properly track album play counts, that's why it's inaccurate.

I'll update the home page to display most played songs instead of albums when using Jellyfin.
