### ISSUE TITLE
Issues using dockerized web version

### ISSUE THREAD

**Issue by stefan1983** [jeffvli/feishin#329]
Hey there, 

I am using the dockerized version of feishin and a navidrome database in the background. When clicking on an album to play it often happens that it wont't start. Sometimes selecting a single track out of the playlist or moving the playback position a bit ahead works then. Does anyone else have this issues?

I am accessing the web via Safari on a current macOS.

Thanks!

**Comment by kgarner7** [comment]
Hi there! Sorry for letting this linger so long. Can you please try the `Preview Here` link on the associated PR and see if this solves your issue?

**Comment by stefan1983** [comment]
HI, sure I'll give it a try.

Regards 👋🏻

**Comment by stefan1983** [comment]
Bug is fixed now! 
Only louder & quieter seems in your fork not to work.

**Comment by kgarner7** [comment]
...Safari...
Anyway, I've used a workaround that uses only WebAudio. Can you try the updated preview and report if the volume slider works again please?

**Comment by stefan1983** [comment]
Sure, I am afraid it is still not working.

**Comment by kgarner7** [comment]
Ugh. looks like it doesn't update the preview url. Can you try https://feishin-1h6501o8s-jeffvli.vercel.app?

**Comment by stefan1983** [comment]
jup, now it works! Thanks
