### ISSUE TITLE
HTTPS/TLS support for dockerized version of feishin

### ISSUE THREAD

**Issue by stefan1983** [jeffvli/feishin#330]
I would like to access my feishin via HTTPS instead of unencrypted HTTP. Is it planned to integrate a SSL/TLS connection to feishin?

If not, I guess setting up a reverse proxy would be an alternative.

**Comment by Kakoluz** [comment]
Feishin on docker runs compiled to static files wich means it is served by a common web server as a plain website. In this case Nginx does the job, you can add support for https on your own, just create a new image using the provided dockerfile and editing the nginx.conf file to suit your needs, like adding a volume with the SSL certificate.

I would just run a reverse proxy in front. way easier and faster.

**Comment by stefan1983** [comment]
I did set up a reverse proxy finally.
