### ISSUE TITLE
Weblate is locked and tranlations cannot be provided

### ISSUE THREAD

**Issue by darwintree** [jeffvli/feishin#340]
## Current Behavior

Weblate does not have permission to commit changes and translations cannot be saved
<img width="1020" alt="image" src="https://github.com/jeffvli/feishin/assets/17946284/449cf4d7-c0af-46c0-a5c8-6b9293153490">

## Steps to Reproduce

Visit Chinses simplified page in feishin's weblate page

## Possible Solution (Not obligatory)

Check if configuration is correct

**Comment by jeffvli** [comment]
Thanks for letting me know. I'll try to fix this.

**Comment by jeffvli** [comment]
I haven't used weblate previously so I'm not exactly sure why the automatic push isn't working... ~~I've disabled the automatic push for now just so translations can be added without erroring out.~~

Resolved by:
1. Adding `hosted@weblate.org` as a collaborator on the repository [per the docs](https://docs.weblate.org/en/latest/vcs.html#accessing-repositories-from-hosted-weblate)
2. Adding the SSH git URL to the push configuration on weblate
