### ISSUE TITLE
Settings crash after setting custom system font

### ISSUE THREAD

**Issue by nathan-contino** [jeffvli/feishin#343]
## Expected Behavior
Expected **Hamburger menu > Settings** to open the settings

## Current Behavior
Settings crashes, so I can't change any settings any more! Doesn't work on reload, either.
Oddly, the custom font I picked (SF Mono) _does_ load correctly.

<img width="593" alt="Screenshot 2023-10-31 at 12 46 39" src="https://github.com/jeffvli/feishin/assets/10657588/5c39bdf0-3a4f-4dea-8d79-822761e3d3f7">

## Steps to Reproduce

1. Open the Settings menu.
2. In **General**, pick **System font**
3. Choose a font from the macOS Fonts folder.
4. Observe the app crash.
5. Try to open the settings menu again. Observe the app crash.
6. Try to reload the settings menu. Still an app crash.

## Context

I like a monospace font for my music player, so I tried picking SF Mono. It does look pretty nice, but I think I'd prefer being able to use my settings menu.

## Your Environment

-   Application version (e.g. v0.1.0) : `0.5.0`
-   Operating System and version (e.g. Windows 10) : macOS Sonoma
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin 10.8.9
-   Node version (if developing locally) : not developing locally

**Comment by jeffvli** [comment]
Can you open the console from the `Open browser devtools` in the app menu and check to see if it says exactly where the error is coming from?

I can't reproduce this on my side (I only use Windows).

Also, resetting the settings to default (or deleting the `store_settings` key from local storage and restarting) may fix it temporarily until a permanent fix can be put in place.
