### ISSUE TITLE
Fullscreen Player has "PAGE.FULLSCREENPLAY" in the tabs

### ISSUE THREAD

**Issue by OriginCode** [jeffvli/feishin#345]
## Expected Behavior

Correct names should be displayed.

## Current Behavior

![image](https://github.com/jeffvli/feishin/assets/17294071/b3003937-c253-4141-89e5-8d2858c3074b)

## Steps to Reproduce

1. Enter Fullscreen Player

## Possible Solution (Not obligatory)

N/A

## Context

N/A

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.0
-   Operating System and version (e.g. Windows 10) : AOSC OS (GNU/Linux 6.4.11, x86_64)
-   Server and version (e.g. Navidrome v0.48.0) : v0.49.3
-   Node version (if developing locally) : N/A

**Comment by OriginCode** [comment]
Uhh it also happens to the settings in fullscreen player:
![image](https://github.com/jeffvli/feishin/assets/17294071/e0511e30-58a5-48f2-a4bf-bf963387bce1)

**Comment by iiPythonx** [comment]
IIRC this is fixed in 0.5.1 which is awaiting release from @jeffvli.

**Comment by jeffvli** [comment]
Yep these are fixed in 401912a70c3eeac9482aa7807363f304b32e3e13 and cd3ec158d36e01bfd2f132efd3f0da9ce6a155fe. I'm going to be pushing the fix in a couple hours.
