### ISSUE TITLE
Lyrics autoload not available on web version

### ISSUE THREAD

**Issue by stefan1983** [jeffvli/feishin#346]
I am using the web version of Feishin and recognized that the auto load of lyrics is not working. In the latest desktop builds for Mac (0.4.0/0.5.0) that works fine. Is this a bug or missing feature?

Feishin web:
<img width="1348" alt="image" src="https://github.com/jeffvli/feishin/assets/8542806/9116369d-2cec-4bb2-b537-964186ea8ac5">

Feishin macOS:
![image](https://github.com/jeffvli/feishin/assets/8542806/04569209-68d5-4f14-93b9-7d2e9579f69d)

**Comment by jeffvli** [comment]
The web player can only load lyircs that are embedded in the file tags.

This is due to a CORS limitation in fetching from external lyrics APIs in the browser.
