### ISSUE TITLE
Wrong Text

### ISSUE THREAD

**Issue by Luk45135** [jeffvli/feishin#349]
## Expected Behavior

The correct text should be displayed

## Current Behavior

It says stuff like PAGE.FULLSCREENPLAYER.UPNEXT

![Screenshot_20231101_200019](https://github.com/jeffvli/feishin/assets/91327705/881f80c2-56e0-4d6c-9e50-77751e1c31d4)

## Steps to Reproduce

1.

2.

3.

4.

## Possible Solution (Not obligatory)

I don't know

## Your Environment

-   Application version (e.g. v0.1.0) : v0.5.0 AppImage
-   Operating System and version (e.g. Windows 10) : Linux nobara-pc 6.5.6-200.fsync.fc38.x86_64 
-   Server and version (e.g. Navidrome v0.48.0) : 0.49.3 8b93962f
-   Node version (if developing locally) :

**Comment by iiPythonx** [comment]
Duplicate of https://github.com/jeffvli/feishin/issues/345, fix is awaiting release

**Comment by Luk45135** [comment]
Oh sorry, i didn't look in the closed issues.
Thanks for very fast response.

**Comment by Luk45135** [comment]
Uhh it also happens when hovering over Play/Pause it says `Player.pause` as you can see in the original screenshot and this doesn't seem to be addressed in https://github.com/jeffvli/feishin/commit/401912a70c3eeac9482aa7807363f304b32e3e13 and https://github.com/jeffvli/feishin/commit/cd3ec158d36e01bfd2f132efd3f0da9ce6a155fe.

**Comment by Luk45135** [comment]
I don't know if it's related but the categories in the sidebar are all lowercase 
![Screenshot_20231101_202818](https://github.com/jeffvli/feishin/assets/91327705/bde8ae3d-25cb-4ab3-8ac3-6925cf11d920)

**Comment by iiPythonx** [comment]
> Uhh it also happens when hovering over Play/Pause it says `Player.pause` as you can see in the original screenshot and this doesn't seem to be addressed in [401912a](https://github.com/jeffvli/feishin/commit/401912a70c3eeac9482aa7807363f304b32e3e13) and [cd3ec15](https://github.com/jeffvli/feishin/commit/cd3ec158d36e01bfd2f132efd3f0da9ce6a155fe).

This was brought up in the Discord, although I don't know if jeffvli has gotten around to fixing it yet:
![image](https://github.com/jeffvli/feishin/assets/35084023/9e63062c-eace-444d-b9f5-17cd1db03803)

As for the sidebar categories, it **seems** like it was fixed in b05d532941f0b0558cea8a23a7ab0e806c2e2182, but don't quote me on that.

**Comment by kgarner7** [comment]
Just checking, are you still seeing any of these issues?

**Comment by Luk45135** [comment]
No, sorry I forgot to close the issue.
