### ISSUE TITLE
Volume control for web version

### ISSUE THREAD

**Issue by Chaphasilor** [jeffvli/feishin#35]
Currently, it seems like the volume can't be changed on the [web client](https://feishin.vercel.app/) (it's fixed at 50%), probably because the volume is implemented using an electron API by default, which doesn't exist on the web.  
However, especially on the web, where you can only control the browser's volume as a whole but not the volume of individual tabs, it would be very nice to have control over the volume. This way, you could have Feishin running in the background but still listen to a video in another tab.

**Comment by jeffvli** [comment]
Thanks for reporting.
