### ISSUE TITLE
2 little bugs with v0.5.1

### ISSUE THREAD

**Issue by Morethanevil** [jeffvli/feishin#354]
First, thanks for this great app! I encountered two little bugs.

## Expected Behavior

1 Save the window size in the windows version.

2 Click play and it plays the song

## Current Behavior
In the windows application I always need to resize the window manually after every start of feishin, it does not save the windowsize. 

Aaaaand I always need to click twice on the play button until it actually plays the song. This only happens for the first song after start of feishin.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.1 (x64 install.exe from github)
-   Operating System and version (e.g. Windows 10) : Windows 11
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin 10.8.11
-   Node version (if developing locally) : -

**Comment by xdjohn99** [comment]
Same. The only difference is [Win 10/Navidrome 0.50.1]

**Comment by kgarner7** [comment]
Both issues should be resolved in latest Feishin.
