### ISSUE TITLE
Accented letters are not capitalized

### ISSUE THREAD

**Issue by KosmoMoustache** [jeffvli/feishin#357]
## Expected Behavior

Accented letters at the start of a word should be capitalized

## Current Behavior

Accented  letters at the start of a word are not capitalized

![2023-11-04_21-30-21_Feishin](https://github.com/jeffvli/feishin/assets/34519077/13266fcf-c150-40c4-9c63-e224b3fd0e52)

## Steps to Reproduce

1. Change the language to french

2. Hover the expand button in the player bar

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.1
-   Operating System and version (e.g. Windows 10) : Windows 10
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3
-   Node version (if developing locally) : -

**Comment by jeffvli** [comment]
Thanks for reporting... seems like the regex isn't catching accented characters when performing text formatting from translations.

**Comment by kgarner7** [comment]
Marking this issue as resolved
