### ISSUE TITLE
Window controls (minimize and maximize) are unclickable after "fixed" play queue style is enabled

### ISSUE THREAD

**Issue by manuel-rw** [jeffvli/feishin#36]
## Prerequisites

- [ ] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
The window control buttons at the top right should minimize, maximize or close the window, when the queue is opened.

## Current Behavior
Maximize and minimize are not clickable, when the queue is opened.

## Steps to Reproduce

1. Click the menu in the top left

2. Click on "Settings"

3. Click on "General"

4. Choose "Fixed" in the "Side play queue style"
5. Close the settings at the top right
6. Open the queue using the menu in the play bar at the bottom
7. Click minimize or maximize buttons

## Context
Not deal breaking, I am just not able to minimize when the fixed style is enabled.

I suspect that the issue is most likely caused by overlapping elements.

## Your Environment

- Operating System and version : Windows 11

Thanks for your great work as always!

**Comment by jeffvli** [comment]
Fixed for the next release.
