### ISSUE TITLE
Improper track listing in album view under Pop_OS! / GNOME

### ISSUE THREAD

**Issue by cyberwolfie1** [jeffvli/feishin#361]
## Expected Behavior

There should be no overlap between the song title and artist in album view, and all songs in the album should be easily clickable.

## Current Behavior

When listing an album, the track listing appears wrong. There is an overlap between the song title and the artist name. This also makes the tracks less responsive to clicks. See screenshot below. The issue is independent on zoom level or font type. 

Note: This only occurs for me in Pop_OS! with GNOME. With KDE Plasma I do not experience this issue in neither 0.4.1, 0.5.0 nor 0.5.1.

![feishin_bug](https://github.com/jeffvli/feishin/assets/149936446/8f44b6a5-88dd-4a50-9309-2b980d22c987)

## Steps to Reproduce

1. Open Feishin and navigate to any album in Pop_OS! with GNOME

2. Listing should appear incorrect.

## Context

Primary problem is that it is harder to initiate playback of tracks. Secondary problem is that it looks bad.

## Your Environment

-   Application version (e.g. v0.1.0) : Feishin v.0.5.1 (but also occured in v.0.4.1)
-   Operating System and version (e.g. Windows 10) : Pop_OS! 22.04 LTS with GNOME 42.5 
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin

**Comment by jeffvli** [comment]
Does resizing the rows in the album page config fix it for you?

![image](https://github.com/jeffvli/feishin/assets/42182408/8c7db632-85d4-4a67-a035-aa5cfbaa0355)

**Comment by cyberwolfie1** [comment]
Yes, that did it!, thanks Item size was set to 33, and it didn't take much upscaling for it to display as intended.

I was not aware of this config, and would probably have expected to find something like that in the general settings?
