### ISSUE TITLE
[Navidrome] Feishin doesn't distinguish owned and shared playlists

### ISSUE THREAD

**Issue by Octelly** [jeffvli/feishin#368]
## Expected Behavior

Show user's and shared playlists separately.

## Current Behavior

It is impossible to tell playlists apart:
![image](https://github.com/jeffvli/feishin/assets/29976879/0da4e88f-b3c1-411f-be8c-039ca3d97ed2)
(only 2 of those were created by me)

## Steps to Reproduce

1. Connect to a multi-user Navidrome instance
2. Observe the playlist section

## Possible Solution

I've seen other players such as [Symfonium](https://symfonium.app/) tackle this in various ways. I think adding a share icon next to shared playlists could be enough, but a separate "shared playlists" section would be better. Ideally the player would also distinguish between private and shared playlists created by the user.

Here's a crude mockup:
![image](https://github.com/jeffvli/feishin/assets/29976879/e19026f2-6484-4b27-9c4a-5b98475100c2)
It would be cool if it could also show who created the playlist, since "Favs" is kind of ambiguous in this example.

## Context

The current behaviour makes it hard to choose the correct playlist.

## Your Environment

-   Application version: **0.5.1** (aur/feishin-bin)
-   Operating System and version: **Arch Linux**
-   Server and version: **Navidrome [0.49.3](https://github.com/navidrome/navidrome/releases/tag/v0.49.3)**

**Comment by jsrol** [comment]
I agree it would be nice, but this isn't a bug imo! ;)

**Comment by Octelly** [comment]
@jsrol idk, it makes the app hard to use for me :/
