### ISSUE TITLE
When using the player's bottom right song rating stars, the rating doesnt update in the rating column of a song list.

### ISSUE THREAD

**Issue by jsrol** [jeffvli/feishin#370]
## Expected Behavior

When i click the star rating at the bottom, i expect the list of songs to update the rating in the rating column. Currently, it doesnt change at all, while navidrome does get the information. Also, the opposite works (if i use the rating column to rate a track, it will show as rated when i play the song in the bottom right).

## Current Behavior

![image](https://github.com/jeffvli/feishin/assets/19502683/01a11165-0db2-46da-a57f-619b9b9ec68d)

## Steps to Reproduce

1. Add rating column to a playlist
2. Give rating to song using the bottom right rating buttons
3. Rating will not update on the rating column

## Context

While the rating functionality isnt affected as they are updating in navidrome regardless, it can cause confusion for users.

## Your Environment

Latest release, win11,navidrome v0.49.3

**Comment by kgarner7** [comment]
Resolved by #707
