### ISSUE TITLE
Unable to type the mpv location into the box

### ISSUE THREAD

**Issue by viasux** [jeffvli/feishin#373]
## Expected Behavior

I should be able to set the MPV executable location.

## Current Behavior

I am unable to type in the text box.

![image](https://github.com/jeffvli/feishin/assets/47131867/c732c4b7-f310-4418-95ed-9e248e5c88e8)

## Steps to Reproduce

1. Download
2. Run
3. Click the text box
4. Type
5. Nothing happens

## Context

I am unable to play anything because of this.

## Your Environment

Artix linux, updated today. I've tried both the aur version and downloading the appimage ver. from github.

Using gnome on xorg because wayland is a dumpsterfire

-   Application version (e.g. v0.1.0) : 0.5.1
-   Operating System and version (e.g. Windows 10) : Artix

**Comment by iiPythonx** [comment]
You can't type into that box (from what I'm aware). Clicking on it is supposed to open a file dialog browser, if it doesn't then something else might be wrong (desktop related issue?).

**Comment by viasux** [comment]
> You can't type into that box (from what I'm aware). Clicking on it is supposed to open a file dialog browser, if it doesn't then something else might be wrong (desktop related issue?).

ah that makes sense although i have no clue how i would fix it lol

**Comment by iiPythonx** [comment]
If you can't get the dialog box to show, you could try to manually create a config file with the mpv path set.
`~/.config/feishin/config.json`:
```json
{
    "mpv_path": "/bin/mpv"
}
```

**Comment by viasux** [comment]
> If you can't get the dialog box to show, you could try to manually create a config file with the mpv path set. `~/.config/feishin/config.json`:
> 
> ```json
> {
>     "mpv_path": "/bin/mpv"
> }
> ```

there was already a config, so I added this:

```
  GNU nano 7.2         /home/via/.config/feishin/config.json          Modified  
{
        "window_has_frame": false
        "mpv_path": "/usr/bin/mpv"
}
```
but it breaks:
```
visys:[via]:~$ feishin
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Expected ',' or '}' after property value in JSON at position 30
    at JSON.parse (<anonymous>)
    at N._deserialize (/usr/share/feishin/resources/app.asar/dist/main/main.js:8:67824)
    at get store [as store] (/usr/share/feishin/resources/app.asar/dist/main/main.js:8:71302)
    at new N (/usr/share/feishin/resources/app.asar/dist/main/main.js:8:69071)
    at new e.exports (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:72392)
    at 96075 (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:509930)
    at n (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:806590)
    at 35533 (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:515186)
    at n (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:806590)
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:807027
libva error: vaGetDriverNames() failed with unknown libva error
```

**Comment by viasux** [comment]
I AM STUPID nevermind i fixed it, read the error message lol

**Comment by kgarner7** [comment]
Just checking in here, is it good to close the issue?

**Comment by iiPythonx** [comment]
> Just checking in here, is it good to close the issue?

I would say it is, sounds like it was a desktop related issue.
