### ISSUE TITLE
Local artist images displayed in low resolution

### ISSUE THREAD

**Issue by ilfarpro** [jeffvli/feishin#377]
Hello! 

I try to be more independent from Internet and downloaded artist images to artist folders. Navidrome handles them as expected and displays at high resolution. However Feishin fetching images at low resolution and they look ugly (check out screenshot to see what I mean).

## Expected Behavior

Feishin fetches artist images from Navidrome in higher resolution so it would not look blurry.
Navidrome gives artist images to Feishin in higher resolution?? Not sure where the root cause of problem.

## Current Behavior

How It Looks: (click to see  at full scale)
<img width="200" alt="ArtistImages" src="https://github.com/jeffvli/feishin/assets/16963651/af623e4f-c858-4a07-891b-ae831067fef8">

Feishin gets artist image URL like this:
`https://navidrome.example.com/share/img/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFyLWZjY2UyMDVkNzg0NDllYTU1OGU2Yjc3MTQwODc5MGJmXzAiLCJpc3MiOiJORCJ9.QFQ_lW23xcGigw553pK_eT4GPraUr6Q0nv7gqhFWvKU?size=150`

End of link contains `?size=150`. I'm not sure if Navidrome gives image in such resolution or Feishin fetching image of this resolution.

Problem is visible on "Artists" page and on actual Artist page. However on Related artists section image suddenly in higher resolution and looks good.

(click to see at full scale)
<img width="200" alt="RelatedArtistsImages" src="https://github.com/jeffvli/feishin/assets/16963651/d25c55c1-0ec7-466b-abdb-96dba5c3bfff">

## Steps to Reproduce

1. Remove Spotify API credentials

2. Provide Artists local images acording to Navidrome's documentation:
https://www.navidrome.org/docs/usage/artwork/#artists

3. Open browser in Incognito mode and login.

4. Check Artists page from left pane.
Check Artist page and take a look at Related artists section

## Possible Solution (Not obligatory)

Fetch Artist images on Artists folder in `?size=600` instead of `?size=150`

## My Environment

-   Application version: v0.5.1
-   Operating System and version: macOS Sonoma 14.1.1
-   Screen resolution: 4K, 2K, (Macbook Air M2) doesn't affect at all, problem is visible anyway. 
-   Server and version : v0.49.3

**Comment by jeffvli** [comment]
Image size is being set to 100 when falling back to local artist url. Will be fixed in the next release.

https://github.com/jeffvli/feishin/blob/1d2e9484d8372692f933b922de4b4df955067b51/src/renderer/api/navidrome/navidrome-normalize.ts#L187-L194

**Comment by Optekah** [comment]
I only use local images in my folders, so they are all very blurry. My heart skipped a beat when I launched Feishin quite early one morning... thought I needed to go back to my optometrist lol.

> in the next release

Did this make its way into 0.5.2 or 0.5.3 by chance? Mayhaps I need to deep rescan my Navidrome library?

**Comment by Nervyalloy5** [comment]
It seems this is still a problem in the 0.5.3 AppImage
I exclusively use local images, so I'd really like to see this fixed.
Even just doubling the value would be a major usability improvement.

**Comment by kgarner7** [comment]
This will be resolved by https://github.com/jeffvli/feishin/commit/04a468f8c9a7978b26862e9a91b188be6bd9def7 (I cannot speak to when the next release will come)

**Comment by Optekah** [comment]
Unfortunately this is still not totally fixed after updating to 0.6.0. Viewing artists in the artists tab shows a somewhat better resolution than before but it's still quite bad compared to the source. It gets even worse when I click on the artist and view their page:

--

**Source image:**
![1 source](https://github.com/jeffvli/feishin/assets/141325652/15725ec8-a54e-473d-bcf7-a18b7d792dbf)

**Source image resized in MS Paint roughly to the same as it displays for me in Feishin (expected result):**
![1 source](https://github.com/jeffvli/feishin/assets/141325652/11c3eef0-074d-4433-a4c0-77e11e6a3802)

**View from the artist tab/list sidebar:**
![2 - view from artist tab](https://github.com/jeffvli/feishin/assets/141325652/e163574d-1985-419d-80b5-6dd19b6fb8cc)

**View from the dedicated artist profile:**
![3 - view from artist profile page](https://github.com/jeffvli/feishin/assets/141325652/576a9b74-f834-4bbd-8321-0c0baf50d363)

Most of this applies to the album resolution as well in the albums list.
