### ISSUE TITLE
Missing ":albumId" param after selecting "Random" sorting in Tracks tab

### ISSUE THREAD

**Issue by manuel-rw** [jeffvli/feishin#378]
## Expected Behavior
The ``Tracks`` tab shows the songs of Jellyfin.

## Current Behavior
The page does not load and shows a warning after I switched to "Random" sorting.
Now I can't reset the sorting.

![image](https://github.com/jeffvli/feishin/assets/30572287/c057970e-c790-4d65-a6b0-fe6c6c05b90a)

Restarting the application does not fix it.

## Possible Solution (Not obligatory)
- Make the album id optional

-   Application version (e.g. v0.1.0) : ``0.5.1``
-   Operating System and version (e.g. Windows 10) : ``Windows 11, amd64``
-   Server and version (e.g. Navidrome v0.48.0) : ``Jellyfin 10.8.12, Docker, x64)``
-   Node version (if developing locally) : ``N/A``

**Comment by jeffvli** [comment]
For a temporary fix, open up the dev tools with ctrl+shift+i and remove the `store_song` key from local storage to reset the filter.

![image](https://github.com/jeffvli/feishin/assets/42182408/5b1594e9-ad7c-482a-acfe-58f96ec5affb)

**Comment by jeffvli** [comment]
Actually, I'm unable to reproduce this issue on my side -- also using Jellyfin 10.8.12.

**Comment by iiPythonx** [comment]
Jellyfin 10.9.0, not seeing this issue.

**Comment by manuel-rw** [comment]
I'll close this issue as I haven't been able to reproduce this myself.

**Comment by F1NAM0RE** [comment]
I have run into the same problem on web version.

Edit: It happens when I swap from "Display type: Table" to Display type: Poster" whilst in the Tracks tab. 
Songs were sorted by recently added in descending order. 
Am using Brave browser.

**Comment by kgarner7** [comment]
This bug appears to happen when you have a song without an album id; in this case, the `LIBRARY_ALBUMS_DETAIL` path breaks. I am able to reproduce this in Jellyfin 10.8.13 and unstable (for some reason Jellyfin just refuses to acknowledge my albums...).
This issue happens for Jellyfin when in Card/Poster display for songs. Unfortunately, I'm not sure how to address this...

**Comment by timaeos** [comment]
For those encountering this issue, take a look at #531 . 

It seems like this is likely a consequence of having files in the top-level of the Music directory structure. If you have files in the top-level, I'd recommend placing them into a directory to match the structure as noted in the [Jellyfin documentation](https://jellyfin.org/docs/general/server/media/music/). For singles that don't have associated albums, throwing them into a `Singles` folder is sufficient.

After updating the directory structure, make sure that you clear Feishin's cache

**Comment by kgarner7** [comment]
Adding on here, I will still look into adding a dummy album page when the album ID is nonexistent (Feishin shouldn't just panic even if Jellyfin behavior is strange).

**Comment by nothing2obvi** [comment]
I just opened Feishin after using it a few days ago just fine and now I get this same error, only on the Home page. I am running the x64 dmg on an Intel Mac.

**Comment by timaeos** [comment]
> I just opened Feishin after using it a few days ago just fine and now I get this same error, only on the Home page. I am running the x64 dmg on an Intel Mac.

@kgarner7  is working on #553 which should hopefully resolve this but in the meantime, check if you have any songs in the top level of your directory structure and if you do, try moving them into a directory and clearing Feishin's cache as noted above

**Comment by OriCat101** [comment]
Idk if this helps, but I get the same error even tho I have no "loose" songs kicking around in my library

**Comment by YourSandwich** [comment]
Same issue here, when scrolling through Tracks
