### ISSUE TITLE
[Feature request] Display app on a different display by default

### ISSUE THREAD

**Issue by Mis1ify** [jeffvli/feishin#379]
## What do you want to be added?
Hi! Love your app. The app always starts on my primary monitor. It would be awesome if there would be an option in settings to change default app start position (or just selecting a display).
## Additional context
For now I use simple script I created, however it's not ideal and sometimes it changes wrong app.
```
nohup ~/.local/feishin/feishin &
sleep 1.75
xdotool key Super+Shift+Right
xdotool key Super+Shift+Right
xdotool key Super+Shift+Up
#xdotool key F11
```

**Comment by Sculas** [comment]
I'd like to work on this.

**Comment by kgarner7** [comment]
I would consider this mostly resolved by https://github.com/jeffvli/feishin/commit/c0110eff82b94033ea605d1ff34be79318c4aa85. Your window position is saved when you exit the application, so as long as you don't remove/change monitors it will reopen how you left it (with the same dimensions)

**Comment by Mis1ify** [comment]
I can confirm it is working within the new version 0.7.1. Thank you so much!
