### ISSUE TITLE
Letting double click on a track add the remaining tracks to queue

### ISSUE THREAD

**Issue by pim-n** [jeffvli/feishin#38]
Depending on the context and view, I think there's different ways of handling the double click event, but I think the two most significant ones are both in album view. At the moment a double click on a track only queues said track.

My suggestion is an implementation equivalent to that of Sonixd. Upon double clicking a track in album view with:

1. **Shuffle disabled**, the clicked track will play and every track with a higher track number of that same album will be queued. 
2. **Shuffle enabled**: the clicked track will play and **all** of the other tracks on the album (higher and lower track number) are queued in random order.

**Comment by jeffvli** [comment]
Fixed in #67
