### ISSUE TITLE
ReplayGain fallback cannot be set

### ISSUE THREAD

**Issue by kdltr** [jeffvli/feishin#388]
## Expected Behavior

ReplayGain fallback should be set when entering a value in the field

## Current Behavior

Setting ReplayGain fallback in the options doesn’t seem to save.

## Steps to Reproduce

1. Go to the settings

2. Fill a value for Replaygain fallback (for example -6)

3. Exit the settings

4. Go back to the settings and see that the fallback is blank again.

## Your Environment

-   Application version : 0.5.2
-   Operating System and version : Debian Sid
-   Server and version : Jellyfin 10.8.11

**Comment by untitled-operator** [comment]
I can confirm this is a bug I've had for a long time
