### ISSUE TITLE
repeat one mode, the lyrics stay at the end and do not scroll except for the first play.

### ISSUE THREAD

**Issue by flashorsink** [jeffvli/feishin#389]
## Expected Behavior

When the song is playing in repeat one mode no matter how many times, the lyrics shoud also scroll following the music play ，but it stop in the end row.

## Current Behavior

When the song is playing in repeat one mode, the lyrics stay at the end and do not scroll except for the first play.the music is still playing, the lyric seems to be dead.
![屏幕截图 2023-11-21 174840](https://github.com/jeffvli/feishin/assets/23011333/635a37aa-4b39-44e2-95f6-3324d65dc4f7)

## Your Environment

-   Application version (e.g. v0.1.0) :0.5.2
-   Operating System and version (e.g. Windows 10) :Windows 10

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/729538d885f28caaaeeb6de09711107a2ed3f8cc
