### ISSUE TITLE
MPV should not be mandatory

### ISSUE THREAD

**Issue by haath** [jeffvli/feishin#392]
Feishin can work just fine with the web player alone, and does not really *require* an mpv installation.
Therefore, the user should not be forced to provide a path to an mpv executable during the first startup.

A sensible default behavior would, in my opinion, have the initial configuration be that the web player is used.
And then, if the user wishes to configure mpv as the player, he can do so in the settings.

**Comment by jeffvli** [comment]
I'll likely change this soon. #177 is the original issue so I'll keep that one up.
