### ISSUE TITLE
Error when trying to save the password

### ISSUE THREAD

**Issue by Hyask** [jeffvli/feishin#393]
## Expected Behavior

Password should be saved successfully

## Current Behavior

In the `Manage Servers` form, saving a server with the `Save password` checkbox checked raises the following error: `An error occurred when trying to save the password`.
I don't have any line appearing in the web dev console output, so I don't have any more details to share.
![image](https://github.com/jeffvli/feishin/assets/7489759/5c926b17-67cb-4155-93e4-a0ef830db08f)

## Steps to Reproduce

1. Add a server
2. Check the `Save password` checkbox
3. Click `Save`
4. The error appears as on the screenshot above

## Possible Solution (Not obligatory)

Confusingly enough, Feishin seems to be able to stay authenticated when closed, and only asks for the password after one or two days. So it **is** actually able to remember some secrets.

## Context

Listening to music on Linux? :D

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.2 (latest as of now), both AppImage and `.tar.xz` version
-   Operating System and version (e.g. Windows 10) : Ubuntu 23.10
-   Server and version (e.g. Navidrome v0.48.0) : 0.49.3
-   Node version (if developing locally) : N/A

**Comment by nadir-ishiguro** [comment]
I had this issue since I first started using Feishin several months ago at version 0.3.0, so it's at least not new. 

I tried both the AppImage and the AUR package `feishin-bin`.

Great app otherwise. Thank you very much for your work!

**Comment by swishkin** [comment]
I have this issue too. Using Artix Linux, Feishin 0.5.2, connected to a Navidrome server.

If it could be an issue with password sanitization/storage/hashing, password looks something like this:

`rShie7Xh^Yjubd%yeo9LtS@jb5iNh52PXH$`

**Comment by cronyakatsuki** [comment]
Happen's also for me using gentoo linux and the appimage.

But I also use keepassxc for secrets storage so if Feishin uses secret's to store password  it might need to work on keepassxc support.

**Comment by fybx** [comment]
Arch Linux, Feishin 0.5.3, with Navidrome 0.50.1 server; I have gnome-keyring installed and configured for secrets.

**Comment by Insprill** [comment]
I'm also having this issue with the same setup as fybx. All other applications that store secrets work fine; only Feishin has this issue.

**Comment by kgarner7** [comment]
Based off of a similar thread from https://github.com/tutao/tutanota/issues/6265, some questions:
- Do you have `libsecret` installed? 
- Does manually setting the password store to a supported value (or basic_text) work as per https://www.electronjs.org/docs/latest/api/safe-storage#safestoragegetselectedstoragebackend-linux

**Comment by nadir-ishiguro** [comment]
> Based off of a similar thread from [tutao/tutanota#6265](https://github.com/tutao/tutanota/issues/6265), some questions:
> 
>    * Do you have `libsecret` installed?
> 
>    * Does manually setting the password store to a supported value (or basic_text) work as per https://www.electronjs.org/docs/latest/api/safe-storage#safestoragegetselectedstoragebackend-linux

In my case, libsecret is installed. Passwords are stored in the Gnome keyring and other Electron apps work without issue, but I'm not sure how to manually set the password store for Feishin.

**Comment by kgarner7** [comment]
You can pass in a cli argument `--password-store="gnome-libsecret"` to Electron/Feishin

**Comment by nadir-ishiguro** [comment]
It's difficult for me to see if it worked as - as mentioned in the issue - Feishin only seems to forget the password after a few days.

**Comment by kgarner7** [comment]
Obviously be careful when running running any code that a stranger gives you, but the following code will invalidate your credentials (exit and reopen feishin after). You can do this in the console from inspect element (control + shift + i). I will try an Ubuntu VM (I don't see this issue on my Arch system) and see if I can reproduce it as well. Sorry for asking your support on this matter

```typescript
const auth = JSON.parse(localStorage.store_authentication);
if (auth.state.currentServer.type === 'navidrome') {
  auth.state.currentServer.ndCredential = '1234'
}
for (const [id, server] of Object.entries(auth.state.serverList)) {
  if (server.type === 'navidrome') {
    server.ndCredential = '1234'
    auth.state.serverList[id] = server
  }
};

localStorage.store_authentication = JSON.stringify(auth);
```

**Comment by kgarner7** [comment]
Also worth noting, to just test password setting, all you need to do is try and save the password in the first place...

**Comment by kgarner7** [comment]
One last thing, can you output `echo $XDG_CURRENT_DESKTOP` for me?

**Comment by cronyakatsuki** [comment]
> One last thing, can you output `echo $XDG_CURRENT_DESKTOP` for me?

for me it's nothing, I just use xmonad.

**Comment by kgarner7** [comment]
Well, that would explain why. Electron is probably just unable to detect the correct session (check out https://chromium.googlesource.com/chromium/src/+/main/base/nix/xdg_util.cc for the resolution). If neither that, `DESKTOP_SESSION`, or `GNOME_DESKTOP_SESSION_ID` is set then Electron cannot detect  the correct session to use

**Comment by kgarner7** [comment]
For everyone having this issue, could you please try the associated PR and see if it resolves your issue?

**Comment by Hyask** [comment]
Is there an AppImage or `tar.gz` available somewhere? I only found the Vercel app, which doesn't match my environment.

**Comment by kgarner7** [comment]
No, you would need to build that yourself. The pipeline only updates the web interface

**Comment by Hyask** [comment]
Oh... I would have expected the CI would have done it somehow.  
Unfortunately, I have absolutely no clue how to build them, and the README doesn't make me think this will be straightforward. I don't know anything about tech revolving around web and Electron, nor do I have the time and bandwidth to dig into that, so unless there is another way, I won't be able to test this.

**Comment by kgarner7** [comment]
I've gone ahead and build them myself and uploaded https://drive.google.com/drive/folders/1QY40cLsa5tUmZoISMkP1eXStub6EFdDZ . If that doesn't work though you're out of luck

**Comment by Insprill** [comment]
My `$XDG_CURRENT_DESKTOP` is also empty since I'm just running i3. I tested out your build, and it indeed saves the password correctly.

**Comment by kgarner7** [comment]
> My `$XDG_CURRENT_DESKTOP` is also empty since I'm just running i3. I tested out your build, and it indeed saves the password correctly.

Thanks for testing! Just to confirm, does retrieving the password also work (I would expect so, but just to confirm; Settings hamburger > Manage Servers > Navidrome server > Edit, password should be filled in)

**Comment by Insprill** [comment]
Yes, the password is entered there correctly.

**Comment by Hyask** [comment]
Just tested your AppImage and tar.gz, they both were able to retrieve the password correctly, displaying it in the server's details. Many thanks for the patch **and** for the build :-)

As that seemed important: `$XDG_CURRENT_DESKTOP` is not empty, but explicitly set to `sway` by `gdm` through `~/.config/environment.d` on my setup.

**Comment by kgarner7** [comment]
Thanks both of you! I'll do some text cleanup (libsecret isn't just a Gnome thing actually, supported by a lot of other providers I learned) and update the README (noting that you either need a libsecret provider, or kwallet4/5/6)  and will merge this in soon

**Comment by FakeMichau** [comment]
I'm on hyprland with keepassxc and the issue persists. I can see that feishin doesn't use libsecret unless I pass ``XDG_CURRENT_DESKTOP=GNOME`` at which point the issue goes away.

**Comment by SushiByte-beep** [comment]
On hyperland this issue persists, passing `XDG_CURRENT_DESKTOP=GNOME` did not work for me.

**Comment by FakeMichau** [comment]
> On hyperland this issue persists, passing `XDG_CURRENT_DESKTOP=GNOME` did not work for me.

You still need something that implements Secret Service, for example I use keepassxc with Secret Service integration enabled.

**Comment by inwardgarden** [comment]
~~This seems to persist for me on Kubuntu 22.04 using latest release 0.7.1~~
~~$XDG_CURRENT_DESKTOP returns KDE~~

~~If I pass --password-store="kwallet5" via CLI to the AppImage it works, otherwise it has the error.~~

Edit: just had to change the setting as described by kgarner7

**Comment by kgarner7** [comment]
The default password store is libsecret. If that doesn't work for you, you can manually set it in Settings > Window > password/secret store

**Comment by inwardgarden** [comment]
Ah, that's my bad for not realizing the setting was available under the Window area to change the default store.

Thank you- that was all it needed!

Sorry to waste your time with this when it was right in front of me the whole time.
