### ISSUE TITLE
Pausing a track generates intermittent scrobble spam

### ISSUE THREAD

**Issue by nathan-contino** [jeffvli/feishin#394]
## Expected Behavior

When I press the play/pause button in macOS, I expect the track to stop playing and scrobbling.

## Current Behavior

Currently, the track does stop playing, but the equalizer icon on the track itself in the track list continues to animate and the play/pause button at the bottom of the screen continues to show the two vertical bar "pause" option (when the track is actually paused -- for instance, after pressing the pause button on screen -- this button should change state to the sideways triangle play button to reflect that clicking the button will begin playing the track).

Even worse, Feishin intermittently scrobbles the currently not-really-paused track to Jellyfin roughly every 7 or 8 minutes, and thus my last.fm account. This generates a lot of spam in my scrobbles! Scrobbles even seem to persist through sleep on my laptops, though on an hourly cadence instead of every 7 or 8 minutes.

Last.fm scrobble evidence:

<img width="535" alt="Screenshot 2023-11-30 at 10 08 51" src="https://github.com/jeffvli/feishin/assets/10657588/f69e1418-554c-4f55-be96-49d9cb711c9b">
<img width="536" alt="Screenshot 2023-11-30 at 10 11 45" src="https://github.com/jeffvli/feishin/assets/10657588/79ccab0b-a43e-4507-8df1-af33af576944">

I do not know if this issue exists on other platforms, but it definitely exists on macOS.

## Steps to Reproduce

1. Pause a track with scrobbling enabled when connected to a Jellyfin instance that scrobbles to last.fm. I can't tell if it matters where you pause the track.

2. Wait 20 minutes; you should see 2 or 3 scrobbles.

## Possible Solution (Not obligatory)

You know better than me.

## Context

It made me sad to have to manually delete a thousand spam scrobbles from my last.fm account when I discovered it. This issue didn't exist on Sonixd, which I used until a couple of months ago, so fortunately I only had to clean a couple of months worth of scrobbles.

## Your Environment

-   Application version (e.g. v0.1.0) : v0.5.2
-   Operating System and version (e.g. Windows 10) : macOS Sonoma 14.0/macOS Monterey on another machine
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin v10.8.9 on Raspberry Pi OS Buster
-   Node version (if developing locally) : n/a

**Comment by nathan-contino** [comment]
Managed to replicate the issue again last night. I assure you, I'm not _quite_ this big a Rush fan:


Feishin player state (note that the play/pause button shows the pause option, even though the music is already paused):
<img width="1800" alt="Screenshot 2023-12-01 at 09 25 25" src="https://github.com/jeffvli/feishin/assets/10657588/a7027e17-60ff-4bb3-8245-e5b916973c37">
Scrobble history from last night, laptop in sleep mode:

<img width="539" alt="Screenshot 2023-12-01 at 09 25 17" src="https://github.com/jeffvli/feishin/assets/10657588/2ea54f17-5bd4-49ee-93fe-add8dcc00d69">

My scrobble settings in Feishin:
<img width="1496" alt="Screenshot 2023-12-01 at 09 30 17" src="https://github.com/jeffvli/feishin/assets/10657588/c68e2ce1-1e25-4c30-bc02-b9dd1eb7cc09">
(enabled, 90%, and currently set to 160 seconds minimum play time. Though an additional piece of feedback: it's unclear how the minimum percent and minimum time settings work -- I assume the minimum setting of the two controls when the track scrobbles? e.g. 90% and 60 seconds always scrobbles at 60 seconds unless you listen to a song less than 66 seconds long, when the percentage kicks in as the actual minimum?)


So it might be better to rename this "keyboard pause button doesn't actually pause". FWIW clicking the virtual play/pause or stop buttons doesn't seem to result in the same issue, so it seems like the keyboard button handler has a subtle bug.

**Comment by jeffvli** [comment]
> I assume the minimum setting of the two controls when the track scrobbles? e.g. 90% and 60 seconds always scrobbles at 60 seconds unless you listen to a song less than 66 seconds long, when the percentage kicks in as the actual minimum?)

Yep, that's correct.

---

Thanks for looking into this. I'll try to reproduce this on my side soon and see if I can implement a fix.

**Comment by nathan-contino** [comment]
Thanks! For anyone else seeing this issue, I've found that setting "seconds" to a high number (like 1000) and "percentage" to the maximum (90% in this version) seems to mitigate the issue: I suspect that as long as you're beneath the minimum scrobble threshold when you pause the song, you won't see this problem. Unfortunately if you listen to a lot of artists with long songs, it's easy to pause in the "danger zone" after the default 60%/240 second mark!

**Comment by kgarner7** [comment]
> Managed to replicate the issue again last night. I assure you, I'm not _quite_ this big a Rush fan:
> 
> Feishin player state (note that the play/pause button shows the pause option, even though the music is already paused): <img alt="Screenshot 2023-12-01 at 09 25 25" width="1800" src="https://private-user-images.githubusercontent.com/10657588/287291631-a7027e17-60ff-4bb3-8245-e5b916973c37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDk1NTAsIm5iZiI6MTcwODMwOTI1MCwicGF0aCI6Ii8xMDY1NzU4OC8yODcyOTE2MzEtYTcwMjdlMTctNjBmZi00YmIzLTgyNDUtZTViOTE2OTczYzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyMjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NzBlYWM3NDBiOTAwNDE1ZWQyMTZkNjA3NjM0NmJkNmRkZTZlMTQ1ZDE3NjdjMzAxNzA4YTdlNjU5ZDc5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s_JbHH9zJt95se6an0htBP5BHFo9_-LUSctCjjZMNEY"> Scrobble history from last night, laptop in sleep mode:
> <img alt="Screenshot 2023-12-01 at 09 25 17" width="539" src="https://private-user-images.githubusercontent.com/10657588/287291618-2ea54f17-5bd4-49ee-93fe-add8dcc00d69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDk1NTAsIm5iZiI6MTcwODMwOTI1MCwicGF0aCI6Ii8xMDY1NzU4OC8yODcyOTE2MTgtMmVhNTRmMTctNWJkNC00OWVlLTkzZmUtYWRkOGRjYzAwZDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyMjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Y2E4MzcyYWQxZjVlYTM3ZjM0OTQ1ZmE3ZGQwNzE5ZGRlM2Y0YTdkNmNhZWIwY2QzOTRiMjc4ODA5YWNmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVlZyG295Bcsbk-GIgxh13daN6uWgDxt4lhAyavmMMw">
> 
> My scrobble settings in Feishin: <img alt="Screenshot 2023-12-01 at 09 30 17" width="1496" src="https://private-user-images.githubusercontent.com/10657588/287292619-c68e2ce1-1e25-4c30-bc02-b9dd1eb7cc09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDk1NTAsIm5iZiI6MTcwODMwOTI1MCwicGF0aCI6Ii8xMDY1NzU4OC8yODcyOTI2MTktYzY4ZTJjZTEtMWUyNS00YzMwLWJjMDItYjlkZDFlYjdjYzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyMjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZWU0ODNiZmMxNjEzNDJmN2FmZjViZjI1MWI3NDRkM2IwNmM0NjVlNWE2MmU4M2Q2OWRkYTU5YzY3Y2M4ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZSk-oRB03yneWtLIFAq14Snv2fVrvKIevU3h8aj4Ptw"> (enabled, 90%, and currently set to 160 seconds minimum play time. Though an additional piece of feedback: it's unclear how the minimum percent and minimum time settings work -- I assume the minimum setting of the two controls when the track scrobbles? e.g. 90% and 60 seconds always scrobbles at 60 seconds unless you listen to a song less than 66 seconds long, when the percentage kicks in as the actual minimum?)
> 
> So it might be better to rename this "keyboard pause button doesn't actually pause". FWIW clicking the virtual play/pause or stop buttons doesn't seem to result in the same issue, so it seems like the keyboard button handler has a subtle bug.

This latter point is fixed by the PR associated with https://github.com/jeffvli/feishin/actions/runs/7939011303. For MacOS, you need to be a trusted accessibility client to control media keys (otherwise, it would go to mpv, bypassing Feishin entirely). Can you please try this to confirm that you see the correct media state?

**Comment by kgarner7** [comment]
As there have not been any updates, and the included PR has been merged I will close this issue.
