### ISSUE TITLE
Feishin 0.5.2 with MPV backend not working after Sonoma 14.1.2 update

### ISSUE THREAD

**Issue by eclecticpassions** [jeffvli/feishin#396]
## Expected Behavior
Trying to play music via Feishin as usual via Navidrome setup on my Raspberry Pi to my Mac.

## Current Behavior
Nothing plays when I click play in Feishin. The bar doesn't move but I can see all the albums and songs. I tried restarting and updating my mpv using `brew update mpv` but it was already up to date.

## Steps to Reproduce

I thought maybe it could be a problem with MPV, so I changed the "Audio Player" setting to Web instead of MPV and it worked. Playing music on an iPad OS client (substreamer) and on Android (symphonium) works so I don't think the issue is with Navidrome/server.

## Context
Maybe the latest Sonoma macOS update broke MPV? I'm on MPV stable 0.37.0.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.2
-   Operating System and version (e.g. Windows 10) : Mac OS Sonoma 14.1.2
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3 on a Rasp Pi 4B
-   Node version (if developing locally) :

**Comment by jeffvli** [comment]
You should try to re-set the mpv path in the settings and then restart the app.

There's some discussion around that in a few threads [1](https://github.com/jeffvli/feishin/issues/286), [2](https://github.com/jeffvli/feishin/discussions/139)

**Comment by eclecticpassions** [comment]
> You should try to re-set the mpv path in the settings and then restart the app.
> 
> There's some discussion around that in a few threads [1](https://github.com/jeffvli/feishin/issues/286), [2](https://github.com/jeffvli/feishin/discussions/139)

Thanks so much @jeffvli! I tried resetting the mpv path and restarting but it didn't work. So I `brew reinstall mpv` and then reset the path to `/opt/homebrew/bin/mpv` (using `whereis mpv` in terminal) and after another restart of the app, it worked. Much appreciated. I'll do this step to troubleshoot next time if I have a similar situation. 

PS. Is there any difference in using Web or MPV for playback actually?
