### ISSUE TITLE
Ability to see codec on album page

### ISSUE THREAD

**Issue by lrduncan** [jeffvli/feishin#397]
## What do you want to be added?
I have a mixture of files and sometimes multiple copies of an album in different formats, such as a FLAC copy and an mp3 copy at varying bit rates. I can sometimes infer what it is by the bitrate on the album tracks, however it would be nice to add a column on the album page that specifies if the file is FLAC, mp3 V0, mp3 320, etc.

## Additional context

Currently I only use Jellyfin for this but I would imagine it would be nice for all servers.

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/860dd8b499f8e4acc07a987fb8f3bfcfea18739e. Of note, for Jellyfin you'll just get something like `mp3` (not V0 vs 320, unfortunately) or `flac`, and Navidrome just gets the codec by reading file extension.
