### ISSUE TITLE
[Feature Request] More extensive MPRIS metadata

### ISSUE THREAD

**Issue by djairoh** [jeffvli/feishin#399]
## What do you want to be added?
The MPRIS module currently exports a few xesam fields, next to the MPRIS specific fields. It'd be great if Feishin also supported the other popular xesam fields as listed on the [Freedesktop specification](https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#mpris-specific).

## Additional context
For my usecase specifically, I have a module in my Waybar which depends on MPRIS metadata to show information about the currently playing song, and would like to include the xesam:userRating field.

**Comment by kgarner7** [comment]
More meteadata exposed by https://github.com/jeffvli/feishin/commit/8287347f913a24636913e50bd8f8eb12c8d8dce9
