### ISSUE TITLE
Quitting Feishin leaves mpv process running

### ISSUE THREAD

**Issue by dweymouth** [jeffvli/feishin#4]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Quitting the Feishin app should terminate the associated mpv process.

## Current Behavior

Quitting Feishin leaves mpv running (and music continuing to play if the app was playing when exiting).

## Steps to Reproduce

1. Launch Feishin
2. Quit Feishin
3. Observe that mpv process is still running

## Your Environment

Mac OS, latest code off development branch.

- Node version :
- electron-react-boilerplate version or branch :
- Operating System and version :
- Link to your project :

**Comment by kgarner7** [comment]
This also happens on Linux. As an add-on, if I kill mpv manually, Feishin panics on start.

**Comment by jeffvli** [comment]
Thanks for the report! It kills itself autometically on Windows so I wasn't aware.

**Comment by dweymouth** [comment]
FYI this bug is still present on MacOS if you close the window (leaving the app running) and then quit the app (from the system menu or right-clicking in the dock and selecting "Quit") without making the window visible again. Quitting the app while the window is present does properly kill the mpv process.

**Comment by jeffvli** [comment]
@dweymouth Thanks, I think it's related to the default close behavior that the boilerplate has set. I remember there were a lot of adjustments made to this on Sonixd so I'll have to re-check it later.

https://github.com/jeffvli/feishin/blob/38a4e1b7497cd69b49209d31a96bd07f2654fe45/src/main/main.ts#L172-L179

**Comment by AlexKurisu** [comment]
This bug is also still present on Linux

**Comment by YourSandwich** [comment]
This issue was fixed for me on ArchLinux #25

**Comment by jeffvli** [comment]
Yep, should be fixed in the latest releases. I'll close this for now unless someone is having issues with it again.
