### ISSUE TITLE
The user is allowed to open multiple instances of the program, with the second instance having errors.

### ISSUE THREAD

**Issue by WhyKickAmooCow** [jeffvli/feishin#40]
In the linux build of feishin, the user is allowed to open multiple instances of the program. The second instance throws multiple errors and appears to be unconfigured to the user. The expected behavior would be to focus the current program instance when attempting to open another, or to not do anything.

**Comment by jeffvli** [comment]
Added in [0.0.1-alpha6](https://github.com/jeffvli/feishin/releases/tag/v0.0.1-alpha6).
