### ISSUE TITLE
Global media hotkeys don't work until toggled

### ISSUE THREAD

**Issue by Insprill** [jeffvli/feishin#404]
## Expected Behavior

Global media hotkeys should be functional out of the box as the default state of the toggle indicates.

## Current Behavior

After a fresh install of the application, or the deletion of the config file, global media hotkeys are not functional until they're toggled off and back on.

## Steps to Reproduce

1. Remove the `global_media_hotkeys` from your config.
2. Start Feishin and start playing a song.
3. Try to use the media hotkeys. They won't be functional.
4. Open the settings and toggle global media hotkeys.
5. Try using the media hotkeys again. They will now be functional.

## Your Environment

-   Application version (e.g. v0.1.0): `v0.5.2`
-   Operating System and version (e.g. Windows 10): `Windows 11`
-   Server and version (e.g. Navidrome v0.48.0): `Navidrome 0.50.1`

**Comment by auyylaso** [comment]
I'm having the same issue on windows 10
On V0.5.3

**Comment by iiPythonx** [comment]
Should be fixed as part of #488.

**Comment by kgarner7** [comment]
Closing this as resolved by #488 (thanks!)
