### ISSUE TITLE
Can't Login to User without a Password on Jellyfin server

### ISSUE THREAD

**Issue by NicholasFlamy** [jeffvli/feishin#405]
## Expected Behavior

Allow me to leave password blank when editing server info or logging in again after session expiration.

## Current Behavior

Password when blank says please fill out this field.

## Steps to Reproduce

Create Jellyfin user without a password and login to Jellyfin server as this user with password left blank. Then when your session expires, if you try to login again it forces password.

## Possible Solution (Not obligatory)

Allow empty password field.

## Context

Login to private Jellyfin server that has no password on my user account so that TV sign in is quick.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.2 (existed before this version, just updated to check if it was a version problem.)
-   Operating System and version (e.g. Windows 10) : Windows 11
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin v10.8.13
-   Node version (if developing locally) :

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/0cdfc64023476c3330bc88dd5431ba9d13973aa5. Thanks!
