### ISSUE TITLE
Please add a linux arm64 appimage

### ISSUE THREAD

**Issue by bubu-bubu-85** [jeffvli/feishin#406]
## What do you want to be added?
On your previous project, there is linux arm releases easily usable (cf https://github.com/jeffvli/sonixd/releases/download/v0.15.5/Sonixd-0.15.5-linux-arm64.AppImage). A an Asahi Linux user, I dream to have the same thing with Feishin.

## Additional context
This will be helpfull for people who use GNU/Linux on ARM platforms.  
Thanks by advance.

**Comment by jeffvli** [comment]
Added in the latest 0.5.3

**Comment by bubu-bubu-85** [comment]
It works like a charm !
Thank you :)
