### ISSUE TITLE
Top Songs for an artist appear to be in random order

### ISSUE THREAD

**Issue by Harteex** [jeffvli/feishin#410]
## Expected Behavior

Top Songs for an artist should be ordered in a sensible order, for example based on plays or at least recent plays.

## Current Behavior

Top Songs are sorted in a way that doesn't make sense, as far as I can tell. It places songs with no plays at all higher up than those that have.
![bild](https://github.com/jeffvli/feishin/assets/815152/d52f4f07-827f-4654-aad3-ccdedc94a661)

## Steps to Reproduce

1. Click an artist and view Top Songs

2.

3.

4.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.2 (feishin.vercel.app)
-   Operating System and version (e.g. Windows 10) : Windows 10
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin 10.8.9
-   Node version (if developing locally) :

**Comment by Optekah** [comment]
It's always been like this for me too, so it's not just you. Jellyfin and Navidrome both on Unraid.

On a somewhat related note, The "recent albums" on this same page as the "top songs" also seem to not display in anything other than a random order as well. Albums from 2023 are buried in the list while ones from the middle or even the beginning of an artists career can pop up at the very forefront.

**Comment by jeffvli** [comment]
For Jellyfin the sort uses `CommunityRating` I believe, which in the case of no metadata will return a random sort. I'll probably just change this to use the PlayCount instead.

Navidrome should work properly, granted you have the `lastfm` integration enabled, since it pulls the top song list from there.

**Comment by iiPythonx** [comment]
> On a somewhat related note, The "recent albums" on this same page as the "top songs" also seem to not display in anything other than a random order as well. Albums from 2023 are buried in the list while ones from the middle or even the beginning of an artists career can pop up at the very forefront.

+1 for this, I can't say I'm having the track sorting issue but my albums on Navidrome are definitely in a random order.
According to the Navidrome UI:
![image](https://github.com/jeffvli/feishin/assets/35084023/23ede7b9-1012-407d-bba9-b0278ba32d4f)

And then Feishin:
![image](https://github.com/jeffvli/feishin/assets/35084023/60dc2a88-0d00-4c6b-bb5c-026f4b760c21)

**Comment by Optekah** [comment]
I personally have no use for the "top songs" and stuff like that haha. I would be super grateful if there was a way to just display all releases by an artist in grid format as soon as I click on the band name. Perhaps I could make a request post.



> Navidrome should work properly, granted you have the `lastfm` integration enabled, since it pulls the top song list from there.

Ah this makes sense. Good to know, thanks!

**Comment by jeffvli** [comment]
> I would be super grateful if there was a way to just display all releases by an artist in grid format as soon as I click on the band name. Perhaps I could make a request post.

Someone already opened an issue for this (though I don't know which one it is off the top of my head), but it's already something I was planning on implementing.

Regarding the recent releases album ordering on Navidrome -- I just confirmed it as well. For some reason the `_sort` parameter is missing when performing the query which is why it's using a random order. I'll fix that soon.

**Comment by Optekah** [comment]
> but it's already something I was planning on implementing

Fantastic news. Very thankful for all your hard work!

**Comment by cyberwolfie1** [comment]
> > but it's already something I was planning on implementing
> 
> Fantastic news. Very thankful for all your hard work!

I am also very happy about this planned enhancement :)

**Comment by iiPythonx** [comment]
> Regarding the recent releases album ordering on Navidrome -- I just confirmed it as well. For some reason the _sort parameter is missing when performing the query which is why it's using a random order. I'll fix that soon.

Are there still plans on this being fixed? Artist albums still show up in a random order when viewing their artist page with Navidrome.

**Comment by kgarner7** [comment]
Yes, see https://github.com/jeffvli/feishin/commit/24bf7ae31fcd7f248cd5c2c68fd3526d0954450e. Sort is by year since that's supported for v0.48.0-current, eventually it can be release date when server features are available
