### ISSUE TITLE
Order albums by YEAR

### ISSUE THREAD

**Issue by vlastaw** [jeffvli/feishin#415]
## What do you want to be added?

InOrder Albums by YEAR in Artist view.

## Additional context

When clicked Artists > pick one > view discography - add the possibility to order view by year.

Thank you!

**Comment by kgarner7** [comment]
Support for this exists for both Navidrome (sort by `Release Year`) and Jellyfin (sort by `Release Date`, which is internally `ProductionYear,PremiereDate,SortName`). If this is not what you are expecting, please add some more details!

**Comment by vlastaw** [comment]
What should I pick then? Recently added is there twice. Is it just a wrong string?

![image](https://github.com/jeffvli/feishin/assets/46008671/6460b5fa-d2c7-4ee9-9735-4997d75263f8)

Thanks

**Comment by kgarner7** [comment]
What version are you using? This should be in latest (or at least `development`)
![image](https://github.com/jeffvli/feishin/assets/17521368/8309de9a-e60d-469c-aa4b-33594f2bc6f8)
Taken from https://feishin.vercel.app

**Comment by vlastaw** [comment]
0.5.3 release, both Windows and Docker.

**Comment by kgarner7** [comment]
Ah yes, this is a recently fixed bug: https://github.com/jeffvli/feishin/pull/458 (if you try the current webapp on vercel it is resolved). In the meantime the second one should work

**Comment by kgarner7** [comment]
I'll mark this as closed since it's fixed on https://feishin.vercel.app/
