### ISSUE TITLE
Artist "Recent Releases" is ordered backwards

### ISSUE THREAD

**Issue by Insprill** [jeffvli/feishin#417]
## Expected Behavior

Recent Releases should show the most recent albums.

## Current Behavior

Recent Releases shows the oldest albums first.
![image](https://github.com/jeffvli/feishin/assets/52843537/280cc250-76ff-431d-a049-8cb37fd43af3)

## Steps to Reproduce

1. Go to an artist.
2. View the "Recent Releases" section.
3. Observe it showing the oldest release first.

## Your Environment

-   Application version: v0.5.3
-   Operating System and version: Windows 11
-   Server and version: Navidrome 0.50.2

**Comment by iiPythonx** [comment]
Possibly related to the sorting issues described in https://github.com/jeffvli/feishin/issues/410?

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/24bf7ae31fcd7f248cd5c2c68fd3526d0954450e (sorted by year)
