### ISSUE TITLE
Precise accent color

### ISSUE THREAD

**Issue by Insprill** [jeffvli/feishin#421]
## What do you want to be added?

An input field to set the accent color to a specific HEX value. Currently, the only way to set the accent color is with the color picker, which makes it extremely difficult to set an exact color. It'd be great if there were an input field allowing a custom HEX code, or RGB values to be entered

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/45e589fbb1ab3b25f29f20bf2bb775b52f3f30b4. Input supports `rgb($R, $G, $B)`, but will still bring up picker
