### ISSUE TITLE
Add definition of 'song_other'

### ISSUE THREAD

**Issue by laker-93** [jeffvli/feishin#422]
Missing entity string definition of 'song_other' in locales. Example from en.json here. other languages seem to be missing it too:

https://github.com/jeffvli/feishin/blob/960427fce82b0ded78d95c882baff51c0726f08c/src/i18n/locales/en.json#L219

**Comment by laker-93** [comment]
I think this is also broken: https://github.com/jeffvli/feishin/blob/development/src/renderer/features/playlists/components/add-to-playlist-context-modal.tsx#L199

The form attribute should be:

'form.addToPlaylist.success'

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/pull/473! The correct field is `track_other`. Practically though, it would be nice to use the pluralized form with count where appropriate...
