### ISSUE TITLE
Make space bar the default shortcut for play/pause

### ISSUE THREAD

**Issue by codenyte** [jeffvli/feishin#425]
## What do you want to be added?

Space bar is a really common keyboard shortcut for play/pause. It's used in various applications/websites like e.g. Spotify, Apple Music, Navidrome, YouTube, VLC, mpv, etc.
I discovered that you can manually add a shortcut for play/pause, but I think that basic things like this should be the default.

**Comment by tmcelroy2202** [comment]
Can you add a shortcut for play / pause ? i see you can add a shortcut for play, and a shortcut for pause, but i do not see a way to bind play and pause to the same shortcut just as a toggle. Shortcut for play / pause instead of shortcut for play and shortcut for pause might also be a crucial enhancement.

**Comment by tmcelroy2202** [comment]
Temporary fix : ive bound winkey + t to playerctl play-pause. 

for xmonad this was as simple as 
    , ((super,                   	xK_t), 		spawn "playerctl play-pause")
in my keybinds section. 

here is the repo for playerctl https://github.com/altdesktop/playerctl 
you will have to install it but i am pretty sure it is in most repos. All i had to do was pacman -S playerctl on arch.

**Comment by iiPythonx** [comment]
> but i do not see a way to bind play and pause to the same shortcut just as a toggle

What version are you running? I'm running 0.5.3 and I have options for all 3 inside my settings:
![image](https://github.com/jeffvli/feishin/assets/35084023/5b29e8db-f745-4d16-ad36-edb5930aae12)

**Comment by tmcelroy2202** [comment]
Yeah this was a brain issue. I have absolutely no clue how i missed that. Gonna delete my comments now.

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/097211954c57db766606d00cd7137bdc8c6580d1 This won't update existing settings, but will work for new installs
