### ISSUE TITLE
Lyrics centered

### ISSUE THREAD

**Issue by OcrSu** [jeffvli/feishin#431]
## What do you want to be added?
Always place the current lyrics in the middle. （Picture2）

Whenever I play to the end, the lyrics always sink to the bottom.（Picture1）

## Additional context
![image](https://github.com/jeffvli/feishin/assets/75876201/38dde03a-b6a0-4d20-bf42-42db240275cf)
![image](https://github.com/jeffvli/feishin/assets/75876201/138162f3-11cb-417d-80e2-f22ea32462e8)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/afb8510cd746796ea3cca297ea08347d74eec255 (additional padding at the bottom)
