### ISSUE TITLE
Saves Playlists as Guest User even tho i am logged in as "Admin"

### ISSUE THREAD

**Issue by kobayashi90** [jeffvli/feishin#433]
## Expected Behavior
Well saving the playlist as Admin User.

## Current Behavior

Saves the Playlist as Guest User (aka pre-defined auto login user) even tho i am clearly logged in as Admin User.

## Steps to Reproduce

Setup an Normal User Account (no Admin) with the var: ND_DEVAUTOLOGINUSERNAME and try to make an playlist while logged into Feishin with another Account that has Admin Rights.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.3
-   Operating System and version (e.g. Windows 10) : Docker (on ArchLinux)
-   Server and version (e.g. Navidrome v0.48.0) : 0.5.3
-   Node version (if developing locally) : -

**Comment by kgarner7** [comment]
This is a problem with Navidrome, nothing Feishin can do about it. See https://github.com/navidrome/navidrome/blob/5125558f5271af40b682feba9b675dddbf205e3f/server/auth.go#L244 and `func UsernameFromConfig` for implementation details.

When `DevAutoLoginUsername` is set, all requests will be that user, regardless of how you login.
