### ISSUE TITLE
Can't clear the year filter in Albums view

### ISSUE THREAD

**Issue by kowalcj0** [jeffvli/feishin#439]
## Expected Behavior

Users should be able to clear the year filter in the Albums view so they can view all albums rather than those from selected year.

## Current Behavior

Users can't clear the year filter in the Albums view.
See steps to reproduce for more details.

## Steps to Reproduce

1. Go to Albums view
2. Click on `Filters` button
3. Enter some year, e.g. `2000` and press Enter
4. You should see albums from year 2000
5. Click on `Filters` button again
6. Clear the year value and press Enter
7. Nothing is going to change. You'll see albums from year 2000

## Possible Solution (Not obligatory)

1. Go to `Menu` -> `Open browser devtools`
2. Go to `Application` tab
3. Then in the `Storage` section, find `Local Storage` and click on `file:///`
4. On the list of Key/Values locate `store_list`
5. Right click on that value and hit `Delete`
6. Refresh the page with `Ctrl+r`

![image](https://github.com/jeffvli/feishin/assets/910451/870436f3-0de6-46ba-8c61-38544c99fca3)

N/A

## Context

It's annoying that one can't clear the filter.

## Your Environment

-   Application version : Feishin-0.4.0-linux-x64
-   Operating System and version : Fedora 39
-   Server and version : Navidrome v0.50.2
-   Node version (if developing locally) : N/A

**Comment by iiPythonx** [comment]
Not seeing this issue on 0.5.3, is there any reason you're still using 0.4?

**Comment by kowalcj0** [comment]
TBH IDK :grin: 
I thought I've updated the app recently but apparently I haven't hahaha
I just switched to 0.5.3 and indeed that issue is gone :grinning: 
Thanks @iiPythonx
