### ISSUE TITLE
Allow theming feishin based on the album art color palette

### ISSUE THREAD

**Issue by amolinae06** [jeffvli/feishin#441]
## What do you want to be added?
Allow to use the album art color palette to theme the whole interface or set the background with a blurred version of the song currently playing.
## Additional context
Either theming the fullscreen player or desktop mode, preferably updating the fullscreen mode and replace the single color bakground feature.

No.

**Comment by kgarner7** [comment]
Full screen player background from track art is available as of https://github.com/jeffvli/feishin/pull/526
