### ISSUE TITLE
Keep currently playing track position when shuffling

### ISSUE THREAD

**Issue by Scrath1** [jeffvli/feishin#442]
## What do you want to be added?
When shuffling a currently playing queue, the current song is also shuffled. This can cause the active song to become the last one in the queue, thereby ending playback after it has finished.
Keeping this song in the same position or always moving it to the first place in the queue would make more sense in my opinion.

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/20b161ee864747773e0f46484adbb1aab067007a
