### ISSUE TITLE
Alphabetical sorting separating upper- and lower-case for Tracks and Smart Playlist (Query Editor)

### ISSUE THREAD

**Issue by breakfast-first** [jeffvli/feishin#445]
## Expected Behavior

Case is ignored when sorting alphabetically resulting in only 1 alphabetized list with mixed cases for all views (as it currently does in artist and album views).
Ex. A, b, C, g, N, p, Z

## Current Behavior

Lowercase letters sort after all uppercase letters resulting in 2 joined alphabetized lists: A-Z followed by a-z when viewing any track listing or setting the sorting in the Query Editor for a Smart Playlist (selecting 'Album Artist' and 'Album' as sort parameter both produced this issue, but selecting 'Sort Album Artist' sorted properly)
Ex. A, C, N, Z, b, g, p

## Steps to Reproduce

1. go to any track listing that includes both lower- and upper-case titles

2. sort by Name

OR

1. create smart playlist that includes both upper- and lower-case artists/albums (or open Query Editor in existing playlist)

2. select 'Album Artist' or 'Album' in sort parameter

3. save and reload playlist

## Possible Solution (Not obligatory)

Use the same sorting behavior (not case-sensitive) for all alphabetical sorting

## Your Environment

-   Feishin 0.5.3 win x64
-   Windows 11
-   Navidrome v0.50.2

**Comment by kgarner7** [comment]
It is worth noting that the Navidrome API (and Navidrome web interface) is a case-sensitive sort. The exception for this is if you have [PreferSortTags](https://www.navidrome.org/docs/usage/configuration-options/#:~:text=all%20its%20subfolders\)-,prefersorttags,-ND_PREFERSORTTAGS) and your files tagged properly, then the artist/album/track is case-insensitive sort

**Comment by kgarner7** [comment]
Closing this because this is an issue with Navidrome smart playlist implementation (case insensitive). Please consider filing an issue on Navidrome itself to support case-insensitive searching.
