### ISSUE TITLE
Add a Setting to customize the order of elements in the Artist view

### ISSUE THREAD

**Issue by rappo** [jeffvli/feishin#446]
## What do you want to be added?

Currently an Artist page has three components:
* Top Songs
* Recent Releases
* Related Artists

I would like to customize the order of these, for example to put Recent Releases first

![image](https://github.com/jeffvli/feishin/assets/2245234/54c4556d-404e-4639-b459-d44cb649ddcb)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/f7dd634f67e042d3d585c7f6f1b625becb5bf4d3
