### ISSUE TITLE
[UI] Mobile Responsive Layout

### ISSUE THREAD

**Issue by rairulyle** [jeffvli/feishin#448]
## What do you want to be added?

I have been using your docker build and accessing the web app on my tablet. However, I also want to access it via mobile, but the problem is that it doesn't look responsive and UI is out of place. I know that this may be a low prio but I want you to know that once this has been solved, I'll be one of the users who will uninstall mobile app jellyfin client!

**Comment by kgarner7** [comment]
Duplicate of #33
