### ISSUE TITLE
Sample rate switcher

### ISSUE THREAD

**Issue by QuiNzX** [jeffvli/feishin#45]
Is there a way to change the sample rate?

For example if the source is 24/96khz and ur device is on 24/48khz then it would automatically switch to the matching sample rate as the source, which isn’t the case as of right now. 

Perhaps exclusive mode, so it exclusively take over ur device.

I would highly appreciate such feature, other than that keep up doing the good work!

**Comment by andrewdunndev** [comment]
I was about to ask the same, looks like mpv has an [`audio-exclusive`](https://mpv.io/manual/master/#options-audio-exclusive) mode that would work. 

Kudos to @dweymouth of [this project](https://github.com/dweymouth/supersonic) for pointing it out.

**Comment by dweymouth** [comment]
@jeffvli You may also want to change the default gapless audio setting for mpv from "yes" to "weak". The latter will close and re-open the audio device if the next track has a different sample rate. (Leading to a gap between tracks if two gapless tracks have different sample rates, but this seems like an extremely unlikely scenario)

**Comment by jeffvli** [comment]
@dweymouth Thanks for that info. I'll switch over to "weak".

**Comment by andrewdunndev** [comment]
@jeffvli would you add a toggle to put mpv into exclusive mode?

**Comment by kdb424** [comment]
Very much in favor of adding a sample rate matching option. It's the only missing feature that I felt I lost when using SonixD and now Feishin. Another vote for support as the mpv backend should make this relatively simple to add.

**Comment by jeffvli** [comment]
Added in [0.0.1-alpha6](https://github.com/jeffvli/feishin/releases/tag/v0.0.1-alpha6).

**Comment by AlexKalopsia** [comment]
Just here to thank you all for working on this. Was sad that sonixd wouldn't allow this, and now very excited for Feishin.
