### ISSUE TITLE
Unexpected Application Error！

### ISSUE THREAD

**Issue by JinLingGitHub** [jeffvli/feishin#454]
## Expected Behavior
This interface pops up directly after the program starts
Feishin-0.5.3-win-x64
1.
![image](https://github.com/jeffvli/feishin/assets/8239862/92a3b346-2ee2-4f50-a8c8-069429880c8a)

2.

3.

4.

## Your Environment

-   Application version (e.g. 0.5.3) :
-   Operating System and version (e.g. Windows 11) :
-   Server and version (e.g. Navidrome v0.48.0) :

**Comment by kgarner7** [comment]
Can you try https://github.com/jeffvli/feishin/pull/470 (Visit Preview) and see if this resolves the issue for you? (In particular, try setting the sample rate to small values, and you should not see any problems)
