### ISSUE TITLE
Have a blurred interface

### ISSUE THREAD

**Issue by ha-ku** [jeffvli/feishin#455]
## Expected Behavior
I should have an interface that stays clear.

## Current Behavior
The interface becomes blurry in use, even for devtools. When the mouse is pointed at an area it becomes temporarily clear, but fades to blur when the mouse is removed.

<img width="767" alt="screenshot 2024-01-21 205558" src="https://github.com/jeffvli/feishin/assets/18721230/26868f9e-f93c-4981-a802-0f22079943e4">

## Steps to Reproduce

1.Open feishin.

2.Just move the cursor around.

## Context
I also have another chrome installed on my computer and it doesn't seem to have this problem. Neither does Sonixd.

## Your Environment

-   Application version (e.g. v0.1.0) :v0.5.3
-   Operating System and version (e.g. Windows 10) :Windows 11 22H2 22621.3007
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin latest
-   Node version (if developing locally) :

**Comment by jeffvli** [comment]
That's strange, never seen this issue before.

Do you have a Nvidia GPU? There are some reports of Antialiasing - FXAA being enabled in Nvidia 3D settings causing blurriness.

**Comment by ha-ku** [comment]
Ah yes, that's exactly the cause. After I turn off the FXAA everything works fine. Thanks!
