### ISSUE TITLE
Focusing on Feishin causes queue to snap back to current song

### ISSUE THREAD

**Issue by kaibagley** [jeffvli/feishin#457]
## Expected Behavior

When changing focus to another app, then hovering the cursor over Feishin and scrolling through the queue, trying to click on a song selects the song we want.

## Current Behavior

Instead of selecting the song we are hovering over, the queue jumps back to the currently playing song, and wherever the cursor is now pointed is the selected song

## Steps to Reproduce

1. Click on another app while Feishin is open on another monitor or another viewable window
2. Hover cursor over Feishin queue, and scroll down some distance
3. Click on a song
4. Queue will jump back to current song, and a song will be selected based on whatever is now under the cursor

## Additional Information

Also happens when scrolling queue while focussed, focus on another app, focus on Feishin and queue will be back to current song. So it seems like its just that when Feishin is focussed on it resets queue position.

Forgive me if I'm wrong, but I found the following: https://github.com/jeffvli/feishin/blob/dcccccea2fac90a93fe599749bbff4767a22d7b1/src/renderer/components/virtual-table/hooks/use-current-song-row-styles.ts#L19
I don't know much, if anything about TypeScript but the issue I'm having may be purposeful behaviour.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.3
-   Operating System and version (e.g. Windows 10) : Windows 10
-   Server and version (e.g. Navidrome v0.48.0) : 0.50.2

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/26102bd70a7e10e75860eb20c44bfa7f1af43b15 (that was a good hint for starting!)
