### ISSUE TITLE
How can I add artists bio?

### ISSUE THREAD

**Issue by PauFCB** [jeffvli/feishin#46]
Hi, How can I see the biographies of the artists like in the example photo of Snail House? I have installed the last.fm plugin but I can't even get it, even with famous artists like John Coltrane or ACDC. Thank you.

**Comment by jeffvli** [comment]
The metadata comes directly from your server.

For Navidrome, this would be with the [lastfm integration](https://www.navidrome.org/docs/usage/external-integrations/#lastfm).

For Jellyfin, it depends on the metadata downloaders that are attached to your music libraries. Feishin pulls the `Overview` field from the artist. You can also try adding the [lastfm plugin](https://github.com/jesseward/jellyfin-plugin-lastfm) if your current metadata fetchers aren't pulling data.
