### ISSUE TITLE
Lyrics not auto downloading

### ISSUE THREAD

**Issue by turkeyphant** [jeffvli/feishin#467]
## Expected Behavior

When fetch lyrics from internet is turned on and sources are activated, lyrics should automatically download.

## Current Behavior

I have to manually click Search for each song then select lyrics instead of the app automatically doing this.

## Steps to Reproduce

1. Open app

2. Play a song with lyrics on one of the sources

3. Navigate to lyrics page

4. No lyrics show until you manually search

## Context

Works fine on another Windows system

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.3
-   Operating System and version (e.g. Windows 10) : Windows 11
-   Server and version (e.g. Navidrome v0.48.0) : [0.51.0](https://github.com/navidrome/navidrome/releases/tag/v0.51.0) (fd61b29a)
-   Node version (if developing locally) :

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/918842e3a5450ed48b916e2745b106c1ba0ee6f8
