### ISSUE TITLE
Embedded lyrics show gibberish 

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#468]
## Current Behavior

![image](https://github.com/jeffvli/feishin/assets/74906541/4e127322-1484-4518-b78e-4dbf2a458710)

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.3
-   Operating System and version (e.g. Windows 10) : Ubuntu 23.10
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.51.0

**Comment by Insprill** [comment]
I can confirm this with Navidrome v0.51.0 playing a FLAC file with embedded lyrics.
![image](https://github.com/jeffvli/feishin/assets/52843537/4b6c893e-b054-4ef8-8f03-d79527c23bf1)

In addition, it doesn't look up lyrics online anymore, even when the track has none embedded.
![image](https://github.com/jeffvli/feishin/assets/52843537/292aeeb2-ba56-495b-b775-5f9b70a5ab7e)

**Comment by TacoCake** [comment]
Navidrome added 'Structured lyrics' in their newest release, which changed the behaviour for lyrics.

https://github.com/navidrome/navidrome/releases/tag/v0.51.0

The function needs modifications to handle the new response structure. Until then, you can roll back navidrome or wait for an update to feishin
