### ISSUE TITLE
Track resumeable after clearing queue

### ISSUE THREAD

**Issue by rkowalsk** [jeffvli/feishin#469]
## Expected Behavior

When pressing the "Clear queue" button at the top of the queue the queue is cleared, the song currently playing song is stopped and the content of the "currently playing song" bar at the bottom of the screen is emptied to indicate that nothing is playing. I think pressing the "Play" button should either do nothing or play a song and indicate in the bottom bar what song is playing.

## Current Behavior

After clearing the queue, if you press the "Play" button, the song that was playing resumes and the bar stays empty (the song name, album, art and the progression bar are empty as if nothing was playing, only the time since the beginning of the song at the left of the progression bar shows the right value).
![Capture d’écran du 2024-01-23 22-33-14](https://github.com/jeffvli/feishin/assets/43633272/f2dfbeb5-1e6d-41b9-a5d9-b03b165297e8)

## Steps to Reproduce

1. Play a playlist or add songs to the queue

2. Press the "Clear queue" at the top of the queue

3. Press the "Play" button

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.3
-   Operating System and version (e.g. Windows 10) : Arch Linux (feishin-bin installed from the AUR)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/527e6a76b541bb9d23ab496b64c094cd6cb6aab9. Pause/play button is disabled if the queue is empty
