### ISSUE TITLE
Playing music from the search screen doesn't add all the entries to the queue

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#472]
## Expected Behavior

In all other places, when you play something, everything in the list is queued. 

## Current Behavior

![image](https://github.com/jeffvli/feishin/assets/74906541/1417c934-c0d9-4a8a-b6a5-04eaa199aa38)

Clicking on these will only queue up the one you clicked on.

## Your Environment

- Application version (e.g. v0.1.0) : 0.5.3
- Operating System and version (e.g. Windows 10) : Ubuntu 23.10
- Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.51.0

**Comment by kgarner7** [comment]
That's similar behavior seen on album track list; you have to select the tracks you want to play (tracks of an album have a 'click on disk' button). So you would either do control + click each item you want to play, or shift + click to select a group. Only selected tracks are played

**Comment by isle9** [comment]
> That's similar behavior seen on album track list.

Are you referring to a specific place in Feishin here, or about something else?

**Comment by kgarner7** [comment]
Anywhere where you have a list of songs (album tracks, song search, playlist, or queue). If you click on and highlight only one track, then only that track will be added to your play queue (or playlist, if you use `Add to playlist`).

**Comment by isle9** [comment]
> If you click on and highlight only one track, then only that track will be added to your play queue

Yes, If I click on (I'm guessing you are referring to selecting one item in the list here), and then right click and click play, it only adds that one, but if I double click on an item in any of those lists (besides search), all of them are added to the play queue. It's been like this for a while.

**Comment by kgarner7** [comment]
I understand the issue a bit better, thanks! This is a bit different from all the other pages, namely because the results are *not* all fetched at once (Feishin will lazy load 300 items at a time). For album/artist the behavior on this page is to go to the album/artist, so I'm not sure the correct approach here.

**Comment by isle9** [comment]
Great, I'm glad we are on the same page now. It's not an urgent issue since you can still select them all and click play, and they will be added to the play queue, but it would be nice if it behaved like it does everywhere else in the future.

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/8900d8126ccc2b4053ed9903f7556deffb6defb2
