### ISSUE TITLE
Select random tracks from library

### ISSUE THREAD

**Issue by kowalcj0** [jeffvli/feishin#474]
## What do you want to be added?

An option to find and play a number of randomly selected tracks from the library.

## Additional context

It's really convenient to explore one's collection by listening to randomly selected tracks from library.

Nope. Mobile clients like Ultrasonic or substreamer have such feature:
![Screenshot_20240126-091859](https://github.com/jeffvli/feishin/assets/910451/e836d029-16d3-4180-91d4-e838b8e6cecf)
![Screenshot_20240126-092405](https://github.com/jeffvli/feishin/assets/910451/e7b01f11-bb3a-4f60-b90b-dc81ed3cd8f4)

**Comment by kgarner7** [comment]
Is this what you mean?
![image](https://github.com/jeffvli/feishin/assets/17521368/43b218d9-d8c2-4c42-b94f-ed98287c0aa1)
Opens this modal
![image](https://github.com/jeffvli/feishin/assets/17521368/06d090e5-ae67-4517-94cd-fdf05e064bd3)

**Comment by TacoCake** [comment]
Wow, I didn't even know this existed ! 

Might need to make it more obvious or something.

**Comment by kgarner7** [comment]
If you have recommendations for a better icon (See https://react-icons.github.io/react-icons/) or interface, feel free to give suggestions!

**Comment by kowalcj0** [comment]
hi @kgarner7 
yes, that's exactly what I was looking for. Thank you opening my eyes!!! :D
It's kinda funny that it's been there all the time and I haven't even noticed it.
I think I expected the same behaviour as on albums page where there's an option to select a random set of albums.

re. recommending a better icon 
Maybe `GiPerspectiveDiceSixFacesRandom`
![image](https://github.com/jeffvli/feishin/assets/910451/4a03a9d3-72ac-47e3-80b2-cb4747e8be4b)
or `GiCardRandom`?
![image](https://github.com/jeffvli/feishin/assets/910451/bd2c9256-867d-4e47-b83f-2da806067108)
or simple dice `GiPerspectiveDiceSixFacesFour`
![image](https://github.com/jeffvli/feishin/assets/910451/3f7eb508-c193-409d-a698-c24f1db2b1d0)
or a dice outline  `IoDiceOutline`
![image](https://github.com/jeffvli/feishin/assets/910451/8a769343-a31b-4124-bfdf-14acbe0fe0f8)

To my mind these icons suggest "randomness".

**Comment by TacoCake** [comment]
I think I'd rather have a single dedicated "Hey put me in continuous random play mode" button (#7), rather than having to manually click the add random songs button every X songs. 

However, I think the dice would work better than the current icon.

**Comment by kgarner7** [comment]
Thanks TacoCake and kowalcj0! I'll update the icon to use dice (I think probably `IoDiceOutline` unless there's a ri variant) and use that to close this issue. Continuous playback would probably be another button/feature down the line...

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/efa0d9ec35ac09f19eaf280f5b48c24de0bec410 (used flat 3 dice, since it's hard to make it clear with 20px). Also make hover immediately show description.
