### ISSUE TITLE
Global hotkeys don't work.

### ISSUE THREAD

**Issue by turkeyphant** [jeffvli/feishin#477]
## Expected Behavior

Pressing global hotkeys such as Media_Prev, Media_Play_Pause, Media_Next performs the relevant actions

## Current Behavior

These keys don't have any effect in Feishin. They work perfectly in Winamp and Spotify. Global hotkeys is enabled.

## Steps to Reproduce

1. Turn on global hotkeys in settings

2. Press any of the media playback hotkeys

## Context

Can't use the keyboard to change tracks or play/pause.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.3
-   Operating System and version (e.g. Windows 10) : Windows 10
-   Server and version (e.g. Navidrome v0.48.0) : [0.51.0](https://github.com/navidrome/navidrome/releases/tag/v0.51.0) (fd61b29a)
-   Node version (if developing locally) :

**Comment by patrick-motard** [comment]
It works for me.

- app version: 0.5.3
- os: windows 11 & OSX Ventura 13.4 m1 chip
- server: navidrome [0.50.1-SNAPSHOT](https://github.com/navidrome/navidrome/compare/v0.50.1...9220d8f5) (9220d8f5)

I would add however that even though play/pause and next/previous work, the Feishin UI often reports the wrong state of playback. For example, if i have another app focused and I pause a song playing in Feishin, and then focus feishin, it still shows that the song is playing even though its not. Probably unrelated to what you're experiencing though.

The only time I've seen the playback buttons not work is if some other audio is taking precedence. Like if audio is playing in a tab in my browser and that was the last app i had focused that played audio. I can go to a different tab, or different app, and the media keys affect that browser tab still, not feishin.

**Comment by patrick-motard** [comment]
#476 is the bug I was describing above.

**Comment by iiPythonx** [comment]
Should be fixed as part of https://github.com/jeffvli/feishin/pull/488, didn't see this duplicate.

**Comment by kgarner7** [comment]
Marking this as resolved. Until a new release, you can use https://feishin.vercel.app
