### ISSUE TITLE
Ratings, favorites and play counts shown as empty in some views even though they are not

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#479]
## Current Behavior

Happens in:
- Play Queue
![image](https://github.com/jeffvli/feishin/assets/74906541/9295850d-4002-4cd8-abdc-cc9c4d738dc9)
- Now Playing bar
![image](https://github.com/jeffvli/feishin/assets/74906541/826d7c17-6f6a-4415-9341-db84b03f35d4)
- Playlists

Doesn't happen in:
- Tracks
![image](https://github.com/jeffvli/feishin/assets/74906541/bfa5dd39-16a4-487a-bf10-d1333b4eba85)
- Album view

No idea why or when it happens.

## Your Environment

    Application version (e.g. v0.1.0) : 0.5.3
    Operating System and version (e.g. Windows 10) : Ubuntu 23.10
    Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.51.0

**Comment by deluan** [comment]
This is probably caused by this bug in Navidrome: https://github.com/navidrome/navidrome/issues/2816

It was already fixed in Navidrome's the develop builds and a bug-fix release is coming out this week.

**Comment by isle9** [comment]
@deluan I'm guessing that the bug-fix release is still planned for the near future?

**Comment by deluan** [comment]
Yes it is. PR https://github.com/navidrome/navidrome/pull/2840 is holding the release, but it is a big change and we want to be sure it is not breaking anything else.

**Comment by deluan** [comment]
Hey @isle9, version 0.51.1 was just released. Please let me know if you still ahve issues with the new version. And don't forget to close this issue if it works :)

**Comment by isle9** [comment]
Seems to work fine now. Thanks for the quick fix!
