### ISSUE TITLE
macOS Build "Damaged" and Cannot Run on M-Series Chips

### ISSUE THREAD

**Issue by jackgraddon** [jeffvli/feishin#482]
## Expected Behavior

macOS ARM build should be able to open.

## Current Behavior

Application crashes on launch, force killed by macOS saying that the build is damaged and needs to be moved to the trash.
<img width="328" alt="image" src="https://github.com/jeffvli/feishin/assets/61634132/b5ccd0f6-0d17-409b-8fa8-c6c0854c2170">

## Steps to Reproduce

1. Download ARM build

2. Open DMG. From here,  you can either open the app from the volume *or* copy the app to Applications. Both will result in a "____ is Damaged" error.

## Your Environment

-   Application version: v0.5.3
-   Operating System and version: macOS Sonoma
-   Machine config: Apple M1 Max w 32GB Ram

**Comment by jackgraddon** [comment]
Update: The x64 build will run on my machine. The x64 build also runs on my 2015 iMac.

**Comment by jeffvli** [comment]
Did you try https://github.com/jeffvli/feishin/issues/104 already?

**Comment by jackgraddon** [comment]
I did not see that issue, I will give it a shot. Thanks!

**Comment by jackgraddon** [comment]
#104 solution worked, thank you and apologies for missing that one.
