### ISSUE TITLE
Playlists not listed when trying to add a song to a playlist

### ISSUE THREAD

**Issue by ghost** [jeffvli/feishin#485]
## Expected Behavior

My playlists are listed and available so that I can add a song to it.

## Current Behavior

Playlists created are not listed when clicking the hamburger menu on a currently playing song and "Add to playlist"

![issue](https://github.com/jeffvli/feishin/assets/71722170/465c7a42-4ee4-42fa-8630-e5236b17f221)

## Steps to Reproduce

1. Install feishin

2. Install navidrome (subsonic)

3. Create a playlist

4. Attempt to add a song to that playlist

## Context

I'm trying to add music to a playlist, but can't.

## Your Environment

-  Operating System and version: Debian 12
-  Application version: 0.5.3
-  Server: navidrome 0.47.5

**Comment by kgarner7** [comment]
This is a duplicate of https://github.com/jeffvli/feishin/issues/311, and can be resolved by upgrading Navidrome. When https://github.com/jeffvli/feishin/pull/484 gets merged, it'll be possible to do a version check in Feishin for this.

**Comment by ghost** [comment]
Oh, I apologize for the duplicate. I guess I'll upgrade Navidrome on my server then. Thanks!
