### ISSUE TITLE
Unable to login when username contains Chinese characters

### ISSUE THREAD

**Issue by weiyideai520** [jeffvli/feishin#496]
Unable to login when username contains Chinese characters

Failed to execute'set Request Header'on XMLHttpRequest':String contains non ISO-8859-1code point.

![Screenshot 2024-02-06 220854](https://i2.100024.xyz/2024/02/06/10jti6u.webp)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/49cbef729ba52864d1e0b5a62a111692c5df5142. You can try it out now on https://feishin.vercel.app
