### ISSUE TITLE
MPV Issues on macOS (Arm)

### ISSUE THREAD

**Issue by jackgraddon** [jeffvli/feishin#497]
## Current Behavior

MPV does not play on macOS through Feishin. MPV will play when the app is opened directly, and a file is dropped on it.

https://github.com/jeffvli/feishin/assets/61634132/93006354-3f62-4590-afd7-42899cea541f

## Steps to Reproduce

I believe this is an issue with linking the application.

1. Link Feishin to Applications/MPV.app (shows as `mpv.app.zip` when done, and then as `/var/folders/nm/wglmbksn2v50k0syrzbb67sm0000gn/T/org.jeffvli.feishin/zip_cache/COFAD521-A4C8-4558-9127-A9EFB5C85C90-66664-00000642DD1F8519` after a relaunch).

2. Play any song

## Context

Unable to use the app with MPV, and must use the Web setting (Hotkeys do not work, and redirect to Apple Music app).

## Your Environment

Application version: v0.5.3
Operating System and version: macOS Sonoma
Machine config: Apple M1 Max w 32GB Ram

**Comment by sramocki** [comment]
Possibly related to https://github.com/jeffvli/feishin/issues/371?

**Comment by vurtomatic** [comment]
@jackgraddon Use the mpv binary installed via brew, not the mpv app that you download from the installation instructions. Refer to https://github.com/jeffvli/feishin/issues/286

**Comment by jackgraddon** [comment]
> @jackgraddon Use the mpv binary installed via brew, not the mpv app that you download from the installation instructions. Refer to #286

Thank you for showing me this issue, tried and it worked. However, I do think this is an unintuitive workaround/solution. I do want to ask why pointing to the binary in the .app file (`/Applications/mpv.app/Contents/MacOS/mpv`) does not work the same way?

**Comment by vurtomatic** [comment]
Agree but I don't know either. I also tried to link directly to the binary in the .app file. My only guess is Feishin can't get in there. If you refer to that issue... the path to mpv installed by brew also seem pretty tricky to track.

**Comment by jackgraddon** [comment]
My apologies I accidentally deleted my comment...

For those who want to read with context (rewritten because I can't remember my exact wording):

> Thank you for the information, I tried and it worked. However I do wonder why one couldn't point to the executable in the mpv.app file (/Contents/MacOS/mpv). This doesn't work, but I wonder why?

**Comment by jackgraddon** [comment]
> Agree but I don't know either. I also tried to link directly to the binary in the .app file. My only guess is Feishin can't get in there. If you refer to that issue... the path to mpv installed by brew also seem pretty tricky to track.

From some (albeit surface level) digging, it looks like the mpv binary that the alias links to is in a sub folder based on its version (yes this is mentioned in the issue but I thought I would go check myself to see if mine is working differently). So updating likely moves it, which might be causing issues... even though I wouldn't think it would. For me, pointing to the full path (in the version folder) did not work, and pointing to the alias did. Unsure why we are getting different results...

**Comment by jackgraddon** [comment]
>  For me, pointing to the full path (in the version folder) did not work, and pointing to the alias did

It seems when I pointed to the alias, feishin grabbed the full path. Seems strange it worked when linked through the alias but not when I set it directly.

**Comment by kgarner7** [comment]
Checking in here, is this issue resolved? Were you able to get MPV working properly?

**Comment by kgarner7** [comment]
As there haven't been any further updates on this issue, and it looks otherwise resolved, I will close this issue. If it still is relevant, please feel free to reopen.
