### ISSUE TITLE
feishin not outputing the correct volume when changed with playerctl

### ISSUE THREAD

**Issue by clanps** [jeffvli/feishin#499]
### Expected Behavior
I was trying to make a script to add 0.1 to the current volume of Feishin with playerctl (for keybinds to adjust volume in only feishin) (e.g. Feishin is at 0.5, I increase it to 0.6)
### Current Behavior
As an example, I set Feishin to 0.6 from 0.5 (by doing `playerctl --player=Feishin volume 0.6` and run `playerctl -p Feishin metadata --format '{{ volume }}'` the expected output would be 0.6 but it instead would read 0.5, the only way to get it to update would be to manually click on the volume slider within the client in which case running the volume command with playerctl would display the correct value.
![feishin](https://github.com/jeffvli/feishin/assets/45113279/286e3e7d-c2f7-4a41-b603-ba8a5c244655)

### Steps to Reproduce
1. set feishins volume with `playerctl --player=Feishin volume <desired volume>`

2. run `playerctl -p Feishin metadata --format '{{ volume }}'`

### Your Environment
Arch Linux 6.7.3
Hyprland 0.35.0
Navidrome 0.51.0
Feishin 0.5.3 from the aur package `feishin-bin`

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/92478b5ca50d75511035f0a87c065191e9f278d8
