### ISSUE TITLE
Library>Tracks view allows you to scroll infinitely past the last track in your library

### ISSUE THREAD

**Issue by dweymouth** [jeffvli/feishin#5]
## Expected Behavior

The Tracks list should end after the last track in your library.

## Current Behavior

The infinite scroll keeps adding empty rows as you scroll past the last track.

## Steps to Reproduce

1. Go to Library>Tracks view
2. Scroll all the way down towards the last track in your library
3. Continue scrolling and note that blank rows get added to the list

## Your Environment

Navidrome server, Mac OS, using the code from development branch as of 12/20/22

**Comment by jeffvli** [comment]
The tracks list is still a WIP!

**Comment by jeffvli** [comment]
Fixed with alpha2
