### ISSUE TITLE
Add Support for getSimilarSongs from Subsonic API

### ISSUE THREAD

**Issue by DezziDez** [jeffvli/feishin#50]
The getSimilarSongs API call would be really nice. To click on a song and create an instant mix is handy. I know this can technically be done with smart playlists, but this call lets you create queues from a single song on the fly.

I use this function in the Symfonium app all the time. It would just be nice to have this on desktop as well.

(Might be harder to implement due to this being Subsonic specific)

**Comment by DezziDez** [comment]
I am clearly an idiot who didn't read. I just assumed since Navidrome was included that the Subsonic API was being used. I didn't realize they could exist separately.

**Comment by jeffvli** [comment]
The subsonic API can be used alongside Navidrome so there's no issue there. In fact, it's already being used because Navidrome's API doesn't support every Subsonic feature in its native API.

I'm planning on adding this though!
