### ISSUE TITLE
Discovery Mode

### ISSUE THREAD

**Issue by brooqs** [jeffvli/feishin#503]
By adding the "Select only unplayed tracks" option to the random list creation panel, we may have the opportunity to listen to the songs that have never been played.
![image](https://github.com/jeffvli/feishin/assets/3336817/68ba4885-d1b1-4cb7-a1b7-e626791337c0)

**Comment by kgarner7** [comment]
Resolved for Jellyfin as of https://github.com/jeffvli/feishin/commit/80931d1b1976c59405aae0d1f0e30fbf82f659c8. 
For Navidrome, this isn't accessible via the API, an equivalent would be a smart playlist of with random sort and `Date Last Played` being empty.
