### ISSUE TITLE
Album/Artists Thumbnails do not rezize correctly

### ISSUE THREAD

**Issue by Lokke** [jeffvli/feishin#505]
## Current Behavior
while resizing the window sometimes the thumbnailsizes will change.
## Steps to Reproduce
https://www.youtube.com/watch?v=JjvVPD3ics0
## Your Environment
-   tested in webclient (0.5.3 - Bug not present), Windows client (0.5.3 - Bug Present) and running inside VisualStudio Code (dev branch - bug present on desktop)
-   Server and version Navidrome v0.51

**Comment by kgarner7** [comment]
The thumbnail size changing is expected to some degree. But there were some actual bugs, resolved by https://github.com/jeffvli/feishin/commit/74075fc374bf3ef2918b54e554f7faf54e5580dc
