### ISSUE TITLE
Sidebar item reorder display

### ISSUE THREAD

**Issue by tixwho** [jeffvli/feishin#506]
## Expected Behavior

drag-and-drop of sidebar configuration items should align the item correctly. Every item can be dragged.

## Current Behavior

Some items will start to freeze and can no longer be dragged after several successful attempts.

The reorder went crazy, like an item under the dragged item will jump up to the very first item, which is not intended. 

Sometimes the item can go over the box and overlap with other settings.
![feishin-flowing-reorder](https://github.com/jeffvli/feishin/assets/44349672/f5745743-4498-4547-8db7-5700b62adcc8)
![feishin-flowing-reorder-2](https://github.com/jeffvli/feishin/assets/44349672/a97cad33-6330-403a-8f8e-f93b49f39922)

## Steps to Reproduce

1. try to randomly drag down different items in Sidebar configuration for multiple times.

2. you will see some other items are being reorganized in a wrong way. and sometimes an item will freeze, but dragging items above it is okay.

3. rarely you will see display errors when an item fly over the zone, like the screenshots indicated.

## Possible Solution (Not obligatory)

none. switch to different tabs and come back can fix the display issue, but reorder is still hard.

## Context

reorder.

## Your Environment

-   Application version (e.g. v0.1.0) : v.0.5.3, AUR installed
-   Operating System and version (e.g. Windows 10) : KDE Plasma 5.27.10; Manjaro 6.6.10; Qt 5.15.12
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome v.051.0
-   Node version (if developing locally) :

**Comment by kgarner7** [comment]
Can you try a build from https://github.com/jeffvli/feishin/actions/runs/7936600961 (check linux binaries) and see if that still has this issue?

**Comment by tixwho** [comment]
Confirmed. The issue is still there, and it's actually super easy to reproduce -- just drag the first item and release it on the second line multiple times -- and you will see items below it start to behave strangely.

https://github.com/jeffvli/feishin/assets/44349672/e6087922-512e-44c8-b822-57a7b8ccf0f9

(recoded the video in h.265 due to attachment size constraints, please download if there's a playback issue, sorry!)

**Comment by kgarner7** [comment]
I've upgraded framer-motion (the package supporting the dragging) to the latest version, can you see if it is still reproducible in https://feishin.vercel.app?

**Comment by tixwho** [comment]
Seems like the problem is fixed for the web-based version!

**Comment by kgarner7** [comment]
Great! If you have a chance, could you also test a recent build https://github.com/jeffvli/feishin/actions/runs/8921781829? I don't anticipate there to be a difference between web and desktop, but I can't say for certain

**Comment by tixwho** [comment]
Hi,
I tried to extract and run the appimage as I did previously, but the console reported `zsh: exec format error: ./Feishin.AppImage` and refused to start the program. A quick search shows that this problem is possily linked to some architecture issue. I wonder if this `linux-binaries` compiled for `x86_64`?

**Comment by kgarner7** [comment]
AH. That is in fact ARM, my bad (I thought it would make both, which it does for MacOS)

**Comment by kgarner7** [comment]
0.7.1 is released, can you check if this error is gone? If so, this issue should be good to be closed

**Comment by tixwho** [comment]
Just tried it out and I think we are doing good! Thanks for the help! Closing the issue now.
