### ISSUE TITLE
[Web Player] Trying to play a track while it's already playing does not restart it

### ISSUE THREAD

**Issue by iiPythonx** [jeffvli/feishin#508]
## Expected Behavior

If I double click on a track while it's already playing, I would expect the track to restart.

## Current Behavior

As you can see, right now the progress bar does what it should (goes back to the beginning), but the audio does not restart, so the progress bar just snaps back to the current track progress after some time.

https://github.com/jeffvli/feishin/assets/35084023/3939c46e-0a21-42b3-a183-c05a370dcc63

## Steps to Reproduce

1. Switch from MPV to the web player

2. Play any track from any album

3. Go back to the album and double click on that same track

4. Observe the progress bar stutter and the audio not restart

## Possible Solution (Not obligatory)

Not sure, guessing the web player is just missing a method to set the time position to 0 when it's already started.

## Context

I'm used to double clicking on a track to restart it (think Spotify or any other audio player, really).

## Your Environment

-   Application version (e.g. v0.1.0) : 20b161e
-   Operating System and version (e.g. Windows 10) : Windows 10 Pro 22H2
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.51.0
-   Node version (if developing locally) : 16.20.0

**Comment by kgarner7** [comment]
This is related to how double click is handled (see https://github.com/jeffvli/feishin/blob/46fdacad813760cb2fda7b34cd7f1761413ed17b/src/renderer/features/now-playing/components/play-queue.tsx#L92). MPV just sets the queue, but for web player there is no seek back. Basically, would need to do https://github.com/jeffvli/feishin/blob/46fdacad813760cb2fda7b34cd7f1761413ed17b/src/renderer/features/player/hooks/use-center-controls.ts#L593

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/90d3fb219d8693993a5ec4f6ef5b55a74e68b49f
