### ISSUE TITLE
Play Count is present twice in the sorting dropdown of the page "Tracks"

### ISSUE THREAD

**Issue by Amatsu-Kami** [jeffvli/feishin#509]
## Expected Behavior

Only one of them should be "Play count", which is probably the second one. The first one doesn't seem to be sorting by play count.

## Current Behavior

![Capture d’écran 2024-02-16 095542](https://github.com/jeffvli/feishin/assets/91038682/91185c3d-5794-4e21-b530-458e91723fb2)

There's two "Play Count" sorting option in the dropdown of the page "Tracks"

## Steps to Reproduce

1. Go on the page "Tracks"

2. Open the sorting dropdown.

3. Two "Play Count" options are presents.

## Context

The first one doesn't work while the second one does.

## Your Environment

-   Application version (e.g. v0.1.0) : v0.5.3
-   Operating System and version (e.g. Windows 10) : Linux (docker)
-   Server and version (e.g. Navidrome v0.48.0) : v0.51.1
-   Node version (if developing locally) :

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/1e5d446ced74a490d29ebcf0207202a288b01504. Thanks!
