### ISSUE TITLE
Update to Tauri?

### ISSUE THREAD

**Issue by aayushdutt** [jeffvli/feishin#513]
Just curious whether there are any plans to update the project to use [Tauri ](https://tauri.app/)instead of Electron for performance benefits and lighter installation?

**Comment by kgarner7** [comment]
While I also agree that Tauri would be nice, practically I'd say the likelihood of this change (especially in the near future) is pretty low. It'd require familiarizing with a new build system, complete rewrite of the backend, and probably considerable changes in the frontend (yes, I know you can keep the frontend typescript. But there's still IPC changes and storage...)

**Comment by jeffvli** [comment]
Adding to what @kgarner7 said, it would make sense if Feishin were simply a webapp being wrapped by Electron, but there's a ton of features running directly on Electron/nodejs that would need to be rewritten just to work for Tauri. I'm also not experienced with Rust so that's another huge blocker.

**Comment by kgarner7** [comment]
Given that I believe the question has been answered, I'll go ahead and close this issue.
