### ISSUE TITLE
Lyrics Support for Jellyfin

### ISSUE THREAD

**Issue by Maxplosion** [jeffvli/feishin#52]
Hi!

just wanted to let you know that in the next Jellyfin release lyrics support should be included see:
https://github.com/jellyfin/jellyfin/pull/8381

It would be great if this would also be implemented in feishin sometime in the future 

Thanks and keep up the great work!

**Comment by Twcd** [comment]
Who is the provider for the lyrics ?

**Comment by Maxplosion** [comment]
you can either embed them into the file as synced or unsynced lyrics or have them externally as .lyc or .txt file

there is no automated lyric load in jellyfin so you provide them on your own or with an external tool

**Comment by jeffvli** [comment]
Awesome, glad that Jellyfin has added native lyrics support!

I added a section for lyrics over in #27, so I'll add this when I have a chance.

**Comment by jeffvli** [comment]
Just a note once this feature is released: local lyrics via txt/lrc files in Jellyfin is currently only available on Jellyfin's `unstable` release.

**Comment by NicholasFlamy** [comment]
> Just a note once this feature is released: local lyrics via txt/lrc files in Jellyfin is currently only available on Jellyfin's `unstable` release.

Does this support embedded lyrics from Jellyfin? I would think not because I helped move that along and it got merged about a week ago.

**Comment by Daivy03** [comment]
Jellyfin has implemented lyrics from version 10.9.0 and up
Refer to this[ jellyfin forum thread](https://forum.jellyfin.org/t-10-9-lyrics-for-songs?highlight=lyric)
