### ISSUE TITLE
Can not play any music

### ISSUE THREAD

**Issue by zzzdajb** [jeffvli/feishin#525]
## Expected Behavior

The player should play the song normally.

## Current Behavior

When I choose a song,sometimes the player starts and then stops.And then nothing happens,it can not play the song.
![image](https://github.com/jeffvli/feishin/assets/122362831/523829e0-d351-4aa4-bf65-6e6d15aa527c)
(It stops automatically.It is not I stop it.)

## Steps to Reproduce

1.Just choose one song and try to play it.

2.The problem may happen.

## Context

I can not use it to play songs at all because I don't know when it will work or not.
What makes me crazy most is that I check that the web version(https://feishin.vercel.app) work normally and doesn't make any trouble.Only the destop version has the bug.
I have checked the docker container of my server,there is no error message,and other players work normally,so I guess it is the bug of feishin.

## Your Environment

-   Application version (e.g. v0.1.0) :0.5.3
-   Operating System and version (e.g. Windows 10) :Windows11
-   Server and version (e.g. Navidrome v0.48.0) :Navidrome 0.51.1 docker
-   Node version (if developing locally) :

**Comment by iiPythonx** [comment]
In Settings -> Playback, can you switch from the MPV player to web? This just sounds like another mpv-related issue (and mpv is no longer the default in development, so this shouldn't even happen starting with the next release).

**Comment by zzzdajb** [comment]
> In Settings -> Playback, can you switch from the MPV player to web? This just sounds like another mpv-related issue (and mpv is no longer the default in development, so this shouldn't even happen starting with the next release).

Thanks a lot! The problem has been solved, and now the player can run normally.
