### ISSUE TITLE
Music doesnt play

### ISSUE THREAD

**Issue by back-lacking** [jeffvli/feishin#528]
## Expected Behavior
When i click play on my player, the chosen music plays

## Current Behavior
When i click play on my player, the chosen music doesnt play and gets stuck at the current timestamp

video demo of the problem
https://github.com/jeffvli/feishin/assets/86173810/97ca9b93-f743-4229-90bb-e9a2a2327b3c

## Steps to Reproduce

1. add navidrome server

2. log into server

3. play song from library

4. see music doesnt play

## Context

this has prevented me from playing music from my library using this player

## Your Environment

-   Application: v0.5.3
-   Operating System: Windows 10 Build 19045.4046
-   Server: Navidrome v0.51.1

**Comment by iiPythonx** [comment]
Are you using the mpv or web backend? If you're using the mpv-based one, try switching to web and see if that fixes the problem.

**Comment by back-lacking** [comment]
> Are you using the mpv or web backend? If you're using the mpv-based one, try switching to web and see if that fixes the problem.

i am using mpv backend, let me change.

**Comment by back-lacking** [comment]
i changed to web backend, music now plays
also, forgot to mention that both feishin and mpv were isntalled using scoop

**Comment by iiPythonx** [comment]
There's a lot of issues related to mpv, in development web is now the default so when 0.6 comes out this shouldn't be an issue anymore.

**Comment by back-lacking** [comment]
i see

**Comment by back-lacking** [comment]
solved by changing from mpv backend to web backend
