### ISSUE TITLE
0.6.0 AppImage not launching

### ISSUE THREAD

**Issue by kbridger** [jeffvli/feishin#530]
## Expected Behavior
Running the AppImage should launch the application

## Current Behavior

Application does not launch.

## Steps to Reproduce

1. Download the 0.6.0 release AppImage
2. Make it executable
3. Run it
4. Observe nothing appears.

## Context
I was running a previous version 0.5.3  I was able to run it immediately after downloading and marking it +x.  I also was able to use Gear Lever to move it to a dedicated AppImage folder and integrate it with the Gnome system (launcher).

I then tried to use the updated version by removing the old and running the new.  I tried using Gear Lever's debug logging but see nothing in there from the AppImage itself.

Now I'm unable to launch via direct launching (via Nautilus) or Gear Lever.

## Your Environment
-   Application version (e.g. v0.1.0) : 0.6.0
-   Operating System and version (e.g. Windows 10) : Fedora 39
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.50.1
-   Node version (if developing locally) : n/a

**Comment by jeffvli** [comment]
Did you download the correct AppImage? There's 2 different versions now, one for arm64 and the original one.

[Feishin-0.6.0-linux-arm64.AppImage](https://github.com/jeffvli/feishin/releases/download/v0.6.0/Feishin-0.6.0-linux-arm64.AppImage)

[Feishin-0.6.0-linux-x86_64.AppImage](https://github.com/jeffvli/feishin/releases/download/v0.6.0/Feishin-0.6.0-linux-x86_64.AppImage)

**Comment by jeffvli** [comment]
> Can I grab some logs during launch to help pin the problem down? I can't even launch it let alone configure a server (unless the server config is stored outside the AppImage in some way)? If the serve exists somewhere in my profile I can delete it and try launching again.

The server config is stored in the app's browser localStorage which can't be accessed unless you can open the app. Feishin also stores cache and configuration within the application directory under `$XDG_CONFIG_HOME` or `~/.config` in the Feishin directory which can be deleted.

**Comment by kbridger** [comment]
Well now I'm embarrassed.  I did mistakenly download the arm version.  Using the x64 version works properly.  Hurray for your help, and apologies for my lack of attention to detail.
