### ISSUE TITLE
Jellyfin Lyrics with Jellyfin `unstable`

### ISSUE THREAD

**Issue by NicholasFlamy** [jeffvli/feishin#535]
## Expected Behavior

Lyrics should have showed up under Lyrics.

## Current Behavior

![Screenshot 2024-03-08 115449](https://github.com/jeffvli/feishin/assets/30300649/0b743967-8b7e-4621-b53b-d64fc9a8b13b)
This happens with both MPV and Web player.

## Steps to Reproduce

1. Start a Jellyfin `unstable` server
2. Point it at music with either embedded lyrics or .lrc files
3. Connect with Feishin and play the song and open the "Now Playing" screen and look under lyrics
5. I get "No lyrics found"

## Context

I wanted to test the feature in Jellyfin `unstable` which will be part of Jellyfin 10.9.X

## Your Environment

-   Application version (e.g. v0.1.0) : v0.6.0
-   Operating System and version (e.g. Windows 10) : Windows 11
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin `unstable` aka v10.9.X

**Comment by kgarner7** [comment]
Looks like since the initial implementation Jellyfin changed the lyrics API endpoint. Since I'd rather not implement it a _third_ time, this will probably have to wait until it hits stable.

**Comment by NicholasFlamy** [comment]
Soon:
https://jellyfin.org/posts/new-ci-new-repo

They froze it so now it's super unlikely to change:
https://jellyfin.org/posts/testing-10.9.0

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/087ea44737f6de13b31724b23ec9d0f89d705f0a.

Make sure to rescan your library for it to take effect!

**Comment by NicholasFlamy** [comment]
> Resolved by [087ea44](https://github.com/jeffvli/feishin/commit/087ea44737f6de13b31724b23ec9d0f89d705f0a).
> 
> Make sure to rescan your library for it to take effect!

I tried to build from the development branch, and building worked, but the Windows Installer seems to be broken. It only installs Uninstall Feishin.exe and not the actual Feishin.exe program.

**Comment by NicholasFlamy** [comment]
I'll try merging the commit into stable in my fork.

**Comment by NicholasFlamy** [comment]
I must be building it wrong. Maybe Windows signature or something? I built 0.6.1 and it's the same issue. I installed it from the release installer here and it installs.

**Comment by iiPythonx** [comment]
How are you building Feishin? Running `npm run package` and then running the setup executable that it gives me, Feishin upgrades fine (win 10).

**Comment by NicholasFlamy** [comment]
Hmm, I'll try that. I was using the GitHub actions in this repo.

**Comment by NicholasFlamy** [comment]
Built it on Windows using `npm run package`, it worked.

**Comment by NicholasFlamy** [comment]
Confirmed the commit works. Also, found a new unrelated issue, will open an issue.
