### ISSUE TITLE
Error when mpv is selected as the player

### ISSUE THREAD

**Issue by SinTan1729** [jeffvli/feishin#536]
## Expected Behavior

Everything should work correctly without errors.

## Current Behavior

When mpv is selected as the player, and I go to the next song in queue by pressing next, most of the time (not always though), I get the following error.
![image](https://github.com/jeffvli/feishin/assets/35728385/b48bc699-8d0c-47f3-9734-3875e611e1ae)
It pops up in front of the player buttons, and renders them unusable until this dialog is closed. The next track plays correctly though.

## Steps to Reproduce

1. Choose mpv as the player.

2. Play a list of songs.

3. Go to the next song using next button a few times.

4. You'll see the error every once in a while.

## Context

I was just playing a playlist.

## Your Environment

-   Application version (e.g. v0.1.0) : v0.6.0
-   Operating System and version (e.g. Windows 10) : Linux pavilion 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64 GNU/Linux
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome v0.51.1

**Comment by mihawk90** [comment]
Can also confirm this on Fedora 39

**Comment by nathan-contino** [comment]
Can also confirm this on macOS Sonoma 14.4.
