### ISSUE TITLE
Feishin shows incorrect release date for all albums whereas Navidrome does not. 

### ISSUE THREAD

**Issue by xusiai** [jeffvli/feishin#537]
## Expected Behavior

Albums should show correct release dates. 

## Current Behavior
All albums show (I assume) the date the files were added in Feishin. Navidrome itself show the correct release dates. This is not unique to this artist - it happens for _all_ releases. Happens in both Chromium and Firefox. I am unable to test the native client as it doesn't run for me at all. 

Feishin: 
![2024-03-11T20:13:00,862692634+01:00](https://github.com/jeffvli/feishin/assets/142084577/263feea0-8ab2-4a23-8adb-c5a685c52a13)

Navidrome:
![2024-03-11T20:14:29,728641469+01:00](https://github.com/jeffvli/feishin/assets/142084577/96742767-0a2d-4c28-8e6c-e237a0eefa04)

## Steps to Reproduce

1. Run Feishin (docker).

2. Open web client. 

## Your Environment

-   Application version : 0.6.0
-   Operating System: Linux with Feishin's latest docker release. 
-   Server and version (e.g. Navidrome v0.48.0) : 0.51.1 (Linux container as well).

**Comment by iiPythonx** [comment]
If I'm not mistaken, Feishin will only display the date the album was added to your Navidrome library **when you are sorting by Recently Added** (which you are). If you switch to (for example) Release Year, you should at least see the correct years. Although, from what I know there aren't any locations in Feishin that will display a full release date, just the year.

**Comment by xusiai** [comment]
> If I'm not mistaken, Feishin will only display the date the album was added to your Navidrome library **when you are sorting by Recently Added** (which you are). If you switch to (for example) Release Year, you should at least see the correct years. Although, from what I know there aren't any locations in Feishin that will display a full release date, just the year.

Tested this and you are correct. A full date would be nice (as Navidrome does) but that's another issue.

**Comment by iiPythonx** [comment]
>A full date would be nice (as Navidrome does) but that's another issue.

After doing a bit of digging it seems like this is actually supported but just not implemented yet:

![image](https://github.com/jeffvli/feishin/assets/35084023/53d80023-3087-4d7b-95c3-547a5e96f133)

That was added a month ago, so maybe a future release will have sorting by release date.

**Comment by Optekah** [comment]
> maybe a future release will have sorting by release date.

This would be a game changer for me. I would love being able to see which albums came first, chronologically speaking. I spent a while trying to figure out why **album 2** that released in November of 2020 was appearing before **album 1** that released in February of 2020. Turns out it's because the _name_ of **album 2** comes before **album 1**, alphabetically, and alphabetically is the only reason from what I can tell. I don't see any other variables without looking at the code. It just comes down to spelling (and having at least the same year of course).

If someone implements this I will send them cat memes or something. 

It's totally a good deal, whoever is reading this should definitely do it :)

**Comment by iiPythonx** [comment]
> If someone implements this I will send them cat memes or something.

Shouldnt be too much work, I did a fairly quick implementation yesterday and it seemed to work.

For a public release though, I *believe* Feishin would need check the server version to prevent breaking compatibility with older Navidrome versions (that don't support sorting by release date).

Example of my hacky solution:

![image](https://github.com/jeffvli/feishin/assets/35084023/265f2c30-d35b-4cda-a31a-fcc214f70fe7)
