### ISSUE TITLE
First played track does not increase playcount

### ISSUE THREAD

**Issue by mihawk90** [jeffvli/feishin#539]
## Expected Behavior

Playcounts should increase consistently

## Current Behavior

When starting playback of a queue, the playcount of the first played track never increases. It does increase fine for the remainder of the queue however. The same is true when starting an album playback by double-clicking a track somewhere in the middle. That one track will not have the playcount increased.
It also increases the playcount of the first played track when "Repeat all" is enabled and the end of queue is reached and it loops back to the first track. So it seems to be connected to only the initial playback.

One thing to note though (although I'm not sure if that's a bug or intended), the playcount of tracks increases immediately as they start playing (or at least after a couple seconds). My assumption was that that is what the "Scrobble" settings are for, but that doesn't seem to be the case (or not working)? It does make me wonder what those settings are for otherwise though :sweat_smile: 

## Steps to Reproduce

1. create a new queue by starting an album or adding tracks manually (remember the playcounts before adding of course)
2. start playing the queue if it didn't automatically
3. skip through a couple tracks
4. notice the playcount going up for all but the first track in queue

Another user I was talking to could also replicate this.

## Context

Just happened to notice it because the playcounts on one of my albums was inconsistent across tracks (even though I only listen to that one as a whole and not single tracks).

## Your Environment

-   Application version (e.g. v0.1.0) : 0.6.0
-   Operating System and version (e.g. Windows 10) : Fedora 39 (AppImage)
-   Server and version (e.g. Navidrome v0.48.0) : 10.8.13
-   Node version (if developing locally) : -

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/ab17ba8add11f06ba735f6701286a3db7f882750
