### ISSUE TITLE
Disconnected shuffle behavior between play queue and play bar

### ISSUE THREAD

**Issue by swishkin** [jeffvli/feishin#541]
## Expected Behavior

Playback (bottom bar) shuffle and queue (right panel) shuffle should be linked and behave the same.

## Current Behavior

Shuffling the play queue visually reorders the queue, but enabling shuffle on the play bar restarts playback at beginning of playlist (off) and then at the current song (on), all without reordering the play queue.

Additionally, shuffle on the play queue panel re-shuffles the queue infinitely without any ability to return to the original state like the play bar shuffle.

![image](https://github.com/jeffvli/feishin/assets/19404743/a8f08411-190c-48a9-bddd-e5de89e6a465)

Also note in the above screenshot that there are duplicate track numbers: 3 and 7 in particular.

Here's what I see in the console:

![image](https://github.com/jeffvli/feishin/assets/19404743/310a9b07-a9ca-43dd-b547-fb6495df50bd)

## Steps to Reproduce

1. Begin playback of an album or playlist

2. Shuffle the play queue; now playback will follow the visually displayed order of the shuffled queue

3. Shuffle on the play bar; now playback will not follow the visually displayed order of the shuffled queue

4. Disable shuffle on the play bar; now playback will again follow the visually displayed order in the shuffle queue

## Possible Solution (Not obligatory)

Personally, I think the user experience should be more like this:

1. Start playlist in the middle; now the entire album plays back, beginning at the selected song, and continuing through the playlist, looping back to the song before your original selected song.
2. Shuffling (from either the play bar or the play queue) the playlist both visually reorders the play queue and shuffles playback, so that the play queue shows a shuffled order AND the playback follows that shuffled order.
3. Disabling shuffle should return the queue to its original order (whether beginning at the first track or somewhere in the middle), and continue playback seamlessly at the current position.
4. Subsequent shuffles should re-shuffle the playlist (different shuffled order from last shuffle) but otherwise behave the same as step 2.

## Your Environment

-   Application version (e.g. v0.1.0) : Feishin 0.6.0
-   Operating System and version (e.g. Windows 10) : Artix Linux 6.7.9
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.51.1 (6d253225)
-   Node version (if developing locally) : N/A

**Comment by kgarner7** [comment]
The shuffle icons are _intentionally_ two different things. One is to toggle shuffling (from the tooltip), and the other is to shuffle the play queue. Having both buttons do the same thing would be incorrect, in particular because enabling/disabling shuffling preserves the original order.
