### ISSUE TITLE
Artists load out of order and repeat when scrolling quickly

### ISSUE THREAD

**Issue by coribald** [jeffvli/feishin#548]
Have seen this issue for a while - couldn't find a similar one here already so I figured I'd report it. Let me know if I can provide any more info or detail!

## Expected Behavior

Artists should load and be sorted as selected when scrolling through album artists.

## Current Behavior

If you quickly scroll down through Artists, with the scrollbar, mouse wheel, or pg-dn, you'll see the same chunks of artists load again - i.e, when sorting alphabetically, if you quickly scroll through artists A-F, you may see artists A-F again, sometimes multiple times, and the expected next group of artists will either be further down the list or missing altogether.

In the screenshot below, you'll see that artists alphabetically A-H loaded three times instead of the remaining artists. (apologies for the low quality gif, happy to share a better one if needed)

![feishin2](https://github.com/jeffvli/feishin/assets/8474579/45e17dd8-69ef-4625-b3a8-db79b0fdb04d)

## Steps to Reproduce

1. Navigate to Artists tab. 
2. Use card view. Sort alphabetically ascending.
3. Scroll quickly by dragging the scrollbar.
4. Observe repeated/out of order artists.

## Your Environment

-   Version: at least 0.5.1 (possibly earlier), and still present on 0.6.1
-   OS: Observed on both Mac (Sonoma, M1) and PC (Windows 11)
-   Navidrome 0.49.3

Thank you!

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/c3fcb7487c79043c0c9c5b4bba1fc1afbd108c16
