### ISSUE TITLE
Favourite-ing an artist from the "Artists" page doesn't work

### ISSUE THREAD

**Issue by kaibagley** [jeffvli/feishin#554]
## Expected Behavior

Favouriting from Artists page (clicking the heart shown when hovering over artist art) favourites the artists properly

## Current Behavior

It shows them as favourited until page is refreshed/reloaded. Favouriting from the actual artist's page works as expected.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.6.1
-   Operating System and version (e.g. Windows 10) : Windows 10
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.51.1

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/15c6ef382a750b2a666d9ec600b1f09265f26f0e
