### ISSUE TITLE
Add the ability to access the settings screen even when server is unavailable

### ISSUE THREAD

**Issue by McFrappe** [jeffvli/feishin#559]
## What do you want to be added?

I want the option to access the settings screen even if i am unable to access the navidrome server or not. 

## Additional context
I just move into a new place where my navidrome server now has a different IP address. Due to this, feishin tries to access my navidrome server through the old IP. I should be able to change this in the settings but i cannot since feishin is just stuck on loading screen.
To solve this, i would need to uninstall feishin, and install it again to invoke the "initial setup" wizard. 

![image](https://github.com/jeffvli/feishin/assets/17787601/4b1cead4-f1fb-42f7-9b28-2f67856b3298)
![image](https://github.com/jeffvli/feishin/assets/17787601/f4c4e33f-99c8-44dd-ad1a-9ab0449f0c19)

Navidrome

Dont know if the same applies to jellyfin since i have not tested it there.

**Comment by saxobroko** [comment]
This also happens when the server is slow or unavailable. Unable to leave this screen.

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/44fcc338257224621b3582e159d4e85150844e5f
