### ISSUE TITLE
[Feature Request] Keep playing on app close

### ISSUE THREAD

**Issue by Explosion-Scratch** [jeffvli/feishin#563]
When you close spotify it keeps playing, this would be really nice for Feishin, especially because I keep accidentally closing it

Love the app btw

**Comment by kgarner7** [comment]
Consider using `Exit to tray`. (Settings > Window > Exit to tray)

**Comment by Explosion-Scratch** [comment]
> Consider using `Exit to tray`. (Settings > Window > Exit to tray)

Oh, perfect! Thanks!
