### ISSUE TITLE
[Bug] Window bar doesn't switch to light theme

### ISSUE THREAD

**Issue by Explosion-Scratch** [jeffvli/feishin#564]
## Expected Behavior

Light mode should update the titlebar to match

## Current Behavior

<img width="806" alt="image" src="https://github.com/jeffvli/feishin/assets/61319150/fd4203ed-5e66-4c9c-9fb0-14f1ad8fd716">

## Steps to Reproduce

Switch to light mode

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/a3573d4f9a2154cf2c2ee90893db73be6756fe98 for windows/macos window bar style (native styme works)
