### ISSUE TITLE
Duplicate items in playlist sidebar

### ISSUE THREAD

**Issue by kgarner7** [jeffvli/feishin#568]
@kgarner7 Not the songs anymore but my Playlists are duplicated now instead:
![image](https://github.com/jeffvli/feishin/assets/20018243/c8eb9af1-6c80-4e38-85ac-38e42a659b38)

And clearing the cache + relogin did not help.

_Originally posted by @YourSandwich in https://github.com/jeffvli/feishin/issues/53#issuecomment-2028596492_

**Comment by kgarner7** [comment]
@YourSandwich If you inspect element (control or command + shift + i) and open the network tab, what is returned from `playlist?_end=0&_order=ASC&_sort=name&_start=0`? Is the response there already doubled? What about on the playlist page

**Comment by YourSandwich** [comment]
@kgarner7 I cannot find this element, typing `playlist?_end=0&_order=ASC&_sort=name&_start=0` in the console throws the error: `Uncaught SyntaxError: Invalid left-hand side in assignment`

In the network section, there is nothing about the Playlist.
When I click on the Playlist, it is still duplicated:
![image](https://github.com/jeffvli/feishin/assets/20018243/d41f5735-c937-4dbb-9d62-ee9ce268b199)

And I see a lot of albumID errors in the console:
```
renderer.js:2 Error: Missing ":albumId" param
    at s (renderer.js:2:1814968)
    at renderer.js:2:1820673
    at Array.map (<anonymous>)
    at A (renderer.js:2:1820542)
    at a.PosterCard (renderer.js:282:96)
    at yi (renderer.js:2:2409563)
    at yc (renderer.js:2:2466418)
    at Cs (renderer.js:2:2455570)
    at Ms (renderer.js:2:2455498)
    at ms (renderer.js:2:2455361)

renderer.js:2 React Router caught the following error during render Error: Missing ":albumId" param
    at s (renderer.js:2:1814968)
    at renderer.js:2:1820673
    at Array.map (<anonymous>)
    at A (renderer.js:2:1820542)
    at a.PosterCard (renderer.js:282:96)
    at yi (renderer.js:2:2409563)
    at yc (renderer.js:2:2466418)
    at Cs (renderer.js:2:2455570)
    at Ms (renderer.js:2:2455498)
    at ms (renderer.js:2:2455361) 
```
Also, my Jellyfin Server does not have any write permission to the storage if this matters.

**Comment by kgarner7** [comment]
You don't type that in the console, you'd look at it in the network tab (but that's irrelevant anyway because this is Jellyfin, not Navidrome).

**Comment by kgarner7** [comment]
You would want to look for the request **in the network tab** that is something of the form `items?Fields=ChildCount%2C%20Genres%2C%20DateCreated%2C%20ParentId%2C%20Overview&IncludeItemTypes=Playlist&MediaTypes=Audio&Recursive=true&SortBy=SortName&SortOrder=Ascending&StartIndex=0`. Consider using the web version (https://feishin.vercel.app) for testing your Jellyfin server

**Comment by YourSandwich** [comment]
Yes, it is duplicated as well `items?Fields=ChildCount, Genres, DateCreated, ParentId, Overview&IncludeItemTypes=Playlist&MediaTypes=Audio&Recursive=true&SortBy=SortName&SortOrder=Ascending&StartIndex=0`

Il attach the response, not everything is duplicated, maybe you can find a pattern there.

For example, `Play This` is duplicated.
[response.json](https://github.com/jeffvli/feishin/files/14833164/response.json)

**Comment by kgarner7** [comment]
I do see that Jellyfin is returning duplicate playlists (by name, not id). As an example (most content snipped):
```json
{
  "Items": [
    {
      "Name": "Melodic Hard",
      "Id": "edabe00ad3fc0fbcda576bf00038adba"
    },
    {
      "Name": "Melodic Metal",
      "Id": "c427782325e65964a8341033ca7c2f53"

    }
  ]
}
```
Every instance that is duplicated is duplicated **because** the name is returned twice by Jellyfin. I would check to see if the playlists are being duplicated there, because from Feishin's point of view these duplicates are distinctly different.

**Comment by YourSandwich** [comment]
Hello, I am sorry. You are right, Jellyfin itself duplicates it as well.
Please close the issue, it's not a Feishin problem.

**Comment by kgarner7** [comment]
No worries! Glad you've at least found the culprit.
