### ISSUE TITLE
mpris "playing" status is not properly updated when changing tracks

### ISSUE THREAD

**Issue by natperron** [jeffvli/feishin#570]
## Expected Behavior

The playing/paused status should be updated properly when changing tracks manually or automatically (at the end of the previous track).

## Current Behavior

When paused and skipping to next track, the status of the player is "Playing" (when it should stay "Paused").
Similar issue happens when the current track is playing and ends: instead of staying in status "Playing", the player changes to "Paused".
![image](https://github.com/jeffvli/feishin/assets/68925286/e894a14c-2453-4008-a141-bae794f087ef)

## Steps to Reproduce

1. Pause on a track.
2. Click on the button to skip to next track.
3. Notice the playing status (using playerctl) is not the same as the status in Feishin.
 - Feishin is paused, but playerctl is "Playing"

Alternative:
1. Let a track end. It should go to the next track.
2. Notice the playing status (using playerctl) is not the same as the status in Feishin.
 - Feishin is playing, but playerctl is "Paused"

## Context

I'm using `playerctl` to make my own music module for my task bar (using eww). Since it has the wrong playing status, I have a "paused" button when playing (and vice-versa) when this bug happens.

## Your Environment

-   Application version: 0.6.1
-   Operating System and version: Debian 12 
-   Server and version: Jellyfin 10.8.13

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/65eca32de3e70b128b7bd5ba9e270563acf28844
