### ISSUE TITLE
Transcoding to lower bitrate

### ISSUE THREAD

**Issue by obeidahmad** [jeffvli/feishin#572]
## What do you want to be added?

I want to have a setting that allows selecting maximum bitrate for audio (transcoding).

## Additional context

I use Jellyfin and I know it has a transcoding option. My android client has a bitrate setting that would transcode the music server side. My library is mostly 24-bit/48kHz .flac so when I am not on my local network it can get very laggy to play my music.

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/528bef01f0ac310a5f7524454203cbf0a40257d9
