### ISSUE TITLE
Unable to open music player from jellyfin to navidrome

### ISSUE THREAD

**Issue by EllisXillia** [jeffvli/feishin#580]
## Expected Behavior

switching server from Jellyfin to Navidrome crashing the entire music player

## Current Behavior

it happend when i play my music then i switch server to navidrome. i put address and it crash
![image](https://github.com/jeffvli/feishin/assets/30818281/e5c28f5f-1717-472d-bbe8-6d4a74b188b4)

however on renderer.js it show warning 
![image](https://github.com/jeffvli/feishin/assets/30818281/3d897875-b5ac-47a8-a613-694cba9f57f2)

## Steps to Reproduce
1. play random music

2. go to server and select navidrome

3. put address, user and password

4. crash

## Possible Solution (Not obligatory)
there no solution for this, i tried uninstall 3 times and restart my computer, keep show same page 

## Context
i can't open my music library on this player

## Your Environment
-   Application version (e.g. v0.1.0) : Feishin 0.6.1
-   Operating System and version (e.g. Windows 10) : Windows 10 22h2
-   Server and version (e.g. Navidrome v0.48.0) : Unraid 6.13.9, bbergle-jellyfin, navidrome v0.51.1
-   Node version (if developing locally) :

**Comment by kgarner7** [comment]
Can you please try and see if the same issue is on https://feishin.vercel.app/? This could be a known fixed issue (but not released)

**Comment by EllisXillia** [comment]
> Can you please try and see if the same issue is on https://feishin.vercel.app/? This could be a known fixed issue (but not released)

![image](https://github.com/jeffvli/feishin/assets/30818281/e7e61a97-792c-4ad6-a16b-3be949c860cf)
works really fine on web browser, but on my cases didn't work. test are jellyfin server and test 2 is navidrome server

**Comment by kgarner7** [comment]
I'm not really sure what you mean. Does this mean you cannot switch back and forth? Can you provide some more details by what you mean?
Also for your Navidrome issue, can you please examine what error you see in the Network tab (e.g. is it authentication, server is down, etc)?

**Comment by EllisXillia** [comment]
https://github.com/jeffvli/feishin/assets/30818281/3f93029d-5d54-4c11-8b64-0da71a6f5ec9

the issue i had, after i added my navidrome server into feishin player app show page "no issue found" but when i click go back it show me same page over and over. i look at navidrome auth and everything is okay

if this app has logs, i can provide later

**Comment by kgarner7** [comment]
Try the build from https://github.com/jeffvli/feishin/actions/runs/8549104144 and see if it helps

**Comment by javaarchive** [comment]
I think I had this using jellyfin only (my navidrome has been down), but I'll take a look at the actions build.

**Comment by EllisXillia** [comment]
> Try the build from https://github.com/jeffvli/feishin/actions/runs/8549104144 and see if it helps

everything is good now. thanks

**Comment by kgarner7** [comment]
Great! This build as fixes that 1. show error warning on server check and 2. allows you to change the server from home page.
Since it sounds like this helps resolve your issue, I'll go ahead and mark it resolved.
