### ISSUE TITLE
Track progress bar stops working after cuing with keyboard

### ISSUE THREAD

**Issue by comatus1649** [jeffvli/feishin#581]
## Expected Behavior

If you have previously clicked on the track progress bar, it is possible to cue the track by pressing the left and right keyboard buttons. The elapsed time counter should update to reflect the selected point in the track, and then continue to count up as playback continues. The visual indicator of the progress bar should also reflect continued playback.

## Current Behavior

After clicking on the progress bar, it is possible to cue (jump a few seconds backwards or forwards) using the keyboard. The time elapsed updates correctly, but then gets stuck where it is. 

## Steps to Reproduce

1. Play a track
2. Click on the progress bar. 
3. Say the playback time is 1:00. Press left keyboard button to cue to eg 0:50
5. Let playback continue
6. Observe that the music continues, but the counter stays at 0:50 and the progress bar is frozen

## Possible Solution (Not obligatory)

No suggestion

## Context

This makes it harder to cue repeatedly as once it has been done once, the progress bar and timestamp doesn't start working again until the next track. 

## Your Environment

-   Application version (e.g. v0.1.0) : 0.6.1
-   Operating System and version (e.g. Windows 10) : Arch Linux x64 (up to date)
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin 10.8.13
-   Node version (if developing locally) : n/a

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/cabd69772ee6ce442ad2ac6a437b36167bcfce50
