### ISSUE TITLE
Wrong Album Date

### ISSUE THREAD

**Issue by tcurdt** [jeffvli/feishin#583]
## Expected Behavior

The album discography view should show the day/year of the release.

## Current Behavior

It seems like the discography page shows the time/date of when the album was added (maybe?)

![Screenshot 2024-04-12 at 00 41 37](https://github.com/jeffvli/feishin/assets/13697/d9e94d93-c9a4-46c2-9882-a64a62627fac)
![Screenshot 2024-04-12 at 00 41 44](https://github.com/jeffvli/feishin/assets/13697/d09a6d5f-b10a-4dee-865f-c128789183ad)

## Your Environment

-   Application version (e.g. v0.1.0) : Version 0.6.1 (0.6.1)
-   Operating System and version (e.g. Windows 10) : 14.3.1 (23D60)
-   Server and version (e.g. Navidrome v0.48.0) :  navidrome 0.51.1
-   Node version (if developing locally) :

**Comment by iiPythonx** [comment]
Seems to be the same issue as https://github.com/jeffvli/feishin/issues/537, specifically https://github.com/jeffvli/feishin/issues/537#issuecomment-1989279636.  
You can change album sorting to Release Year if you want it to provide you with the same year it does in the detailed album view.

**Comment by tcurdt** [comment]
Ah, I just noticed this is due to the sorting. I switched to release year and now it's all good. I hope this gets persisted for all new views. Then this can be closed.

**Comment by tcurdt** [comment]
We just crossed comments here :)
Thanks for the quick response.
Love the project btw.

**Comment by tcurdt** [comment]
Seems like the setting gets stored 🎉
