### ISSUE TITLE
hide shared playlists

### ISSUE THREAD

**Issue by Wirezat** [jeffvli/feishin#589]
The navidrome webinterface has an option to "close" the tab of shared playlists. this would be very usefull for feishin as well in order to quickly find playlists.

This could also be complimented or replaced by https://github.com/jeffvli/feishin/issues/142 (playlist folders)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/0b383b758ed7fb2ad31221964ec967c9157ebdb4
