### ISSUE TITLE
Feishin is not a trusted accessibility client. Media keys will not work until this setting is changed.

### ISSUE THREAD

**Issue by josangmi** [jeffvli/feishin#590]
## Expected Behavior

Feishin is not a trusted accessibility client. Media keys will not work until this setting is changed.

## Steps to Reproduce

1. when open the apps
2. 
<img width="411" alt="image" src="https://github.com/jeffvli/feishin/assets/46701832/b15f39a0-3533-4f2b-b648-35fe7e1aa7a2">

## Your Environment

-   Application version (e.g. v0.1.0) : 0.6.1
-   Operating System and version (e.g. Windows 10) : macos 13.4
-   Server and version (e.g. Navidrome v0.48.0) : 
-   Node version (if developing locally) :

**Comment by kgarner7** [comment]
This is a macOS limitation; if you want media keys to work, you will need to make Feishin a trusted accessibility client. I've updated it to only show the warning once, but this is expected behavior.
