### ISSUE TITLE
Artist page does not sort properly

### ISSUE THREAD

**Issue by signalno11** [jeffvli/feishin#593]
## Expected Behavior
When sorting by name, the artists show up in alphabetical order

## Current Behavior
Artists that start with a lowercase letter are moved to the bottom of the list, instead of being treated case-insensitively

## Steps to Reproduce

1. Have a library that has artists that start in lowercase

2. Sort by name on the album artists page

## Possible Solution (Not obligatory)
Sort ignoring case. The albums page already does this, it seems.

## Context

It's just annoying and not what I expect, and dare I say, incorrect behavior.

## Your Environment

-   Application version (e.g. v0.1.0): 0.6.1
-   Operating System and version (e.g. Windows 10): Windows 7, webapp
-   Server and version (e.g. Navidrome v0.48.0): Jellyfin 10.8.13

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/595eba152a6642050fbfd8ce4242279e6ab26c99
