### ISSUE TITLE
VU meter bars don't continue to animate when application is in backgorund

### ISSUE THREAD

**Issue by justin-mi** [jeffvli/feishin#594]
## Expected Behavior

VU meter bars continue to animate when application goes into the background.

## Current Behavior

When moving application to the background (ie clicking off of the Feishin window and onto another application) the VU meter bars stop animating.

![Screenshot_20240422_205852](https://github.com/jeffvli/feishin/assets/403319/98f45ca8-2456-4a25-ac76-8041d6f675c7)

## Steps to Reproduce

1. Have track playing.

2. Bring another application into focus

3. VU Meter bars stop animating

## Context

Seeing the VU meter bars stop animating out of the corner of my eye is just annoying, not a huge quality of life issue though. I had searched and saw there weren't any issues reported for this, so I figured I'd bring it up.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.6.1
-   Operating System and version (e.g. Windows 10) :  EndeavourOS Linux x86_64, 
     -   Kernel: 6.8.7-arch1-1
     -   DE: Plasma 6.0.4
     -   WM: KWin X11
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin Version: 10.8.13
-   Node version (if developing locally) : NA

**Comment by kgarner7** [comment]
This is an intentional design to be less wasteful when not in focus (and I suspect also inspired by behavior from Spotify).
