### ISSUE TITLE
Album names sorting by capitalization

### ISSUE THREAD

**Issue by Dylancyclone** [jeffvli/feishin#597]
### Expected Behavior

When sorting by name, albums should appear in alphabetical order, regardless of capitalization (as in AaBbCc instead of ABCabc)

### Current Behavior

Albums are currently sorted with capital letters first, and lowercase letters second (as in ABCabc, an album starting with a capital "Z" sorts before an album starting with a lowercase "a")
![image](https://github.com/jeffvli/feishin/assets/19830705/b1bdc56f-7a06-4aae-ba4e-8c276b7b1d4e)

### Steps to Reproduce

1. Go to the albums page
2. Sort by "Name"
3. Notice albums starting with lowercase letters are all the way at the bottom of the list, instead of next to similar letters

### Possible Solution

Sort case insensitive

### Context

I noticed this issue (https://github.com/jeffvli/feishin/issues/593), but a fix seemed to only be applied to Jellyfin and not Navidrome

### Application version

0.6.1

### Operating System and version

Webapp in Firefox

### Server and Version

Navidrome v0.51.1

**Comment by kgarner7** [comment]
This is because the Navidrome API also returns the values sorted in case-sensitive fashion. You _might_ be able to resolve this on your server (also the web ui) by setting [`PreferSortTags`](https://www.navidrome.org/docs/usage/configuration-options/#:~:text=PreferSortTags-,nd_prefersorttags,-Use%20Sort_*%20tags) to true

**Comment by Dylancyclone** [comment]
Dang unfortunately that setting didn't help. I'll make a ticket over there, since it doesn't seem right to sort it that way. Thank you!

**Comment by kgarner7** [comment]
More specifically, this feature works **if** you have sort_* tags in your files; those are what are stored in a case insensitive fashion. If not, then I don't think it'll help

**Comment by Dylancyclone** [comment]
I found an issue on Navidrome talking about the same thing. It seems the `PreferSortTags` works for some sorts (such as artist sorting), but not the Album Sort for some reason https://github.com/navidrome/navidrome/issues/2425#issuecomment-1913685824

**Comment by Dylancyclone** [comment]
In case anyone is wondering about this, this was fixed upstream in Navidrome in version [v0.52.5](https://github.com/navidrome/navidrome/releases/tag/v0.52.5)
