### ISSUE TITLE
Add the random album on the home page to the "Home page configuration" settings

### ISSUE THREAD

**Issue by ryankupk** [jeffvli/feishin#599]
### What do you want to be added?

The element at the top of the home page which highlights a random album should be part of the settings section "Home page configuration". Frankly, I hate it, and was disappointed to see that it wasn't part of the settings given that it's the largest element by far and provides almost no value (to me). It would be nice if this could be in some way hidden/removed. 

![image](https://github.com/jeffvli/feishin/assets/34145544/dd3e62d5-5d26-4ee3-aa0b-a29beed8d4b3)

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/bb2f8461edc17252d337016853674740466d19c4
