### ISSUE TITLE
Album uses just one cover by default

### ISSUE THREAD

**Issue by AvMavs** [jeffvli/feishin#6]
## Expected Behavior
Each track in a certain album has its own cover, and Sonixd shows the track's cover for that as it should.

## Current Behavior
Feishin shows the cover for one track for the entire album. (Same Navidrome server)

## Steps to Reproduce

1. Make an album with different tracks having their own covers

2. Try playback.

## Possible Solution

Replicate the behavior Sonixd uses and use track covers.

## Context

This is not really a priority issue as it's an Alpha and a WIP, but just thought you should know.

## Your Environment

- Operating System and version : Windows 11 22623.1037; Feishin 0.0.1-alpha2

**Comment by jeffvli** [comment]
Thanks! Should be able to fix this pretty easily.
