### ISSUE TITLE
Option to choose how long it takes for feishin to log you out of a server

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#60]
Feishin seems to log me out of Navidrome every 24 hours and changing the settings in Navidrome doesn't seem to affect it.

Context: [Navidrome Discord](https://discord.com/channels/671335427726114836/704303730660737113/1089648498363875439)

**Comment by jeffvli** [comment]
I've implemented the token refresh method to be compatible with the Navidrome API, which follows the process of:

1. Retrieving the new access token on every API request
2. Storing the access token locally so it shouldn't log you out on the next open

I'll perform a test to see if the token actually stays valid for the time specified by `ND_SESSIONTIMEOUT` using 72h and checking every 24h.

**Comment by isle9** [comment]
Has this been implemented in alpha6? Seems like it still logs me out at 24h.

**Comment by isle9** [comment]
Seems like I was using the wrong syntax in the Navidrome config file. I'll check if this still happens in a day or two.

**Comment by jeffvli** [comment]
Possibly fixed, we'll see though :)

**Comment by ElMarco99** [comment]
It still logs me out after 24hrs, i am on the last version of Feishin (0.1.1) and on Navidrome in a docker container on an Unraid server.

**Comment by jeffvli** [comment]
@ElMarco99 The recent fix has not been released yet.
