### ISSUE TITLE
Add to Playlist on Artist Page doesn't work for artists with multiple songs in multiple albums 

### ISSUE THREAD

**Issue by IanAuckes** [jeffvli/feishin#601]
### Expected Behavior

On the Artist page, "Add to playlist" should add all songs by that artist to the chosen playlist.

### Current Behavior

Songs only get added to playlist if:
1. Artist has only one album
2. Artist has multiple albums, but only one song per album
 
If the artist has multiple albums and each album has multiple songs, the songs don't get added to the playlist. Though the toast says - added N tracks to 1 playlist.

### Steps to Reproduce

1. Create a new playlist
2. Search for an artist by name and go the the page for that artist.
3. Open the "..." menu on the artist page (ensure artist has multiple albums and each album has more than one song)
4. Choose "Add to playlist"
5. Pick the new playlist you created and click "Add"
6. No songs get added to the playlist

### Context

Same objectives as #296

### Application version

v0.6.1

### Operating System and version

Linux Mint 21.1 Cinnamon

### Server and Version

Jellyfin v10.8.13

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/d1bcd2b2fb3171ec1037bb24c08e6036cd3300e5
