### ISSUE TITLE
Remember song/queue on launch

### ISSUE THREAD

**Issue by metronidazole** [jeffvli/feishin#605]
### What do you want to be added?

It would be nice if Feishin could remember the last playing song/queue when you restart the app.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
If you're on desktop, this is already possible: Settings > General > Save play queue

**Comment by metronidazole** [comment]
Couldn't find it when looking the other day - thanks!
