### ISSUE TITLE
Ability to download music files

### ISSUE THREAD

**Issue by ullmannJan** [jeffvli/feishin#606]
### What do you want to be added?

Sometimes it is useful to download music files to have them easily accessible. The option to download full audio-file(s) when right clicking on a song/album/playlist would be very much appreciated. 

The functionality exists on symfonium (android player for jellyfin, subsonic, etc.) and on the default jellyfin client, so implementing this feature should be possible.

Thanks for your great work! 

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
You can download files via https://github.com/jeffvli/feishin/commit/10fca2dc12795248c17b5416cf5a093e3e731ee1. Note that this is **not** offline sync of files (https://github.com/jeffvli/feishin/issues/47)

**Comment by ullmannJan** [comment]
That's awesome! Thanks for your work. I think you mean c4677a63f6e90aac6b430df795277698ea3bf3fa though

**Comment by kgarner7** [comment]
...yes. Sometimes you get lost in commits.
