### ISSUE TITLE
Windows 0.7.0 issue running after install Window 10 Pro 64bit

### ISSUE THREAD

**Issue by Bezeker** [jeffvli/feishin#607]
### Expected Behavior

It should run the program

### Current Behavior

Say the following "This app can't run on your PC" 

### Steps to Reproduce

1. Install new version
2. Run exe and get the error

### Application version

v0.7.0

### Operating System and version

Windows 10 Pro 64bit

### Server and Version

0.51.1 (6d253225)

**Comment by iiPythonx** [comment]
This is a known issue in the discord server at least (no amd64 build), @jeffvli was working on checking this out.

**Comment by iiPythonx** [comment]
--> https://github.com/jeffvli/feishin/releases/download/v0.7.1/Feishin-0.7.1-win-x64.exe
