### ISSUE TITLE
[Bug] "Next song" button in the media bar will not function and the selected song will repeat instead of progressing to the next song.

### ISSUE THREAD

**Issue by Rycia** [jeffvli/feishin#61]
Using Windows 10 Pro 22H2, on latest 0.0.1 alpha 5.
I am also mentioning this in #9 .
- [x ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)

## Expected Behavior

When within a playlist or Library (Albums, tracks, ect, but specifically tracks) particularly in views where you can see individual tracks (or anything), and you play a song, and hit the next song, and the next song within the playlist, album, or within your filtered songs in Library, will play.

Even if it's not a bug, it's basic functionality that should be present even if it won't support shuffling, ect, yet.

## Current Behavior

Song selected in any circumstance will play on loop without properly going to the next song.

## Steps to Reproduce
Simply play a song within a playlist, album, or within the "songs" list filtered to favorite and wait for it to end.

**Comment by jeffvli** [comment]
Can you check that you actually have more than 1 song in the queue when this happens?

Double clicking on individual songs for example in the `Tracks` page only adds the one song to your queue currently.
You'll have to use the big play button in the header, or use the dropdown menu items to actually add all songs in the filtered view to the queue.

**Comment by Rycia** [comment]
It seems to that when I am in Favorites filter on my song page and only click one song, it doesn't add the rest of the songs to queue. Since this is a feature problem, I will make another issue and close this. See #67

I confirm that if I add a song to queue, it will play properly.
