### ISSUE TITLE
Behavior of left and right clicks on the system tray

### ISSUE THREAD

**Issue by alscaldas** [jeffvli/feishin#610]
### What do you want to be added?

Would it be possible to make the left click open and/or close the application to the system tray and the keep the right click behavior as it is now?

Now only the right click works, and it takes 2 clicks just to open the application main window.

I use KDE Plasma 6, but I believe that it's the sort of behavior from which every user user benefit.

Thanks for the excellent work.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/a9e0689619e004b9df62c75471bd2fbae965d5a1.
