### ISSUE TITLE
Desktop app crashes to white screen when liking album on Album view

### ISSUE THREAD

**Issue by jsspen** [jeffvli/feishin#619]
### Expected Behavior

Album should be added to likes and everything else continues as ususal

### Current Behavior

Clicking the heart icon on an album while on the Album view page causes the entire app to white out. If any music is playing when it happens that stops immediately, too. I've let it sit for a while but it doesn't come back and must be closed and restarted. I've tried liking albums in other places (on an artists page, on the home page) and it acts as normal so it seems it's something about the Album view page.

### Steps to Reproduce

1. Go to Album review
2. Click the heart icon to "like" an album

### Application version

v0.7.1

### Operating System and version

Windows 10 Desktop

### Server and Version

Navidrome v0.49.3

**Comment by kgarner7** [comment]
Already fixed by https://github.com/jeffvli/feishin/commit/c5e8472746617abaa72fb26c92d8f7644f61e07d
