### ISSUE TITLE
[Bug] Opening a 2nd instance of Feishin while a song is playing causes double playback; shouldn't allow 2 instances of feishin.

### ISSUE THREAD

**Issue by Rycia** [jeffvli/feishin#62]
Using Windows 10 Pro 22H2, on latest 0.0.1 alpha 5.
I am also mentioning this in #9 .
- [x ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)

## Expected Behavior

When opening Feishin, and opening it a 2nd time, Feishin should warn about already being open, or open the current instance of Feishin instead of making a 2nd one (and cause double playback issues.)

I imagine this can cause a lot of internal issues if more than one instance can be open at once, and there's no need to be more than one.

Most other music programs open the current instance for you if it's already open.

## Current Behavior
When opening a 2nd instance of Feishin on top of another currently running one currently playing a song, the 2nd instance will open and play the currently playing song over the currently playing song; doubling on playback of the same song and (probably) various other issues.

I did this on accident once while testing again and it's probably not a good thing.

## Steps to Reproduce
Open feishin, play a song, and while that song is playing, open another instance of Feishin.

**Comment by jeffvli** [comment]
Thanks for reporting. Fixed.
