### ISSUE TITLE
Handle albums with two different dates

### ISSUE THREAD

**Issue by Hydronicx** [jeffvli/feishin#621]
### What do you want to be added?

Some albums get reissued, so they can have tags that show the original release date (e.g. 1999) and the reissue date (e.g. 2019).
Currently, only the original year is used in Feishin. Both dates should be used. This is already done in the Navidrome web client (displayed as "♫ 1999 · Released Dec 13, 2019").

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/9923c021fafa6a22cfbc5754561c916eb0e541c8
