### ISSUE TITLE
Ability to play music videos

### ISSUE THREAD

**Issue by KiimaRo** [jeffvli/feishin#624]
### What do you want to be added?

The ability to have music videos playing.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Mostly duplicate of https://github.com/jeffvli/feishin/issues/13.
Additionally, at least with MPV backend it would be fairly difficult (at least not having the application in a separate window), as embedding MPV into Electron doesn't appear to be an easy task
