### ISSUE TITLE
Support non-square cover art

### ISSUE THREAD

**Issue by Hydronicx** [jeffvli/feishin#625]
### What do you want to be added?

Currently, non-square cover art is cropped to the lowest dimension. This is not desirable. Non-square art should be supported and displayed in full.

Some albums have non-square cover art (think DVDs, box sets, etc.).
Moreover, even regular cover art that should be square in theory might be slightly less square. Current behavior results in some cropping even in this case, which is not desirable.

Non-square cover art is supported for example in the Navidrome web UI.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/38ed083693846d81ff6da89db05aadece05a47d2
