### ISSUE TITLE
Giving a track a rating causes the UI to crash

### ISSUE THREAD

**Issue by alexisharara** [jeffvli/feishin#63]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Worst case rating is not updated if not implemented 

## Current Behavior

UI is stuck with a page showing 'Something went wrong'

## Steps to Reproduce
1. Give a track a rating (using jellyfin server)
2. Try to load the Tracks page
![image](https://user-images.githubusercontent.com/30680965/228422087-31e2c86c-bbb9-43a4-b436-cdebdf7692c7.png)
3. Reloading does nothing

**Comment by jeffvli** [comment]
Ratings aren't supported for Jellyfin, seems like I forgot to remove the column from being added.

To fix the error, you'll need to clear local storage (which clears the settings) and then restart the app.

**Comment by kgarner7** [comment]
This fix was merged in https://github.com/jeffvli/feishin/pull/24, so I'll mark this as done
