### ISSUE TITLE
Support for basic video

### ISSUE THREAD

**Issue by Kreyren** [jeffvli/feishin#630]
### What do you want to be added?

Context: I am trying to make a superior version to spotify in a self-hosted setting and for that i want to have a music that also plays some eye candy video in reduced bitrate to spare the bandwidth e.g. https://www.youtube.com/watch?v=TSemuWv5mjM

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by iiPythonx** [comment]
Partial duplicate of #13?

**Comment by Kreyren** [comment]
> Partial duplicate of https://github.com/jeffvli/feishin/issues/13? --@iiPythonx (https://github.com/jeffvli/feishin/issues/630#issuecomment-2133803265)

Agree
