### ISSUE TITLE
Photo on Artists page is inconsistent with photo on that artist's page

### ISSUE THREAD

**Issue by nothing2obvi** [jeffvli/feishin#633]
### Expected Behavior

The photo of an artist on the Artists page should be the same as the photo on that individual artist's page.

### Current Behavior

This is only happening for one artist. The artist's photo on the Artists page is not the same as what is on Navidrome. If I click on the artist and go to their individual page, the photo there is consistent with Navidrome. Please see the artist `beabadoobee` in these screenshots:

![Screenshot 2024-05-28 at 1 00 15 AM](https://github.com/jeffvli/feishin/assets/85228035/936c8377-6e4f-495d-878a-eba28caa9fad)

![Screenshot 2024-05-28 at 1 00 28 AM](https://github.com/jeffvli/feishin/assets/85228035/7710d5b1-e86a-4118-bd0a-453cebd6da99)

I have tried reinstalling Feishin and even deleting `/Users/username/Library/Application Support/feishin` but I get the same result.

### Steps to Reproduce

1. Set a custom photo for an artist in Navidrome
2. Open Feishin and look at Artists page photo. See that it is not consistent with Navidrome.
3. Click on that individual artist. See that the photo is consistent with Navidrome.

### Context

It's annoying.

### Application version

v0.7.1

### Operating System and version

MacOS Sonoma 14.5

### Server and Version

Navidrome 0.52.5

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/b30fadd149eb832a1f2810886b1513f356c50159
