### ISSUE TITLE
Suggest change the information on how to fix the quarantine situation on MacOS 

### ISSUE THREAD

**Issue by ebee04** [jeffvli/feishin#637]
### Expected Behavior

`xattr -r -d com.apple.quarantine /Applications/Feishin.app`
This should remove Feishin from quarantine.

### Current Behavior

I was getting the error `option -r not recognized` 

### Steps to Reproduce

Fairly obvious from above.
`xattr -r -d com.apple.quarantine /Applications/Feishin.app`

### Possible Solution

I believe this issue stems from me having two versions of xattr installed. The Python version does not use "-r" as a command.

Instead, I ran `sudo /usr/bin/xattr -r -d com.apple.quarantine /Applications/Feishin.app`.

I suggest that the instructions are changed to this command to cover situations like mine.

### Application version

7.0.0

### Operating System and version

MacOS Sonoma 14.5, ARM

### Server and Version

Navidrome

**Comment by jeffvli** [comment]
Updated on #104
