### ISSUE TITLE
[Request] Replaygain Tag Support

### ISSUE THREAD

**Issue by Rycia** [jeffvli/feishin#64]
Separating from #9.

I already asked on Discord if this was already within the code, and I was told it was, but please make sure that Feishin supports replaygain tags.

When using Sonixd for desktop with Navidrome, it seemed to not ever have support to reading replaygain tags. These tags make sure all my tracks are the same value without having to re-encode my tracks; which after doing multiple times, will degrade the quality of my tracks.

Musicbee does well implementing these tags and it works in musicbee, but Sonixd doesn't read them even though it is within the Navidrome API.

**Comment by jeffvli** [comment]
Added in [0.0.1-alpha6](https://github.com/jeffvli/feishin/releases/tag/v0.0.1-alpha6).
