### ISSUE TITLE
Wrong album covers when sorting by random

### ISSUE THREAD

**Issue by dolceAlka** [jeffvli/feishin#641]
### Expected Behavior

Matching album cover for album info (artist, name) displayed

### Current Behavior

When you scroll down too fast for all images to load in in the album page and press refresh sorting by random, some albums will have the wrong album image loaded

### Steps to Reproduce

1. Using the scroll bar scroll down much lower than current position
2. press refresh

### Possible Solution

Likely that fetching the images from the first scroll downwards is queued and then after the refresh does not clear queue for fetch or render and images get loaded wrongly. 

### Application version

v0.71

### Operating System and version

Windows 11, Web

### Server and Version

Navidrome 0.52.5

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/94edda1856014a3491cc43c24c802de23ca42256
