### ISSUE TITLE
Bug: Macos show blank screen after close window and open again

### ISSUE THREAD

**Issue by yuygfgg** [jeffvli/feishin#642]
### Expected Behavior

start the app and show the main window

<img width="1435" alt="截屏2024-06-12 08 36 54" src="https://github.com/jeffvli/feishin/assets/140488233/9ddf75b5-61e7-4ac4-99b8-eb561f871cc4">

### Current Behavior

show blank window

<img width="1429" alt="截屏2024-06-12 08 34 48" src="https://github.com/jeffvli/feishin/assets/140488233/7489e62d-75ac-49f2-9e33-ba46489343ff">

### Steps to Reproduce

1. close the window by clicking the left button

2. click feishin icon in dock

3. you will see blank screen

### Possible Solution

maybe reload the app? I don't know anything about react.

### Application version

0.7.1 

### Operating System and version

macos latest

### Server and Version

navidrome 0.51.1

**Comment by brian-xu** [comment]
also affected, on ARM (m1 pro) if that matters

**Comment by jeffvli** [comment]
Try to open to browser dev tools and check what the error is in the console.

Use ctrl + shift + i (or cmd for macos)

**Comment by brian-xu** [comment]
Nothing happens, I just get an error sound.

**Comment by yuygfgg** [comment]
<img width="295" alt="截屏2024-07-14 17 26 30" src="https://github.com/user-attachments/assets/e7c17061-63b2-453f-b6c6-70e22a57353c">
it shows this error when open for the first time.

**Comment by yuygfgg** [comment]
> Try to open to browser dev tools and check what the error is in the console.
> 
> Use ctrl + shift + i (or cmd for macos)

nothing happen after pressing ctrl (or cmd)  + shift + i

**Comment by jeffvli** [comment]
@yuygfgg If you can access the UI before the white screen crash, then open the devtools from the menu. Then check the exact error from the console.
![image](https://github.com/user-attachments/assets/0813eda5-4fad-4d2a-a047-1c4cf02f3291)

@brian-xu I~~f you can clone the repo, install nodejs and run the dev version you may be able to debug it from the devtools console. Unfortunately without the actual error I'm unable to troubleshoot it since I don't know where the error is coming from on your side.~~ See comment below for pre-built versions.

**Comment by yuygfgg** [comment]
@jeffvli 


<img width="1436" alt="截屏2024-07-14 17 46 05" src="https://github.com/user-attachments/assets/863d4c4e-6a05-4f48-b6f8-264c219396a6">
There is no error before crash. and when I close the window and open again, it became blank screen.

**Comment by jeffvli** [comment]
I [built a version](https://github.com/jeffvli/feishin/actions/runs/9927120495) that shows the devtools by default when opening the app. Install one of the versions below and see if you can see the error using the devtools.

[Feishin-0.7.2-mac-x64.dmg](https://share.jeff-server.com/u/Feishin-0.7.2-mac-x64.dmg)
[Feishin-0.7.2-mac-arm64.dmg](https://share.jeff-server.com/u/Feishin-0.7.2-mac-arm64.dmg)

**Comment by yuygfgg** [comment]
> I [built a version](https://github.com/jeffvli/feishin/actions/runs/9927120495) that shows the devtools by default when opening the app. Install one of the versions below and see if you can see the error using the devtools.
> 
> [Feishin-0.7.2-mac-x64.dmg](https://share.jeff-server.com/u/Feishin-0.7.2-mac-x64.dmg) [Feishin-0.7.2-mac-arm64.dmg](https://share.jeff-server.com/u/Feishin-0.7.2-mac-arm64.dmg)

nothing showed up and still blank screen.

BTW, after I click on the feishin icon on dock, it stucked for about 2 seconds before the blank screen shows up.

**Comment by jeffvli** [comment]
Unfortunately I can't help much more than that. You will need to run the development version yourself and see if you can find where the error is coming from. I don't have a macOS device and I can't reproduce this error on my Windows machine.

Install nodejs, clone the repo, do a `npm install --legacy-peer-deps`, and then `npm run start` to start the dev build.

**Comment by yuygfgg** [comment]
> Unfortunately I can't help much more than that. You will need to run the development version yourself and see if you can find where the error is coming from. I don't have a macOS device and I can't reproduce this error on my Windows machine.
> 
> Install nodejs, clone the repo, do a `npm install --legacy-peer-deps`, and then `npm run start` to start the dev build.

```
(node:71552) ExtensionLoadWarning: Warnings loading extension at /Users/a1/Library/Application Support/Electron/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd:
  Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.
  Permission 'notifications' is unknown or URL pattern is malformed.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

(node:71552) UnhandledPromiseRejectionWarning: Error: Attempted to register a second handler for 'open-item'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:2:100960)
    at createWindow (/Users/a1/feishin/src/main/main.ts:2:9216)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:71552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by yuygfgg** [comment]
@jeffvli 
I solved the problem by moving the ipcMain.handle('open-item', ...) registration to the global scope.
