### ISSUE TITLE
Bump Electron to newer version, e.g. v29

### ISSUE THREAD

**Issue by onny** [jeffvli/feishin#643]
### Expected Behavior

Updating electron in package.json to >= v29

### Current Behavior

Current Electron version is v27.X which is EOL

### Steps to Reproduce

See package.json dependencies

### Possible Solution

Versions prior to Electron v29 are EOL, [see](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline).

Please upgrade version to >= v29.

Best regards
Jonas

### Application version

0.7.1

### Operating System and version

NixOS

### Server and Version

Jellyfin latest

**Comment by jeffvli** [comment]
This issue will require more attention due to Electron v28 introducing ESM as a breaking change.

#659

**Comment by jeffvli** [comment]
Resolved in #659, updated electron to major version v31.
