### ISSUE TITLE
Jellyfin - Can only have one feishin instance logged in at a time

### ISSUE THREAD

**Issue by jmilette** [jeffvli/feishin#644]
### Expected Behavior

I should be able to have multiple feishin installations on various computers/locations logged in at once.

### Current Behavior

As soon as a second feishin instance logs in, the first will log out.  Occurs irrespective of network (internal vs over internet) or OS (windows vs linux).  I've tried with Jellyfin's "Maximum number of simultaneous user sessions" set to 0 (disabled) and 20 with no change in behavior.  Using Jellyfin 10.9.5.

### Steps to Reproduce

From a primary computer, log into Jellyfin with Feishin
From a secondary computer, log into Jellyfin with Feishin.  Note the primary computer's Feishin has been logged out.

### Possible Solution

I don't know enough about how the auth works, but I did find it interesting that if you reproduce this with a web hosted Feishin, the same thing applies but only to the hosted version - i.e. if you sign into the web version, it will sign out other web versions but not the desktop apps, and vice versa.  

### Application version

0.7.1

### Operating System and version

Arch Linux, Windows 10, Firefox web app

### Server and Version

Jellyfin 10.9.5

**Comment by neohesperidin** [comment]
I'm also experiencing the same issue, using the desktop version at home and at work.
I've tried making another user to see if that helps, will report back tomorrow evening.
