### ISSUE TITLE
[Compatibility] Conflicts with NVidia Shadowplay

### ISSUE THREAD

**Issue by DessertOverlord** [jeffvli/feishin#648]
### Expected Behavior

Normally, I can use NVidia Shadowplay's instant replay feature to capture the last X minutes of gameplay for use later. 

### Current Behavior

When Feishin is open and playing music, it seems to confuse ShadowPlay and capture only a still image, but with audio intact.

### Steps to Reproduce

1. Set up NVidia Shadowplay and turn on instant replay.
2. Open Feishin.
3. Being playing music.
4. Capture a clip.

### Context

Just trying to listen to music while playing games and taking clips.

### Application version

v0.7.1

### Operating System and version

Windows 10 Desktop

### Server and Version

Navidrome v0.51.1

**Comment by jeffvli** [comment]
I can't reproduce this on my system unfortunately.

Only thing I can think of is reinstalling Geforce Experience/shadowplay and retrying. You could also try forking and compiling your own version with hardware acceleration disabled (maybe it's being detected by GPU?) as [shown in the Electron docs](https://www.electronjs.org/docs/latest/tutorial/offscreen-rendering) using `app.disableHardwareAcceleration()`.

**Comment by DessertOverlord** [comment]
Interesting. I've also now replicated the same issue when playing a different game (Battlefield 2042) using Sonixd, while Feishin was causing problems with Chivalry 2. I'll try reinstalling GeForce experience and see if my mileage changes.

Thanks!

**Comment by DessertOverlord** [comment]
Reinstalling GeForce Experience seems to have resolved this for now. Feishin is no longer causing Shadowplay to wig out with Chivalry 2, I haven't tested BF2042 with Sonixd yet though. No idea why.
