### ISSUE TITLE
[Request] Allow setting Album/Song/Artist views in Library to by default show favorites/liked only instead of defaulting to everything

### ISSUE THREAD

**Issue by Rycia** [jeffvli/feishin#65]
Separating from #9.

You should allow us to set, by default, to automatically filter to favorited/liked/loved songs/albums ect in the Library subtabs. 

By default, it will show the entire library in the format given (eg song view, album view, ect.) 

Some people (like me) like to play a mix of all my favorites in those tabs the second I open Sonixd, and Feishin, and it's inconvenient to not automatically have the option to sort everything by favorite and choose our default.

**Comment by marcus-k** [comment]
I think this is a pretty big one. One of the big things turning me away from this UI is the lack of a favorites/liked songs button in the sidebar. It is very inconvenient needing to toggle the favorites filter in the filters menu just do this. At the very least, I think this toggle should be not hidden behind a menu but placed either as a sidebar item or as a button in the main library area.

**Comment by mvastum** [comment]
Yes, I'd love a similar feature as well. Would it be possible to auto-create a playlist with all favorites? As in any new song I like will automatically be added to that playlist. This way I could just shuffle the playlist and enjoy my favorites without the need for toggling anything on or off.

**Comment by kgarner7** [comment]
Both Jellyfin:
(albums)
![image](https://github.com/jeffvli/feishin/assets/17521368/c9e32b2f-86f9-4911-a37f-896273f8cfbd)
(tracks)
![image](https://github.com/jeffvli/feishin/assets/17521368/23572e05-a1ac-43d3-953f-5c231ca284f2)
And Navidrome
(albums)
![image](https://github.com/jeffvli/feishin/assets/17521368/3de12e8d-1771-4ef5-b1ed-46a759dc4533)
(tracks)
![image](https://github.com/jeffvli/feishin/assets/17521368/1786f7f0-3112-45bb-b7d2-fa21a615983c)
support this. These filters are persistent as well

**Comment by kgarner7** [comment]
> Yes, I'd love a similar feature as well. Would it be possible to auto-create a playlist with all favorites? As in any new song I like will automatically be added to that playlist. This way I could just shuffle the playlist and enjoy my favorites without the need for toggling anything on or off.

What server are you using? If Navidrome, consider a [smart playlist](https://github.com/navidrome/navidrome/issues/1417)
