### ISSUE TITLE
Display multiple disc subtitles in a single disc

### ISSUE THREAD

**Issue by auranunderscore** [jeffvli/feishin#651]
### What do you want to be added?

As it stands currently, only the first disc subtitle tag of a disc is displayed, however different tracks in a single disc can have different disc subtitles. Please add support for this by displaying each disc subtitle grouping

As an example, disc 1 of this boxset has two sections, one for the main album and one for the bonus tracks
![image](https://github.com/jeffvli/feishin/assets/126738276/c83aa1d9-3f6a-414d-87db-05ccef8e4d98)

However, only the first section is properly labelled
![image](https://github.com/jeffvli/feishin/assets/126738276/f69f1858-1757-4534-801b-3a3aa4f0365a)

Rough mockup of what this could look like
![image](https://github.com/jeffvli/feishin/assets/126738276/1ac9659b-5329-41c0-89c2-ec4cc627babe)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/8a8542ddb1173e0feaf059a41a4cb52657a22111 (Navidrome only; Jellyfin as far as I can tell doesn't expose disc subtitles at all)
