### ISSUE TITLE
"Your session has expired" with Jellyfin 10.9.6

### ISSUE THREAD

**Issue by Morethanevil** [jeffvli/feishin#653]
### Expected Behavior

Opening the app it should login normally

### Current Behavior

Every now and then Feishin says "Your session has expired, please relogin"

I need to fill in my password

### Steps to Reproduce

.

### Possible Solution

It would be cool, if Feishin could use the stored credentials and tries to relogin itself, if this fails, then it should throw the error. 

### Application version

0.7.1

### Operating System and version

Fedora, Windows 11 happens on both

### Server and Version

Jellyfin 10.9.6

**Comment by ghost** [comment]
I have been experiencing a very similar problem when using Feishin on multiple computers.
For example, when I open Feishin on my Laptop and log in, and then later try to use Feishin on my PC, I get the message that my session expired, and need to log in again. The same thing happens the other way around too.

I am using Feishin v0.7.1 with Jellyfin 10.9.4, experiencing this issue on both Windows 11 and Fedora.

Edit: OP's issue could very well be related to #644.
