### ISSUE TITLE
Feishin doesn't continue the music playback

### ISSUE THREAD

**Issue by DanieleMassa** [jeffvli/feishin#655]
### Expected Behavior

the app should play the following track when the current one has ended

### Current Behavior

feishin stops playing the music and doesn't start the following track. for a while it worked, now it doesn't, even tho i haven't change anything

### Steps to Reproduce

Install feishin, setup a navidrome connection and play an album

### Context

I'm hosting my navidrome server on a proxmox container on my raspberrypi. I've 2 containers acually. one with flac music, where I have absolutely no problems, and another with flac music where i'm facing the issue. the concerning thing is that with other players i cannot replicate this behavior (tested on the official navidrome webplayer and on [Synfonium](https://symfonium.app/) and [Tempo](https://github.com/CappielloAntonio/tempo) on my smartphone)

### Application version

0.7.1

### Operating System and version

Ubuntu 24.04

### Server and Version

Navidrome v0.52.5

**Comment by DanieleMassa** [comment]
edit: I've just tried to create another container with a similar configuration and I noticed that the problem is occurring only with FLAC files

**Comment by TacoCake** [comment]
Could be related to #608 ?

**Comment by DanieleMassa** [comment]
SOLUTION: switch the player from "Web" to "MPV"

**Comment by DanieleMassa** [comment]
SOLUTION: switch the player from "Web" to "MPV"

**Comment by Hugo7th** [comment]
Sorry for the wrong  info here, problem happen again, but it is all about playing .m4a songs, so may be something wrong with m4a, not mpv version.     

> same problem here, M2 Mac mini Sonoma, mpv installed via applite, looks like it is using stolendata version becuase of url laboratory.stolendata.net pop up in adguard.  and it will not continue play the list, switch to homebrew version fix this problem. Not 100% sure who cause the problem,  but it works for me._

**Comment by Hugo7th** [comment]
> Sorry for the wrong info here, problem happen again, but it is all about playing .m4a songs, so may be something wrong with m4a, not mpv version.
> 
> > same problem here, M2 Mac mini Sonoma, mpv installed via applite, looks like it is using stolendata version becuase of url laboratory.stolendata.net pop up in adguard.  and it will not continue play the list, switch to homebrew version fix this problem. Not 100% sure who cause the problem,  but it works for me._

roll back to 0.7.1 on Macmini M2, it solved the problem, dont know why
