### ISSUE TITLE
Make the volume slider wider

### ISSUE THREAD

**Issue by ryankupk** [jeffvli/feishin#667]
### What do you want to be added?

I tend to click on the volume slider to change volume rather than any other method. As is, it's like 1 inch on the screen and (I don't think) it gets bigger or smaller if I change the window size. There's a lot of empty room in that corner of the player as well, I think that making it 2x or even bigger than it currently is would be good. 

Could even move it down so that the speed, heart, and queue buttons are on the row that they're on now, and the volume slider is alone on the row below. This arguably is more consistent with the UI in the middle of the bottom of the screen, but I think that the difference is extremely minute and I don't have strong opinions about it. 

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/028ccfb1cd40fd70c4593cccef3df26eb43b1e11 (configurable option)
