### ISSUE TITLE
Allow browse/sort/search by publisher 

### ISSUE THREAD

**Issue by toothdog** [jeffvli/feishin#669]
### What do you want to be added?

Feishin currently allows users to browse and sort pages for albums, tracks, artists, genres, and playlists, and I would like the option to do the same according to the publisher tag in order to sort the collection according to record label. Currently, publisher information is not accessible at all through the app, including the "Get info" popup.

**Comment by kgarner7** [comment]
The record label tag isn't stored at all in Navidrome, so there would be no way to sort by that. This would be resolved eventually by https://github.com/navidrome/navidrome/pull/2709, which would allow for much richer tags.

Similarly, unless Jellyfin's term for record label is "Studios" (which isn't being populated for me from tags), I don't see anywhere that exposes that metadata either (or reads it from file).

This feature would require one (or both) servers to implement it before being really practical.
