### ISSUE TITLE
[Request] When in the Library song's tab, automatically queue all the other songs within the current filter.

### ISSUE THREAD

**Issue by Rycia** [jeffvli/feishin#67]
Due to the issue in #61,

I have found that when selecting a song in Tracks, Albums, or Artists in the Library tabs, the only thing added to queue within favorite view is what you play.

At first, it made me think that queuing was broken and I made a previous issue about it.

You should create an option (or outright implement) a way to automatically add other songs to queue when clicking on a song/album/artist while filtering favorites (or any other filter) in Library, or at least for just song selection.

Make sure that there's a way to make the queue not remove the song from the queue after it's done playing unless switching to a playlist or library subtab, or move it to the end of the queue, to prevent it simply stopping. Perhaps a sort of infinite replay queue lock? I can open a "queue lock" feature issue if it seems like a good idea, because I can also see this being implemented outside of filtering in just the library tab, such as putting albums on repeat.

**Comment by Kidsnd274** [comment]
I have the same issue here. When playing a specific track from a playlist/album/etc., it only queues your current song and not the rest of the listed songs.

**Comment by jeffvli** [comment]
Resolved for the next version
