### ISSUE TITLE
Audio Device Selection does NOT work as intended.

### ISSUE THREAD

**Issue by Astrocule** [jeffvli/feishin#671]
### Expected Behavior

I go into settings, I use the web player for playback, I change the Default audio device from Default to any of the 3 peripherals plugged in.
The audio should now come out of ANY of the 3 I choose automatically upon selection.

### Current Behavior

It stays on my default audio device for my system. 
The image below, is a ss of the console. This is spammed only when changing my audio device.
![image](https://github.com/user-attachments/assets/057d657e-491f-4176-b9ec-a438a300e858)
(nothing else was outputting to any other tabs of the dev tools)

### Steps to Reproduce

1. Open any Web based app that isnt Feishin and uses a chromium or web based backend for Audio (like discord)
2. Open Feishin and go to settings
3. Select your audio device.

### Possible Solution

I can only assume, this is because other apps I have open are web-based, and also use chromium as its audio-player/backend. This forces Feishin to use that selected audio device even if told to use a different device within the app.

I can only image using a different audio backend would fix the entire issue, but rewriting the entire app to not be web-based is NOT a solution. I am no where near experienced to suggest things.

(edit) I kinda realized since MPV does work fine, wouldn't it just be best to make mpv a dependency/built in with Feishin and just make that the default backend audio player? 

### Context

I cannot listen to music on my external speakers, while talking/doing something else on another web-based app because switching the chromium input for Feishin to speakers, causes ALL chromium based apps to switch. 
I can, switch Feishin, then force the other chromium apps to use my headphones individually, but I shouldn't have to do such a thing when using an app. Not only is it time consuming, but I have to do it anytime I close and open Feishin and or any other web-based app.

### Application version

v.0.7.1

### Operating System and version

Arch Linux, Web app, KDE plasma + pipewire.

### Server and Version

Navidrome V0.52.5 (c5560888)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/af69a584183c2a08be1222bc7418fb898b8ac60a. Note that this is not available for the webapp, only desktop using webaudio-based player
