### ISSUE TITLE
Poor icon visibilty in fullscreen player with light dynamic backgrounds 

### ISSUE THREAD

**Issue by cyberwolfie1** [jeffvli/feishin#675]
### Expected Behavior

When I enter the fullscreen player, the top icons (Minimize, Configure and the window-buttons if Web UI is enabled) should be adaptively colored to provide good contrast to the background. 

### Current Behavior

If either the dynamic background provides a very light color, or if using the album cover image as a background when the album color is very light, the icons become very difficult to see.

### Steps to Reproduce

Easiest way to trigger this:

1. Start playing from an album with very light colors on the album cover
2. Enable background image

### Possible Solution

The icon colors could perhaps switch between light and darker colored depending on the average color of the background int he top row?

### Application version

0.7.1

### Operating System and version

Tuxedo OS 3 and Linux Mint 21.3

### Server and Version

N/A

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/886786d4282e18678a6e931306158d61da189b8c
