### ISSUE TITLE
Lyrics not displaying

### ISSUE THREAD

**Issue by 2MPP** [jeffvli/feishin#677]
### Expected Behavior

Display lyrics from lrc file

### Current Behavior

Not displaying them

### Steps to Reproduce

1. Get music + lrc file
2 Put them in the same folder
3. open lyric view
4. No lyrics displayed

### Context

I have music file + the lyrics in the same file and with the same name so song.mp3 and then song.lrc 
![example](https://github.com/user-attachments/assets/2f799da4-7982-47c5-8cc2-d65790c2bd56)
![Lyric view](https://github.com/user-attachments/assets/99d301c7-c497-46dc-b55f-05b2789037dc)

### Application version

0.7.1

### Operating System and version

Windows 10

### Server and Version

0.52.5

**Comment by kgarner7** [comment]
If this is Navidrome (you only listed version), then it only reads lyrics from embedded metadata (not LRC files).

**Comment by 2MPP** [comment]
Ah shit okay i will find out a way to embed them into the metadata i didnt realise thats how navidrome did it
