### ISSUE TITLE
Whole Feishin client refuses to load anything for about 30 seconds when playing a new song

### ISSUE THREAD

**Issue by llek1000** [jeffvli/feishin#681]
### Expected Behavior

Play a song and be able to use the app (pull other data from the server) immediately.

### Current Behavior

After playing a song, I have to wait about 30 seconds before I can load anything else (including playing another song, listing songs, opening lyrics - anything to do with the server). I do not think this has something to do with the navidrome server as the navidrome web interface is usable even during the "freeze" of the Feishin client.
![image](https://github.com/user-attachments/assets/7f3f998d-264e-4a4d-8940-00532d0b5e3c)
![image](https://github.com/user-attachments/assets/5cecedc1-c3b9-4e99-ace2-1e38dbff6560)

### Steps to Reproduce

1. Play a song
2. Try to play another song, or try to load anything from the server
3. The client cannot load anything for about 30 seconds
4. Wait for the client to unfreeze

### Application version

0.7.1

### Operating System and version

Windows 11

### Server and Version

Navidrome v0.52.5

**Comment by jeffvli** [comment]
Unfortunately I haven't encountered this issue before which makes it hard for me to debug. If you have experience with React, you could try running the dev version and try to check exactly where the app is hitching.

Also, if you're connecting to your Navidrome server behind a reverse proxy, also try it using the local/private address.

**Comment by Gecksy** [comment]
I'm also experiencing the same issue. I'm not sure what further information I can provide to help troubleshoot further. 

It isn't all the time but it's enough to be annoying. I'm talking maybe 8 times/hour. 
Randomly if I open a playlist or play a song it'll hang for ages and I'll get the 'this is taking awhile' message.

No playlists will load during this and it takes a good 30ish seconds for the media to start playing. Everything goes back to normal after the track starts playing but it's a bit jarring when it happens. I've cleared the app cache. I'm using the portable zip if that helps.

I'm using Feishin 0.7.3 on Win 11 if that helps. 

Also thank you for developing such a great player. :)

**Comment by jeffvli** [comment]
If you're on Navidrome and you double click a song on the Song page, it queues up the entire library (which if you have a large library it will take a while). You want to select the songs you want to play, right click, and use the play options from the context menu.

**Comment by Gecksy** [comment]
It's happening with a few playlists. From as few as 24 tracks to 400+.
I tested with my Jellyfin server and I was able to replicate the issue. The
Jellyfin app and Navidrome web app are fine.

I am however seeing this in Feishin:
[image: image.png]
I also get the 'Loading songs... This is taking a while' message.

I have swapped from Web player to MPV and it appears to have  resolved the
issue!

Thanks for developing such a cool player! :).

**Comment by llek1000** [comment]
> Also, if you're connecting to your Navidrome server behind a reverse proxy, also try it using the local/private address.

Sorry for the late reply. You are correct, this was caused by my reverse proxy. I somehow did not try to access it directly via a private IP. Thank you very much for pointing this out! I am sorry for reporting this as a bug as it is not. 

If anyone stumbles upon this, you have to have proxy_buffering off - now I was confused at first, because I thought that if the web app is working fine, that the reverse proxy config is fine as well - this is apparently not the case.

Oh, and of course, thank you very much for developing and maintaining such an amazing app!

Edit: Issue was not fixed by editing the buffers of the reverse proxy, and still persists, the freezing only happens when using the "Web Player", it works fine with MPV. See #608 for more.

**Comment by llek1000** [comment]
This could maybe, possibly have something to do with the freezes?
![image](https://github.com/user-attachments/assets/e1c157fb-879f-4940-b7ea-a7881ba81d73)
It apparently has trouble loading the actual player?

![image](https://github.com/user-attachments/assets/97916a8c-26f6-42de-b6a9-0b9c14cba228)
The "stream.view?...." is the same as the one the player is deffering. 

But I really do not know what I'm doing :)), so please correct me if I'm wrong. 
I am posting this here, since I am connecting to Navidrome and not Jellyfin, but the issue seems to be the same.

**Comment by kgarner7** [comment]
My guess is that it's a problem with the server? Your errors do point to another issue resolved by https://github.com/jeffvli/feishin/commit/4c49e403abe1b0ecf8a5f327e6166eae997f138f. Please try https://feishin.vercel.app (or do a build yourself) to see if that is resolved.

**Comment by llek1000** [comment]
The updated build on https://feishin.vercel.app/ seems to work fine. I am no longer getting any errors, I will continue to test this build today and post an update if the issue has been resolved.

**Comment by llek1000** [comment]
Okay, so after about 6 hours of testing, I have not encountered the freezing using the build on https://feishin.vercel.app/, so the issue seems to be fixed - hopefully this time for real! Thank you very much!

I will build the feishin client with the fix, and I will be using that for now, until this fix makes it into the next release.
