### ISSUE TITLE
synced lyrics overflowing

### ISSUE THREAD

**Issue by LordFoogThe4rd** [jeffvli/feishin#683]
### Expected Behavior

synced lyrics wrap when there isn't enough space

### Current Behavior

synced lyrics overflow outside of the lyrics box
![image](https://github.com/user-attachments/assets/ce8f0cc2-816c-4b33-8bd1-d0e79f78d48d)

### Steps to Reproduce

1. choose synced lyrics

### Application version

0.7.1

### Operating System and version

Kubuntu 23.10

### Server and Version

Navidrome 0.49.3

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/ebebdc1e03b2d0a51067a7e143febca20a7fd635
