### ISSUE TITLE
AppImage Icon Not Rendering

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [jeffvli/feishin#685]
### Expected Behavior

AppImage should have the feishin icon

### Current Behavior

AppImage icon not rendering
![image](https://github.com/user-attachments/assets/d6cfdcb0-43a7-46dc-afdb-92c636e78066)

### Steps to Reproduce

Install and run the 0.7.2 Appimage on Fedora Workstation (Gnome) using AppImage Launcher

### Possible Solution

Add icon to AppImage build

### Application version

0.7.2

### Operating System and version

Fedora 40 Workstation

### Server and Version

Jellyfin

**Comment by jeffvli** [comment]
There weren't any changes made to the icon in the previous release. Maybe you can try doing a clean reinstall and reboot to see if it fixes itself.

**Comment by kgarner7** [comment]
Since there has not been any activity on this issue, I will go ahead and close it. If this still persists, please add more details here with the latest release.
