### ISSUE TITLE
Wrong Electron version (27)

### ISSUE THREAD

**Issue by sigmakey** [jeffvli/feishin#686]
### Expected Behavior

The release notes for v0.7.2 mention upgrading Electron to version 31. 

### Current Behavior

I downloaded the Linux x86_64 release and found it was using Electron 27 (same for the AppImage).

### Steps to Reproduce

1. Download the v0.7.2 release (tested on Linux)
2. Open devtools console
3. Run `navigator.userAgent`
4. Observe the result, I get:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) feishin/0.7.2 Chrome/118.0.5993.144 Electron/27.1.0 Safari/537.36`

### Application version

v0.7.2

### Operating System and version

Linux (Arch)

### Server and Version

Navidrome 0.52.5

**Comment by jeffvli** [comment]
I forgot to bump `electronVersion` in the electron-builder configuration. I'll push a new version.
