### ISSUE TITLE
Jellyfin: Playlist IsPublic option

### ISSUE THREAD

**Issue by reggermont** [jeffvli/feishin#694]
### What do you want to be added?

Jellyfin's [CreatePlaylist](https://api.jellyfin.org/#tag/Playlists/operation/CreatePlaylist) and [UpdatePlaylist](https://api.jellyfin.org/#tag/Playlists/operation/UpdatePlaylist) now supports a `IsPublic` boolean to set the playlist public or not

### Is this a server-specific feature? (e.g. Jellyfin only)

- [X] Yes

**Comment by kgarner7** [comment]
https://github.com/jeffvli/feishin/commit/93377dcc4fca9f851470879693d29a9174009e6f. Bizarrely, Jellyfin doesn't appear to offer any way to _query_ whether the playlist
