### ISSUE TITLE
Support lms

### ISSUE THREAD

**Issue by alscaldas** [jeffvli/feishin#695]
### What do you want to be added?

I'd like to be able to connect to a [lms](https://github.com/epoupon/lms) server. It works with Navidrome, Gonic but not with lms.

### Additional context

When I try to connect inserting url, username and password, I get the message `Token authentication not supported for LDAP users.`

I tried using both `https://sub.domain` and `http://my.ip.addr:port` and got the same result.

Also tried enabling/disabling `"Ignore cors"` and `"Ignore ssl"` but neither worked.

As it isn't explicitly stated that lms is supported (although it's Subsonic compatible), I imagine supporting it would be considered a new feature, hence I opened it as a feature request instead of a bug.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
1. Subsonic as a whole isn't supported: https://github.com/jeffvli/feishin/issues/306
2. It looks like if you use ldap, you have to use the legacy auth (password only).

I don't know how you were able to get any other subsonic server to work.

**Comment by guss77** [comment]
I also have this issue. This is not limited to LMS - there are other subsonic servers that use non-challenge authentication, and Feishin will not work with any of them: Airsonic with some password formats, Ampache with local passwords, gonic and probably others. 

Most Subsonic clients deal with this by having an option to use [the older plain text (or hex encoded, which is basically the same thing, security-wise) authentication protocol](https://opensubsonic.netlify.app/docs/api-reference/#authentication).
