### ISSUE TITLE
Move songs in a playlist manually

### ISSUE THREAD

**Issue by DMtgd220** [jeffvli/feishin#698]
### What do you want to be added?

move up or down songs in a playlist, or be able to freely move music in a playlist, without having to sort them. 

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/10fca2dc12795248c17b5416cf5a093e3e731ee1. Only available when sorting by ID, and one song at a time
