### ISSUE TITLE
Manually add lyrics

### ISSUE THREAD

**Issue by Reiwn** [jeffvli/feishin#700]
### What do you want to be added?

I want to manually add lyrics.

### Additional context

I tried using Feishin Client because of Navidrome doesn't support the external .lrc lyrics file. Navidrome only support embedded lyrics.But I don't want to use the embedded lyrics.And the Feishin Client support get lyrics online. It's good!
I know mpv player support .lrc lyrics,so can I manually add lyrics? The lyrics from the Internet are not translated,but I usually listen Janpanese Anime music.

I have been troubled by the lyrics problem of Navidrome for a long time,I want to solve the problem through its third-party client.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by iiPythonx** [comment]
Feishin doesn't provide any feature to do something like that, and it's also worth noting that Feishin pulls the lyrics directly from Navidrome, not from MPV.
Navidrome has ongoing discussion about this, see https://github.com/navidrome/navidrome/issues/1421.

**Comment by Reiwn** [comment]
> Feishin doesn't provide any feature to do something like that, and it's also worth noting that Feishin pulls the lyrics directly from Navidrome, not from MPV. Navidrome has ongoing discussion about this, see [navidrome/navidrome#1421](https://github.com/navidrome/navidrome/issues/1421).

I've seen  https://github.com/navidrome/navidrome/issues/1421 before,Of course I know Navidrome doesn't support external lyrics.But have you read my requirements in detail?I want to solve the navidrome's problem of external .lrc lyrics through its third-party client.I don't mean to use Feishin add lrc lyrics to navidrome song.I mean to use Feishin display the external lrc lyrics.
Feishin can get lyrics online,it's not the navidrome lyrics.So it's external lyrics.
![image](https://github.com/user-attachments/assets/64cc152e-c492-4a30-a79f-96dabe810d09)

**Comment by kgarner7** [comment]
There's a difference between getting lyrics online (with a known API) and reading from filesystem. Doing it the Jellyfin way would require assuming that Feishin is on the same system as Navidrome (by filepath). 

Since you are not embedding the lyrics, your best bet is to hope that https://github.com/navidrome/navidrome/pull/2897 gets merged in. It is unlikely that such a workaround will be added here.

**Comment by Reiwn** [comment]
> There's a difference between getting lyrics online (with a known API) and reading from filesystem. Doing it the Jellyfin way would require assuming that Feishin is on the same system as Navidrome (by filepath).
> 
> Since you are not embedding the lyrics, your best bet is to hope that [navidrome/navidrome#2897](https://github.com/navidrome/navidrome/pull/2897) gets merged in. It is unlikely that such a workaround will be added here.

I guess Feishin should be based on Chromium.I think I can provide a path with readable permissions for Feishin to use, and achieve the purpose by reading the lrc file.Of course I hope https://github.com/navidrome/navidrome/pull/2897 gets merged in,it's best.
Thank you for your contribution and suggestions to the Navidrome project. I will close this issue.
