### ISSUE TITLE
"Use native cover art aspect ratio" doesn't seem to work properly

### ISSUE THREAD

**Issue by metaisfacil** [jeffvli/feishin#704]
### Expected Behavior

Non-square covers should be displayed without stretching. The setting description says there should be remaining space left empty on the sides.

### Current Behavior

I don't see the original aspect ratio used literally anywhere album art appears. Cassette covers are vertically squished and digipak covers are horizontally squished. I've seen at least one release where toggling the switch will cause a _very_ slight change, but it was almost a perfect square anyway so it made no meaningful difference.

### Steps to Reproduce

1. Switch on "Use native cover art aspect ratio" in settings.

### Application version

v0.7.3

### Operating System and version

Windows 10 desktop

### Server and Version

Jellyfin v10.9.9

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/e4ca0164faf8631876bdb01cce1a22647d23e551

**Comment by neohesperidin** [comment]
Hiya, I still seem to be experiencing this issue on v0.8.1.
I've attached a screenshot from Feishin and one from Finamp where it displays as I'd expect.
![image](https://github.com/user-attachments/assets/dbfc20f6-2b9c-4cab-83d1-878eca48f9d3)
![image](https://github.com/user-attachments/assets/b8a4b5ce-7c56-4583-8666-954f63244838)

Could you take another look?

**Comment by kgarner7** [comment]
https://github.com/jeffvli/feishin/commit/3025e84c58da333cfd98c0eb5db4b8cbfd73cde9
