### ISSUE TITLE
playback history

### ISSUE THREAD

**Issue by tcurdt** [jeffvli/feishin#709]
### What do you want to be added?

I would be great to have some sort of playback history.
This could also be a local feature if there is no server support for it.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by PixelMelt** [comment]
You can somewhat use this feature by using Navidrome's smart playlists

**Comment by tcurdt** [comment]
@PixelMelt Can you elaborate? Sure, Navidrome has a "Recently Played". But that list is not shown in Feishin.

**Comment by kgarner7** [comment]
Tracks > sort by Recently Played

**Comment by tcurdt** [comment]
> Tracks > sort by Recently Played

That works.
