### ISSUE TITLE
Custom CSS injection

### ISSUE THREAD

**Issue by TheSunCat** [jeffvli/feishin#711]
### What do you want to be added?

Hi! Thanks for developing this app. I'm really happy with the interface, however I'd love to be able to match the colors to other applications on my system (specifically my GTK theme). I can see that Feishin uses CSS variables already, so these could be set following the system theme.

I'm not aware of a way to automate fetching GTK colors via Electron, but being able to set them myself via CSS in a config file (like I do for Vesktop in the `~/.config/vesktop/themes` dir) would already be great.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Supported via https://github.com/jeffvli/feishin/commit/6125901023a0b18239ebcb39552e0885e255ca10, with caveats:
1. Must be text.
2. CSS is sanitized; not everything will work. This is by design.
