### ISSUE TITLE
Discord Rich Presence: Say "listening to" instead of "playing a game"

### ISSUE THREAD

**Issue by TheFeelTrain** [jeffvli/feishin#712]
### What do you want to be added?

Have the Discord Rich Presence say "listening to" instead of "playing a game"

### Additional context

Seems to be a somewhat new feature that other clients have implemented:

![351899080-3d7265c6-5065-4b92-9f69-d41a564df6dc](https://github.com/user-attachments/assets/42aff450-cfb4-4ab7-85ad-447a6c9970a9)

![image](https://github.com/user-attachments/assets/a07b1112-ee71-4df4-9342-571dc86e5963)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/284db988c91f56f13a48f04ae420a3b8394c2652

**Comment by leethobbit** [comment]
EDIT: I did not realize this was creating a toggle feature for listening. So sorry for the confusion!

**Comment by iiPythonx** [comment]
>  I saw it was tagged for 0.10.1 but the changes aren't present.

Running off of 0.10.1, the toggle is available:
![image](https://github.com/user-attachments/assets/e727f496-dc4f-40aa-8094-9b45b6eb2fd7)

Are you sure you're running the latest release?
