### ISSUE TITLE
Elgato Stream Deck Plugin

### ISSUE THREAD

**Issue by Felitendo** [jeffvli/feishin#713]
### What do you want to be added?

An Elgato Stream Deck Plugin where we can (similary to the Spotify Plugin) skip, pause, stop, play, mute, change the volume of songs

### Additional context

https://marketplace.elgato.com/product/spotify-integration-windows-5e3a6d60-570a-40f3-b186-dbcd122216a2

https://docs.elgato.com/sdk/plugins/getting-started

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Respectfully, but are you (or someone else who has the device) willing to make a PR/build to add this feature? That's really the only realistic way this would be implemented.
If you need websocket controls, there's pretty rich controls in `src/main/features/core/remote/index.ts`

**Comment by Felitendo** [comment]
I could try, but I have never made a elgato stream deck plugin before

**Comment by Felitendo** [comment]
Are you the owner of the images in the assets folder? If so, can i use the pause, play and the Feishin icon for my Plugin? It will be open sourced on this account btw

**Comment by kgarner7** [comment]
> Are you the owner of the images in the assets folder? If so, can i use the pause, play and the Feishin icon for my Plugin? It will be open sourced on this account btw

That's a question for @jeffvli

**Comment by jeffvli** [comment]
I don't own the icons, but I'm pretty sure I pulled them from an MIT (or equivalently) licensed library so it should be fine to use.
You don't need to give any credits to this repo for them.

**Comment by Felitendo** [comment]
I'm working on it but I could really use some help.

https://github.com/Felodeck/Feishin-Plugin

**Comment by iiPythonx** [comment]
> I'm working on it but I could really use some help.

What are you missing? Looks like you have nearly all the events already covered (play/skip/etc).

**Comment by Felitendo** [comment]
> > I'm working on it but I could really use some help.
> 
> What are you missing? Looks like you have nearly all the events already covered (play/skip/etc).

Hey thanks, yeah I got everything working now. Just thought I can't do it but somehow did

**Comment by Felitendo** [comment]
Now I only need to add the Icons and Names and I'll be done by tomorrow I think. I will be keeping you updated here and I will post again once my Plugin gets acceted to be on the official Elgato Marketplace

**Comment by Felitendo** [comment]
For anyone wondering:

The Plugin is still under review and will probably be published by the end of the week if everything goes to plan :)

**Comment by Felitendo** [comment]
It finally got accepted :D

You can find it here: https://marketplace.elgato.com/product/feishin-d55fd48d-f102-4d21-83ce-bc1ea12beeba

The source code is available here: https://github.com/Felodeck/Feishin-Plugin

**Comment by jeffvli** [comment]
Great work!

Feel free to submit a PR to add your plugin to the README of the repo. You could add a new section with a header of `Related Projects` or similar.
