### ISSUE TITLE
No music plays ("sounds") from web player for macOS 12

### ISSUE THREAD

**Issue by thebiblelover7** [jeffvli/feishin#719]
### Expected Behavior

Music should be heard from the web player (otherwise what's the point of Feishin?)

### Current Behavior

Currently, on macOS 12 devices, the web player shows progress on the music being played, but does not produce any hearable sounds.
Opening the dev tools shows that the actual music track is loaded, but still no sound comes out.

### Steps to Reproduce

Attempt to play music on a Mac with version 12.

### Context

My school is trying to use Feishin as a "nice" client for Navidrome, but it only works on devices that have a macOS version >12. I have tested this on multiple macbooks. Those with version >12 work fine, but those below do not work.
Playing the music directly from Navidrome works totally fine.

### Application version

v0.7.0, v0.7.1, v0.7.2, v0.7.3

### Operating System and version

MacOS 12

### Server and Version

Navidrome v0.52.5

**Comment by iiPythonx** [comment]
Might not work (at least easily) on MacOS, but a lot of these web player issues get resolved by switching to MPV in playback settings. If you can, I would highly encourage you try it and see if that fixes the issue (although I'm not terribly sure why it would be related to your version of MacOS).

**Comment by thebiblelover7** [comment]
@iiPythonx I guess I didn't make it clear, but I'm using this in the web player (meaning playing from the browser). As far as I understand, playing with MPV in the browser is not possible....

**Comment by iiPythonx** [comment]
Ah, I assumed you were using the desktop app with the web player enabled. In that case I guess it would be something browser related, maybe @kgarner7 could provide some assistance?

**Comment by thebiblelover7** [comment]
I just tried using Feishin from the app instead of a browser and it worked totally fine. I also tried it in Firefox 129 and it also worked totally fine. I assume it must be something with the older Safari version.

**Comment by kgarner7** [comment]
My best guess is old safari's handling of web audio is even worse. Unfortunately I have no way of debugging this.

**Comment by kgarner7** [comment]
https://github.com/jeffvli/feishin/commit/93055b3bf1679e03a7213e0686783a5fbbf5da94 (disabling web audio) is the best I can offer. See if that works (https://feishin.vercel.app). Note that this disables replaygain

**Comment by thebiblelover7** [comment]
@kgarner7 Thanks for working on that! I will test it tomorrow and let you know if it works properly. At least it will be a "workaround" for those with old Safari versions, until they can upgrade.

P.S.: This also happens on old iPad OSes, so hopefully this fixes both.... It's almost certainly an issue with old Safari.

**Comment by kgarner7** [comment]
Note that after disabling [web audio](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API), you will need to reload the page for it to take effect (this is a limitation that also comes from Safari). If it does work, I can look into providing a way (query parameter? idk) to disable it from the start.

**Comment by thebiblelover7** [comment]
After checking the disable web audio toggle, it does solve the problem. A query parameter wouldn't really help for us (I think at least), since we have many different devices, and for some, replaygain is really nice to have. I wonder if it would be possible to detect if web audio is supported in a browser, and if not, disable it and refresh, maybe even with a popup that explains what's going on...

But otherwise, this is fixed! Thanks!

**Comment by kgarner7** [comment]
The thing is, Feishin will try to check if WebAudio exists https://github.com/jeffvli/feishin/blob/93055b3bf1679e03a7213e0686783a5fbbf5da94/src/renderer/components/audio-player/index.tsx#L133. So what appears to be going on is that old Safari _provides_ WebAudio but it (or the implementation) doesn't quite work.

**Comment by thebiblelover7** [comment]
oh, I see.... okay. We'll live with it :) Thanks for the work!
