### ISSUE TITLE
[Request] Add Discord rich presence

### ISSUE THREAD

**Issue by Rycia** [jeffvli/feishin#72]
Like Sonixd's Rich Presence, add Rich Presence to Feishin.

One thing I disliked about Sonixd's rich presence is that my status would say `Playing Sonixd` As a difference, it would make more sense to change it to `Playing Music` and have the details of the music and what's playing when the profile is opened to then say `Playing with Sonixd` to still keep the credit of the program within it. It's simply that most people wouldn't recognize `Playing Sonixd` and associate that to playing music.

It is possible within the discord API to define what the status says.

It would also be great as an option to show presence to show `Playing Song Name - Artist` and update after a song is playing, for, let's say. 5-10 seconds after the song is playing to avoid the API getting bombed every time you spam skip a song, or just change it whenever you register a song as being played. I'm not sure how Discord has API limits but if I remember correctly, they're a bit finnicky/strict when it comes to statuses.

**Comment by Fluttrr** [comment]
I'd love this as well, but I'd also add that in sonixd, discord rich presence would also show when you're not playing a song and there was no option to turn that off. I often leave the program open in the background without actually listening to music but I don't want people to see me listening to nothing 80% of the time so an option to turn that off would be great too.
