### ISSUE TITLE
Skip silence at beginning/end of tracks for better gapless playback

### ISSUE THREAD

**Issue by huantianad** [jeffvli/feishin#721]
### What do you want to be added?

Some songs have a bit of built-in silence at the beginning and the end, either because of a fade-in/fade-out, or just because of imperfect encoding (can add some offset at the start and end). 

The current gapless playback feature, part of the mpv backend, seeks to remove any silence between tracks as the result of the player; however, this cannot get rid of any silence that's built into the start/end of tracks, resulting in an imperfect "gapless" experience overall.

It's definitely possible to process and mutate all of my audio files to remove this silence, but that would be time consuming and would require destructive mutation of my files, which I'd like to avoid. This responsibility should not also fall to the [server side](https://github.com/navidrome/navidrome/issues/2082); thus, I suggest some sort of processing be done on the client to simply skip any silence

### Additional context

I currently use Feishin with a Navidrome server and the mpv backend, so at least personally for me I'd like to see it at least supported with this configuration haha, but I don't think there would be any reason it would be server api specific.

Perhaps this is something that falls to mpv to do? I wouldn't assume so though...

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by huantianad** [comment]
Yk, sometimes I should wait before posting; I have found a possible answer just using an mpv argument:
`--af=silenceremove=start_periods=1:start_threshold=-50dB:detection=peak,areverse,silenceremove=start_periods=1:start_threshold=-50dB:detection=peak,areverse`

Perhaps this could be exposed as an option similar to the gapless audio option?

**Comment by kgarner7** [comment]
Thanks for finding this! I do have concerns making this a built-in, specifically because [`areverse`](https://ffmpeg.org/ffmpeg-all.html#areverse) requires storing the entire buffer, which can add considerable delay to processing/playing large files, as well as significant memory consumption (especially over network).

Some context: processing a relatively large file (376 MB) on **localhost** caused a delay of multiple seconds, and over 1 GB of memory...

**Comment by huantianad** [comment]
Yeah that's the main issue I have with this method of doing it, i don't really like how it has to reverse the audio file twice to get rid of silence at the end. Unfortunately, the end_period argument to removesilence will remove the rest of the audio file if it encounters silence in the middle of the file too, instead of only removing silence that goes to the end of the file.

But that's the main reason I was wondering if there was some better way of doing it with the client itself that didn't require this...

**Comment by kgarner7** [comment]
Something like `--af=silenceremove=start_periods=2:start_threshold=-50dB:detection=peak:stop_periods=-2:stop_threshold=-50dB`?

**Comment by huantianad** [comment]
Oh does using 2 and -2 work for removing silence at the start and end? I tried 1 and 1 as well as 1 and -1 but that didn't work for me. I'll give a try later

**Comment by kgarner7** [comment]
In my limited testing, it definitely removed more than 2 seconds at the end, but I did notice silence from the end being removed. If I tried a **positive** end, I noticed that some tracks were completely skipped

**Comment by huantianad** [comment]
I think you're misunderstanding what `start_periods` and `end_periods` does; if I use your flags, it'll end up skipping any silence in the middle of the track as well. ffmpeg docs are kinda not the best at explaining, but after reading it a few times I kinda understood https://ffmpeg.org/ffmpeg-filters.html#silenceremove

**Comment by kgarner7** [comment]
I tried with positive stop_periods before and that really didn't do as expected. Might have some luck with https://stackoverflow.com/questions/25697596/using-ffmpeg-with-silencedetect-to-remove-audio-silence as well, but your mileage will likely vary.

**Comment by huantianad** [comment]
I think the TL;DR is that `silenceremove` can only remove silence from the start of the track, in the way that we want. So if we want to use it to remove silence from the end, `areverse` is the only way to do it.

The only other way I could think of doing this would be if the server could pre-process the audio to note how long the silence is at the start and end; then it would be trivial to just trim the audio file client-side.

**Comment by kgarner7** [comment]
If that's the case, I'm not particularly keen making that a built-in option, as it can come with significant performance implications.
