### ISSUE TITLE
release 0.8 not starting on macOS

### ISSUE THREAD

**Issue by tcurdt** [jeffvli/feishin#727]
### Expected Behavior

The app should open. Maybe ask about being unsigned. But open.

### Current Behavior

![Screenshot 2024-09-03 at 17 46 03](https://github.com/user-attachments/assets/09bb9395-4d92-491c-809e-92366ea1dffe)

### Steps to Reproduce

Tried the arm zip and dmg.
Moved to applications.
Right-click open.

### Application version

0.8

### Operating System and version

macOS 14.6.1

### Server and Version

?

**Comment by kgarner7** [comment]
https://github.com/jeffvli/feishin/issues/104

**Comment by tcurdt** [comment]
Sorry, didn't see that.

Hm. That's odd.
Unsigned does not necessarily mean one has to remove it from quarantine manually.

A bit strange. But it does indeed work now.
