### ISSUE TITLE
Top song expanding over 10 songs on One artist. 

### ISSUE THREAD

**Issue by Blavkentropy1** [jeffvli/feishin#729]
### Expected Behavior

The Top 10 artist songs are shown, and no more 

### Current Behavior

The List skips the top song 9, and goes to 10, then showing the same song in a loop. 
This the puts the same song on a list courting up i.e 11, 12,13 etc. Making the program unusable, and eventually leading to a crash. 

I cant replicate this with any other artist so far. 
I Cant find out how to get Verbose Faishin logs, please advise if there is a way to do this. 

![Feishing V0 8 1 Bug](https://github.com/user-attachments/assets/0d94e056-5b77-4282-bf43-3a1e9b661968)
![Feishing V0 8 1 Bug2](https://github.com/user-attachments/assets/1c8128a7-c3c2-4ec5-bc8c-79770f532d54)
![Feishing V0 8 1 Bug3](https://github.com/user-attachments/assets/95cda34d-b898-4f8d-a6da-6e4011d8830f)

### Steps to Reproduce

1. Open Feishin V0.8.0 or V0.8.1 
2. Select the Artist "African Imperial Wizard"
3. The page loads and the Top Songs expands until it crashes. 

### Context

This only seems to effect this one artist on V 0.8.0 and 8.1. I cant replicate this on any other artist at this time. 
This loops different songs every time. 

Fault Finding Done
Testing on 0.7.3 works correctly. 
Testing on 2 windows desktops. Both have the same issue through Local connection and External. 
Moved the folder out of the monitored directory. Re-scanned Navidrome, then added the files back. Same issue. 
To my knowledge, there is no odd Metadata. 
Logs on Navidrome or Feishin don't show anything. 

I spun up a docker container to test this with the below settings. 
I could replicate on V0.8.0 and V0.8.1 but not V0.7.3

docker run --name feishin -p 9180:9180 ghcr.io/jeffvli/feishin:latest

### Application version

V0.8.0, V0.8.1

### Operating System and version

Windows 11 (10.0.22631.4037) & Docker

### Server and Version

Navidrome 0.52.5

**Comment by Blavkentropy1** [comment]
Found another Band. 
I suspect this is due to it having special characters in the title. 
Artist
ᚾᛟᚢ ᛁᛁ // ᚦᛟᚦ ᚷᛁᚷ
![Feishing V0 8 1 Bug4](https://github.com/user-attachments/assets/44a6cda6-0d3c-4a6f-bdb1-0339c21fd3fe)

**Comment by jeffvli** [comment]
The console message indicates that it's erroring due to duplicate rows.

I believe it's due to changes made in https://github.com/jeffvli/feishin/pull/707 with the changes made in how row ids are calculated in the top songs list.

The fetched data should probably be filtered to remove any duplicate entries before it's rendered.
@kgarner7 Can you take a look?

**Comment by kgarner7** [comment]
https://github.com/jeffvli/feishin/commit/e6bd8deb0c19b17186eac33581ee587009b5cc1f
