### ISSUE TITLE
Broken title bar button on Home

### ISSUE THREAD

**Issue by fuyarde** [jeffvli/feishin#73]
Hello, 

There is a small problem on the Home page.
The `mantine-1q7k2b3` div doesn't have enough `padding-top`, which means that the title bar buttons are above the slider.

![image](https://user-images.githubusercontent.com/21694620/229838209-6a3ce005-fa25-450b-ab83-9a975ac866ac.png)

___

Setting `padding-top: 5rem` instead of `3rem` solves the problem.

![image](https://user-images.githubusercontent.com/21694620/229840200-debd2564-ebdf-4150-a890-e97efa0f8084.png)

## Your Environment

- Application version : `0.0.1-alpha6`
- Operating System and version : `Fedora 37 x86`

**Comment by jeffvli** [comment]
Was resolved in 0.1.0.
