### ISSUE TITLE
Scrolling in playlist view (not full playlist) of smart playlists in certain cases yields bad listings

### ISSUE THREAD

**Issue by thebiblelover7** [jeffvli/feishin#733]
### Expected Behavior

Feishin should show the playlist sorted all at once.

### Current Behavior / Steps to Reproduce

As you can see in the following recording, when scrolling through the playlist page (not the full playlist page) of a **smart playlist**, the sorting gets a bit messed up.

https://github.com/user-attachments/assets/598e11e1-4fd3-40d4-9fd1-bb59d8ae9c47

I assume it may have to do with setting the sorting to "random"...

<img width="386" alt="Screenshot 2024-09-08 at 7 33 40 PM" src="https://github.com/user-attachments/assets/a857a42a-a60a-4634-8add-e82845ea8aeb">

### Possible Solution

For smart playlists that yield different results on every query (e.g., sorting=random), load the whole playlist when loading the playlist page.

### Application version

v0.8.0

### Operating System and version

MacOS Ventura 13.6.3

### Server and Version

Navidrome v0.52.5

**Comment by kgarner7** [comment]
See: https://github.com/navidrome/navidrome/pull/3244 (this also impacts Navidrome's own UI)

**Comment by kgarner7** [comment]
It has been merged, new Navidrome release probably this week

**Comment by thebiblelover7** [comment]
Perfect, thanks!
