### ISSUE TITLE
Volume level equalizer

### ISSUE THREAD

**Issue by fze015** [jeffvli/feishin#734]
### What do you want to be added?

Musics does not always have the same level of sound, which can be very annoying.

I think adding a setting that would equalize the volume level of music would be helpful.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
This already exists: it's called ReplayGain. This works in Navidrome if you have your files tagged with replaygain, and Jellyfin if you either have files tagged with track gain (that's all it uses) or enable LUFS scan.
I've added https://github.com/jeffvli/feishin/commit/e2a05f4204c42e74ec185e7078688d4c316e79fa to support normalized gain, which is apparently new in 10.9.
