### ISSUE TITLE
Add Playlist button to collapsible side bar

### ISSUE THREAD

**Issue by adam-tj** [jeffvli/feishin#737]
### What do you want to be added?

Currently there is a button which opens a list of playlists with the regular side bar.
![image](https://github.com/user-attachments/assets/5fc4d67b-9913-424b-bacf-79849971edd1)
There is no equivalent button with the side bar collapsed.
![image](https://github.com/user-attachments/assets/ec5fe53b-fc49-4cfd-9a44-054c0e7503ba)

I think this would be a nice addition

### Additional context

Jellyfin server, I don't use Navidrome so I can't confirm if it is a server-specific issue or not.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
This is possible. Settings > General > Sidebar configuration, and select playlist
