### ISSUE TITLE
Feature: localization

### ISSUE THREAD

**Issue by YunchaoZheng** [jeffvli/feishin#74]
## What do you want to be added?

Has localization been planned for feishin yet?

What about anyone just comment here with your language who wanted to contribute
And wait for localization framework set up

**Comment by jeffvli** [comment]
It is planned, but most likely coming after I have finalized the overall app design (after alpha).

I don't want to prematurely add localization since it is possible that there will be large changes to the existing text which will cause frequent re-translations.

**Comment by WarlockFish** [comment]
![图片](https://github.com/jeffvli/feishin/assets/30708115/c5b746b9-d502-4e82-9d0a-5e719ef964e9)

 Is this function completed?  This option is not optional

**Comment by 7Adrian** [comment]
I can help create Polish localization after you finish implementation if needed.
