### ISSUE TITLE
When displayed below album information and above tracklist, comments do not recognise line breaks

### ISSUE THREAD

**Issue by emes81** [jeffvli/feishin#740]
### Expected Behavior

Line breaks should be shown

### Current Behavior

Here's an example of how things look in Navidrome's web client:

![image](https://github.com/user-attachments/assets/6a9f9918-5b44-4e43-86cb-00268fff8af1)
![image](https://github.com/user-attachments/assets/8a253958-239f-4351-aad1-c52ff4d42430)

This particlar album is a one-track mix, with the tracklist and additional info added as a comment. The text is very long, but easily navigable.

Here's the same in Feishin:
![image](https://github.com/user-attachments/assets/ddd29457-d82c-4ccb-a028-bbc9af505e7f)
![image](https://github.com/user-attachments/assets/57ff9881-afc1-4f34-bb7a-a5b538f1bb9a)

Line breaks are no longer visible. This results in the tracklists being essentially unusable, and the paragraphs of text also are likewise difficult to read.

### Steps to Reproduce

1. Tag all audio files in an album with a comment. The comment must contain line breaks (e.g. a tracklist)
2. Add said album to Navidrome instance
3. Refresh recently added in Feishin client linked to Navidrome instance and check the comments - line breaks are not shown

### Context

Trying to read a longer piece of text and tracklists embedded in album tags. Lack of line breaks makes reading this info in Feishin difficult to impossible

### Application version

0.8.1

### Operating System and version

Arch/Gnome 46/Flatpak app

### Server and Version

Navidrome v0.52.5

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/8221af9a8f3eb726022f070d9d181b786273618a
