### ISSUE TITLE
"Play shuffled" does not actually switch to the correct song when it's playing other songs

### ISSUE THREAD

**Issue by OriginCode** [jeffvli/feishin#741]
### Expected Behavior

"Play shuffled" should recreate the queue and play the first song in the queue.

### Current Behavior

It shows the song of the new queue but still plays the previous one.

### Steps to Reproduce

1. Play any song
2. Choose "Play shuffled" from the context menu of any album/playlist.
3. It's now playing the previous song but showing the new one at the bottom.

### Application version

v0.9.0

### Operating System and version

Linux (AOSC OS 11.5.2 amd64, Sway (Wayland))

### Server and Version

0.52.5

**Comment by kgarner7** [comment]
https://github.com/jeffvli/feishin/commit/660c9744bf44de230727f3b75ea7555e63ad02ec, thanks for the report
