### ISSUE TITLE
Metadata lyrics show on Navidrome but not on Feishin

### ISSUE THREAD

**Issue by DaInfLoop** [jeffvli/feishin#745]
### Expected Behavior

Lyrics added via the `Lyrics` metadata field should show up on Feishin's lyrics page, as lyrics are fetched straight from Navidrome.

### Current Behavior

The lyrics don't show up on Feishin, however they do so on Navidrome's web interface.

Images (both are seeked to 0:57)

Web interface:
![image](https://github.com/user-attachments/assets/c85074fa-bea8-4f73-ac5f-c03fde009f76)

Feishin:
![image](https://github.com/user-attachments/assets/a69f9628-adc7-412c-bf06-6634300528e1)

### Steps to Reproduce

1. Add lyrics from a *.lrc file to the Lyrics metadata field to an mp3 file.
2. Play the song in Navidrome's web interface and enable lyrics. The lyrics set should show up.
3. Play the song in Feishin, use the full-screen player and go to the lyrics tab. The lyrics set do not show up.

### Context

The song I'm writing lyrics for doesn't exist on Musixmatch and therefore there are no lyrics on Spotify, so when Navidrome tries to fetch the lyrics, it can't. I add the lyrics metadata field since Navidrome doesn't support *.lrc files at the moment, and Feishin doesn't seem to recognise it.

### Application version

0.9.0

### Operating System and version

Ubuntu 22.04.03 LTS

### Server and Version

Navidrome v0.52.5

**Comment by kgarner7** [comment]
There are a number of things that could be happening.
1. Please try clearing your cache (Settings > General > Clear feishin cache)
2. Please report the results of `getLyricsBySongId` on the lyrics tab. Specifically, _after_ clearing the cache, please open browser devtools (hamburger > Open browser devtools) and navigate to the network tab _prior_ to opening the lyrics tab.

Alternatively, if you can share the file I can also test to see why it might not be showing properly.

**Comment by DaInfLoop** [comment]
Hi sorry, I have this really bad thing where I forget that I haven't responded to things.

I did refresh feishin's cache and it worked. Thanks for helping :)
