### ISSUE TITLE
0.0.1-alpha6 - Macos m1 13.2.1 (22D68) - no playback, can't alter settings SOLVED

### ISSUE THREAD

**Issue by greenfishgit22** [jeffvli/feishin#75]
## Expected Behavior

Being able to choose settings and playback

## Current Behavior

No option of adding any settings or picking the path to mpv location. No playback of audio working.

Screenshot of setttings, no option of changing anything, everything is a blank

https://ibb.co/K5S4cqz

![Uploading 2023-04-05_14-55.png…]()

I'm not sure if this is relevant but when I downloaded the package it said "package corrupt or damaged" the .dmg file. I tried several times to re-download it but I got the same message. 

Had to use this command in order to get Feishin up and running on macos

sudo xattr -r -d com.apple.quarantine /Applications/Feishin.app

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Application version :
- Operating System and version :
- Node version (if developing locally) :

**Comment by jeffvli** [comment]
All of the options should be visible on the right-hand side of the page. Are those hidden for you? Your screenshot doesn't show it, but are they being blocked by the open queue window?

![image](https://user-images.githubusercontent.com/42182408/230223125-0bc54ba9-c1d5-4190-aab1-b5ae418f2ecb.png)

**Comment by greenfishgit22** [comment]
Yeah you're right, it was the queue window blocking settings. The only way for me to get audio is if I choose web player. Audio wise are there any difference between mpv vs webplayer? The path to my MPV is correct but no sound. Thanks for the prompt response!

**Comment by jeffvli** [comment]
MPV allows for gapless audio, replaygain (if your files are tagged), among other benefits.

Once you set the MPV path, you'll need to do a full restart of the app to reload the player. Make sure the app fully closes before starting it again (also, performing a reboot of your machine will force it to close if the previous doesn't fix it).

**Comment by greenfishgit22** [comment]
> MPV allows for gapless audio, replaygain (if your files are tagged), among other benefits.
> 
> Once you set the MPV path, you'll need to do a full restart of the app to reload the player. Make sure the app fully closes before starting it again (also, performing a reboot of your machine will force it to close if the previous doesn't fix it).

I did that. If I use mpv as audioplayer there's no sound and the track never starts, it sits at 00.00

Here's a screenshot of my settings https://ibb.co/5LWkvKp

Tried re-adding mpv, restarting application and my macbook

Thanks

**Comment by jeffvli** [comment]
The issue seems to be that you're trying to use the `.exe` mpv application, which is for Windows only.

You'll need a m1 macOS compatible version of mpv, which seems to require building the app yourself. I don't own an m1 mac so I can't really help with debugging this, but here's some documentation I found after doing a quick search: https://gist.github.com/dbrookman/74b8bcfb37a23452f7137b83bca9580f

**Comment by greenfishgit22** [comment]
I have built the required mpv application for macos on  previous versions. I just re-installed mpv for mac and now it works :)

Thank you so much for this excellent application and for your kind support!

Issues solved!
