### ISSUE TITLE
Wrong song order in queue when playing an album from the home page.

### ISSUE THREAD

**Issue by K0SS4** [jeffvli/feishin#752]
### Expected Behavior

When I click on play on an album from the home page(like recently played) it should play the songs according to track numbers.

### Current Behavior

I don't know how it sorts it because the order is persistent but wrong. Here's an example:

Track order of the album:
![image](https://github.com/user-attachments/assets/7ebdbbb2-39fe-428c-b063-e26fc64e2ee7)

When I click play from the home page:
![image](https://github.com/user-attachments/assets/10a73574-0017-4e4c-abe5-f5e3e5bc93b4)

The first song matches but then it goes out of order.  This seemingly random order is persistent across application restarts.

### Steps to Reproduce

Check the order of an album and then click play from the home page:
![image](https://github.com/user-attachments/assets/36f93fec-dd5a-4e2f-b835-04c95383974f)

The order should be incorrect.

### Application version

0.9.0

### Operating System and version

Windows 11

### Server and Version

Navidrome 0.53.1

**Comment by K0SS4** [comment]
I checked and it works fine on: [feishin.vercel.app](https://feishin.vercel.app/).

I will also check on the linux desktop app later.

**Comment by kgarner7** [comment]
See https://github.com/jeffvli/feishin/discussions/751
