### ISSUE TITLE
Bug: Volume is not correct after restart

### ISSUE THREAD

**Issue by YunchaoZheng** [jeffvli/feishin#76]
## Expected Behavior

If VolumeUI is set <100%, then it should do so after restart

## Current Behavior
Set VolumeUI <100%, 40% e.g.

But Feishin will always play as 100% volume everytime restart

Need to addjust volume again to get back to correct volume.

## Steps to Reproduce

1. Set the volume <100%, 40% for example

2. Restart Feishin

3. Play any thing

4. In the UI it displayed as 40%, but **indeed playing as 100%**, as in this screen snip 

<img src="https://user-images.githubusercontent.com/53668768/230299851-2921d69e-c51c-4003-9cf9-163310fefe72.png" width=500 hight=300></img>

## Possible Solution (Not obligatory)

Read the volumeUI after startup

## Context

This is not serious bug, but fix it will improve user experience

## Your Environment

- Application version : Feishin-0.0.1-alpha6-win-x64.exe
- Operating System and version : Windows 11 22H2 22621.1344
- Node version (if developing locally) : Release channel

**Comment by manuel-rw** [comment]
This is a serious issue for me. I always forget and blast my ears on 100% volume. I am using Sonixd for now, until this is fixed :)

**Comment by jeffvli** [comment]
Sorry about that. I think I found the issue.. should be fixed in the next release which is coming soon.

**Comment by manuel-rw** [comment]
Thanks for the quick reply. I'll try it out, as soon as it comes out. Thanks!
