### ISSUE TITLE
Side-Scrolling Volume Control Only Increases Volume

### ISSUE THREAD

**Issue by jamie6king** [jeffvli/feishin#761]
### Expected Behavior

When using a mouse with a side-scroll wheel (e.g. MX Master 3s) on the volume control in the bottom-right, it should change based on the direction of the scroll wheel (e.g. down decreases volume, up increases volume).

### Current Behavior

When using a mouse with a side-scroll wheel (e.g. MX Master 3s) on the volume control in the bottom-right, it only increases volume. Both scrolling down and and up increases the volume.

### Steps to Reproduce

1. Get a mouse that has a side-scrolling wheel.
2. Play a song.
3. Try and adjust the volume by hovering over the volume control and use the side-scroll wheel.
4. It only increases.

### Application version

v0.9.0

### Operating System and version

MacOS 14.6.1

### Server and Version

Navidrome v0.53.3

**Comment by kgarner7** [comment]
https://github.com/jeffvli/feishin/commit/a89b6640a921e5e60e0ecb46cc1c5588008f9295
