### ISSUE TITLE
Remote Control API

### ISSUE THREAD

**Issue by tessamerrill** [jeffvli/feishin#763]
### What do you want to be added?

Allowing external programs / devices to control playback.

### Additional context

I know the Remote Control Server exists, however there is no API documentation for interfacing with it.

This would be useful for controlling via a Stream Deck.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
You're in luck, someone just built a stream deck plugin: https://github.com/jeffvli/feishin/issues/713

**Comment by kgarner7** [comment]
The types are formally defined in https://github.com/jeffvli/feishin/blob/development/src/remote/types.ts (client requests and server events). The one detail is if you specify username/password, you need to authenticate using `authenticate` with the header being the value of a [Basic Auth header](https://en.wikipedia.org/wiki/Basic_access_authentication), so `Basic base64(username:password)`
