### ISSUE TITLE
Playing album doesn't play tracks in order

### ISSUE THREAD

**Issue by yashaskm11** [jeffvli/feishin#764]
### Expected Behavior

Clicking play button on album should play all tracks in order 1-n

### Current Behavior

Clicking play button on album plays tracks in random/shuffle

### Steps to Reproduce

From home screen / albums section, click play button on any album.

### Possible Solution

Seemed to be an issue recently, was working fine on previous versions (not sure exactly which version).

### Context

Trying to play album in order, requires to go to album details page and then click on play button.

### Application version

v0.9.0

### Operating System and version

Windows 10

### Server and Version

Navidrome 0.53.2

**Comment by jeffvli** [comment]
Navidrome 0.53.2 [changed the names of their sort mappings in their internal API](https://github.com/jeffvli/feishin/pull/754).

New release soon.
