### ISSUE TITLE
Playback Speed resets to 1.00x on app startup even though the UI shows 1.25x

### ISSUE THREAD

**Issue by qstar-inc** [jeffvli/feishin#769]
### Expected Behavior

The playback speed to be set to the value used in previous session, or the UI value should be same as actual speed.

### Current Behavior

The playback speed resets to 1.00x even when UI shows 1.25x.

### Steps to Reproduce

1. Set Playback Speed to 1.25x
2. Starts playing at 1.25x
2. Restart app
3. See Playback Speed at 1.25x
4. Starts playing at 1.00x

### Application version

0.10.1

### Operating System and version

Windows 11 desktop

### Server and Version

Navidrome 0.52.5

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/ecef9bea5efd3577d909ecce0208b65d9e304a27
