### ISSUE TITLE
No Audio Output

### ISSUE THREAD

**Issue by simulans** [jeffvli/feishin#771]
### Expected Behavior

Audio will output to speakers

### Current Behavior

Audio files play and show progress, but there is no speaker output. System audio and other applications are working as expected. Able to play from server webui without issues. There is no notable console output.

### Steps to Reproduce

- Start Feishin
- Play song

no settings were changed - audio device is set to default, 
only known difference is the application upgraded to 0.10.1
tested setting audio device manually, no change

### Application version

0.10.1

### Operating System and version

Void Linux

### Server and Version

Navidrome 0.51.1

**Comment by simulans** [comment]
Is this related to the change in v0.10.0?

---
Important for Navidrome: v0.10.0 removes support for Navidrome < v0.53.2 due to sort mappings changing in its API.
---

**Comment by iiPythonx** [comment]
That change wouldn't affect your audio output, it only changes the sort mappings (ie how feishin sorts your tracks, albums, etc.). If you're using the web player, try switching to mpv (or switching to web if you're on mpv already), there have been known scenarios where the web player acts strangely.

**Comment by simulans** [comment]
I had upgraded Navidrome to 0.53.3 before I saw your response.

I did not have mpv installed, but installed it and switched which seems to work. The web player still does not. Is mpv necessary to use the application?

**Comment by iiPythonx** [comment]
It isn't required, no, more testing would have to be done to figure out why the web player isn't functioning (could be audio codecs, etc). Maybe @kgarner7 could be of some help to you, considering he does most of the web audio related components.

**Comment by kgarner7** [comment]
You can disable web audio (Playback > Use Web Audio), as I've seen a few cases of some files not playing properly (as far as I can tell, files with more than two channels). I'm personally unable to reproduce this as I don't have any setup for that.

**Comment by simulans** [comment]
I just tried that again, and it there still isn't any output. I can use mpv for now, but is there anything I can provide to help debug? I couldn't find any log files on my system.

**Comment by kgarner7** [comment]
> I just tried that again, and it there still isn't any output. I can use mpv for now, but is there anything I can provide to help debug? I couldn't find any log files on my system.

By disable web audio, I _specifically_ mean use web audio, but deselect "Use web audio". That'll help narrow down if it's specifically a [Web Audio](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) issue, or whether it just can't be played in the browser at all. What kind of file are you trying to play?

**Comment by simulans** [comment]
It's any tracks at all, varied bitrate mp3s and flacs. Everything should only be two channel. I did try switching off 'use web audio' before I commented last. It did not seem to have an effect. I was using mpv fine, but this morning it is no longer playing any tracks using either mpv or web audio. Other applications and my navidrome web player are outputting audio as expected.

Update: mpv worked again after restarting the system.

**Comment by simulans** [comment]
I'm not sure if it was due to the upgrade to 0.11.0, but neither mpv nor web options have output currently.

As before, other web pages including my navidrome server work fine, and mpv itself works fine. The restart that got mpv working again last time did not change anything this time.

Are there any logs or information I can provide that would help debug?
