### ISSUE TITLE
"Play Next" feature

### ISSUE THREAD

**Issue by Celibistrial** [jeffvli/feishin#774]
### What do you want to be added?

![image](https://github.com/user-attachments/assets/37094eb8-1d41-4e38-bebe-20b666f892aa)
Could you add a "Play Next" button to the menu, which moves a selected song to the next position in the playlist, rather than having to manually drag it.

 Not sure if i have articulated it well but what i mean is suppose i am playing a playlist with songs 1 to 100, if i am playing song 30 currently there is no way to play song 40 next(well there is but i have to manually drag it all the way). There should be a button that moves the selected song to play next

Thank you

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by TrevTV** [comment]
I'd also love this feature, I implemented my own version (likely very poorly) but gave up on maintaining it since I didn't feel like merging updates :P

Here it is in case it helps with development
https://github.com/TrevTV/feishin/commit/2bc7b77a94561c3243c0da00e8bddbf097128a8b

**Comment by Celibistrial** [comment]
@TrevTV Nice work! 
Would it be possible for you to create a release from your fork? (so that i can install it)
I tried forking your repo and getting github workflow to create a release for linux but for some reason it wouldn't publish the linux.tar.gz files.

**Comment by jeffvli** [comment]
@Celibistrial You need to update the `publish` configuration under `build` in the root package.json file to point to your repo.

@TrevTV If you want to put your commits on a fresh branch and submit a PR, we can go through a review to get it merged.
