### ISSUE TITLE
macOS arm64 version reported as damaged

### ISSUE THREAD

**Issue by Rob0xFF** [jeffvli/feishin#776]
### Expected Behavior

macOS arm64 version should open on Apple Silicon Macs.

### Current Behavior

macOS arm64 version ist reported as damaged and therefore does not start. intel64 version works with Rosetta.

### Steps to Reproduce

1. Download current arm64 build for macOS
2. Double click on the app symbol

### Application version

v0.10.1-arm64

### Operating System and version

macOS 15.0

### Server and Version

Navidrome 0.53.3 (13af8ed4) @ umbrel

**Comment by jeffvli** [comment]
Check the pinned issues: https://github.com/jeffvli/feishin/issues/104

**Comment by Rob0xFF** [comment]
Okay, thank you, I missed this. I am used to activate non signed applications via the system preferences.
