### ISSUE TITLE
ALAC files do not play in web audio player

### ISSUE THREAD

**Issue by EmmaKnijn** [jeffvli/feishin#779]
### Expected Behavior

I'd expect ALAC files to also play in the web audio player.

### Current Behavior

Now the song stays static and never starts when attempting to play a song that is in ALAC.
The song does play when in MPV mode.

Mediainfo from the file, it is in the m4a container
![image](https://github.com/user-attachments/assets/420c2fc6-ab2d-4b83-83f8-25bb4487cb5a)

### Steps to Reproduce

1. Play a song that is ALAC (like an Apple Music rip)
2. Observe bug

### Possible Solution

Somehow implement support for ALAC in the web player component

### Application version

0.9.0

### Operating System and version

Windows 11 Dekstop

### Server and Version

Navidrome 0.52.5

**Comment by pyxfluff** [comment]
This is probably intended due to how Electron's audio player works, idk how much they can do about this

**Comment by jeffvli** [comment]
ALAC isn't supported in browser html/web audio (except for Safari apparently). The desktop app uses Electron which runs on Chromium.

To use the web player for your ALAC files, you will need to enable transcoding for ALAC files within Navidrome and apply it to the player instance created by Feishin. (All configuration needs to be done within the Navidrome web ui).

**Comment by kgarner7** [comment]
> ALAC isn't supported in browser html/web audio (except for Safari apparently). The desktop app uses Electron which runs on Chromium.
> 
> To use the web player for your ALAC files, you will need to enable transcoding for ALAC files within Navidrome and apply it to the player instance created by Feishin. (All configuration needs to be done within the Navidrome web ui).

I would like to point out you can also transcode in Feishin itself. But regardless, ALAC is not generally supported. If you still want lossless, I would recommend converting to something like FLAC

**Comment by EmmaKnijn** [comment]
How do I configure transcoding within Feishin? I'd like to do this by default on a self hosted instance of Feishin with Docker

**Comment by kgarner7** [comment]
Settings > Playback > enable transcoding, then type a format that you want to transcode to (most likely, mp3; Navidrome by default only supports `mp3` and `opus`, but you can add others). There's no way to make this a default.
