### ISSUE TITLE
Clicking "Play" or "Add Last" on albums sometimes adds the tracks to the queue out of order

### ISSUE THREAD

**Issue by ryankupk** [jeffvli/feishin#782]
### Expected Behavior

When playing an album by clicking the play symbol on the album cover, or by clicking the 3 dots and selecting "Play" or "Add Last", all tracks are played in order by track number 

### Current Behavior

Tracks are *sometimes* added to the queue in order, and sometimes are added with the first track at the end of the queue and the remaining tracks at the start. For example instead of 
1. Track 1
2. Track 2
3. Track 3

They're instead in the queue as 
1. Track 2
2. Track 3
3. Track 1

This doesn't happen every time, and I haven't been able to figure out when or why it happens. I tested in the browser and wasn't able to replicate it, but I'm not sure if that's just because it hasn't happened *yet* from my basic testing or if it wouldn't happen at all. 

### Steps to Reproduce

Click the play button on an album from the home screen or album search OR click "Play" from the 3 dot menu OR click "Add Last" from the 3 dot menu

### Context

![image](https://github.com/user-attachments/assets/5bffb3bb-721f-4b63-b82d-e455e158d239)
![image](https://github.com/user-attachments/assets/9b7e7502-35a0-47a1-b939-78ec735dbed4)

Play button behavior is set to "Play" and not "Play Shuffled", and shuffle is not selected in the player bar.

I tried doing a soft and hard reset of the cache from the settings and can still reproduce. 

### Application version

0.9.0

### Operating System and version

Windows 11 desktop

### Server and Version

Navidrome 0.53.3

**Comment by kgarner7** [comment]
See #764. You need to update to 0.10 or newer.

**Comment by ryankupk** [comment]
> See #764. You need to update to 0.10 or newer.

Shoot, thanks for linking to that. I tried looking through the issues and didn't see this, I don't think I was looking at closed issues though. 

I guess the real question is why my client wasn't updated from 0.9.0 but maybe that's on me
