### ISSUE TITLE
Excessive GPU usage on fullscreen player

### ISSUE THREAD

**Issue by pohuing** [jeffvli/feishin#783]
### Expected Behavior

Feishin shouldn't use 30-50% of a Rx 6900xt to animate a playing indicator with a dynamic background.
Similarly, playing music shouldn't cause my laptop to take off.
### Current Behavior

This happens in Firefox and Edge(so probably all Chromium based browsers) on AMD and Intel iGPUs.

Playing music with dynamic background enabled and with the "Up Next" tab visible causes excessive GPU usage. 
This only happens if the Browser is the active window.
The GPU usage scales with window size and refresh rate. 
My screenshots are on a 1440@240hz screen. On a system with a Rx6900xt as the GPU.

![grafik](https://github.com/user-attachments/assets/17d22dc6-7548-4e9a-b8e3-41487d9cfb80)

![grafik](https://github.com/user-attachments/assets/16ff50bf-1c99-44ad-a92c-8046c6de02f2)

### Steps to Reproduce

1. Play any song
2. Navigate to the fullscreen player
3. Enable "Dynamic background"
4. Observe GPU usage in Task Manager/gputop/whatever MacOS has

### Possible Solution

I believe the issue is caused by the animation of the now playing indicator. An option for a non animated indicator would alleviate the issue.

In the same vein, feishin does not respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion). So this could be a two in one fix with a toggle that defaults depending on the query.

### Context

Ultimately my goal is just to have a colder laptop. This isn't a big deal since the browser playing feishin is usually not focused anyways.

### Application version

10.1

### Operating System and version

Windows 10-11

### Server and Version

Jellyfin 10.9.11

**Comment by jeffvli** [comment]
Thanks for opening this issue.

You're right, after testing it myself I noticed any playing indicator causes the GPU usage to go up by a considerable amount. Apparently animating SVGs quite expensive for the GPU. I'll see about the changes to respect `prefers-reduced-motion` for the indicator as well as possibly converting the svg to a gif instead.

**Comment by jeffvli** [comment]
I've opted to just remove the animated icon for now. I considered making it a gif, but I realized that it wouldn't be color customizable with the app theme due to its static nature.

**Comment by ENDlezZenith** [comment]
> I've opted to just remove the animated icon for now. I considered making it a gif, but I realized that it wouldn't be color customizable with the app theme due to its static nature.

Just a thought, probably adding an option for switching on/off whether to use the animation (default value off), thus letting the user to consider the GPU performance trade off by themselves as a workaround or so?

**Comment by jeffvli** [comment]
> > I've opted to just remove the animated icon for now. I considered making it a gif, but I realized that it wouldn't be color customizable with the app theme due to its static nature.
> 
> Just a thought, probably adding an option for switching on/off whether to use the animation (default value off), thus letting the user to consider the GPU performance trade off by themselves as a workaround or so?

Yeah, I'll probably just re-add it with a toggle and add a description about performance issues.

**Comment by ENDlezZenith** [comment]
> > I've opted to just remove the animated icon for now. I considered making it a gif, but I realized that it wouldn't be color customizable with the app theme due to its static nature.
> 
> Just a thought, probably adding an option for switching on/off whether to use the animation (default value off), thus letting the user to consider the GPU performance trade off by themselves as a workaround or so?

30% on an RX 6900 XT, astonished by how SVG could cause such big performance problem. Actually, interesting that no one has noticed this performance deteriorate before. I wouldn't notice that even it is 100% GPU (100% if the SVG is in screen, 0% if scrolled to bottom so that it's not) for me until this issue has been posted. Could it be a wrong readout provided by Windows?

**Comment by DrENDzZ** [comment]
Could it be a wrong readout provided by Windows or something? Just a thought since there is no lagging performed and also operations are still really fluent and responsive.

**Comment by ENDlezZenith** [comment]
Could it be a wrong readout provided by Windows or something? Just a thought since there is no lagging performed and also operations are still really fluent and responsive.

**Comment by pohuing** [comment]
I think the reason it wasn't noticed is because it's hard to notice. The issue only occurs if the window is in focus. So other interactive applications with high gpu usage(ie games) aren't at the forefront of a user's mind.
I only noticed it because my laptop was thermal throttling again during builds. So considering that's how I noticed I doubt it's a faulty readout. I'll check the reported power usage later to be sure

**Comment by pohuing** [comment]
> 30% on an RX 6900 XT, astonished by how SVG could cause such big performance problem. Actually, interesting that no one has noticed this performance deteriorate before. I wouldn't notice that even it is 100% GPU (100% if the SVG is in screen, 0% if scrolled to bottom so that it's not) for me until this issue has been posted. Could it be a wrong readout provided by Windows?

It's in conjunction with blurring a background 240 times a second at 1440p remember. If you don't have dynamic background enabled the gpu load only goes to ~6%.

**Comment by ENDlezZenith** [comment]
True, I agree. Made another little test. I've switched to use the iGPU and found that the page toggle to Fullscreen Player is really laggy in 0.10.1 comparing to a fluent transition in 0.11.0

**Comment by 2048khz-gachi-rmx** [comment]
I know the indicator has been removed and all, but I can't reproduce it on an RX 6600, or at least the usage isn't _that_ bad, neither in the electron app nor in firefox/brave (= chromium) at commit c7214fc (0.10.1 release, at the time of this issue)


https://github.com/user-attachments/assets/baec65c6-9c15-44d8-87f2-a456e703604f
