### ISSUE TITLE
Being able to resume the session/queue after restart

### ISSUE THREAD

**Issue by goyban** [jeffvli/feishin#786]
### What do you want to be added?

After restarting the OS or the app Feishin doesn't remember the last playing queue.
It would be really good if I could open it and just continue listening to what I was listening before closing it but this is how it looks like when I open it again:

![image](https://github.com/user-attachments/assets/9e8f7aa5-eab2-44d4-9c1d-e5ac4f3142b0)

P.N.: I'm not sure if this is related to Jellyfin or not, I couldn't find anything in the issues or settings.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by kgarner7** [comment]
Settings > General > Save play queue. Note this requires you to manually close the application (pressing x)
