### ISSUE TITLE
On the Home page, if I click play on an album, it shuffles the album. How do I make it start from the beginning of the album?

### ISSUE THREAD

**Issue by nothing2obvi** [jeffvli/feishin#787]
### Expected Behavior

If I click play on an album, from the Home page, I expect it to play the album from the beginning.

### Current Behavior

The album shuffles.

### Steps to Reproduce

1. Go to Home page
2. Click play on an album
3. Album shuffles

### Possible Solution

Feishin may not be honoring the `Play button behavior` which is set to `Play`.

### Context

I could still click on the actual album and press play from there, at which point, it plays from the beginning. However, I would like albums to play from the beginning when I click on them from the Home page.

### Application version

0.7.1

### Operating System and version

MacOS Sonoma 14.5

### Server and Version

Navidrome v0.53.3

**Comment by kgarner7** [comment]
See #764. You need to update your application to latest.

**Comment by nothing2obvi** [comment]
Thanks, I just updated and it's fixed.

**Comment by kgarner7** [comment]
I've also gone ahead and just pinned it, a couple of people missed it. Cheers!
