### ISSUE TITLE
Incorrect year is showing in the Album menu

### ISSUE THREAD

**Issue by Blavkentropy1** [jeffvli/feishin#794]
### Expected Behavior

The Year set in the ID3 tags is shown as 2024 or the date (if set)

### Current Behavior

The year is shown as "Dec 31 20xx" 
If 2024, it will be Dec 31 2023, if release year is 2023 it will show Dec 31 2022 etc. 

Nothing stands out in the Dev tool menu regarding this.  No errors are shown in the console. 

![image](https://github.com/user-attachments/assets/79cecc66-8449-4d6f-868a-6fc964d73b15)

### Steps to Reproduce

1. Open Feishinon Windows
2. Open a any Album. 
3. The year is shown as Dec 31, 2023 (Or Minus one year from the release year)

![image](https://github.com/user-attachments/assets/11b24df5-1883-4f94-8e73-e32858f22aa3)

### Context

Year is shown incorrectly in that one field.  It seems to be anchored to Dec 31 rather than January 1st. 
Columns, Full Screen player all show correctly. I have not seen the incorrect date show anywhere else except the album window.  
![image](https://github.com/user-attachments/assets/c7c546e4-28e0-40c8-91a5-52eed134cd9d)

Example of 2020 album showing 2019
![image](https://github.com/user-attachments/assets/714bdfc8-893e-4f36-a838-ec4826faf13d)

Year is shown as 2024 as confirmed in Tagscanner

![image](https://github.com/user-attachments/assets/cc090c2c-89ce-42f3-9d21-3175307efa99)

### Application version

V0.11.0 & V0.10.0

### Operating System and version

Windows 11 Business 24H2 and 11Pro 23H2. Also https://feishin.vercel.app/

### Server and Version

Navidrome V0.53.3

**Comment by jeffvli** [comment]
Thanks for the info. I pushed a fix that should hopefully resolve this.

**Comment by chr0m** [comment]
Is this fixed? I only started using feishin yesterday and I have the issue. If I have the year 2024 for an album, it shows as 31st December 2023. Maybe the fix has been done but there hasn't been a release since? Also, can we get it to just show the year if there's not a date. Even if it showed 31st December 2024 or 1st January 2024 when the year was 2024 it wouldn't be ideal 😂
