### ISSUE TITLE
Subsonic server content not loading

### ISSUE THREAD

**Issue by offobject** [jeffvli/feishin#795]
### Expected Behavior

Add server, library collection should appear.

### Current Behavior

I add the server and it says it was successful in adding it, however the library of content never loads, just an endless "loading" circle. I thought maybe it was taking a very long time to index but that doesn't seem to be the case, it just hangs up perpetually. Tried turning firewall off, no change.

### Steps to Reproduce

Download latest .exe installer, install, enter Astiga/Subsonic server info. 

### Application version

0.11

### Operating System and version

Windows 11

### Server and Version

Subsonic (Astiga)

**Comment by jeffvli** [comment]
Open the browser devtools either using the file menu in the sidebar or ctrl + shift + I and check the console and network tabs for errors.

**Comment by offobject** [comment]
Console: 
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: file:///C:/Users/###/AppData/Local/Programs/feish

Network:
Continually loads items labelled getAlbumList2. It keeps adding these in perpetuity as the loading continues.

**Comment by jeffvli** [comment]
How large is your library? The app paginates through your entire library to determine the count of items which may take a while if you have a lot.

**Comment by offobject** [comment]
390 GB. Perhaps I just haven't waited long enough. There was never any lag for Sonixd which might be confusing me. Let me leave it to run for a few hours and I'll post an update later...

**Comment by jeffvli** [comment]
It shouldn't be taking hours, but if you have a slow connection to your server it could take up to a minute. 390GB would probably be less than 10k albums which would only require around 20 network requests which ideally should be done in a few seconds. Check each network request in the devtools individually and make sure the request params are increasing the pagination offset on each one.

**Comment by offobject** [comment]
Offset, under the Payload tab, remains at 0 for each request, and if I let it it will stretch well beyond 20 requests.

**Comment by jeffvli** [comment]
Well that definitely shouldn't be happening. I'll spin up an Astiga server later and test on my side.

**Comment by offobject** [comment]
Cheers!

**Comment by jeffvli** [comment]
After some testing, it turns out Astiga is returning all their content IDs as integers rather than strings. That caused a parsing issue which in turn broke app functionality.

[Seems like they're aware](https://community.asti.ga/discussion/728/playlist-id-type-is-different-from-api-spec), but it might be a good idea to leave an additional comment there as well noting that all ids should be returned as strings.

In the meantime, I've fixed it by adding additional logic to handle it. New release incoming soon.

**Comment by jeffvli** [comment]
Also it seems like the `search3` API endpoint doesn't return any results breaks the tracks and search pages (though it may just be my astiga setup).

**Comment by gravelld** [comment]
Thanks for looking at this @jeffvli . One of our users filed the same issue: https://community.asti.ga/discussion/728/playlist-id-type-is-different-from-api-spec#latest . We'll look into this asap.
