### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Rycia** [jeffvli/feishin#8]
## Prerequisites
Note: I'm on Windows 10 Pro.
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400) _though I can't really do this because of my OS._

## Expected Behavior

Load the program without an error on Windows 10 Pro.

## Steps to Reproduce

1. Load the program for the first time.
![image](https://user-images.githubusercontent.com/43384589/213066014-ecc3552b-70bf-48db-bc60-518c3d07823f.png)

## Context
Close the socket, errors occuring in `resources\app.asr\dist\main\main.js` `14:311807, 311556, and 310576.`

Not have an error on startup.

Downloaded from the .zip of latest and threw it into a folder on an external drive.

## Your Environment

Latest Windows 10 Pro, latest alpha version with the prebuilt .zip's.

- Node version :
- Operating System and version :
![image](https://user-images.githubusercontent.com/43384589/213066317-9c4a1eb5-939e-4a78-ba1b-6de3cdd013f6.png)

**Comment by FabulousSoldier** [comment]
I get the exact same error message on Windows 11 Pro with the  **Feishin-0.0.1-alpha5-win-x64.exe** release.

**Comment by jeffvli** [comment]
I believe this error occurs if `mpv` doesn't exist on the system PATH on startup.

Are you still able to use the application after setting the mpv path?

**Comment by FabulousSoldier** [comment]
Yes, after setting the mpv path everything works fine and the error message does not appear again.

**Comment by D3viloper** [comment]
I also have the problem on macos (13.1 on M1). 
If you select "web player" in settings, you can use the app normaly. (I don't have mpv installed)

**Comment by toasty-sunbeam** [comment]
Same problem with MacOS 13.2 on an Intel chip. Selecting "Web player" in Settings makes the app work, but the error message still pops up whenever you launch the program.

**Comment by jeffvli** [comment]
Should be resolved in latest versions.
