### ISSUE TITLE
Request to add support for bilingual lyrics

### ISSUE THREAD

**Issue by py233** [jeffvli/feishin#800]
### What do you want to be added?

Request to add support for bilingual lyrics

same timeline
.lrc format below
```
[00:01.123] Original
[00:01.123] Translation
```

### Additional context

the original and the translation should be highlighted at the same time

here is a comparison of the results: 

feishin: 
![image](https://github.com/user-attachments/assets/9570f9fb-63c8-4099-8b14-e9691dc40920)

others app: 
![IMG_6321](https://github.com/user-attachments/assets/02282c5d-8b4d-4461-a17a-6aba0116949b)

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
This has already been implemented. Check the `Playback` page under settings to input your translation language, provider, and API key.

https://github.com/jeffvli/feishin/pull/747
