### ISSUE TITLE
Feishin Network Error when trying to connect to Local Navidrome Instance

### ISSUE THREAD

**Issue by Dcanadian** [jeffvli/feishin#803]
### Expected Behavior

Going to [feishin.vercel.app](https://feishin.vercel.app), I understand from the docs that you simply put in your server URL and add your credentials to connect Feishin to the server.

### Current Behavior

Unfortunately, I get a network error every time I put in my credentials
<img width="334" alt="image" src="https://github.com/user-attachments/assets/e6c66e53-a698-4250-aacf-2b07cbe273f4">
My server is currently only supporting HTTP protocols, but I saw in the docs that there was an example of a HTTP server working. I'm sure it must be a simple fix, but I'm positively baffled. Does my server have to be on HTTPS for Feishin to connect to it?

### Steps to Reproduce

1.(Go to [feishin.vercel.app](https://feishin.vercel.app), and navigate to "Add Server."
2. Input all necessary credentials, and click "Add."
3. Watch it fail and scratch your head.)

### Application version

0.11.1

### Operating System and version

MacOS

### Server and Version

Navidrome 0.52.5

**Comment by kgarner7** [comment]
As a _desktop application_? No issues. But access to localhost from other sites is often disallowed by browsers.

**Comment by Dcanadian** [comment]
Thanks for the tip - I hadn't tried the desktop app. However, I'm having no end of problems trying to download the arm64 version of the app - MacOS keeps flagging it for malware. Any tips on bypassing that? The normal "Privacy and Security" workaround doesn't work.

**Comment by kgarner7** [comment]
Check the pinned issues: https://github.com/jeffvli/feishin/issues/104
