### ISSUE TITLE
Playlist in collapsed sidebar

### ISSUE THREAD

**Issue by Wirezat** [jeffvli/feishin#814]
### What do you want to be added?

in the collapsed sidebar, there currently is no way to access the playlist. a button like the "home" or "Artist" buttons leading to a playlist page would be usefull

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
This is implemented under the `Sidebar configuration` setting in the `General` tab on the settings page.
