### ISSUE TITLE
Searching in collapsed sidebar

### ISSUE THREAD

**Issue by Wirezat** [jeffvli/feishin#815]
### What do you want to be added?

in the collapsed sidebar, there currently is no way to search for songs. having the search bar in the collapsed sidebar would be very usefull for small monitors

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
Same as #814.

You can also add a hotkey to open the search page under the `Hotkeys` tab.
