### ISSUE TITLE
Subsonic/Astiga default album art not loading

### ISSUE THREAD

**Issue by offobject** [jeffvli/feishin#816]
### Expected Behavior

Either correct album art displays or default album art displays

### Current Behavior

Some album art displays correctly while others show a broken image icon. I would be fine if it just showed some default album art rather than the icon. 
![Screenshot 2024-10-27 152133](https://github.com/user-attachments/assets/eda98747-8578-47c7-bcb6-cfc92bae678b)

### Steps to Reproduce

Connect Astiga server and open software

### Application version

0.11.1

### Operating System and version

Windows 11

### Server and Version

Subsonic/Astiga

**Comment by jeffvli** [comment]
I believe this is the same issue as #841
