### ISSUE TITLE
Smart Playlist : Apply genre filters to all song genres

### ISSUE THREAD

**Issue by ejalal** [jeffvli/feishin#819]
### What do you want to be added?

Tried to create a "Rock" smart playlist by using "Genre is Rock", but then found out that I have plenty of rubbish songs I don't wan't in that playlist, some Electronic ones who pretend to be Rock songs.

Then I added another filter with "Genre is not Electronic", with parent rule groupe to "Match all", and this didn't change anything.

Because a song can have one to many Genres, I beleive the Genre filter in Smart playlist checks against each Genre of the song independently of the other filters of type "Genre", where they should be grouped/aggregated to do the inclusion and exclusion all at once.

Another way of doing this is to apply the Genre filter also to songs already selected by the previous filters

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
Smart playlists (Navidrome-specific) are handled server side, so you'll need to create this issue in the [Navidrome repository](https://github.com/navidrome/navidrome/issues).

**Comment by ejalal** [comment]
Thanks for your replu, didn't think it was an issue with Navidrome, there's already an issue [#2708](https://github.com/navidrome/navidrome/issues/2708) on this matter there
