### ISSUE TITLE
Enhancement Request: Add Full Album to Playlist When Selecting a Track from it

### ISSUE THREAD

**Issue by thomaschampagne** [jeffvli/feishin#825]
### What do you want to be added?

Hi ! First thanks for all this this player !!

Writing this issue as a Enhancement Request to _Add a Full Album to Playlist When Selecting a Track from it_. 

💡 This a a behavior you have in many music players : **Deezer, Spotify, Navidrome, Symfonium**...

- **Currently**:  When the 4th track, "Breathing Underwater," is clicked, only this track is added to the playlist and starts playing.

  ![image](https://github.com/user-attachments/assets/da13442a-ca7e-4b0a-b66e-7b16e2153f1b)

- **Expected/Wanted**: When the same track is clicked, all tracks from the album should be added to the playlist, starting with the 4th track. This would allow the 5th, 6th, ... tracks to play consecutively.
- 
  ![image](https://github.com/user-attachments/assets/f148aae7-58c1-47bc-ba66-1d9d34954609)

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
The behavior you want already exists. Instead of clicking on the button overlaying the image, double click the row to queue the entire album.

**Comment by thomaschampagne** [comment]
Thanks a lot ! Didn't think it was actually possible :)

Thanks for your amazing work. I use feishin everyday !
