### ISSUE TITLE
When i start feshin i want to instant play music in random mode

### ISSUE THREAD

**Issue by yodatak** [jeffvli/feishin#827]
### What do you want to be added?
Thanks again for this awsome app i use it a lot but something can i think be improved
I want to be able to press by exemple play button and instant play music in random mode ( if i open feishin i want to play music i don't want to go to tracks

![image](https://github.com/user-attachments/assets/8dbf0b66-e7e3-4dff-b5a1-ae4c993d7e57)

here by exemple is grey
![image](https://github.com/user-attachments/assets/b734ffb6-6112-4a40-8f0b-293cb14a6299)

i have to go here
![image](https://github.com/user-attachments/assets/89c716d8-c63c-488e-a359-eae61219fe72)

and it alway start with the top 1 song and not in random mode

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
Use the dice button on the player bar (the last button on the right).
