### ISSUE TITLE
Change outgoing HTTP User Agent

### ISSUE THREAD

**Issue by voc0der** [jeffvli/feishin#831]
### What do you want to be added?

Seems the outgoing user agent maybe a chrome or bot variant, which makes sense given its electron. Any chance it could be customizable, so it looks like its coming from Firefox? Or maybe just give it a unique UA string that doesn't get it confused with Chrome?

### Additional context

I filter user agents at the load balancer level and it is blocking feishin.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes
- [x] No

**Comment by kgarner7** [comment]
The desktop application _is_ Chromium (Electron, specifically). Otherwise, it takes the user agent from whatever browser you use.

**Comment by voc0der** [comment]
https://stackoverflow.com/questions/35672602/how-to-set-electron-useragent

I know electron defaults to chrome, I'm just saying (many) apps make their own user string so it's clearly not confused as being chrome and the load balancer can handle it. In my case, nginx blocks all chrome identifying clients, so this app simply can't connect.

I should've included this in the first post but I respect your stance nonetheless. Thank you for replying.
