### ISSUE TITLE
BPM column should show the BPM's

### ISSUE THREAD

**Issue by octaviz** [jeffvli/feishin#832]
### Expected Behavior

The BPM column should show the BPM's of the ID3 tag file.

### Current Behavior

The BPM field is empty, my flac files all have the BPM data.

### Steps to Reproduce

No

### Application version

1.11.1

### Operating System and version

Docker NAS Synology

### Server and Version

Subsonic 6.16

**Comment by jeffvli** [comment]
The `BPM` column isn't exposed on the original Subsonic API. You would need to upgrade to a server that supports the improved [OpenSubsonic](https://opensubsonic.netlify.app/) API.

You can view a partial list [here](https://github.com/jeffvli/feishin?tab=readme-ov-file#what-music-servers-does-feishin-support)
