### ISSUE TITLE
Add "Copy Stream Url" to the right click dropdown on songs

### ISSUE THREAD

**Issue by nezsha** [jeffvli/feishin#833]
### What do you want to be added?

Niche problem, but I usually play music on my mumble server via stream urls. And since the client doesn't have an option for copying the stream url I have to log in to my web client, then search for the music and then copy the url.  
I think it's a pretty easy feature to implement.
![image](https://github.com/user-attachments/assets/fff2cff6-cea7-41ce-a4b8-d5782778e790)

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by Hushworkz** [comment]
Off-topic, but how did you get the tranclucent, colorfull background?

**Comment by nezsha** [comment]
> Off-topic, but how did you get the tranclucent, colorfull background?

I'm using i3 with picom to make windows tranclucent. And the colors just come from my asus rog background. I haven't modified feishin.
