### ISSUE TITLE
Make playlist view similar to album view

### ISSUE THREAD

**Issue by cyberwolfie1** [jeffvli/feishin#836]
### What do you want to be added?

Currently the playlist view consist of only the list of songs. From my point of view, it would be an UI-improvement to make the playlist view more similar to the album view, i.e. including the playlist image and some information about the playlist (e.g. number of songs, total play time).

Combined with #79, #746 and #835, this would make the playlist functionality pretty much complete in my eyes.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by v0id-3r** [comment]
Hi cyberwolfie1.

EDIT:
I think I just saw what you meant - so forget about my question below 😅

best regards.










-----------------------------------------------------------
Do you mean something like this in the queue window?
Original: 
![feishin_queue_original](https://github.com/user-attachments/assets/0e5b531b-b8a0-4723-b0a8-86913e1b18f8)

Custom:
![feishin_queue_custom](https://github.com/user-attachments/assets/3e24783c-dd2a-4bc9-b53f-d28032545a23)

If so you can change it here
![Abb_002458](https://github.com/user-attachments/assets/62b9463e-92d5-48c5-abc1-ba44eac88bf2)

(FYI: I am using the docker version in the web browser).

**Comment by cyberwolfie1** [comment]
No, I meant some more like the difference between these two:

Current playlist view:
![Screenshot_20241111_033027](https://github.com/user-attachments/assets/d39e4c14-3204-476d-8c19-1d41ae132b80)

Current album view:
![Screenshot_20241111_033049](https://github.com/user-attachments/assets/3066ffd1-2df4-44ef-b1fb-815909811be5)

**Comment by jeffvli** [comment]
This actually used to be the default playlist view. Due to the performance implications of potentially rendering thousands of songs in a playlist it was converted over to the default virtualized list view.

Unfortunately not planning on bringing it back.
