### ISSUE TITLE
Unable to make playlist, Add button greyed out

### ISSUE THREAD

**Issue by Anexgohan** [jeffvli/feishin#837]
### Expected Behavior

Should be able to make playlist
![Arc_nEMhsgADP5](https://github.com/user-attachments/assets/057e0110-e563-450e-90ac-400d1e8bc32c)

### Current Behavior

The Button to Add is not clickable

### Steps to Reproduce

1. Select songs
2. add to playlist
3. Add button not clickable

### Application version

latest

### Operating System and version

docker-debian

### Server and Version

jellyfin

**Comment by cyberwolfie1** [comment]
I can also not create a playlist that way. I am able to create a playlist from the playlist overview, and then add songs to it.

**Comment by Anexgohan** [comment]
> I can also not create a playlist that way. I am able to create a playlist from the playlist overview, and then add songs to it.

Where is this playlist overview?

**Comment by cyberwolfie1** [comment]
> > I can also not create a playlist that way. I am able to create a playlist from the playlist overview, and then add songs to it.
> 
> Where is this playlist overview?

In the sidebar, but if it is not showing then you can enable it under "Sidebar configuration" in General in settings. Click the Edit-button, and check the box.

**Comment by Anexgohan** [comment]
> > > I can also not create a playlist that way. I am able to create a playlist from the playlist overview, and then add songs to it.
> > 
> > 
> > Where is this playlist overview?
> 
> In the sidebar, but if it is not showing then you can enable it under "Sidebar configuration" in General in settings. Click the Edit-button, and check the box.

Holy heck, thanks man, though it was the most convoluted way to create a simple playlist but it worked, thanks a lot, now i'm in awe how you even discovered it, lol.

For anyone in the same boat:
![Feishin_taVdP1OSrU](https://github.com/user-attachments/assets/6271107d-e42c-48a7-8651-18fc37d98b9d)

**Comment by jeffvli** [comment]
Seems like you've already figured it out, but yes playlist creation requires you to use the dedicated `Create Playlist` popup.

If you expand the sidebar, there's a button on there to access it too.

![image](https://github.com/user-attachments/assets/408e0fa4-a53b-4d8a-8107-d5500831a331)

**Comment by Anexgohan** [comment]
> Seems like you've already figured it out, but yes playlist creation requires you to use the dedicated `Create Playlist` popup.
> 
> If you expand the sidebar, there's a button on there to access it too.
> 
> ![image](https://private-user-images.githubusercontent.com/42182408/386011317-408e0fa4-a53b-4d8a-8107-d5500831a331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTAzNjMsIm5iZiI6MTczMTU1MDA2MywicGF0aCI6Ii80MjE4MjQwOC8zODYwMTEzMTctNDA4ZTBmYTQtYTUzYi00ZDhhLTgxMDctZDU1MDA4MzFhMzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAyMDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYmIxZmVjYjc5ZGY5ZmExNDBmN2JlMjkyNzU2NTEwYjlkMmQxMDlkODI2MWM1NTA2YzA2YjQ1MjgwZDc5OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T9nhcDy6ODQhTDZvhGPBlzwkI5oh7VO2EIe8SQBGZjc)

Why not just let the user create the playlist in that dialog box, that seems to be the most straight forward way rather than this convoluted way of going into the settings enabling stuff only to be able to access the playlist.

**Comment by jeffvli** [comment]
The default view when starting the app for the first time uses the expanded sidebar (which by default includes the dedicated playlist list). Since the sidebar item configuration isn't separate for the expanded/collapsed views, it didn't make sense to have both the playlist navigation as well as the playlist list visible. It's up to the user at that point if they prefer the collapsed or expanded view and the sidebar configuration allows them to put whatever they want on there.

I agree the configuration is confusing if the user doesn't know exactly what to look for, but at the very least there is a search button on the settings page. I'm not planning on updating this behavior in feishin as I'm currently working on a [rewrite](https://github.com/audioling/audioling) but I will take this into consideration for it.

**Comment by cyberwolfie1** [comment]
> The default view when starting the app for the first time uses the expanded sidebar (which by default includes the dedicated playlist list). Since the sidebar item configuration isn't separate for the expanded/collapsed views, it didn't make sense to have both the playlist navigation as well as the playlist list visible. It's up to the user at that point if they prefer the collapsed or expanded view and the sidebar configuration allows them to put whatever they want on there.
> 
> I agree the configuration is confusing if the user doesn't know exactly what to look for, but at the very least there is a search button on the settings page. I'm not planning on updating this behavior in feishin as I'm currently working on a [rewrite](https://github.com/audioling/audioling) but I will take this into consideration for it.

Does the rewrite mean we can't expect much work on Feishin at all, or will there be parallel development for some time?

**Comment by Anexgohan** [comment]
> The default view when starting the app for the first time uses the expanded sidebar (which by default includes the dedicated playlist list). Since the sidebar item configuration isn't separate for the expanded/collapsed views, it didn't make sense to have both the playlist navigation as well as the playlist list visible. It's up to the user at that point if they prefer the collapsed or expanded view and the sidebar configuration allows them to put whatever they want on there.
> 
> I agree the configuration is confusing if the user doesn't know exactly what to look for, but at the very least there is a search button on the settings page. I'm not planning on updating this behavior in feishin as I'm currently working on a [rewrite](https://github.com/audioling/audioling) but I will take this into consideration for it.

Why rewrite, genuinely curious its such a well made and functioning player, any roadmap ?
