### ISSUE TITLE
Make queue reflect correct order when "Play shuffled" is enabled

### ISSUE THREAD

**Issue by cyberwolfie1** [jeffvli/feishin#838]
### What do you want to be added?

Currently, if "Play shuffled" is enabled, the play queue still shows the original order of the songs, and not the newly generated shuffled order. It would be nice if it showed the new order of songs to be played, and even an "Re-shuffle" option in the queue view that could be used to quickly generate a new order of songs.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
If you view the `Now Playing` page, or the queue in the sidebar, there is a button in the command bar to manually shuffle the queue. You will want to use that instead of the shuffle option in the bottom player bar.
