### ISSUE TITLE
Narrow window mode

### ISSUE THREAD

**Issue by johnwoltman** [jeffvli/feishin#842]
### What do you want to be added?

I've been using Feishin for a few weeks now and it's very good, thank you for all the hard work.  Would you consider adding a "narrow window" mode similar to plex amp for library browsing?  The plex amp window can be made especially narrow, essentially showing the same interface as the mobile version.  The current Feishin interface looks good narrow if I'm looking at the now playing view, but the library / browsing view (not sure what the actual term for it is) still requires a wide window.
![plexamp-example1-recently-added](https://github.com/user-attachments/assets/c6a3ba8c-0bc7-4746-9753-727747fd859e)
![plexamp-example2-home](https://github.com/user-attachments/assets/907d92e7-849d-4861-8258-32307d2a0fef)
![plexamp-example3-now-playing](https://github.com/user-attachments/assets/0b5e1f8a-8584-454e-bf95-28186d7808f2)

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
The term you're looking for is to add  `mobile-responsiveness` to the app. It's not planned for Feishin, but I will be planning on it for the [rewrite](https://github.com/audioling/audioling).

**Comment by johnwoltman** [comment]
Thanks!
