### ISSUE TITLE
"Appears on" Feature

### ISSUE THREAD

**Issue by reimarcopaulo** [jeffvli/feishin#843]
### What do you want to be added?

Hi there, thanks for the amazing work you've done so far! I was wondering if it would be possible to add an "Appears On" feature, similar to the one on the Jellyfin web client or other streaming apps. The main goal would be to show a list of albums where the artist is featured but isn’t the main album artist. It’s a bit tricky to explain in words, so I’ve included an image to help illustrate.
![image](https://github.com/user-attachments/assets/c9a12996-a82c-4172-99c0-da6399cef1a3)

### Is this a server-specific feature? (e.g. Jellyfin only)

- [ ] Yes

**Comment by jeffvli** [comment]
This feature already exists but was bugged I believe. A [fix was pushed on Oct 31](https://github.com/jeffvli/feishin/pull/812) which is pending release (soon).
