### ISSUE TITLE
An error occurred - missing parameter: 'u' when adding my navidrome server to the app

### ISSUE THREAD

**Issue by bwest2102** [jeffvli/feishin#848]
### Expected Behavior

Server should be added to the list and be properly authenticated to add Navidrome library to Feishin app.

### Current Behavior

When selecting Navidrome and entering in my details to add my Navidrome server to the server list, I am met with an error message: An error occurred - missing parameter: 'u'

### Steps to Reproduce

1. Open Feishin
2. When first downloading, the 'Server Required' screen should appear
3. Click 'open menu'
4. Click 'manage servers'
5. Click 'add server'
6. Top the top of the add server dialog, click 'Navidrome'
7. Enter server name (Put whatever in)
8. Enter URL of Navidrome instance
9. Enter username
10. Enter password
11. Click 'Save password' (OPTIONAL)
12. Click 'Add'.

### Possible Solution

Check to make sure that when entering login information, that the u= parameter is passed through correctly in the app. (This is untested on previous versions of the app.)

### Context

This prevents the 'Navidrome' option from being selected, allowing for extra playlist features and playlist sharing which is unavailable when selecting the 'Subsonic' option.

### Application version

0.11.1

### Operating System and version

MacOS Big Sur (11.7.10)

### Server and Version

0.53.3 (13af8ed4)

### Node Version (if developing locally)

N/A

**Comment by jeffvli** [comment]
Do you have special characters in your username by any chance?

From the sidebar file menu, open the browser devtools to the network tab and then retry adding your Niavdrome server and check what the exact URL being sent to authenticate to Navidrome is.

It should be `<url>/ping/view?c=Feishin&f=json&u=<username>&s=<salt>t=<hash>`.

**Comment by ningw42** [comment]
Maybe relevant, after updating to 0.12.0.  I got the same error message in Navidrome's log.

I tried to downgrade to 0.11.1, it works. My username it very simple, just 'ning'.

```
 991   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028495
 992   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028494
 993   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028496
 994   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="API: Failed response" endpoint=/rest/getCoverArt.view error=10 message="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028494
 995   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="API: Failed response" endpoint=/rest/getCoverArt.view error=10 message="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028495
 996   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="API: Failed response" endpoint=/rest/getCoverArt.view error=10 message="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028496
 997   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028497
 998   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="API: Failed response" endpoint=/rest/getCoverArt.view error=10 message="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028497
 999   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028498
1000   │ Nov 19 22:26:51 yuki navidrome[1940343]: time="2024-11-19T22:26:51+08:00" level=warning msg="API: Failed response" endpoint=/rest/getCoverArt.view error=10 message="missing parameter: 'u'" requestId=yuki/9rxaUvNZej-028498
```

**Comment by thegoija** [comment]
Having the same kind of issue, for me it started with 0.12.0 when grabbing cover arts. Covers are not being loaded when using the global search.

Error on navidrome server:
`time="2024-11-19T14:20:14Z" level=warning msg="API: Failed response" endpoint=/rest/getCoverArt.view error=10 message="missing parameter: 'u'" requestId=c4b234c506b7/LzeoTzewzP-099027`

Based on devtools, the request changed with 0.12.0:
0.11.1:
`<url>/rest/getCoverArt.view?id=mf-8208e4e8d3496754e9241710ae7ea882_5a04ec00&u=<username>&s=<salt>&t=<hash>&v=1.13.0&c=feishin&size=300`

0.12.0:
`<url>/rest/getCoverArt.view?id=mf-8208e4e8d3496754e9241710ae7ea882_5a04ec00&u%3D<username>%26s%3D<salt>%26t%3D<hash>&v=1.13.0&c=feishin&size=300`

seems to be html encoding issue

**Comment by ningw42** [comment]
> Having the same kind of issue, for me it started with 0.12.0 when grabbing cover arts. Covers are not being loaded when using the global search.
> 
> Error on navidrome server: `time="2024-11-19T14:20:14Z" level=warning msg="API: Failed response" endpoint=/rest/getCoverArt.view error=10 message="missing parameter: 'u'" requestId=c4b234c506b7/LzeoTzewzP-099027`
> 
> Based on devtools, the request changed with 0.12.0: 0.11.1: `<url>/rest/getCoverArt.view?id=mf-8208e4e8d3496754e9241710ae7ea882_5a04ec00&u=<username>&s=<salt>&t=<hash>&v=1.13.0&c=feishin&size=300`
> 
> 0.12.0: `<url>/rest/getCoverArt.view?id=mf-8208e4e8d3496754e9241710ae7ea882_5a04ec00&u%3D<username>%26s%3D<salt>%26t%3D<hash>&v=1.13.0&c=feishin&size=300`
> 
> seems to be html encoding issue

I think you’re right. This commit seems to be related. https://github.com/jeffvli/feishin/commit/8ec4551b46ff532d3790f23faa63f7ee472ffa33

**Comment by bwest2102** [comment]
> Do you have special characters in your username by any chance?
> 
> From the sidebar file menu, open the browser devtools to the network tab and then retry adding your Niavdrome server and check what the exact URL being sent to authenticate to Navidrome is.
> 
> It should be `<url>/ping/view?c=Feishin&f=json&u=<username>&s=<salt>t=<hash>`.

Ok, I tried it again and it worked this time, but now I am getting: Error - o.body.data.map is not a function
and Error - Error setting sink: Cannot proceed setSinkId on a closed AudioContext.

**Comment by bwest2102** [comment]
> Do you have special characters in your username by any chance?
> 
> From the sidebar file menu, open the browser devtools to the network tab and then retry adding your Niavdrome server and check what the exact URL being sent to authenticate to Navidrome is.
> 
> It should be `<url>/ping/view?c=Feishin&f=json&u=<username>&s=<salt>t=<hash>`.

And no, I do not have any special characters in my username, its just my first and last name and 2 numbers.

**Comment by bwest2102** [comment]
Update: I found the solution to most of the problems.

I found that the latest version of Feishin or Navidrome are using endpoints that I didn't have set up in my zero trust policies for my tunneled apps. 

Turns out the new versions use both /rest/* AND /api/* paths as well, which I didn't have set up as a bypass. After I set up the bypass for the /api/* path the issues stopped. 

I have cloudflare zero trust set up to bypass the traffic that has /rest/* and /api/* uri paths if it's coming from any IP range on my mobile career, or my workplace's or my home's static IP addresses.

So for future reference, if anyone is running their Navidrome through cloudflare and has zero trust set up, be sure the /rest and /api endpoints are both able to be connected to and that cloudflare zero trust doesn't interfere with it.

**Comment by mazzz1y** [comment]
The same issue for [gonic](https://github.com/sentriz/gonic):

```
2024/11/20 17:35:44 subsonic error code 10: please provide a "u" parameter
```

I don't have any firewall restrictions, so I don't think this is related. @bwest2102, we probably need to reopen the issue.

**Comment by bwest2102** [comment]
> The same issue for [gonic](https://github.com/sentriz/gonic):
> 
> ```
> 2024/11/20 17:35:44 subsonic error code 10: please provide a "u" parameter
> ```
> 
> I don't have any firewall restrictions, so I don't think this is related. @bwest2102, we probably need to reopen the issue.

I believe a new version was just released fixing that issue.

**Comment by tanpro260196** [comment]
This is still happening on latest release, specifically only on Navidrome server, switching to Subsonic works fine.

**Comment by bwest2102** [comment]
> This is still happening on latest release, specifically only on Navidrome server, switching to Subsonic works fine.
> 

I no longer have the issue, I needed to whitelist some specific URIs on my zero trust service for feishin to work properly. I can list them here if you want.

**Comment by tanpro260196** [comment]
> > This is still happening on latest release, specifically only on Navidrome server, switching to Subsonic works fine.
> 
> I no longer have the issue, I needed to whitelist some specific URIs on my zero trust service for feishin to work properly. I can list them here if you want.

I already whitelisted /rest/ and /api/, didn't help much.
Also tried bypassing WAF and make direct connection, same behaviour.

**Comment by bwest2102** [comment]
Here are the URIs you have to bypass in order for Feishin to properly authenticate with Navidrome:
1. /auth/login
2. /rest/*
3. /api/*

If you want people to be able to access shares on your Navidrome instance, you would whitelist this URI too:
/share/*

**Comment by bwest2102** [comment]
> > > This is still happening on latest release, specifically only on Navidrome server, switching to Subsonic works fine.
> > 
> > 
> > I no longer have the issue, I needed to whitelist some specific URIs on my zero trust service for feishin to work properly. I can list them here if you want.
> 
> I already whitelisted /rest/ and /api/, didn't help much. Also tried bypassing WAF and make direct connection, same behaviour.

Here are the URIs you have to bypass in order for Feishin to properly authenticate with Navidrome:
1. /auth/login
2. /rest/*
3. /api/*

If you want people to be able to access shares on your Navidrome instance, you would whitelist this URI too:
/share/*
