### ISSUE TITLE
Album Art Missing in Related Tab (Navidrome)

### ISSUE THREAD

**Issue by sleroq** [jeffvli/feishin#849]
### Expected Behavior

Album art loads normally.

### Current Behavior

Album art doesn't load in the "related" tab.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/user-attachments/assets/77de2f58-4674-4a1e-b57d-d76973edbf18)

</p>
</details> 

### Steps to Reproduce

1. Add navidrome server
2. Play any song.
3. Open in full-screen player.
4. Switch to "related" tab.

### Possible Solution

The issue appears to be incorrectly encoded credentials in `getSimilarSongs`. This was introduced by adding `encodeURIComponent` in https://github.com/jeffvli/feishin/commit/8ec4551b46ff532d3790f23faa63f7ee472ffa33

I attempted to fix this but got stuck because `NavidromeController` is using a function for the Subsonic API in [getSimilarSongs](https://github.com/jeffvli/feishin/blob/fac1d3fb62f5eadcd2d79c7a29152d2c1b94cd15/src/renderer/api/navidrome/navidrome-controller.ts#L419), and the type definitions for song are conflicting.

Potential solutions:
- Remove `encodeURIComponent` from the ss API (though might impact other servers, I can only test Navidrome)
- Create a separate function specifically for Navidrome API with compatible types (idk)

### Context

Thank you for creating Feishin. It's the best Navidrome client and I appreciate the work you've put into the project. ♥️

### Application version

v0.12.0

### Operating System and version

any

### Server and Version

Navidrome v0.53.3

**Comment by jeffvli** [comment]
Resolved by #850
