### ISSUE TITLE
Queue will not be saved after exit

### ISSUE THREAD

**Issue by xitara** [jeffvli/feishin#86]
## Expected Behavior

Queue should be saved on exit. Testet on WIndows 11.
Servers: Jellyfin and Navidrome on Debian/Bullseye

## Current Behavior

After restart feishin (same issue in sonixd) the Queue is empty

## Steps to Reproduce

1. Fill Queue

2. Play a song

3. Exit feishin

4. Start feishin

5. Now queue is empty

## Your Environment

- Application version : v0.0.1-alpha6 (sonixd: latest)
- Operating System and version : Windows 11 Pro 22h2
- Node version (if developing locally) : v18.16.0

**Comment by jeffvli** [comment]
Resolved in #111
