### ISSUE TITLE
Genres with many entries not loading well

### ISSUE THREAD

**Issue by Cambi0nn** [jeffvli/feishin#866]
### Expected Behavior

When I press play from the genre list, I expect all songs of that genre to be added to the queue.
When I open a specific genre page, I expect to see all album. 

### Current Behavior

I only get the first 10 tracks when I add them from the genre list to queue.
When opening the page of that genre, it acts like there are no tracks.

The getGenres call returns the correct data, with the largest genre containing 361 albums, and 1880 tracks.
The getAlbumList2 call has the following response, so I'm guessing something is missing there:
```
{
    "subsonic-response": {
        "status": "ok",
        "version": "1.16.0",
        "serverVersion": "Astiga\/production",
        "albumList2": {
            "album": []
        }
    }
}
```

### Steps to Reproduce

- Select "Genres" on the side menu.
- select a genre of choice.

### Application version

0.12.1

### Operating System and version

Manjaro Linux, kernel 6.6.54-2

### Server and Version

Astiga

**Comment by gravelld** [comment]
This is an issue with Astiga, I suggest you close it...
