### ISSUE TITLE
Bug: Album Artist and Artists pictures not showing correctly due to wrong port

### ISSUE THREAD

**Issue by Bpi031** [jeffvli/feishin#868]
### Expected Behavior

Description: There is an issue with the Album Artist pictures not displaying correctly. It seems to be caused by fetching the wrong port. The fetch artist image should follow the server connection and Navidrome port.
Expected behavior: The pictures should display correctly without any errors.
Error message:
```
Error fetching average color Error: FastAverageColor: Error loading image "https://abc.com/share/img/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFyLWI5M2NiNjQ3MjI0NDk0YTdiZDZmNWFmMzk5NGY4YTY3XzAiLCJpc3MiOiJORCJ9.jGxsMOAvZ7xRXCIwaOeYGAyZygHHHtl_eCijXZ-LKZA?size=1200".
    at z (renderer.js:2:2001636)
    at Image.i (renderer.js:2:2004774), 
```

Correct get request:
```
URL:https://abc.com:4500/share/img/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFyLWQ2NDk5YjkxOTAwZWYxYjJkYjM1ZDA0NDU3ODQ2YzA1XzAiLCJpc3MiOiJORCJ9.zwC1VQc--eRUpDIF1hOgSz1OoPh7BK8VhOhMmkS3xxE?size=1200

Status: 200
```

This issue seems to be similar to issues #90 and #317.

### Current Behavior

The pictures are not displaying correctly and the error message above is shown.

### Steps to Reproduce

1.Start the Navidrome server at port 4500.
2.Open the Feishin interface.
3.Navigate to the Album Artist or Artists page.
4.Observe that the pictures are not displaying correctly and the error message is shown.
5.Getting 403 (Forbidden) error message in console.

### Possible Solution

Fetch artist image follows the server connection and Navidrome port. Update the code to dynamically use the correct port based on the server configuration.

### Application version

0.12.1

### Operating System and version

Macos 15.1.1

### Server and Version

Navidrome 0.53.3

<img width="1809" alt="Screenshot 2024-12-09 at 12 36 36 PM" src="https://github.com/user-attachments/assets/e87511ee-927d-437a-8ebf-d062babe2b65">

**Comment by Bpi031** [comment]
It appears that the artist list pictures are not displaying artist icons due to an icon size issue. When the icon size is set to 300, the artist icons do not display. However, changing the icon size to 301 or any other value causes the icons to display correctly. This suggests there may be a problem specifically when the icon size is 300.
<img width="2251" alt="Screenshot 2024-12-09 at 12 40 31 PM" src="https://github.com/user-attachments/assets/0c76f6a9-ddf8-4139-9e18-b39de23f1033">
server request check:
```
Summary
URL: https://abc.com:4500/rest/getCoverArt.view?id=ar-b93cb647224494a7bd6f5af3994f8a67&u=haha&s=9e6677&t=880ccb5fffc70f1e29bae169d15fffb5&v=1.13.0&c=feishin&size=300
Status: 200
```

**Comment by synchromatik** [comment]
hey there, i had the same bug- but apparently, navidrome have some issues with cover arts for artists. Take a look, it solved it for me
[I suggest, going to any artists in navidrome, if the image is missing that's causing ](https://github.com/navidrome/navidrome/issues/2222)

After the fix:
![image](https://github.com/user-attachments/assets/6ae73f47-0292-4c09-93c1-8628e0ab8782)

**Comment by Bpi031** [comment]
@synchromatik Thank for your help.
