### ISSUE TITLE
[Navidrome] Artist images are not displayed

### ISSUE THREAD

**Issue by Nervyalloy5** [jeffvli/feishin#90]
## Expected Behavior

Artist images should be displayed in both the album artists tab and the main artist page.

## Current Behavior

When connected to a Navidrome server artist images are not displayed:
![image](https://user-images.githubusercontent.com/24869676/234375036-8cc32fbe-f370-4443-a9ab-6b95b7c90681.png)
![image](https://user-images.githubusercontent.com/24869676/234376984-0184107d-3494-4818-b100-d38b3272f67e.png)

Images are displayed in the Navidrome WebUI:
![image](https://user-images.githubusercontent.com/24869676/234375264-a98023fc-4900-44dd-af32-7f6f6c342e6d.png)

Images are also displayed in sonixd while connected to Navidrome:
![image](https://user-images.githubusercontent.com/24869676/234376122-7d4fb6d6-22a9-4d6d-8cf3-e2d9d7b7a8ed.png)

If Feishin is instead connected to a Jellyfin server images are displayed correctly:
![image](https://user-images.githubusercontent.com/24869676/234376605-138cb618-39ad-47bc-a31d-9b22b0bccc58.png)

## Steps to Reproduce

1. Open Feishin. [0.0.1-alpha6-linux-x86_64.AppImage]

2. Connect to Navidrome server.

3. Click on either the Album Artists tab or an Artists main page.

4. Observe the issue.

## Context

Trying to make the switch from sonixd to feishin. and while it works great for playback, lack of artist images makes navigation more difficult.
I would also rather not switch back to jellyfin for music, as it is a bit lacking in features.

## Your Environment

- Application version : feishin-0.0.1-alpha6-linux-x86_64.AppImage
- Operating System and version : ArchLinux x86_64  Kernel 6.2.11-zen1-1-zen
- Desktop Environment: SwayWM (wayland)
- Navidrome Version: Docker [deluan/navidrome:develop] [0.49.3-SNAPSHOT] (c12510d6)

**Comment by jeffvli** [comment]
This is fixed for the next release.
