### ISSUE TITLE
Let us use letters in the server URL

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#91]
I'd like to use http://localhost:4533 for my Navidrome server.

**Comment by jeffvli** [comment]
Using localhost should work from the add server menu unless I'm missing something?

If it doesn't work, you can always use http://127.0.0.1:4533 to the same effect as localhost.

**Comment by isle9** [comment]
I can confirm that you can indeed add a new server using either of those, but it seems like you can't edit the URL after adding the server at all. If you change it at all, you get the red warning.
That seemed to be the issue. 
I'd recommend adding an explanation about this behavior somewhere in the app. A great way to do that would be to add a hover text bubble over the red warning icon.

**Comment by jeffvli** [comment]
Ah I see what you mean now.

![image](https://user-images.githubusercontent.com/42182408/234839418-98655622-b255-4c1f-8c96-c90f7a43cbf3.png)

The red warning icon doesn't mean that there is an error with the field. It is being used to indicate which text fields have been modified from their original value. You can test this behavior by also modifying the "Name" and "Username" fields in addition to the url.

Though looking back at it, it is definitely misleading. I'll change it to a warning color (yellow) and add a tooltip for it like you suggested.

**Comment by isle9** [comment]
Another thing that also seemed to confuse me and to think that there might be a problem is the fact that the save button is greyed out. I thought that it might be because of an error, but it's because I didn't enter my password again.
I guess it makes sense to ask for a password when changing server info if you're sharing the app with someone else?
It would also be a good idea to highlight the password field somehow.
Maybe instead of graying out the save field, you would let users click on it but then flash the password field if it's empty or incorrect.

**Comment by jeffvli** [comment]
Added improvements to the UX for the update server form: https://github.com/jeffvli/feishin/commit/2d7c52a6b6daecb27414089b50fd795ad0b4d775
This should hopefully resolve any future confusion when updating an existing server.

- Auto focuses the password field: This way you don't need additional clicks; just enter your password and then press enter to update
- Set the save button to always enabled, but uses the native browser "required" input to force all fields to be filled out before submitting is allowed
- Added a hover tooltip to the field modified indicator

![image](https://github.com/jeffvli/feishin/assets/42182408/25d1ab08-0c82-4b63-b6be-7c1a1c0ff08c)
