### ISSUE TITLE
[Feature request] Playback-speed

### ISSUE THREAD

**Issue by YourSandwich** [jeffvli/feishin#94]
## What do you want to be added?
Ability to change the Playback speed of the song.

**Comment by pauldmccallum** [comment]
I too would like this ability as a built-in feature when listening to Audio Books. However, the workaround I found is to add --speed=1.50 in the playback settings under MPV parameters.

**Comment by YourSandwich** [comment]
Thank you for implementing the feature <3

It would be great if an option for changing the pitch correction filter would be available.
Details are available in the manual for MPV under the AUDIO FILTERS section.

mpv uses scaletempo2 by default, while rubberband (librubberband) seems to perform better for fast pasted music.
