### ISSUE TITLE
[Jellyfin] Tracks images are not displayed if not embedded in file

### ISSUE THREAD

**Issue by pinsarda** [jeffvli/feishin#97]
## Expected Behavior

There should be covers on those tracks.

## Current Behavior

![Capture d’écran du 2023-05-06 16-54-27-min](https://user-images.githubusercontent.com/42810697/236631936-342e7356-1a42-4480-ba43-73edbb5adab5.png)

There is no images for songs while albums are fine. This is most probably due to my audio files not embedding images : I use a single one for each album, stored in their associated folders under "cover.jpg" or "cover.png"
This is not an issue on other clients.

## Steps to Reproduce

Have some .m4a files (probably works with mp3 too) with no cover embedded, but a cover.jpg file in their directory. 

## Possible Solution

I didn't have time to look into the code/request to jellyfin but I guess jellyfin must return a null value when requested for a cover for each song. A fallback to album cover when jellyfin doesn't return anything should be an easy fix.

## Your Environment

- Application version : alpha6
- Latest version of jellyfin (10.8.10)

(By the way, thank you for your work !)

**Comment by jeffvli** [comment]
I thought I had already implemented this, but it turns out it was bugged. Will be fixed in the next release!
