### ISSUE TITLE
[Feature Request] Lyrics view

### ISSUE THREAD

**Issue by Hyruleh3ro** [jeffvli/feishin#98]
I would like to be able to view the lyrics of songs while playing them. (e.g. taking the lyrics from Musixmatch)

**Comment by jeffvli** [comment]
A section for lyrics is already available in the full screen player view (#27).

Actual lyrics fetching will be implemented in a later release with the possible fetchers:
- Musixmatch
- Netease
- Genius

**Comment by nulledone** [comment]
"Musixmatch" was not implemented, would love to see it if it is possible

**Comment by kgarner7** [comment]
Musixmatch was intentionally not implemented, as it requires a non-free api key for proper use

**Comment by jagauthier** [comment]
This is a stupid question I'm sure - but I am brand new to this application. I can't see any references for disaplying lyrics in the UI (desktop).
